import { and, eq, gte, sql } from 'drizzle-orm'
import { createError } from 'h3'
import { getDatabase } from '../../database'
import { managedSiteAiCostLedger, managedSiteAiEditProposals } from '../../database/schema'
import { canonicalFingerprint } from './canonical'
import { AI_EDITOR_LIMITS, type AiBudgetPort } from './ai'
import type { AiEditProposal, PageActor } from './types'

function databaseOrThrow() { const database = getDatabase(); if (!database) throw createError({ statusCode: 503, statusMessage: 'AI editor ledger database is unavailable.' }); return database }
export function createDrizzleAiBudgetPort(): AiBudgetPort { return { async claim(scope, input) { const database = databaseOrThrow(); const dayStart = new Date(input.now); dayStart.setUTCHours(0, 0, 0, 0); const [usage] = await database.select({ requests: sql<number>`count(*)`, inputTokens: sql<number>`coalesce(sum(${managedSiteAiCostLedger.inputTokens}), 0)` }).from(managedSiteAiCostLedger).where(and(eq(managedSiteAiCostLedger.ownerUserId, scope.ownerUserId), eq(managedSiteAiCostLedger.projectId, scope.projectId), gte(managedSiteAiCostLedger.createdAt, dayStart))); const [replay] = await database.select({ id: managedSiteAiCostLedger.id }).from(managedSiteAiCostLedger).where(and(eq(managedSiteAiCostLedger.ownerUserId, scope.ownerUserId), eq(managedSiteAiCostLedger.projectId, scope.projectId), eq(managedSiteAiCostLedger.requestFingerprint, input.requestFingerprint))).limit(1); if (replay) return { allowed: true, remainingRequests: Math.max(0, AI_EDITOR_LIMITS.requestsPerDay - Number(usage?.requests || 0)), reasonCode: null }; if (Number(usage?.requests || 0) >= AI_EDITOR_LIMITS.requestsPerDay || Number(usage?.inputTokens || 0) + input.estimatedInputTokens > AI_EDITOR_LIMITS.inputTokensPerDay) return { allowed: false, remainingRequests: 0, reasonCode: 'AI_PLAN_BUDGET_EXCEEDED' }; await database.insert(managedSiteAiCostLedger).values({ ownerUserId: scope.ownerUserId, projectId: scope.projectId, proposalId: null, providerKey: 'deterministic-scoped-planner', requestUnits: 1, inputTokens: input.estimatedInputTokens, outputTokens: 0, costMicros: 0, requestFingerprint: input.requestFingerprint, createdAt: input.now }); return { allowed: true, remainingRequests: AI_EDITOR_LIMITS.requestsPerDay - Number(usage?.requests || 0) - 1, reasonCode: null } } } }

export async function saveAiProposal(actor: PageActor, proposal: AiEditProposal): Promise<AiEditProposal> { const database = databaseOrThrow(); if (actor.ownerUserId !== proposal.ownerUserId || actor.projectId !== proposal.projectId) throw createError({ statusCode: 403, statusMessage: 'AI proposal is outside the active tenant.' }); await database.insert(managedSiteAiEditProposals).values({ proposalId: proposal.proposalId, ownerUserId: actor.ownerUserId, projectId: actor.projectId, pageId: proposal.pageId, expectedPageVersion: proposal.expectedPageVersion, intent: proposal.intent, summary: proposal.summary, operations: proposal.operations, diff: proposal.diff, warnings: proposal.warnings, affectedBlockIds: proposal.affectedBlockIds, visionMode: proposal.visionMode, proposalFingerprint: proposal.proposalFingerprint, status: proposal.status === 'refused' ? 'rejected' : proposal.status, expiresAt: new Date(proposal.expiresAt) }).onDuplicateKeyUpdate({ set: { proposalFingerprint: proposal.proposalFingerprint } }); return proposal }
export async function loadAiProposal(actor: PageActor, proposalId: string): Promise<AiEditProposal> { const database = databaseOrThrow(); const [row] = await database.select().from(managedSiteAiEditProposals).where(and(eq(managedSiteAiEditProposals.ownerUserId, actor.ownerUserId), eq(managedSiteAiEditProposals.projectId, actor.projectId), eq(managedSiteAiEditProposals.proposalId, proposalId))).limit(1); if (!row) throw createError({ statusCode: 404, statusMessage: 'AI proposal was not found in this site.' }); const proposal: AiEditProposal = { proposalId: row.proposalId, ownerUserId: row.ownerUserId, projectId: row.projectId, pageId: row.pageId, intent: row.intent as AiEditProposal['intent'], summary: row.summary, operations: row.operations as AiEditProposal['operations'], diff: row.diff as AiEditProposal['diff'], warnings: row.warnings as string[], affectedBlockIds: row.affectedBlockIds as string[], expectedPageVersion: row.expectedPageVersion, proposalFingerprint: row.proposalFingerprint, status: row.status === 'rejected' ? 'refused' : row.status === 'approved_to_draft' || row.status === 'expired' ? 'clarification_required' : row.status, expiresAt: row.expiresAt.toISOString(), mayPublishDirectly: false, visionMode: row.visionMode }; const { proposalFingerprint, ...stable } = proposal; if (canonicalFingerprint(stable) !== proposalFingerprint) throw createError({ statusCode: 409, statusMessage: 'Durable AI proposal fingerprint mismatch.' }); return proposal }
export async function markAiProposalApplied(actor: PageActor, proposalId: string): Promise<void> { const database = databaseOrThrow(); const result = await database.update(managedSiteAiEditProposals).set({ status: 'approved_to_draft' }).where(and(eq(managedSiteAiEditProposals.ownerUserId, actor.ownerUserId), eq(managedSiteAiEditProposals.projectId, actor.projectId), eq(managedSiteAiEditProposals.proposalId, proposalId), eq(managedSiteAiEditProposals.status, 'proposed'))); if (Number((result as any)?.[0]?.affectedRows || 0) !== 1) throw createError({ statusCode: 409, statusMessage: 'AI proposal was already applied or is no longer valid.' }) }
