import { createHmac, timingSafeEqual } from 'node:crypto'
import { createError } from 'h3'
import { assertSafeLink, parseBlock } from './catalog'
import { canonicalFingerprint, diffPages, finalizePageDocument, parsePageDocument } from './canonical'
import { compilePageDocument } from './compiler'
import { PAGE_COMMAND_VERSION, type AppliedPageOperation, type MediaAuthorityResolver, type PageActor, type PageBlock, type PageCommand, type PageDiff, type PageDocument, type PageEditorRepository, type PageMediaBinding, type PagePublicationReceipt, type SafeLink } from './types'

function invalid(message: string): never { throw createError({ statusCode: 422, statusMessage: message }) }
function conflict(message: string): never { throw createError({ statusCode: 409, statusMessage: message }) }
function forbidden(message: string): never { throw createError({ statusCode: 403, statusMessage: message }) }
function actorAuthority(actor: PageActor): string { return `${actor.authority}:${actor.actorUserId ?? 'system'}:${actor.role}` }
function assertActor(actor: PageActor, mutation = false): void { if (!Number.isSafeInteger(actor.ownerUserId) || actor.ownerUserId < 1 || !Number.isSafeInteger(actor.projectId) || actor.projectId < 1) forbidden('Page editor tenant authority is invalid.'); if (mutation && actor.role === 'viewer') forbidden('Viewer role cannot mutate page drafts.') }
function parseCommand(input: unknown): PageCommand {
  if (!input || typeof input !== 'object' || Array.isArray(input)) invalid('Page command must be a plain object.')
  const value = input as any; const allowed = ['schemaVersion', 'type', 'expectedPageVersion', 'idempotencyKey', 'target', 'payload', 'reason']; if (Object.keys(value).some(key => !allowed.includes(key)) || value.schemaVersion !== PAGE_COMMAND_VERSION || !['update_text', 'update_link', 'replace_media', 'add_block', 'remove_block', 'duplicate_block', 'move_block', 'update_block_variant', 'update_items', 'toggle_visibility', 'schedule_visibility', 'update_seo', 'restore_version'].includes(value.type) || !Number.isSafeInteger(value.expectedPageVersion) || value.expectedPageVersion < 1 || typeof value.idempotencyKey !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,127}$/u.test(value.idempotencyKey) || !value.target || typeof value.target !== 'object' || Array.isArray(value.target) || typeof value.reason !== 'string' || !value.reason.trim() || value.reason.length > 500) invalid('Page command envelope is invalid.')
  if (Object.keys(value.target).some(key => !['blockId', 'path', 'index', 'bindingId', 'version'].includes(key))) invalid('Page command target contains unknown fields.')
  return { schemaVersion: PAGE_COMMAND_VERSION, type: value.type, expectedPageVersion: value.expectedPageVersion, idempotencyKey: value.idempotencyKey, target: { ...value.target }, payload: value.payload, reason: value.reason.trim() }
}
function targetBlock(page: PageDocument, command: PageCommand): { block: PageBlock; index: number } { if (typeof command.target.blockId !== 'string') invalid('Page command requires a target block.'); const index = page.sections.findIndex(block => block.blockId === command.target.blockId); if (index < 0) conflict('Target block no longer exists in this page version.'); return { block: page.sections[index]!, index } }
function safePath(path: unknown, root = 'data'): string[] { if (typeof path !== 'string') invalid('Page command path is missing.'); const parts = path.split('.'); if (parts[0] !== root || parts.length < 2 || parts.length > 5 || parts.some(part => !/^[A-Za-z][A-Za-z0-9_]*$/u.test(part) || ['__proto__', 'prototype', 'constructor'].includes(part))) invalid('Page command path is not allowlisted.'); return parts }
function setAtPath(block: PageBlock, path: string[], value: unknown, expectedKind: 'string' | 'link' | 'array'): PageBlock {
  const clone = structuredClone(block) as any; let cursor: any = clone
  for (const part of path.slice(0, -1)) { if (!cursor || typeof cursor !== 'object' || Array.isArray(cursor) || !(part in cursor)) conflict('Page command target path is stale.'); cursor = cursor[part] }
  const leaf = path.at(-1)!; if (!(leaf in cursor)) conflict('Page command target field is stale.')
  if (expectedKind === 'string' && (typeof cursor[leaf] !== 'string' || typeof value !== 'string' || !value.trim() || value.length > 4000 || /<[^>]*>|javascript\s*:|data\s*:/iu.test(value))) invalid('Updated text is invalid or contains executable markup.')
  if (expectedKind === 'link') { if (value !== null) { if (!value || typeof value !== 'object' || Array.isArray(value)) invalid('Updated link is invalid.'); assertSafeLink(value as SafeLink) } }
  if (expectedKind === 'array' && (!Array.isArray(cursor[leaf]) || !Array.isArray(value) || value.length > 100)) invalid('Updated block items are invalid.')
  cursor[leaf] = structuredClone(value); return parseBlock(clone)
}
function parseReplacementBinding(value: unknown): PageMediaBinding {
  const shell = finalizePageDocument({ schemaVersion: 'managed-site-page-document-v1', pageId: 'binding0', version: 1, locale: 'en', route: '/', contentType: 'standard', designThemeId: 'default', designTokenVersion: 'tokens-v1', designTokens: { palette: 'indigo_sand', typeScale: 'balanced', spacing: 'balanced', radius: 'soft', maxWidth: 'standard', contrast: 'aa' }, sections: [{ blockId: 'block000', type: 'image_text', visible: true, layoutVariant: 'split', data: { title: 'Binding', description: 'Validation', mediaBindingId: (value as any)?.bindingId, imagePosition: 'left' }, mediaBindingIds: [(value as any)?.bindingId], schedule: null }], seo: { title: 'Binding', description: 'Validation binding document', canonicalPath: '/', noindex: true, ogBindingId: null }, publicationState: 'draft', mediaBindings: [value as PageMediaBinding], parentVersion: null, actorAuthority: 'system_test', createdAt: new Date(0).toISOString() }); return shell.mediaBindings[0]!
}

export function applyCommandToDocument(beforeInput: PageDocument, commandInput: unknown, actor: PageActor, now = new Date()): { page: PageDocument; operation: AppliedPageOperation; diff: PageDiff } {
  assertActor(actor, true); const before = parsePageDocument(beforeInput); const command = parseCommand(commandInput); if (command.expectedPageVersion !== before.version) conflict('Page draft version is stale; refresh or save a copy before continuing.')
  const sections = structuredClone(before.sections); const mediaBindings = structuredClone(before.mediaBindings); let seo = structuredClone(before.seo)
  switch (command.type) {
    case 'update_text': { const { index } = targetBlock(before, command); sections[index] = setAtPath(sections[index]!, safePath(command.target.path), command.payload, 'string'); break }
    case 'update_link': { const { index } = targetBlock(before, command); sections[index] = setAtPath(sections[index]!, safePath(command.target.path), command.payload, 'link'); break }
    case 'update_items': { const { index } = targetBlock(before, command); sections[index] = setAtPath(sections[index]!, safePath(command.target.path), command.payload, 'array'); break }
    case 'replace_media': { if (typeof command.target.bindingId !== 'string') invalid('Media replacement requires a binding identity.'); const index = mediaBindings.findIndex(binding => binding.bindingId === command.target.bindingId); if (index < 0) conflict('Media binding no longer exists.'); const replacement = parseReplacementBinding(command.payload); if (replacement.bindingId !== command.target.bindingId) invalid('Media replacement must preserve binding identity; replace-all is a separate explicit operation.'); mediaBindings[index] = replacement; break }
    case 'add_block': { const envelope = command.payload && typeof command.payload === 'object' && !Array.isArray(command.payload) && 'block' in (command.payload as any) ? command.payload as any : { block: command.payload, mediaBindings: [] }; const block = parseBlock(envelope.block); if (sections.some(item => item.blockId === block.blockId)) conflict('Added block identity already exists.'); if (!Array.isArray(envelope.mediaBindings) || envelope.mediaBindings.length > 100) invalid('Added block media bindings are invalid.'); for (const raw of envelope.mediaBindings) { const binding = parseReplacementBinding(raw); if (mediaBindings.some(item => item.bindingId === binding.bindingId) || !block.mediaBindingIds.includes(binding.bindingId)) conflict('Added block media binding identity collided or is unreferenced.'); mediaBindings.push(binding) } if (block.mediaBindingIds.some(id => !mediaBindings.some(binding => binding.bindingId === id))) conflict('Added block references media bindings that were not supplied.'); const index = command.target.index === undefined ? sections.length : Number(command.target.index); if (!Number.isInteger(index) || index < 0 || index > sections.length) invalid('Added block index is invalid.'); sections.splice(index, 0, block); break }
    case 'remove_block': { const { index, block } = targetBlock(before, command); if (block.mediaBindingIds.length) { const remaining = new Set(sections.filter((_, candidate) => candidate !== index).flatMap(item => item.mediaBindingIds)); for (let cursor = mediaBindings.length - 1; cursor >= 0; cursor--) { const binding = mediaBindings[cursor]!; if (block.mediaBindingIds.includes(binding.bindingId) && !remaining.has(binding.bindingId) && seo.ogBindingId !== binding.bindingId) mediaBindings.splice(cursor, 1) } } sections.splice(index, 1); break }
    case 'duplicate_block': { const { index, block } = targetBlock(before, command); const newBlockId = (command.payload as any)?.newBlockId; if (typeof newBlockId !== 'string' || !/^[A-Za-z0-9][A-Za-z0-9_-]{7,63}$/u.test(newBlockId) || sections.some(item => item.blockId === newBlockId)) invalid('Duplicate block requires a new stable block identity.'); sections.splice(index + 1, 0, { ...structuredClone(block), blockId: newBlockId }); break }
    case 'move_block': { const { index } = targetBlock(before, command); const toIndex = Number((command.payload as any)?.toIndex); if (!Number.isInteger(toIndex) || toIndex < 0 || toIndex >= sections.length) invalid('Block destination index is invalid.'); const [block] = sections.splice(index, 1); sections.splice(toIndex, 0, block!); break }
    case 'update_block_variant': { const { index } = targetBlock(before, command); if (typeof command.payload !== 'string') invalid('Block layout variant is invalid.'); sections[index] = parseBlock({ ...sections[index]!, layoutVariant: command.payload }); break }
    case 'toggle_visibility': { const { index } = targetBlock(before, command); if (typeof command.payload !== 'boolean') invalid('Block visibility must be boolean.'); sections[index] = { ...sections[index]!, visible: command.payload }; break }
    case 'schedule_visibility': { const { index } = targetBlock(before, command); sections[index] = parseBlock({ ...sections[index]!, schedule: command.payload }); break }
    case 'update_seo': { if (!command.payload || typeof command.payload !== 'object' || Array.isArray(command.payload) || Object.keys(command.payload as object).some(key => !['title', 'description', 'noindex', 'ogBindingId'].includes(key))) invalid('SEO update is invalid.'); seo = { ...seo, ...(command.payload as Partial<typeof seo>), canonicalPath: before.route }; break }
    case 'restore_version': invalid('Restore version must resolve its authoritative snapshot through the repository.')
  }
  const page = finalizePageDocument({ ...before, version: before.version + 1, parentVersion: before.version, sections, mediaBindings, seo, publicationState: 'draft', actorAuthority: actorAuthority(actor), createdAt: now.toISOString() }); const normalizedCommand = { ...command, actorAuthority: actorAuthority(actor) }; const requestFingerprint = canonicalFingerprint({ version: PAGE_COMMAND_VERSION, actor: { ownerUserId: actor.ownerUserId, projectId: actor.projectId, authority: actor.authority, role: actor.role }, command }); const operation: AppliedPageOperation = { command: normalizedCommand, fromVersion: before.version, toVersion: page.version, requestFingerprint, resultFingerprint: page.fingerprint, createdAt: now.toISOString() }; return { page, operation, diff: diffPages(before, page) }
}

export async function applyPageCommand(repository: PageEditorRepository, actor: PageActor, pageId: string, commandInput: unknown, now = new Date()) {
  assertActor(actor, true); return repository.transaction(transaction => applyPageCommandInTransaction(transaction, actor, pageId, commandInput, now))
}

export async function applyPageCommandInTransaction(transaction: PageEditorRepository, actor: PageActor, pageId: string, commandInput: unknown, now = new Date()) { const command = parseCommand(commandInput); const replay = await transaction.findOperation(actor.ownerUserId, actor.projectId, command.idempotencyKey); const requestFingerprint = canonicalFingerprint({ version: PAGE_COMMAND_VERSION, actor: { ownerUserId: actor.ownerUserId, projectId: actor.projectId, authority: actor.authority, role: actor.role }, command }); if (replay) { if (replay.requestFingerprint !== requestFingerprint) conflict('Page command idempotency key collided with a different request.'); const page = await transaction.findVersion(actor.ownerUserId, actor.projectId, pageId, replay.toVersion); if (!page) conflict('Replayed page operation has no durable version.'); return { page, operation: replay, replayed: true, diff: null } } const current = await transaction.findCurrent(actor.ownerUserId, actor.projectId, pageId); if (!current) throw createError({ statusCode: 404, statusMessage: 'Page was not found in this managed site.' }); const result = applyCommandToDocument(current, command, actor, now); if (!await transaction.compareAndAppend(actor.ownerUserId, actor.projectId, command.expectedPageVersion, result.page, result.operation)) conflict('Page draft changed concurrently; no edits were overwritten.'); return { ...result, replayed: false } }

export async function restorePageVersion(repository: PageEditorRepository, actor: PageActor, pageId: string, input: { version: number; expectedPageVersion: number; idempotencyKey: string; reason: string }, now = new Date()) {
  assertActor(actor, true); return repository.transaction(transaction => restorePageVersionInTransaction(transaction, actor, pageId, input, now))
}

export async function restorePageVersionInTransaction(transaction: PageEditorRepository, actor: PageActor, pageId: string, input: { version: number; expectedPageVersion: number; idempotencyKey: string; reason: string }, now = new Date()) { const source = await transaction.findVersion(actor.ownerUserId, actor.projectId, pageId, input.version); const current = await transaction.findCurrent(actor.ownerUserId, actor.projectId, pageId); if (!source || !current) throw createError({ statusCode: 404, statusMessage: 'Requested page version was not found.' }); const command: PageCommand = { schemaVersion: PAGE_COMMAND_VERSION, type: 'restore_version', expectedPageVersion: input.expectedPageVersion, idempotencyKey: input.idempotencyKey, target: { version: input.version }, payload: { sourceFingerprint: source.fingerprint }, reason: input.reason }; if (current.version !== input.expectedPageVersion) conflict('Page draft version is stale; restore did not overwrite newer work.'); const replay = await transaction.findOperation(actor.ownerUserId, actor.projectId, input.idempotencyKey); const requestFingerprint = canonicalFingerprint({ command, actor: actorAuthority(actor) }); if (replay) { if (replay.requestFingerprint !== requestFingerprint) conflict('Restore idempotency key collided.'); return { page: await transaction.findVersion(actor.ownerUserId, actor.projectId, pageId, replay.toVersion), operation: replay, replayed: true } } const page = finalizePageDocument({ ...source, version: current.version + 1, parentVersion: current.version, publicationState: 'draft', actorAuthority: actorAuthority(actor), createdAt: now.toISOString() }); const operation: AppliedPageOperation = { command: { ...command, actorAuthority: actorAuthority(actor) }, fromVersion: current.version, toVersion: page.version, requestFingerprint, resultFingerprint: page.fingerprint, createdAt: now.toISOString() }; if (!await transaction.compareAndAppend(actor.ownerUserId, actor.projectId, current.version, page, operation)) conflict('Page draft changed concurrently; restore did not overwrite it.'); return { page, operation, replayed: false, diff: diffPages(current, page) } }

export async function createPagePublicationIntent(input: { repository: PageEditorRepository; actor: PageActor; pageId: string; expectedPageVersion: number; resolveMedia: MediaAuthorityResolver; releaseReference: string; publicationTargetReference: string; idempotencyKey: string; now?: Date }) {
  assertActor(input.actor, true); if (!input.actor.canPublish || !['platform_owner', 'customer_admin'].includes(input.actor.role)) forbidden('Publisher capability is required to publish a managed page.'); if (!/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,159}$/u.test(input.releaseReference) || !/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,159}$/u.test(input.publicationTargetReference) || !/^[A-Za-z0-9][A-Za-z0-9_.:-]{7,127}$/u.test(input.idempotencyKey)) invalid('Publication authority references are invalid.')
  const page = await input.repository.findCurrent(input.actor.ownerUserId, input.actor.projectId, input.pageId); if (!page) throw createError({ statusCode: 404, statusMessage: 'Page was not found.' }); if (page.version !== input.expectedPageVersion) conflict('Page version is stale; publication intent was not created.'); const artifact = await compilePageDocument({ actor: input.actor, document: page, resolveMedia: input.resolveMedia, mode: 'publish', now: input.now }); const stable = { version: 'managed-site-page-publication-intent-v1', ownerUserId: input.actor.ownerUserId, projectId: input.actor.projectId, pageId: page.pageId, pageVersion: page.version, artifactFingerprint: artifact.artifactFingerprint, mediaSetFingerprint: artifact.mediaSetFingerprint, releaseReference: input.releaseReference, publicationTargetReference: input.publicationTargetReference, idempotencyKey: input.idempotencyKey }; const receipt: PagePublicationReceipt = { pageId: page.pageId, pageVersion: page.version, status: 'intent_created', artifactFingerprint: artifact.artifactFingerprint, mediaSetFingerprint: artifact.mediaSetFingerprint, releaseReference: input.releaseReference, publicationTargetReference: input.publicationTargetReference, receiptFingerprint: canonicalFingerprint(stable), createdAt: (input.now || new Date()).toISOString() }; return { artifact, receipt: await input.repository.appendPublicationReceipt(input.actor.ownerUserId, input.actor.projectId, receipt), externalCalls: false, deployed: false, nextAuthority: 'existing_first_party_publication_and_managed_site_release' as const }
}

export function createPagePreviewGrant(input: { actor: PageActor; page: PageDocument; secret: string; now?: Date; ttlMs?: number }) {
  assertActor(input.actor); if (input.secret.length < 32) throw createError({ statusCode: 503, statusMessage: 'Page preview signing secret is not configured.' }); const now = input.now || new Date(); const expiresAt = new Date(now.getTime() + Math.min(input.ttlMs || 15 * 60 * 1000, 30 * 60 * 1000)); const payload = Buffer.from(JSON.stringify({ v: 1, ownerUserId: input.actor.ownerUserId, projectId: input.actor.projectId, pageId: input.page.pageId, pageVersion: input.page.version, pageFingerprint: input.page.fingerprint, exp: expiresAt.getTime() })).toString('base64url'); const signature = createHmac('sha256', input.secret).update(payload).digest('base64url'); return { token: `${payload}.${signature}`, expiresAt: expiresAt.toISOString(), headers: { 'Cache-Control': 'private, no-store, max-age=0', 'X-Robots-Tag': 'noindex, nofollow, noarchive' } }
}
export function verifyPagePreviewGrant(token: string, secret: string, now = new Date()) {
  const [payload, signature, extra] = token.split('.'); if (!payload || !signature || extra || secret.length < 32) forbidden('Page preview token is invalid.'); const expected = createHmac('sha256', secret).update(payload).digest(); let received: Buffer; try { received = Buffer.from(signature, 'base64url') } catch { forbidden('Page preview token is invalid.') } if (received!.length !== expected.length || !timingSafeEqual(received!, expected)) forbidden('Page preview token signature is invalid.'); let data: any; try { data = JSON.parse(Buffer.from(payload, 'base64url').toString('utf8')) } catch { forbidden('Page preview token payload is invalid.') } if (data.v !== 1 || !Number.isSafeInteger(data.ownerUserId) || !Number.isSafeInteger(data.projectId) || typeof data.pageId !== 'string' || !Number.isSafeInteger(data.pageVersion) || !/^[a-f0-9]{64}$/u.test(data.pageFingerprint) || !Number.isFinite(data.exp) || data.exp <= now.getTime()) forbidden('Page preview token is expired or malformed.'); return data
}
