import { createHash, randomUUID } from 'node:crypto'
import { and, asc, eq, inArray, isNull, lte, ne, or } from 'drizzle-orm'
import { createError } from 'h3'
import { getDatabase } from '../../database'
import { contentOperationPublicationTargets, managedSiteMediaUsageBindings, managedSitePagePublicationAttempts, managedSitePagePublicationReceipts, managedSitePagePublicationWorks, managedSitePages, managedSitePageVersions, managedSiteReleaseProjections } from '../../database/schema'
import { getContentOperationsRuntimeDependencies, type ContentOperationsRuntimeDependencies } from '../../content-operations/runtime-dependencies'
import { executeFirstPartyPublication } from '../../first-party-publishing/executor'
import { planFirstPartyPublication } from '../../first-party-publishing/command'
import type { ApprovedFirstPartyPublication, FirstPartyExecutionResult, FirstPartyPublishTarget } from '../../first-party-publishing/types'
import { getDrizzleMediaVaultRepository } from '../media-vault/repository-drizzle'
import { canonicalFingerprint, canonicalJson, parsePageDocument } from './canonical'
import { compilePageDocument } from './compiler'
import { managedPageRouteSlug, serializeManagedPageTransport } from './transport'
import type { CompiledPageArtifact, PageActor, PageDocument } from './types'

export type PublicationWorkRow = typeof managedSitePagePublicationWorks.$inferSelect
type PublicationTargetRow = typeof contentOperationPublicationTargets.$inferSelect
export type PagePublicationExecutor = (input: { target: FirstPartyPublishTarget; publication: ApprovedFirstPartyPublication; now: Date; dependencies: ContentOperationsRuntimeDependencies }) => Promise<FirstPartyExecutionResult>

const RELEASE_STATES = ['approved', 'payment_verified', 'deployment_pending', 'live_verified', 'geo_active'] as const
const MAX_ATTEMPTS = 5
function ownerScopeKey(ownerUserId: number): string { return `owner-${createHash('sha256').update(String(ownerUserId), 'utf8').digest('hex').slice(0, 32)}` }
function rowsAffected(value: unknown): number { return Number((value as any)?.[0]?.affectedRows || 0) }
function executionActor(work: PublicationWorkRow): PageActor { return { ownerUserId: work.ownerUserId, projectId: work.projectId, actorUserId: null, authority: 'system_workflow', role: 'platform_owner', canPublish: true } }
function targetProjection(row: PublicationTargetRow, work: PublicationWorkRow): FirstPartyPublishTarget {
  if (row.ownerUserId !== work.ownerUserId || row.clientId !== work.clientId || row.id !== work.publicationTargetId || !['astro', 'nuxt'].includes(row.framework) || !['first_party_git', 'first_party_signed_api'].includes(row.transport)) throw Object.assign(new Error('Publication target authority drifted.'), { reasonCode: 'TARGET_AUTHORITY_DRIFT' })
  return { targetId: row.targetId, ownerScopeKey: ownerScopeKey(work.ownerUserId), framework: row.framework as 'astro' | 'nuxt', transport: row.transport as 'first_party_git' | 'first_party_signed_api', targetOrigin: row.targetOrigin, contentRoot: row.contentRoot, defaultBranch: row.defaultBranch || 'main', repositoryOwner: row.repositoryOwner, repositoryName: row.repositoryName, endpointPath: row.endpointPath, credentialReference: row.credentialReference, status: row.status, allowedContentTypes: row.allowedContentTypes as string[], allowedLanguages: row.allowedLanguages as string[], maximumPayloadBytes: row.maximumPayloadBytes, executionEnabled: row.executionEnabled }
}
function publicationProjection(work: PublicationWorkRow, page: PageDocument, artifact: CompiledPageArtifact): ApprovedFirstPartyPublication {
  const body = serializeManagedPageTransport(artifact); if (!body) throw Object.assign(new Error('Compiled page cannot enter the managed-page transport.'), { reasonCode: 'ARTIFACT_BYTES_MISMATCH' }); const contentHash = createHash('sha256').update(body, 'utf8').digest('hex'); if (contentHash !== work.contentHash) throw Object.assign(new Error('Stored transport bytes no longer match the work content hash.'), { reasonCode: 'ARTIFACT_BYTES_MISMATCH' })
  const identity = `managed-page-${work.pageId}-v${work.pageVersion}`; const slug = managedPageRouteSlug(page.route)
  if (!slug) throw Object.assign(new Error('Managed page route cannot be represented by the canonical artifact path.'), { reasonCode: 'ARTIFACT_PATH_INVALID' })
  return { ownerScopeKey: ownerScopeKey(work.ownerUserId), scheduleEntryId: `entry-${identity}`, productionPlanId: `plan-managed-release-${work.releaseId}`, productionDeliverableId: `deliverable-${identity}`, jobId: `job-${identity}`, draftId: `draft-${identity}`, draftVersion: work.pageVersion, draftStage: 'optimized', reviewId: `review-customer-confirmed-${work.id}`, reviewDecision: 'approved_for_delivery', riskGateStatus: 'passed', evidenceSnapshotHash: page.fingerprint, contentHash, title: page.seo.title, body, slug, contentType: 'managed_page', language: page.locale, scheduledAt: work.createdAt.toISOString(), scheduleKey: `managed-page:${work.pageId}:${work.pageVersion}:${work.operationKind}`, authoritySourceIds: [`managed-site-release-${work.releaseId}`, `page-version-${work.pageVersion}`], ruleIds: ['managed-site-page-publish-v1', `page-content-${page.contentType}`, 'customer-confirmed-draft-v1'] }
}

export async function validateAndExecutePublicationWork(input: { work: PublicationWorkRow; page: PageDocument; target: PublicationTargetRow; releaseStatus: string; resolveMedia: Parameters<typeof compilePageDocument>[0]['resolveMedia']; now: Date; dependencies: ContentOperationsRuntimeDependencies; executor?: PagePublicationExecutor }) {
  if (!RELEASE_STATES.includes(input.releaseStatus as any)) throw Object.assign(new Error('Managed-site release authority is no longer publishable.'), { reasonCode: 'RELEASE_REVOKED' })
  if (input.page.version !== input.work.pageVersion || input.page.fingerprint !== input.work.pageFingerprint) throw Object.assign(new Error('Page version changed after publication was queued.'), { reasonCode: 'STALE_PAGE_VERSION' })
  const artifact = await compilePageDocument({ actor: executionActor(input.work), document: input.page, resolveMedia: input.resolveMedia, mode: 'publish', now: input.now, generatedAt: input.work.createdAt })
  if (artifact.artifactFingerprint !== input.work.artifactFingerprint || artifact.mediaSetFingerprint !== input.work.mediaSetFingerprint || canonicalJson(artifact) !== canonicalJson(input.work.artifact)) throw Object.assign(new Error('Page artifact or media authority changed after publication was queued.'), { reasonCode: 'STALE_ARTIFACT_OR_MEDIA' })
  const target = targetProjection(input.target, input.work); if (target.status !== 'active' || !target.executionEnabled) throw Object.assign(new Error('Publication target is revoked or execution-disabled.'), { reasonCode: 'TARGET_REVOKED' })
  const publication = publicationProjection(input.work, input.page, artifact); const plan = planFirstPartyPublication(target, publication, input.now.toISOString()); if (plan.status !== 'planned') return plan
  const executor = input.executor || (async value => executeFirstPartyPublication({ target: value.target, publication: value.publication, now: value.now.toISOString(), serverNow: value.now.toISOString(), mode: 'execute', ...value.dependencies }))
  const result = await executor({ target, publication, now: input.now, dependencies: input.dependencies })
  if (result.status === 'delivered' && (result.publicationId !== publication.productionDeliverableId || result.contentHash !== publication.contentHash || result.artifactFingerprint !== plan.command.artifactFingerprint || result.idempotencyKey !== plan.command.idempotencyKey)) return { status: 'blocked' as const, code: 'RESPONSE_INVALID' as const, reasons: ['first-party delivery receipt did not match the exact planned artifact and identity'] }
  return { ...result, externalCalls: true }
}

export async function claimPagePublicationWorks(database: any, input: { now: Date; limit: number; leaseOwner?: string; leaseMs?: number }) {
  const leaseOwner = input.leaseOwner || `editor-publisher-${randomUUID()}`; const leaseUntil = new Date(input.now.getTime() + Math.min(Math.max(input.leaseMs || 120_000, 10_000), 300_000)); const due = await database.select().from(managedSitePagePublicationWorks).where(and(inArray(managedSitePagePublicationWorks.status, ['queued', 'retry_wait', 'leased']), lte(managedSitePagePublicationWorks.availableAt, input.now), or(isNull(managedSitePagePublicationWorks.leaseUntil), lte(managedSitePagePublicationWorks.leaseUntil, input.now)))).orderBy(asc(managedSitePagePublicationWorks.availableAt), asc(managedSitePagePublicationWorks.id)).limit(Math.min(Math.max(input.limit, 1), 200)); const claimed: PublicationWorkRow[] = []
  for (const candidate of due) { const updated = await database.update(managedSitePagePublicationWorks).set({ status: 'leased', leaseOwner, leaseUntil, attemptCount: candidate.attemptCount + 1, updatedAt: input.now }).where(and(eq(managedSitePagePublicationWorks.id, candidate.id), inArray(managedSitePagePublicationWorks.status, ['queued', 'retry_wait', 'leased']), eq(managedSitePagePublicationWorks.attemptCount, candidate.attemptCount), or(isNull(managedSitePagePublicationWorks.leaseUntil), lte(managedSitePagePublicationWorks.leaseUntil, input.now)))); if (rowsAffected(updated) === 1) claimed.push({ ...candidate, status: 'leased', leaseOwner, leaseUntil, attemptCount: candidate.attemptCount + 1, updatedAt: input.now }) }
  return claimed
}

export async function claimSpecificPagePublicationWork(database: any, workId: number, now: Date, leaseOwner = `editor-publisher-${randomUUID()}`, leaseMs = 120_000): Promise<PublicationWorkRow | null> {
  const [candidate] = await database.select().from(managedSitePagePublicationWorks).where(eq(managedSitePagePublicationWorks.id, workId)).limit(1); if (!candidate || !['queued', 'retry_wait', 'leased'].includes(candidate.status) || candidate.availableAt > now || candidate.leaseUntil && candidate.leaseUntil > now) return null; const leaseUntil = new Date(now.getTime() + Math.min(Math.max(leaseMs, 10_000), 600_000)); const updated = await database.update(managedSitePagePublicationWorks).set({ status: 'leased', leaseOwner, leaseUntil, attemptCount: candidate.attemptCount + 1, updatedAt: now }).where(and(eq(managedSitePagePublicationWorks.id, workId), eq(managedSitePagePublicationWorks.attemptCount, candidate.attemptCount), inArray(managedSitePagePublicationWorks.status, ['queued', 'retry_wait', 'leased']), or(isNull(managedSitePagePublicationWorks.leaseUntil), lte(managedSitePagePublicationWorks.leaseUntil, now)))); return rowsAffected(updated) === 1 ? { ...candidate, status: 'leased', leaseOwner, leaseUntil, attemptCount: candidate.attemptCount + 1, updatedAt: now } : null
}

export async function executeDrizzlePagePublicationWork(work: PublicationWorkRow, input: { now?: Date; database?: any; dependencies?: ContentOperationsRuntimeDependencies; executor?: PagePublicationExecutor } = {}) {
  const database = input.database || getDatabase(); if (!database) throw createError({ statusCode: 503, statusMessage: 'Publication database is unavailable.' }); const now = input.now || new Date(); const media = getDrizzleMediaVaultRepository(database)
  const [pageRow] = await database.select({ currentDraftVersion: managedSitePages.currentDraftVersion }).from(managedSitePages).where(and(eq(managedSitePages.ownerUserId, work.ownerUserId), eq(managedSitePages.projectId, work.projectId), eq(managedSitePages.pageId, work.pageId))).limit(1)
  const [versionRow] = await database.select({ document: managedSitePageVersions.document }).from(managedSitePageVersions).where(and(eq(managedSitePageVersions.ownerUserId, work.ownerUserId), eq(managedSitePageVersions.projectId, work.projectId), eq(managedSitePageVersions.pageId, work.pageId), eq(managedSitePageVersions.version, work.pageVersion))).limit(1)
  const [target] = await database.select().from(contentOperationPublicationTargets).where(eq(contentOperationPublicationTargets.id, work.publicationTargetId)).limit(1); const [release] = await database.select({ status: managedSiteReleaseProjections.status }).from(managedSiteReleaseProjections).where(and(eq(managedSiteReleaseProjections.id, work.releaseId), eq(managedSiteReleaseProjections.ownerUserId, work.ownerUserId), eq(managedSiteReleaseProjections.projectId, work.projectId))).limit(1)
  let result: FirstPartyExecutionResult
  try { if (!pageRow || pageRow.currentDraftVersion !== work.pageVersion || !versionRow || !target || !release) throw Object.assign(new Error('Publication authority lineage is missing or stale.'), { reasonCode: 'STALE_PUBLICATION_AUTHORITY' }); const page = parsePageDocument(versionRow.document); result = await validateAndExecutePublicationWork({ work, page, target, releaseStatus: release.status, resolveMedia: (actor, binding) => media.findAsset(actor, binding.assetId), now, dependencies: input.dependencies || getContentOperationsRuntimeDependencies(), executor: input.executor }) } catch (error: any) { result = { status: 'blocked', code: error?.reasonCode || 'INVALID_INPUT', reasons: [String(error?.message || 'Publication validation failed.').slice(0, 500)] } as FirstPartyExecutionResult }
  const retry = result.status === 'retryable_failure' && work.attemptCount < Math.min(work.maxAttempts, MAX_ATTEMPTS); const terminalSuccess = result.status === 'delivered'; const terminalBlocked = !terminalSuccess && !retry; const attemptStatus = result.status === 'delivered' ? 'delivered' : result.status === 'retryable_failure' ? 'retryable_failure' : result.status === 'permanent_failure' ? 'permanent_failure' : 'blocked'; const errorCode = result.status === 'delivered' ? null : result.status === 'dry_run' ? 'DRY_RUN_NOT_DELIVERY' : result.code; const receiptFingerprint = canonicalFingerprint({ version: 'managed-site-page-publication-attempt-v1', workId: work.id, attemptNumber: work.attemptCount, requestFingerprint: work.requestFingerprint, result })
  await database.transaction(async (transaction: any) => {
    await transaction.insert(managedSitePagePublicationAttempts).values({ workId: work.id, ownerUserId: work.ownerUserId, projectId: work.projectId, publicationTargetId: work.publicationTargetId, attemptNumber: work.attemptCount, idempotencyKey: work.idempotencyKey, requestFingerprint: work.requestFingerprint, status: attemptStatus, receiptFingerprint, remoteRevision: result.status === 'delivered' ? result.remoteRevision : null, remoteState: result.status === 'delivered' ? result.remoteState : null, errorCode, result, createdAt: now })
    if (terminalSuccess) await transaction.update(managedSitePagePublicationWorks).set({ status: 'succeeded', leaseOwner: null, leaseUntil: null, lastErrorCode: null, updatedAt: now }).where(and(eq(managedSitePagePublicationWorks.id, work.id), eq(managedSitePagePublicationWorks.status, 'leased'), eq(managedSitePagePublicationWorks.leaseOwner, work.leaseOwner!)))
    else if (retry) await transaction.update(managedSitePagePublicationWorks).set({ status: 'retry_wait', availableAt: new Date(now.getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, work.attemptCount - 1))), leaseOwner: null, leaseUntil: null, lastErrorCode: errorCode, updatedAt: now }).where(and(eq(managedSitePagePublicationWorks.id, work.id), eq(managedSitePagePublicationWorks.status, 'leased'), eq(managedSitePagePublicationWorks.leaseOwner, work.leaseOwner!)))
    else await transaction.update(managedSitePagePublicationWorks).set({ status: 'blocked', leaseOwner: null, leaseUntil: null, lastErrorCode: errorCode, updatedAt: now }).where(and(eq(managedSitePagePublicationWorks.id, work.id), eq(managedSitePagePublicationWorks.status, 'leased'), eq(managedSitePagePublicationWorks.leaseOwner, work.leaseOwner!)))
    await transaction.update(managedSitePagePublicationReceipts).set({ status: terminalSuccess ? (work.operationKind === 'rollback' ? 'rolled_back' : 'succeeded') : retry ? 'publishing' : 'failed', providerReceiptReference: terminalSuccess ? receiptFingerprint : null }).where(and(eq(managedSitePagePublicationReceipts.ownerUserId, work.ownerUserId), eq(managedSitePagePublicationReceipts.projectId, work.projectId), eq(managedSitePagePublicationReceipts.pageId, work.pageId), eq(managedSitePagePublicationReceipts.pageVersion, work.pageVersion), eq(managedSitePagePublicationReceipts.publicationTargetId, work.publicationTargetId)))
    if (terminalBlocked) await transaction.update(managedSitePages).set({ status: 'failed', updatedAt: now }).where(and(eq(managedSitePages.ownerUserId, work.ownerUserId), eq(managedSitePages.projectId, work.projectId), eq(managedSitePages.pageId, work.pageId), eq(managedSitePages.currentDraftVersion, work.pageVersion)))
    if (terminalSuccess) {
      const unfinished = await transaction.select({ id: managedSitePagePublicationWorks.id }).from(managedSitePagePublicationWorks).where(and(eq(managedSitePagePublicationWorks.ownerUserId, work.ownerUserId), eq(managedSitePagePublicationWorks.projectId, work.projectId), eq(managedSitePagePublicationWorks.pageId, work.pageId), eq(managedSitePagePublicationWorks.pageVersion, work.pageVersion), eq(managedSitePagePublicationWorks.idempotencyKey, work.idempotencyKey), ne(managedSitePagePublicationWorks.status, 'succeeded'))).limit(1)
      if (!unfinished.length) {
        await transaction.update(managedSitePageVersions).set({ lifecycleStatus: work.operationKind === 'rollback' ? 'rolled_back' : 'published' }).where(and(eq(managedSitePageVersions.ownerUserId, work.ownerUserId), eq(managedSitePageVersions.projectId, work.projectId), eq(managedSitePageVersions.pageId, work.pageId), eq(managedSitePageVersions.version, work.pageVersion)))
        await transaction.update(managedSitePages).set({ publishedVersion: work.pageVersion, status: 'published', updatedAt: now }).where(and(eq(managedSitePages.ownerUserId, work.ownerUserId), eq(managedSitePages.projectId, work.projectId), eq(managedSitePages.pageId, work.pageId), eq(managedSitePages.currentDraftVersion, work.pageVersion)))
        await transaction.update(managedSiteMediaUsageBindings).set({ releasedAt: now }).where(and(eq(managedSiteMediaUsageBindings.ownerUserId, work.ownerUserId), eq(managedSiteMediaUsageBindings.projectId, work.projectId), eq(managedSiteMediaUsageBindings.pageId, work.pageId), ne(managedSiteMediaUsageBindings.pageVersion, work.pageVersion), isNull(managedSiteMediaUsageBindings.releasedAt)))
      }
    }
  })
  return { workId: work.id, status: terminalSuccess ? 'succeeded' : retry ? 'retry_wait' : 'blocked', attemptNumber: work.attemptCount, receiptFingerprint, result, externalCalls: (result as any).externalCalls === true }
}
