import { and, desc, eq, isNull } from 'drizzle-orm'
import { createError } from 'h3'
import { getDatabase } from '../../database'
import { managedSiteMediaUsageBindings, managedSitePageOperations, managedSitePagePublicationReceipts, managedSitePages, managedSitePageVersions } from '../../database/schema'
import { canonicalFingerprint, parsePageDocument } from './canonical'
import type { AppliedPageOperation, PageDocument, PageEditorRepository, PagePublicationReceipt } from './types'

function dbOrThrow() { const database = getDatabase(); if (!database) throw createError({ statusCode: 503, statusMessage: 'Page editor database is unavailable.' }); return database }
function rowsAffected(value: unknown): number { return Number((value as any)?.[0]?.affectedRows || 0) }
function receipt(row: typeof managedSitePagePublicationReceipts.$inferSelect): PagePublicationReceipt { return { pageId: row.pageId, pageVersion: row.pageVersion, status: row.status === 'publishing' || row.status === 'rollback_pending' ? 'intent_created' : row.status, artifactFingerprint: row.artifactFingerprint, mediaSetFingerprint: row.mediaSetFingerprint, releaseReference: row.releaseId ? `release:${row.releaseId}` : null, publicationTargetReference: row.publicationTargetId ? `target:${row.publicationTargetId}` : null, receiptFingerprint: row.receiptFingerprint, createdAt: row.createdAt.toISOString() } }
export function makeDrizzlePageEditorRepository(database: any): PageEditorRepository {
  const repository: PageEditorRepository = {
    async transaction<T>(work: (repository: PageEditorRepository) => Promise<T>) { return database.transaction((transaction: any) => work(makeDrizzlePageEditorRepository(transaction))) as Promise<T> },
    async listPages(ownerUserId, projectId) { const rows = await database.select({ pageId: managedSitePages.pageId }).from(managedSitePages).where(and(eq(managedSitePages.ownerUserId, ownerUserId), eq(managedSitePages.projectId, projectId))).limit(100); return (await Promise.all(rows.map((row: { pageId: string }) => repository.findCurrent(ownerUserId, projectId, row.pageId)))).filter(Boolean) as PageDocument[] },
    async findCurrent(ownerUserId, projectId, pageId) { const [page] = await database.select({ version: managedSitePages.currentDraftVersion }).from(managedSitePages).where(and(eq(managedSitePages.ownerUserId, ownerUserId), eq(managedSitePages.projectId, projectId), eq(managedSitePages.pageId, pageId))).limit(1); return page ? repository.findVersion(ownerUserId, projectId, pageId, page.version) : null },
    async findVersion(ownerUserId, projectId, pageId, version) { const [row] = await database.select({ document: managedSitePageVersions.document }).from(managedSitePageVersions).where(and(eq(managedSitePageVersions.ownerUserId, ownerUserId), eq(managedSitePageVersions.projectId, projectId), eq(managedSitePageVersions.pageId, pageId), eq(managedSitePageVersions.version, version))).limit(1); return row ? parsePageDocument(row.document) : null },
    async listVersions(ownerUserId, projectId, pageId) { const rows = await database.select({ document: managedSitePageVersions.document }).from(managedSitePageVersions).where(and(eq(managedSitePageVersions.ownerUserId, ownerUserId), eq(managedSitePageVersions.projectId, projectId), eq(managedSitePageVersions.pageId, pageId))).orderBy(desc(managedSitePageVersions.version)).limit(200); return rows.map((row: { document: unknown }) => parsePageDocument(row.document)) },
    async insertInitial(ownerUserId, projectId, page) { const parsed = parsePageDocument(page); await database.transaction(async (transaction: any) => { await transaction.insert(managedSitePages).values({ pageId: parsed.pageId, ownerUserId, projectId, locale: parsed.locale, route: parsed.route, contentType: parsed.contentType, currentDraftVersion: 1, publishedVersion: 0, status: 'draft' }); await transaction.insert(managedSitePageVersions).values({ ownerUserId, projectId, pageId: parsed.pageId, version: 1, parentVersion: null, document: parsed, documentFingerprint: parsed.fingerprint, lifecycleStatus: 'draft', actorAuthority: parsed.actorAuthority, createdAt: new Date(parsed.createdAt) }) }) },
    async compareAndAppend(ownerUserId, projectId, expectedVersion, page, operation) { const updated = await database.update(managedSitePages).set({ currentDraftVersion: page.version, status: 'draft', updatedAt: new Date() }).where(and(eq(managedSitePages.ownerUserId, ownerUserId), eq(managedSitePages.projectId, projectId), eq(managedSitePages.pageId, page.pageId), eq(managedSitePages.currentDraftVersion, expectedVersion))); if (rowsAffected(updated) !== 1) return false; await database.insert(managedSitePageVersions).values({ ownerUserId, projectId, pageId: page.pageId, version: page.version, parentVersion: page.parentVersion, document: page, documentFingerprint: page.fingerprint, lifecycleStatus: 'draft', actorAuthority: page.actorAuthority, createdAt: new Date(page.createdAt) }); await database.insert(managedSitePageOperations).values({ ownerUserId, projectId, pageId: page.pageId, fromVersion: operation.fromVersion, toVersion: operation.toVersion, commandType: operation.command.type, command: operation.command, idempotencyKey: operation.command.idempotencyKey, requestFingerprint: operation.requestFingerprint, actorAuthority: operation.command.actorAuthority, createdAt: new Date(operation.createdAt) }); return true },
    async findOperation(ownerUserId, projectId, idempotencyKey) { const [row] = await database.select().from(managedSitePageOperations).where(and(eq(managedSitePageOperations.ownerUserId, ownerUserId), eq(managedSitePageOperations.projectId, projectId), eq(managedSitePageOperations.idempotencyKey, idempotencyKey))).limit(1); if (!row) return null; return { command: row.command as AppliedPageOperation['command'], fromVersion: row.fromVersion, toVersion: row.toVersion, requestFingerprint: row.requestFingerprint, resultFingerprint: (await repository.findVersion(ownerUserId, projectId, row.pageId, row.toVersion))?.fingerprint || '', createdAt: row.createdAt.toISOString() } },
    async appendPublicationReceipt(ownerUserId, projectId, input) {
      const [existing] = await database.select().from(managedSitePagePublicationReceipts).where(eq(managedSitePagePublicationReceipts.receiptFingerprint, input.receiptFingerprint)).limit(1)
      if (existing) return receipt(existing)
      const releaseId = Number(input.releaseReference?.split(':').at(-1)); const targetId = Number(input.publicationTargetReference?.split(':').at(-1))
      await database.transaction(async (transaction: any) => {
        await transaction.insert(managedSitePagePublicationReceipts).values({ ownerUserId, projectId, pageId: input.pageId, pageVersion: input.pageVersion, releaseId: Number.isSafeInteger(releaseId) ? releaseId : null, publicationTargetId: Number.isSafeInteger(targetId) ? targetId : null, status: input.status, artifactFingerprint: input.artifactFingerprint, mediaSetFingerprint: input.mediaSetFingerprint, receiptFingerprint: input.receiptFingerprint, providerReceiptReference: null, createdAt: new Date(input.createdAt) })
        const page = await repository.findVersion(ownerUserId, projectId, input.pageId, input.pageVersion); if (!page) throw createError({ statusCode: 409, statusMessage: 'Publication receipt has no exact PageDocument version.' })
        await transaction.update(managedSiteMediaUsageBindings).set({ releasedAt: new Date() }).where(and(eq(managedSiteMediaUsageBindings.ownerUserId, ownerUserId), eq(managedSiteMediaUsageBindings.projectId, projectId), eq(managedSiteMediaUsageBindings.pageId, input.pageId), isNull(managedSiteMediaUsageBindings.releasedAt)))
        if (page.mediaBindings.length) await transaction.insert(managedSiteMediaUsageBindings).values(page.mediaBindings.map(binding => { const block = page.sections.find(section => section.mediaBindingIds.includes(binding.bindingId)); const bindingFingerprint = canonicalFingerprint({ version: 'managed-site-media-usage-v1', ownerUserId, projectId, pageId: page.pageId, pageVersion: page.version, blockId: block?.blockId || 'seo', role: binding.role, assetId: binding.assetId, assetVersion: binding.assetVersion, assetSha256: binding.assetSha256 }); return { ownerUserId, projectId, assetId: binding.assetId, assetVersion: binding.assetVersion, assetSha256: binding.assetSha256, pageId: page.pageId, pageVersion: page.version, blockId: block?.blockId || 'seo', role: binding.role, bindingFingerprint, releasedAt: null } }))
      })
      const [created] = await database.select().from(managedSitePagePublicationReceipts).where(eq(managedSitePagePublicationReceipts.receiptFingerprint, input.receiptFingerprint)).limit(1)
      return receipt(created!)
    },
    async listPublicationReceipts(ownerUserId, projectId, pageId) { const rows = await database.select().from(managedSitePagePublicationReceipts).where(and(eq(managedSitePagePublicationReceipts.ownerUserId, ownerUserId), eq(managedSitePagePublicationReceipts.projectId, projectId), eq(managedSitePagePublicationReceipts.pageId, pageId))).orderBy(desc(managedSitePagePublicationReceipts.createdAt)).limit(200); return rows.map(receipt) },
  }; return repository
}
export function getDrizzlePageEditorRepository(): PageEditorRepository { return makeDrizzlePageEditorRepository(dbOrThrow()) }
