import { and, asc, eq, inArray, isNull, lte, or } from 'drizzle-orm'
import { getDatabase } from '../../database'
import { managedSiteMediaAssets, managedSiteMediaEvents, managedSiteMediaProcessingRuns, managedSiteMediaUploadSessions, managedSitePagePublicationReceipts } from '../../database/schema'
import { stableFingerprint } from '../../seo-geo-core/repository'

export async function runDrizzleEditorMaintenance(now = new Date(), limit = 100) {
  const database = getDatabase(); if (!database) return { status: 'blocked', reasonCode: 'DATABASE_UNAVAILABLE', expiredUploads: 0, retentionDue: 0, processingDue: 0, publishRetriesDue: 0, externalCalls: false }
  const uploads = await database.select({ id: managedSiteMediaUploadSessions.id, ownerUserId: managedSiteMediaUploadSessions.ownerUserId, projectId: managedSiteMediaUploadSessions.projectId, uploadId: managedSiteMediaUploadSessions.uploadId, assetId: managedSiteMediaUploadSessions.assetId }).from(managedSiteMediaUploadSessions).where(and(inArray(managedSiteMediaUploadSessions.status, ['issued', 'uploading', 'uploaded']), lte(managedSiteMediaUploadSessions.expiresAt, now))).orderBy(asc(managedSiteMediaUploadSessions.expiresAt)).limit(limit)
  for (const upload of uploads) { await database.transaction(async transaction => { await transaction.update(managedSiteMediaUploadSessions).set({ status: 'expired' }).where(and(eq(managedSiteMediaUploadSessions.id, upload.id), inArray(managedSiteMediaUploadSessions.status, ['issued', 'uploading', 'uploaded']))); const receiptFingerprint = stableFingerprint({ action: 'orphan_upload_expired', uploadId: upload.uploadId, at: now.toISOString() }); await transaction.insert(managedSiteMediaEvents).values({ ownerUserId: upload.ownerUserId, projectId: upload.projectId, assetId: upload.assetId, uploadId: upload.uploadId, eventType: 'orphan_upload_expired', actorAuthority: 'system_workflow', beforeFingerprint: null, afterFingerprint: null, metadata: { objectDeletionRequired: true }, receiptFingerprint, occurredAt: now }).onDuplicateKeyUpdate({ set: { receiptFingerprint } }) }) }
  const retention = await database.select({ ownerUserId: managedSiteMediaAssets.ownerUserId, projectId: managedSiteMediaAssets.projectId, assetId: managedSiteMediaAssets.assetId }).from(managedSiteMediaAssets).where(and(eq(managedSiteMediaAssets.status, 'trashed'), lte(managedSiteMediaAssets.retentionUntil, now))).limit(limit)
  for (const asset of retention) { const receiptFingerprint = stableFingerprint({ action: 'trash_retention_due', assetId: asset.assetId, at: now.toISOString().slice(0, 10) }); await database.insert(managedSiteMediaEvents).values({ ...asset, uploadId: null, eventType: 'trash_retention_due', actorAuthority: 'system_workflow', beforeFingerprint: null, afterFingerprint: null, metadata: { automaticPermanentDeletion: false, ownerConfirmationRequired: true }, receiptFingerprint, occurredAt: now }).onDuplicateKeyUpdate({ set: { receiptFingerprint } }) }
  const processing = await database.select({ id: managedSiteMediaProcessingRuns.id }).from(managedSiteMediaProcessingRuns).where(and(inArray(managedSiteMediaProcessingRuns.status, ['queued', 'retry_wait']), or(isNull(managedSiteMediaProcessingRuns.nextAttemptAt), lte(managedSiteMediaProcessingRuns.nextAttemptAt, now)), or(isNull(managedSiteMediaProcessingRuns.leaseUntil), lte(managedSiteMediaProcessingRuns.leaseUntil, now)))).limit(limit)
  const retries = await database.select({ id: managedSitePagePublicationReceipts.id }).from(managedSitePagePublicationReceipts).where(eq(managedSitePagePublicationReceipts.status, 'failed')).limit(limit)
  return { status: 'completed', expiredUploads: uploads.length, retentionDue: retention.length, processingDue: processing.length, publishRetriesDue: retries.length, processingExecuted: 0, publishRetriesExecuted: 0, externalCalls: false, limitations: ['Processing and publication retries require their separately governed adapter/authority; this maintenance tick only discovers due work and safely expires orphan sessions.'] }
}
