import { randomUUID } from 'node:crypto'
import { and, asc, eq, inArray, isNull, lt, lte, or } from 'drizzle-orm'
import { getDatabase } from '../../database'
import { managedSiteEditorJobReceipts, managedSiteEditorJobs, managedSiteMediaAssets, managedSiteMediaAssetVersions, managedSiteMediaEvents, managedSiteMediaProcessingRuns, managedSiteMediaUploadSessions, managedSitePagePublicationWorks, managedSitePages, managedSitePageVersions } from '../../database/schema'
import { stableFingerprint } from '../../seo-geo-core/repository'
import { resolveEditorRuntime } from './runtime'
import { retryMediaProcessing } from '../media-vault/service'
import { applyPageCommand } from './engine'
import { parsePageDocument } from './canonical'
import { claimSpecificPagePublicationWork, executeDrizzlePagePublicationWork } from './publication-runtime'
import { EDITOR_SCHEDULER_LIMITS, runEditorSchedulerTick, type EditorJobHandlers, type EditorSchedulerJob, type EditorSchedulerPort } from './scheduler'

function rowsAffected(value: unknown): number { return Number((value as any)?.[0]?.affectedRows || 0) }
export const ORPHAN_UPLOAD_EXPIRY_STATUSES = ['issued', 'uploading', 'uploaded', 'completing', 'expired', 'rejected'] as const
export function editorJobId(kind: string, source: string, fingerprint: string): string { return `edj_${stableFingerprint({ kind, source, fingerprint }).slice(0, 48)}` }
function timestamp(value: Date | string | null | undefined): string | null { return value instanceof Date ? value.toISOString() : value ? new Date(value).toISOString() : null }
export function publicationJobStateFingerprint(work: { status: string; attemptCount: number; availableAt: Date | string; requestFingerprint: string }): string { return stableFingerprint({ version: 'managed-site-publication-source-state-v1', status: work.status, attemptCount: work.attemptCount, availableAt: timestamp(work.availableAt), requestFingerprint: work.requestFingerprint }) }
export function mediaProcessingJobStateFingerprint(run: { status: string; attemptCount: number; nextAttemptAt: Date | string | null; leaseUntil?: Date | string | null; processingFingerprint: string }): string { return stableFingerprint({ version: 'managed-site-media-processing-source-state-v1', status: run.status, attemptCount: run.attemptCount, nextAttemptAt: timestamp(run.nextAttemptAt), leaseUntil: timestamp(run.leaseUntil), processingFingerprint: run.processingFingerprint }) }
export function isMediaProcessingSourceDue(run: { status: string; nextAttemptAt: Date | null; leaseUntil: Date | null }, now: Date): boolean { if (run.status === 'processing') return Boolean(run.leaseUntil && run.leaseUntil <= now); return ['queued', 'retry_wait', 'failed'].includes(run.status) && (!run.nextAttemptAt || run.nextAttemptAt <= now) && (!run.leaseUntil || run.leaseUntil <= now) }
async function enqueue(database: any, value: { ownerUserId: number; projectId: number; kind: EditorSchedulerJob['kind']; sourceReference: string; stateFingerprint: string; payload: Record<string, unknown>; availableAt?: Date }) { await database.insert(managedSiteEditorJobs).values({ jobId: editorJobId(value.kind, value.sourceReference, value.stateFingerprint), ...value, status: 'queued', availableAt: value.availableAt || new Date() }).onDuplicateKeyUpdate({ set: { stateFingerprint: value.stateFingerprint } }) }

export async function discoverDrizzleEditorJobs(database: any, now: Date, sourceLimit = 200) {
  let discovered = 0
  const publications = await database.select().from(managedSitePagePublicationWorks).where(and(inArray(managedSitePagePublicationWorks.status, ['queued', 'retry_wait', 'leased']), lte(managedSitePagePublicationWorks.availableAt, now), or(isNull(managedSitePagePublicationWorks.leaseUntil), lte(managedSitePagePublicationWorks.leaseUntil, now)))).orderBy(asc(managedSitePagePublicationWorks.availableAt)).limit(sourceLimit)
  for (const work of publications) { await enqueue(database, { ownerUserId: work.ownerUserId, projectId: work.projectId, kind: 'publish_retry', sourceReference: `publication-work:${work.id}`, stateFingerprint: publicationJobStateFingerprint(work), payload: { workId: work.id }, availableAt: work.availableAt }); discovered++ }
  const processing = await database.select({ run: managedSiteMediaProcessingRuns, assetId: managedSiteMediaAssetVersions.assetId }).from(managedSiteMediaProcessingRuns).innerJoin(managedSiteMediaAssetVersions, eq(managedSiteMediaProcessingRuns.assetVersionId, managedSiteMediaAssetVersions.id)).where(and(lt(managedSiteMediaProcessingRuns.attemptCount, EDITOR_SCHEDULER_LIMITS.maxAttempts), or(and(inArray(managedSiteMediaProcessingRuns.status, ['queued', 'retry_wait', 'failed']), or(isNull(managedSiteMediaProcessingRuns.nextAttemptAt), lte(managedSiteMediaProcessingRuns.nextAttemptAt, now)), or(isNull(managedSiteMediaProcessingRuns.leaseUntil), lte(managedSiteMediaProcessingRuns.leaseUntil, now))), and(eq(managedSiteMediaProcessingRuns.status, 'processing'), lte(managedSiteMediaProcessingRuns.leaseUntil, now))))).limit(sourceLimit)
  for (const row of processing) { await enqueue(database, { ownerUserId: row.run.ownerUserId, projectId: row.run.projectId, kind: 'media_processing', sourceReference: `media-processing:${row.run.id}`, stateFingerprint: mediaProcessingJobStateFingerprint(row.run), payload: { processingRunId: row.run.id, assetId: row.assetId, sourceAttemptCount: row.run.attemptCount }, availableAt: row.run.nextAttemptAt || now }); discovered++ }
  const uploads = await database.select().from(managedSiteMediaUploadSessions).where(and(inArray(managedSiteMediaUploadSessions.status, [...ORPHAN_UPLOAD_EXPIRY_STATUSES]), lte(managedSiteMediaUploadSessions.expiresAt, now))).limit(sourceLimit)
  for (const upload of uploads) { const fingerprint = stableFingerprint({ uploadId: upload.uploadId, requestFingerprint: upload.requestFingerprint, expiresAt: upload.expiresAt.toISOString() }); await enqueue(database, { ownerUserId: upload.ownerUserId, projectId: upload.projectId, kind: 'orphan_upload_expiry', sourceReference: `upload:${upload.id}`, stateFingerprint: fingerprint, payload: { uploadRowId: upload.id, uploadId: upload.uploadId, assetId: upload.assetId, objectKey: upload.objectKey, quotaIdempotencyKey: upload.idempotencyKey, quotaRequestFingerprint: upload.requestFingerprint } }); discovered++ }
  const trash = await database.select().from(managedSiteMediaAssets).where(and(eq(managedSiteMediaAssets.status, 'trashed'), lte(managedSiteMediaAssets.retentionUntil, now))).limit(sourceLimit)
  for (const asset of trash) { const fingerprint = stableFingerprint({ assetId: asset.assetId, retentionUntil: asset.retentionUntil?.toISOString() }); await enqueue(database, { ownerUserId: asset.ownerUserId, projectId: asset.projectId, kind: 'trash_retention', sourceReference: `asset:${asset.id}`, stateFingerprint: fingerprint, payload: { assetId: asset.assetId } }); discovered++ }
  const pages = await database.select({ ownerUserId: managedSitePages.ownerUserId, projectId: managedSitePages.projectId, pageId: managedSitePages.pageId, version: managedSitePages.currentDraftVersion, document: managedSitePageVersions.document }).from(managedSitePages).innerJoin(managedSitePageVersions, and(eq(managedSitePageVersions.pageId, managedSitePages.pageId), eq(managedSitePageVersions.version, managedSitePages.currentDraftVersion))).limit(sourceLimit)
  for (const row of pages) { const page = parsePageDocument(row.document); for (const block of page.sections) { if (!block.schedule) continue; const from = block.schedule.visibleFrom ? Date.parse(block.schedule.visibleFrom) : null; const until = block.schedule.visibleUntil ? Date.parse(block.schedule.visibleUntil) : null; const desired = (from === null || from <= now.getTime()) && (until === null || until > now.getTime()); if (desired === block.visible) continue; const fingerprint = stableFingerprint({ pageId: page.pageId, version: page.version, blockId: block.blockId, schedule: block.schedule, desired }); await enqueue(database, { ownerUserId: row.ownerUserId, projectId: row.projectId, kind: 'scheduled_visibility', sourceReference: `page:${page.pageId}:block:${block.blockId}`, stateFingerprint: fingerprint, payload: { pageId: page.pageId, pageVersion: page.version, blockId: block.blockId, desired } }); discovered++ } }
  return { discovered, publications: publications.length, processing: processing.length, uploads: uploads.length, trash: trash.length }
}

export function createDrizzleEditorSchedulerPort(database: any, leaseOwner = `editor-scheduler-${randomUUID()}`): EditorSchedulerPort {
  async function record(target: any, job: EditorSchedulerJob, status: 'succeeded' | 'retry_wait' | 'blocked', outcome: string, reasonCode: string | null, fingerprint: string, now: Date, metadata: Record<string, unknown>) { await target.insert(managedSiteEditorJobReceipts).values({ jobId: job.jobId, ownerUserId: job.ownerUserId, projectId: job.projectId, attemptNumber: job.attempt, status, outcome, reasonCode, receiptFingerprint: fingerprint, metadata, createdAt: now }) }
  return {
    async claim(input) { const candidates = await database.select().from(managedSiteEditorJobs).where(and(inArray(managedSiteEditorJobs.status, ['queued', 'retry_wait', 'leased']), lte(managedSiteEditorJobs.availableAt, input.now), or(isNull(managedSiteEditorJobs.leaseUntil), lte(managedSiteEditorJobs.leaseUntil, input.now)))).orderBy(asc(managedSiteEditorJobs.availableAt), asc(managedSiteEditorJobs.id)).limit(Math.min(input.maxTenants * input.maxPerTenant * 4, 800)); const tenants = new Set<string>(); const counts = new Map<string, number>(); const claimed: EditorSchedulerJob[] = []; for (const row of candidates) { if (claimed.length >= input.maxTotal) break; const tenant = `${row.ownerUserId}:${row.projectId}`; if ((!tenants.has(tenant) && tenants.size >= input.maxTenants) || (counts.get(tenant) || 0) >= input.maxPerTenant) continue; const updated = await database.update(managedSiteEditorJobs).set({ status: 'leased', leaseOwner, leaseUntil: input.leaseUntil, attemptCount: row.attemptCount + 1, updatedAt: input.now }).where(and(eq(managedSiteEditorJobs.id, row.id), eq(managedSiteEditorJobs.attemptCount, row.attemptCount), inArray(managedSiteEditorJobs.status, ['queued', 'retry_wait', 'leased']), or(isNull(managedSiteEditorJobs.leaseUntil), lte(managedSiteEditorJobs.leaseUntil, input.now)))); if (rowsAffected(updated) !== 1) continue; tenants.add(tenant); counts.set(tenant, (counts.get(tenant) || 0) + 1); claimed.push({ jobId: row.jobId, ownerUserId: row.ownerUserId, projectId: row.projectId, kind: row.kind, attempt: row.attemptCount + 1, availableAt: row.availableAt.toISOString(), leaseUntil: input.leaseUntil.toISOString(), stateFingerprint: row.stateFingerprint, sourceReference: row.sourceReference, payload: row.payload as Record<string, unknown> }) } return claimed },
    async succeed(job, receipt, now) { await database.transaction(async (transaction: any) => { const updated = await transaction.update(managedSiteEditorJobs).set({ status: 'succeeded', leaseOwner: null, leaseUntil: null, updatedAt: now }).where(and(eq(managedSiteEditorJobs.jobId, job.jobId), eq(managedSiteEditorJobs.status, 'leased'), eq(managedSiteEditorJobs.leaseOwner, leaseOwner), eq(managedSiteEditorJobs.attemptCount, job.attempt))); if (rowsAffected(updated) !== 1) throw Object.assign(new Error('Scheduler success lease was lost.'), { reasonCode: 'SCHEDULER_LEASE_LOST' }); await record(transaction, job, 'succeeded', receipt.outcome, null, receipt.fingerprint, now, { sourceReference: job.sourceReference }) }) },
    async retry(job, input, now) { await database.transaction(async (transaction: any) => { const fingerprint = stableFingerprint({ jobId: job.jobId, attempt: job.attempt, status: 'retry_wait', reasonCode: input.reasonCode, nextAttemptAt: input.nextAttemptAt.toISOString() }); const updated = await transaction.update(managedSiteEditorJobs).set({ status: 'retry_wait', availableAt: input.nextAttemptAt, leaseOwner: null, leaseUntil: null, lastErrorCode: input.reasonCode, updatedAt: now }).where(and(eq(managedSiteEditorJobs.jobId, job.jobId), eq(managedSiteEditorJobs.status, 'leased'), eq(managedSiteEditorJobs.leaseOwner, leaseOwner), eq(managedSiteEditorJobs.attemptCount, job.attempt))); if (rowsAffected(updated) !== 1) throw Object.assign(new Error('Scheduler retry lease was lost.'), { reasonCode: 'SCHEDULER_LEASE_LOST' }); await record(transaction, job, 'retry_wait', 'handler_retry', input.reasonCode, fingerprint, now, { nextAttemptAt: input.nextAttemptAt.toISOString() }) }) },
    async block(job, reasonCode, now) { await database.transaction(async (transaction: any) => { const fingerprint = stableFingerprint({ jobId: job.jobId, attempt: job.attempt, status: 'blocked', reasonCode }); const updated = await transaction.update(managedSiteEditorJobs).set({ status: 'blocked', leaseOwner: null, leaseUntil: null, lastErrorCode: reasonCode, updatedAt: now }).where(and(eq(managedSiteEditorJobs.jobId, job.jobId), eq(managedSiteEditorJobs.status, 'leased'), eq(managedSiteEditorJobs.leaseOwner, leaseOwner), eq(managedSiteEditorJobs.attemptCount, job.attempt))); if (rowsAffected(updated) !== 1) throw Object.assign(new Error('Scheduler blocked lease was lost.'), { reasonCode: 'SCHEDULER_LEASE_LOST' }); await record(transaction, job, 'blocked', 'handler_blocked', reasonCode, fingerprint, now, {}) }) },
  }
}

export function createDrizzleEditorHandlers(database: any, now: Date): EditorJobHandlers {
  return {
    async media_object_cleanup(job) {
      const objectKeys = Array.isArray(job.payload?.objectKeys)
        ? job.payload.objectKeys.filter(
            (value): value is string =>
              typeof value === 'string' && value.length > 0 && value.length <= 512
          )
        : []
      if (!objectKeys.length || objectKeys.length > 12 || new Set(objectKeys).size !== objectKeys.length)
        throw Object.assign(new Error('Media cleanup payload is invalid.'), { reasonCode: 'INVALID_CLEANUP_PAYLOAD', terminal: true })
      const actor = { ownerUserId: job.ownerUserId, projectId: job.projectId, actorUserId: null, authority: 'system_workflow' as const, role: 'platform_owner' as const }
      const runtime = await resolveEditorRuntime(actor)
      const receipts: Array<{ objectKey: string; deleted: boolean; receiptReference: string }> = []
      for (const objectKey of objectKeys) {
        const deletion = await runtime.storage.deleteObject({ ...actor, objectKey })
        receipts.push({ objectKey, ...deletion })
      }
      const receiptFingerprint = stableFingerprint({ version: 'media-object-cleanup-receipt-v1', jobId: job.jobId, attempt: job.attempt, receipts })
      await runtime.mediaRepository.appendEvent(actor, { eventType: 'media_object_cleanup_succeeded', assetId: null, uploadId: null, receiptFingerprint, metadata: { sourceReference: job.sourceReference || null, receipts }, occurredAt: now.toISOString() })
      const finalize = job.payload?.finalizeDeletion as { assetId?: unknown; originalBytes?: unknown } | null | undefined
      if (finalize) {
        const assetId = typeof finalize.assetId === 'string' ? finalize.assetId : ''
        const originalBytes = Number(finalize.originalBytes)
        if (!assetId || !Number.isSafeInteger(originalBytes) || originalBytes < 0)
          throw Object.assign(new Error('Media deletion finalizer is invalid.'), { reasonCode: 'INVALID_DELETION_FINALIZER', terminal: true })
        await runtime.mediaRepository.transaction(async repository => {
          const fingerprint = stableFingerprint({ version: 'media-permanent-delete-v1', ownerUserId: actor.ownerUserId, projectId: actor.projectId, assetId, originalBytes })
          const pending = await repository.findAsset(actor, assetId)
          if (!pending || pending.status !== 'deletion_pending') throw Object.assign(new Error('Asset is not in the exact deletion-pending state.'), { reasonCode: 'STALE_DELETION_AUTHORITY', terminal: true })
          const persistedOriginalBytes = await repository.getOriginalBytesForAsset(actor, assetId)
          if (persistedOriginalBytes !== originalBytes) throw Object.assign(new Error('Deletion quota lineage changed before cleanup finalization.'), { reasonCode: 'STALE_DELETION_QUOTA_LINEAGE', terminal: true })
          await repository.creditQuota(actor, { idempotencyKey: `delete:${assetId}`.slice(0, 128), requestFingerprint: fingerprint, delta: { originalBytes, assetCount: 1 } })
          const updated = await repository.updateAsset(actor, assetId, { status: 'deleted', deletedAt: now.toISOString() })
          if (!updated) throw Object.assign(new Error('Deletion-pending asset no longer exists.'), { reasonCode: 'STALE_DELETION_AUTHORITY', terminal: true })
          await repository.appendEvent(actor, { eventType: 'media_permanently_deleted', assetId, uploadId: null, receiptFingerprint: stableFingerprint({ fingerprint, receipts }), metadata: { objectReceipts: receipts.map(item => item.receiptReference), objectCount: receipts.length, quotaOriginalBytesReleased: originalBytes, quotaAssetCountReleased: 1, recoveredByCleanupJob: true }, occurredAt: now.toISOString() })
        })
      }
      return { outcome: 'media_objects_cleanup_succeeded', externalCalls: runtime.storage.kind === 's3_compatible' }
    },
    async publish_retry(job) { const work = await claimSpecificPagePublicationWork(database, Number(job.payload?.workId), now, `editor-publication-${job.jobId}`, EDITOR_SCHEDULER_LIMITS.leaseMs); if (!work) return { outcome: 'publication_already_claimed_or_not_due', externalCalls: false }; const result = await executeDrizzlePagePublicationWork(work, { database, now }); if (result.status === 'retry_wait') throw Object.assign(new Error('First-party publication requested retry.'), { reasonCode: 'PUBLICATION_RETRY_WAIT', externalCalls: result.externalCalls }); if (result.status === 'blocked') throw Object.assign(new Error('First-party publication was blocked.'), { reasonCode: 'PUBLICATION_BLOCKED', terminal: true, externalCalls: result.externalCalls }); return { outcome: `publication_${result.status}`, externalCalls: result.externalCalls } },
    async media_processing(job) {
      const runId = Number(job.payload?.processingRunId)
      const assetId = String(job.payload?.assetId || '')
      const sourceAttemptCount = Number(job.payload?.sourceAttemptCount); if (!Number.isSafeInteger(sourceAttemptCount) || sourceAttemptCount < 0 || sourceAttemptCount >= EDITOR_SCHEDULER_LIMITS.maxAttempts) return { outcome: 'media_processing_attempt_bound_reached', externalCalls: false }
      const claimedAttempt = sourceAttemptCount + 1
      const lease = await database.update(managedSiteMediaProcessingRuns).set({ status: 'processing', leaseUntil: new Date(now.getTime() + EDITOR_SCHEDULER_LIMITS.leaseMs), attemptCount: claimedAttempt, updatedAt: now }).where(and(eq(managedSiteMediaProcessingRuns.id, runId), eq(managedSiteMediaProcessingRuns.attemptCount, sourceAttemptCount), or(and(inArray(managedSiteMediaProcessingRuns.status, ['queued', 'retry_wait', 'failed']), or(isNull(managedSiteMediaProcessingRuns.leaseUntil), lte(managedSiteMediaProcessingRuns.leaseUntil, now))), and(eq(managedSiteMediaProcessingRuns.status, 'processing'), lte(managedSiteMediaProcessingRuns.leaseUntil, now)))))
      if (rowsAffected(lease) !== 1) return { outcome: 'media_processing_already_claimed', externalCalls: false }
      const actor = { ownerUserId: job.ownerUserId, projectId: job.projectId, actorUserId: null, authority: 'system_workflow' as const, role: 'platform_owner' as const }
      let externalCalls = false
      try {
        const runtime = await resolveEditorRuntime(actor)
        externalCalls = runtime.storage.kind === 's3_compatible'
        await retryMediaProcessing({ repository: runtime.mediaRepository, storage: runtime.storage, scanner: runtime.scanner, processor: runtime.processor }, actor, { assetId }, now)
        await database.update(managedSiteMediaProcessingRuns).set({ status: 'succeeded', leaseUntil: null, nextAttemptAt: null, errorCode: null, updatedAt: now }).where(and(eq(managedSiteMediaProcessingRuns.id, runId), eq(managedSiteMediaProcessingRuns.status, 'processing')))
        return { outcome: 'media_processing_succeeded', externalCalls }
      } catch (error: any) {
        const blocked = claimedAttempt >= EDITOR_SCHEDULER_LIMITS.maxAttempts
        await database.update(managedSiteMediaProcessingRuns).set({ status: blocked ? 'failed' : 'retry_wait', leaseUntil: null, nextAttemptAt: blocked ? null : new Date(now.getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, job.attempt - 1))), errorCode: String(error?.reasonCode || 'MEDIA_PROCESSING_RETRY_FAILED').slice(0, 120), updatedAt: now }).where(and(eq(managedSiteMediaProcessingRuns.id, runId), eq(managedSiteMediaProcessingRuns.status, 'processing')))
        if (blocked) throw Object.assign(error instanceof Error ? error : new Error('Media processing retry failed.'), { externalCalls, terminal: true })
        return { outcome: 'media_processing_retry_scheduled', externalCalls }
      }
    },
    async orphan_upload_expiry(job) { const updated = await database.update(managedSiteMediaUploadSessions).set({ status: 'expired', leaseUntil: null }).where(and(eq(managedSiteMediaUploadSessions.id, Number(job.payload?.uploadRowId)), inArray(managedSiteMediaUploadSessions.status, [...ORPHAN_UPLOAD_EXPIRY_STATUSES]))); if (rowsAffected(updated) !== 1) return { outcome: 'upload_already_finalized', externalCalls: false }; const actor = { ownerUserId: job.ownerUserId, projectId: job.projectId, actorUserId: null, authority: 'system_workflow' as const, role: 'platform_owner' as const }; const runtime = await resolveEditorRuntime(actor); const deletion = await runtime.storage.deleteObject({ ...actor, objectKey: String(job.payload?.objectKey || '') }); await runtime.mediaRepository.transaction(repository => repository.releaseQuota(actor, { idempotencyKey: String(job.payload?.quotaIdempotencyKey || ''), requestFingerprint: String(job.payload?.quotaRequestFingerprint || '') })); const fingerprint = stableFingerprint({ action: 'orphan_upload_expired', uploadId: job.payload?.uploadId, deletion }); await runtime.mediaRepository.appendEvent(actor, { eventType: 'orphan_upload_expired', assetId: String(job.payload?.assetId || ''), uploadId: String(job.payload?.uploadId || ''), receiptFingerprint: fingerprint, metadata: { deletion }, occurredAt: now.toISOString() }); return { outcome: 'orphan_upload_expired_and_deleted', externalCalls: runtime.storage.kind === 's3_compatible' } },
    async trash_retention(job) { const assetId = String(job.payload?.assetId || ''); const fingerprint = stableFingerprint({ action: 'trash_retention_due', ownerUserId: job.ownerUserId, projectId: job.projectId, assetId, stateFingerprint: job.stateFingerprint }); await database.insert(managedSiteMediaEvents).values({ ownerUserId: job.ownerUserId, projectId: job.projectId, assetId, uploadId: null, eventType: 'trash_retention_due', actorAuthority: 'system_workflow', beforeFingerprint: null, afterFingerprint: null, metadata: { automaticPermanentDeletion: false, ownerConfirmationRequired: true }, receiptFingerprint: fingerprint, occurredAt: now }).onDuplicateKeyUpdate({ set: { receiptFingerprint: fingerprint } }); return { outcome: 'retention_notification_recorded', externalCalls: false } },
    async scheduled_visibility(job) { const actor = { ownerUserId: job.ownerUserId, projectId: job.projectId, actorUserId: null, authority: 'system_workflow' as const, role: 'platform_owner' as const, canPublish: false }; await applyPageCommand((await import('./repository-drizzle')).makeDrizzlePageEditorRepository(database), actor, String(job.payload?.pageId || ''), { schemaVersion: 'managed-site-page-command-v1', type: 'toggle_visibility', expectedPageVersion: Number(job.payload?.pageVersion), idempotencyKey: `schedule-${job.jobId}`.slice(0, 128), target: { blockId: String(job.payload?.blockId || '') }, payload: job.payload?.desired === true, reason: 'Apply governed scheduled visibility.' }, now); return { outcome: 'scheduled_visibility_applied', externalCalls: false } },
  }
}

export async function runDrizzleEditorMaintenance(now = new Date()) {
  const database = getDatabase(); if (!database) return { status: 'blocked', reasonCode: 'DATABASE_UNAVAILABLE', discovered: 0, claimed: 0, processingExecuted: 0, publishRetriesExecuted: 0, externalCalls: false }
  const discovery = await discoverDrizzleEditorJobs(database, now); const result = await runEditorSchedulerTick(createDrizzleEditorSchedulerPort(database), createDrizzleEditorHandlers(database, now), now); return { status: 'completed', ...discovery, ...result, processingExecuted: result.receipts.filter(item => item.kind === 'media_processing' && item.outcome !== 'media_processing_already_claimed').length, processingSucceeded: result.receipts.filter(item => item.kind === 'media_processing' && item.status === 'succeeded').length, publishRetriesExecuted: result.receipts.filter(item => item.kind === 'publish_retry' && item.externalCalls).length, publishRetriesSucceeded: result.receipts.filter(item => item.kind === 'publish_retry' && item.status === 'succeeded' && item.externalCalls).length }
}
