import { describe, expect, it } from 'vitest'
import { assertDisjointComplete, assertObservationIsUsable, buildCitationSelectionDataset, calculateBinaryMetrics, calculateRankingMetrics, canBePrimaryCitationTruth, deriveFeatureVector, evaluatePromotionGate, getShadowReadiness, isHardNegativeCandidate, normalizeManualObservation, normalizeTrustedObservation, parseModelFamily, parseTrainingConfig, scoreWithParameters, splitDatasetMembers, standardizedFeatureContributions, trainPairwiseLogisticRanker, trainRegularizedLogisticBaseline, type DatasetMember, type OutcomeObservation } from '../server/geo-outcome-model'
import { createMemoryGeoOutcomeRepository } from './support/geo-outcome-memory-repository'
import { sha256Hex } from '../server/geo-outcome-model/canonical'

const ownerUserId = 42
const hash = (value: string) => sha256Hex(value)
function rawObservation(overrides: Record<string, unknown> = {}) { const group = String(overrides.group || 'group-1'); const day = Number(overrides.day || 1); const date = new Date(Date.UTC(2026, 0, day)).toISOString(); const positive = overrides.citationStatus === 'cited'; const { group: _group, day: _day, website, page, canonical, content, evidence, receipt, ...fields } = overrides; void _group; void _day; return { schemaVersion: 'geo-outcome-observation-v1', projectId: null, clientId: null, websiteIdentityHash: hash(String(website || `site-${group}`)), queryIdentityHash: hash(group), normalizedQueryHash: hash(group), candidatePageIdentityHash: hash(String(page || `page-${group}-${positive ? 'positive' : 'negative'}`)), canonicalPageHash: hash(String(canonical || `canonical-${group}`)), contentHash: hash(String(content || `content-${group}-${positive ? 'positive' : 'negative'}`)), evidenceSnapshotHash: hash(String(evidence || `evidence-${group}`)), publicationReceiptFingerprint: hash(String(receipt || `receipt-${group}`)), engine: fields.engine || 'chatgpt', model: 'test-model', modelVersion: 'v1', interface: fields.interface || 'consumer_surface', locale: 'en', region: 'US', runIdentity: String(fields.runIdentity || `run-${group}`), runTimestamp: date, observationWindow: { start: date, end: new Date(Date.UTC(2026, 0, day, 1)).toISOString() }, observableStatus: fields.observableStatus || 'observable', retrievalStatus: fields.retrievalStatus || 'retrieved', citationStatus: fields.citationStatus || 'cited', citationPosition: fields.citationStatus === 'not_cited' ? null : 1, mentionStatus: positive ? 'mentioned' : 'not_mentioned', recommendationStatus: 'unknown', labelBasis: fields.labelBasis || 'manual_verified_primary', verificationStatus: fields.verificationStatus || 'unverified', evidenceLocatorHashes: fields.evidenceLocatorHashes || [hash(`locator-${group}`)], appliedRuleHashes: [], contentFeatureVector: { contentType: 'article', locale: 'en', pageAgeBucket: '8_30d', contentLengthBucket: positive ? 'l' : 's', headingHierarchy: positive ? 'structured' : 'flat', directAnswerPresence: positive ? 'present' : 'absent', faqStructure: 'absent', structuredDataPresence: positive ? 'present' : 'absent', citationMarkerCount: positive ? 3 : 0, approvedAuthoritySourceCount: positive ? 2 : 0, evidenceUtilizationRatio: positive ? .8 : .1, entityCoverage: positive ? .8 : .1, selectedAutoGeoRuleHashes: [], appliedAutoGeoRuleHashes: [], canonicalFlag: 'valid', indexabilityFlag: 'indexable', internalLinkDepthBucket: '1', contentFreshnessBucket: 'fresh', queryPageLexicalOverlap: positive ? .8 : .1, topicClusterEqual: 'yes', verifiedPublicationAgeDays: 10, priorObservationCount: 1 }, ...fields } }
function observation(overrides: Record<string, unknown> = {}, trusted = false): OutcomeObservation { const input = rawObservation({ verificationStatus: trusted ? 'verified' : 'unverified', ...overrides }); return trusted ? normalizeTrustedObservation(input, ownerUserId) : normalizeManualObservation(input, ownerUserId) }
function member(row: OutcomeObservation, label: 0 | 1, hardNegative: boolean): DatasetMember { return { observationFingerprint: row.observationFingerprint, websiteIdentityHash: row.websiteIdentityHash, normalizedQueryHash: row.normalizedQueryHash, runIdentity: row.runIdentity, queryGroupKey: `${row.runIdentity}:${row.normalizedQueryHash}`, label, hardNegative, consentStatus: row.consentStatus, piiStatus: row.piiStatus, reviewFingerprint: row.reviewFingerprint, featureVector: deriveFeatureVector(row), observation: row, splitAssignment: 'train' } }

 describe('observation intake and governance', () => {
  it('rejects unknown fields, PII keys, malformed timestamps, and invalid engines', () => { expect(() => normalizeManualObservation({ ...rawObservation(), unknownField: true }, ownerUserId)).toThrow(/unknown field/i); expect(() => normalizeManualObservation({ ...rawObservation(), email: 'owner@example.test' }, ownerUserId)).toThrow(/sensitive/i); expect(() => normalizeManualObservation({ ...rawObservation(), runTimestamp: 'not-a-date' }, ownerUserId)).toThrow(/runTimestamp/i); expect(() => normalizeManualObservation({ ...rawObservation(), engine: 'untrusted-engine' }, ownerUserId)).toThrow(/engine/i) })
  it('cannot self-assert verified primary truth at intake', () => { expect(() => normalizeManualObservation(rawObservation({ verificationStatus: 'verified', citationStatus: 'cited' }), ownerUserId)).toThrow(/self-assert/i); const row = observation({ citationStatus: 'cited' }); expect(row.verificationStatus).toBe('unverified'); expect(row.verificationAuthority).toBe('intake'); expect(canBePrimaryCitationTruth(row)).toBe(false) })
  it('keeps provider, aggregate and heuristic evidence out of citation truth', () => { for (const labelBasis of ['provider_api_secondary_only', 'search_console_aggregate_only', 'first_party_analytics_aggregate_only', 'heuristic_auxiliary_only'] as const) { const row = observation({ labelBasis, interface: labelBasis === 'provider_api_secondary_only' ? 'provider_api' : 'consumer_surface' }, true); expect(canBePrimaryCitationTruth(row)).toBe(false); expect(assertObservationIsUsable(row)).toBeUndefined() } })
  it('accepts only same-run verified observable hard negatives', () => { const positive = observation({ group: 'same', page: 'positive', citationStatus: 'cited' }, true); const negative = observation({ group: 'same', page: 'negative', citationStatus: 'not_cited' }, true); expect(isHardNegativeCandidate(negative, positive)).toBe(true); expect(isHardNegativeCandidate(observation({ group: 'other', page: 'arbitrary', citationStatus: 'not_cited' }, true), positive)).toBe(false); expect(isHardNegativeCandidate(observation({ group: 'same', page: 'failed', citationStatus: 'not_cited', observableStatus: 'provider_error' }, true), positive)).toBe(false); expect(isHardNegativeCandidate(observation({ group: 'same', page: 'stale', citationStatus: 'not_cited', verificationStatus: 'stale' }, true), positive)).toBe(false); expect(isHardNegativeCandidate(observation({ group: 'same', page: 'engine', citationStatus: 'not_cited', engine: 'gemini' }, true), positive)).toBe(false) })
 })

 describe('durable memory adapter and idempotency', () => {
  it('persists observations across adapter recreation and isolates owners', async () => { const first = createMemoryGeoOutcomeRepository(); const row = observation({ group: 'persist', page: 'p1' }); await first.saveObservationTransactional(ownerUserId, row); const restarted = createMemoryGeoOutcomeRepository(first.exportState()); expect((await restarted.listObservations(ownerUserId)).map(item => item.observationFingerprint)).toContain(row.observationFingerprint); expect(await restarted.listObservations(ownerUserId + 1)).toEqual([]) })
  it('claims one mutation under concurrency and detects collisions', async () => { const repo = createMemoryGeoOutcomeRepository(); const inputFingerprint = hash('input'); const claims = await Promise.all(Array.from({ length: 12 }, () => repo.claimMutation(ownerUserId, 'route', 'same-key', inputFingerprint))); expect(claims.filter(item => item.outcome === 'claimed')).toHaveLength(1); expect(claims.filter(item => item.outcome === 'in_progress')).toHaveLength(11); const collision = await repo.claimMutation(ownerUserId, 'route', 'same-key', hash('other-input')); expect(collision.outcome).toBe('collision'); await repo.completeMutation(ownerUserId, 'route', 'same-key', inputFingerprint, { ok: true }); const restarted = createMemoryGeoOutcomeRepository(repo.exportState()); expect((await restarted.claimMutation(ownerUserId, 'route', 'same-key', inputFingerprint)).outcome).toBe('replay') })
  it('rolls back an atomic transaction after a late failure', async () => { const repo = createMemoryGeoOutcomeRepository(); const row = observation({ group: 'rollback', page: 'p1' }); await expect(repo.transaction(async tx => { await tx.saveObservationTransactional(ownerUserId, row); throw new Error('late failure') })).rejects.toThrow('late failure'); expect(await repo.listObservations(ownerUserId)).toEqual([]) })
 })

 describe('leakage-safe dataset and split', () => {
  it('builds only verified citation labels and records six disjoint partitions', () => { const rows = Array.from({ length: 6 }, (_, index) => [observation({ group: `g-${index}`, page: `positive-${index}`, website: `site-${index}`, day: index + 1, citationStatus: 'cited' }, true), observation({ group: `g-${index}`, page: `negative-${index}`, website: `site-${index}`, day: index + 1, citationStatus: 'not_cited' }, true)]).flat(); const provider = observation({ group: 'g-provider', page: 'p-provider', citationStatus: 'cited', labelBasis: 'provider_api_secondary_only', interface: 'provider_api' }, true); const built = buildCitationSelectionDataset([...rows, provider], ownerUserId); expect(built.members).toHaveLength(12); expect(built.manifest.sourceBasisCounts.provider_api_secondary_only).toBeUndefined(); expect(built.split).not.toBeNull(); expect(built.manifest.trainRowCount + built.manifest.validationRowCount + built.manifest.testRowCount + built.manifest.siteHoldoutRowCount + built.manifest.queryHoldoutRowCount + built.manifest.temporalHoldoutRowCount).toBe(12); assertDisjointComplete(built.split!, built.members) })
  it('is deterministic regardless of input order and rejects impossible topology', () => { const rows = Array.from({ length: 24 }, (_, index) => member(observation({ group: `g-${index}`, page: `p-${index}`, website: `site-${index}`, day: index + 1, citationStatus: index % 2 ? 'not_cited' : 'cited' }, true), index % 2 ? 0 : 1, index % 2 === 1)); const first = splitDatasetMembers(rows); const second = splitDatasetMembers([...rows].reverse()); expect(second).toEqual(first); expect(() => splitDatasetMembers(rows.slice(0, 5))).toThrow(/six non-empty|topology/i) })
  it('isolates adversarial cross-run sites and canonical queries through transitive components', () => {
    const rows = Array.from({ length: 12 }, (_, index) => {
      const sharedWebsite = index < 2 ? 'shared-site-a' : index >= 4 && index <= 5 ? 'shared-site-chain' : `site-${index}`
      const normalizedQueryHash = index >= 2 && index <= 3 ? hash('shared-query-x') : index >= 5 && index <= 6 ? hash('shared-query-chain') : hash(`query-${index}`)
      return [
        member(observation({ group: `adversarial-${index}`, page: `positive-${index}`, website: sharedWebsite, day: index + 1, normalizedQueryHash, queryIdentityHash: normalizedQueryHash, citationStatus: 'cited' }, true), 1, false),
        member(observation({ group: `adversarial-${index}`, page: `negative-${index}`, website: sharedWebsite, day: index + 1, normalizedQueryHash, queryIdentityHash: normalizedQueryHash, citationStatus: 'not_cited' }, true), 0, true),
      ]
    }).flat()
    const split = splitDatasetMembers(rows)
    expect(splitDatasetMembers([...rows].reverse())).toEqual(split)
    assertDisjointComplete(split, rows)
    const partitionEntries: Array<[string, string[]]> = [['train', split.train], ['validation', split.validation], ['test', split.test], ['siteHoldout', split.siteHoldout], ['queryHoldout', split.queryHoldout], ['temporalHoldout', split.temporalHoldout]]
    const partitionByFingerprint = new Map(partitionEntries.flatMap(([partition, fingerprints]) => fingerprints.map(fingerprint => [fingerprint, partition] as const)))
    for (const identity of ['websiteIdentityHash', 'normalizedQueryHash'] as const) {
      const partitions = new Map<string, Set<string>>()
      for (const row of rows) { const values = partitions.get(row[identity]) || new Set<string>(); values.add(partitionByFingerprint.get(row.observationFingerprint)!); partitions.set(row[identity], values) }
      expect([...partitions.values()].every(values => values.size === 1)).toBe(true)
    }
  })
  it('does not reuse source label row for a hard negative when no matching same-run pair exists', () => { const positive = observation({ group: 'only-positive', page: 'p', citationStatus: 'cited' }, true); const built = buildCitationSelectionDataset([positive], ownerUserId); expect(built.members).toEqual([]); expect(built.manifest.status).toBe('gate_blocked') })
 })

 describe('deterministic trainers and config boundaries', () => {
  const config = { epochs: 20, learningRate: .1, l2: .01, seed: 0, featureCatalogVersion: 'geo-outcome-feature-catalog-v1' as const }
  it('trains identical logistic weights for reversed input and blocks invalid classes', () => { const rows = Array.from({ length: 20 }, (_, index) => member(observation({ group: `train-${index}`, page: `train-page-${index}`, day: index + 1, citationStatus: index % 2 ? 'not_cited' : 'cited' }, true), index % 2 ? 0 : 1, index % 2 === 1)); const first = trainRegularizedLogisticBaseline(rows, config); const second = trainRegularizedLogisticBaseline([...rows].reverse(), config); expect(first.coefficients).toEqual(second.coefficients); expect(first.trainingRowCount).toBe(20); expect(() => trainRegularizedLogisticBaseline(rows.filter(row => row.label === 1), config)).toThrow(/positive and negative/i) })
  it('normalizes pairwise differences using train-row statistics without centering differences', () => { const rows = Array.from({ length: 10 }, (_, index) => [member(observation({ group: `pair-${index}`, page: `positive-${index}`, day: index + 1, citationStatus: 'cited' }, true), 1, false), member(observation({ group: `pair-${index}`, page: `negative-${index}`, day: index + 1, citationStatus: 'not_cited' }, true), 0, true)]).flat(); const parameters = trainPairwiseLogisticRanker(rows, config); expect(parameters.trainingRowCount).toBe(20); expect(parameters.pairCount).toBe(10); expect(parameters.coefficients.some(value => Math.abs(value) > 1e-8)).toBe(true) })
  it('rejects unknown config keys, nonzero seed, unsupported family and nonfinite features', () => { expect(() => parseTrainingConfig({ ...config, typo: 1 })).toThrow(/unknown training config/i); expect(() => parseTrainingConfig({ ...config, seed: 1 })).toThrow(/non-deterministic/i); expect(() => parseModelFamily('unknown')).toThrow(/unsupported/i); const row = member(observation({ group: 'nan', page: 'nan', citationStatus: 'cited' }, true), 1, false); expect(() => trainRegularizedLogisticBaseline([{ ...row, featureVector: { ...row.featureVector, values: row.featureVector.values.map(value => ({ ...value, value: Number.NaN })) } }, member(observation({ group: 'nan2', page: 'nan2', citationStatus: 'not_cited' }, true), 0, true)], config)).toThrow(/finite/i) })
  it('keeps prediction score and feature contributions on the same standardization contract', () => { const parameters = { coefficients: [4], intercept: 0, normalizationStatistics: { mean: [1], standardDeviation: [2] } }; expect(scoreWithParameters(parameters, [3])).toBeCloseTo(0.98201379, 6); expect(standardizedFeatureContributions(parameters, [3], ['feature'])).toEqual([{ key: 'feature', contribution: 4, missing: false }]) })
 })

 describe('metrics and release semantics', () => {
  it('is permutation-invariant and preserves ratio reconstruction for binary metrics', () => { const labels = [1, 0, 1, 0, 1, 0]; const scores = [.8, .8, .4, .4, .2, .2]; const perm = [5, 4, 3, 2, 1, 0]; const metrics = calculateBinaryMetrics(labels, scores); const permuted = calculateBinaryMetrics(perm.map(index => labels[index]!), perm.map(index => scores[index]!)); expect(permuted).toEqual(metrics); expect(metrics.precision).toBe(metrics.numerators.precision! / metrics.denominators.precision!); expect(metrics.recall).toBe(metrics.numerators.recall! / metrics.denominators.recall!); expect(metrics.f1).toBe(metrics.numerators.f1! / metrics.denominators.f1!); expect(calculateBinaryMetrics([1], [.5]).rocAuc).toBeNull() })
  it('reports ranking micro denominators and deterministic tie ordering', () => { const rows = [member(observation({ group: 'rank', page: 'b', citationStatus: 'not_cited' }, true), 0, true), member(observation({ group: 'rank', page: 'a', citationStatus: 'cited' }, true), 1, false), member(observation({ group: 'rank2', page: 'c', citationStatus: 'cited' }, true), 1, false)]; const metrics = calculateRankingMetrics(rows, [.5, .5, .2]); const reversed = calculateRankingMetrics([...rows].reverse(), [.2, .5, .5]); expect(metrics).toEqual(reversed); expect(metrics.precisionAt3).toBe(metrics.numerators.precisionAt3! / metrics.denominators.precisionAt3!); expect(metrics.recallAt5).toBe(metrics.numerators.recallAt5! / metrics.denominators.recallAt5!) })
  it('keeps undefined metric denominators null', () => { expect(calculateBinaryMetrics([1], [.5]).prAuc).toBeNull(); expect(calculateRankingMetrics([], []).mrr).toBeNull(); const noPositive = member(observation({ group: 'none', page: 'n', citationStatus: 'not_cited' }, true), 0, true); expect(calculateRankingMetrics([noPositive], [.4]).status).toBe('insufficient_data') })
 })
