import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import {
  CONTENT_ARTIFACT_SCHEMA_VERSION,
  DETERMINISTIC_SCAFFOLD_LIMITATION,
  GEOFLOW_PROTOCOL_VERSION,
  SIGNING_ALGORITHM,
  SIGNING_METHOD,
  SIGNING_PATH,
  briefFingerprintFromDraft,
  buildCanonicalSigningInput,
  buildGeoFlowRequest,
  canonicalRequestFingerprint,
  canonicalizeContractValue,
  deriveExternalArticleKey,
  mapDiscoveryStackStatusToGeoFlow,
  mapGeoFlowStatusToDiscoveryStack,
  planSigningEnvelope,
  resolveGeoFlowIdempotency,
  validateGeoFlowRequest,
  validateGeoFlowResponse,
  validateGeoFlowStatusEventForStoredState,
  validatePublicHttpsUrl,
  verifyGeoFlowLineage,
  verifySigningEnvelope,
  verifyStatusTransition,
} from '../server/geoflow-integration'
import type { ContentArtifact, GeoFlowRequest, GeoFlowRequestDraft, GeoFlowResponse, SigningEnvelope } from '../server/geoflow-integration/types'
import { BODY_HASH, BODY_MARKDOWN, CHUNK_HASH, HASH_A, HASH_B, HASH_C, makeDraftResponse, makeFailureResponse, makeProgressResponse, makeRequest, makeRetryResponse, validContentArtifact, validRequest, validRequestDraft, validResponse, validRevisionDraft, validEnvelopeInput } from './fixtures/geoflow-integration/fixtures'

function expectFailure(result: { ok: boolean; reason?: string }, reason: string): void { expect(result.ok).toBe(false); if (!result.ok) expect(result.reason).toBe(reason) }
function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T }
function sha256(value: string): string { return createHash('sha256').update(Buffer.from(value, 'utf8')).digest('hex') }
function plannedEnvelope(overrides: Record<string, unknown> = {}): SigningEnvelope { const result = planSigningEnvelope({ ...validEnvelopeInput, ...overrides }); if (!result.ok) throw new Error(result.reason); return result.value }
function signingContext(overrides: Record<string, unknown> = {}): Record<string, unknown> { return { request: validRequest, verificationTime: '2026-08-25T04:02:00.000Z', maxClockSkewSeconds: 60, expectedSender: 'discoverystack-control-plane', expectedReceiver: 'geoflow-content-engine', expectedKeyId: 'key-1', nonceFreshnessVerifier: () => true, signatureVerifier: () => true, ...overrides } }
function responseWith(overrides: Record<string, unknown>): unknown { return { ...validResponse, ...overrides } }
function artifactWith(overrides: Partial<ContentArtifact>): ContentArtifact { return { ...validContentArtifact, ...overrides } }


describe('GEOFlow generation contract V1 — request and brief', () => {
  it('accepts the canonical article request', () => { expect(buildGeoFlowRequest(validRequestDraft).ok).toBe(true) })
  it('accepts faq content type', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, contentType: 'faq' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.contentType).toBe('faq') })
  it('accepts service_page content type', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, contentType: 'service_page' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.contentType).toBe('service_page') })
  it('accepts zh-hant language', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, language: 'zh-hant' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.language).toBe('zh-hant') })
  it('normalizes brief title with NFKC and whitespace rules', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.brief.title).toBe('NFKC Article Title') })
  it('normalizes brief audience with trim and whitespace rules', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, audience: '  Content   operators  ' } }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.brief.audience).toBe('Content operators') })
  it('preserves normalized goal order', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.brief.goals).toEqual(['Answer the question', 'Support review']) })
  it('preserves normalized constraint order', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.brief.constraints).toEqual(['Use approved evidence', 'Keep the answer precise']) })
  it('allows an empty constraints array', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, constraints: [] } }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.brief.constraints).toEqual([]) })
  it('rejects a missing brief title', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, title: undefined } }), 'INVALID_INPUT') })
  it('rejects a missing brief audience', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, audience: undefined } }), 'INVALID_INPUT') })
  it('rejects missing brief goals', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: undefined } }), 'INVALID_INPUT') })
  it('rejects an empty goals array', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: [] } }), 'REQUIRED_EVIDENCE_MISSING') })
  it('rejects duplicate normalized goals', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: ['Goal', '  Goal  '] } }), 'INVALID_INPUT') })
  it('rejects duplicate normalized constraints', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, constraints: ['Rule', ' Rule '] } }), 'INVALID_INPUT') })
  it('rejects an overlong brief title', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, title: 'x'.repeat(301) } }), 'LIMIT_EXCEEDED') })
  it('rejects an overlong brief audience', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, audience: 'x'.repeat(301) } }), 'LIMIT_EXCEEDED') })
  it('rejects an overlong goal item', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: ['x'.repeat(501)] } }), 'LIMIT_EXCEEDED') })
  it('rejects an overlong constraint item', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, constraints: ['x'.repeat(501)] } }), 'LIMIT_EXCEEDED') })
  it('rejects more than ten goals', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: Array.from({ length: 11 }, (_, index) => `Goal ${index}`) } }), 'LIMIT_EXCEEDED') })
  it('rejects more than twenty constraints', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, constraints: Array.from({ length: 21 }, (_, index) => `Constraint ${index}`) } }), 'LIMIT_EXCEEDED') })
  it('computes briefFingerprint from the normalized brief payload', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.briefFingerprint).toBe(briefFingerprintFromDraft(result.value)) })
  it('does not accept caller-supplied briefFingerprint on a draft', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, briefFingerprint: HASH_B } as unknown), 'UNKNOWN_FIELD') })
  it('brief title mutation changes briefFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, title: 'Different title' } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.briefFingerprint).not.toBe(b.value.briefFingerprint) })
  it('brief audience mutation changes briefFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, audience: 'Different audience' } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.briefFingerprint).not.toBe(b.value.briefFingerprint) })
  it('brief goal mutation changes briefFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, goals: ['Different goal'] } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.briefFingerprint).not.toBe(b.value.briefFingerprint) })
  it('content type mutation changes briefFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, contentType: 'faq' }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.briefFingerprint).not.toBe(b.value.briefFingerprint) })
  it('language mutation changes briefFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, language: 'zh-hant' }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.briefFingerprint).not.toBe(b.value.briefFingerprint) })
  it('brief constraint mutation changes requestFingerprint', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, brief: { ...validRequestDraft.brief, constraints: ['Different constraint'] } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('rejects draft mode with revisionContext', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, revisionContext: { parentDraftId: 1, parentContentHash: HASH_A, changeRequestReviewId: 2, instructions: 'change' } }), 'INVALID_INPUT') })
  it('accepts revision mode with complete revisionContext', () => { const result = buildGeoFlowRequest(validRevisionDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.revisionContext?.parentDraftId).toBe(606) })
  it('rejects revision mode without revisionContext', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: null }), 'INVALID_INPUT') })
  it('rejects revision context without parentDraftId', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, parentDraftId: undefined } }), 'INVALID_INPUT') })
  it('rejects revision context without parentContentHash', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, parentContentHash: undefined } }), 'INVALID_HASH') })
  it('rejects revision context without changeRequestReviewId', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, changeRequestReviewId: undefined } }), 'INVALID_INPUT') })
  it('rejects revision context without instructions', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, instructions: undefined } }), 'INVALID_INPUT') })
  it('rejects an overlong revision instruction', () => { expectFailure(buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, instructions: 'x'.repeat(4001) } }), 'LIMIT_EXCEEDED') })
  it('revision parentDraftId mutation changes requestFingerprint', () => { const a = buildGeoFlowRequest(validRevisionDraft); const b = buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, parentDraftId: 607 } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('revision parentContentHash mutation changes requestFingerprint', () => { const a = buildGeoFlowRequest(validRevisionDraft); const b = buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, parentContentHash: HASH_B } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('revision review ID mutation changes requestFingerprint', () => { const a = buildGeoFlowRequest(validRevisionDraft); const b = buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, changeRequestReviewId: 708 } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('revision instructions mutation changes requestFingerprint', () => { const a = buildGeoFlowRequest(validRevisionDraft); const b = buildGeoFlowRequest({ ...validRevisionDraft, revisionContext: { ...validRevisionDraft.revisionContext!, instructions: 'Different instructions' } }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('rejects a publication capability', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestedCapabilities: ['publication'] }), 'INVALID_INPUT') })
  it('rejects an unknown requested capability', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestedCapabilities: ['unknown-capability'] }), 'INVALID_INPUT') })
  it('rejects knowledge_rag with no authority sources', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, authoritySourceIds: [], evidenceChunks: [] }), 'REQUIRED_EVIDENCE_MISSING') })
  it('rejects knowledge_rag with no evidence chunks', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [] }), 'REQUIRED_EVIDENCE_MISSING') })
  it('rejects autogeo_optimization with no selected rules', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, selectedRuleIds: [] }), 'REQUIRED_RULE_MISSING') })
  it('accepts prompt_pack without evidence requirements', () => { expect(buildGeoFlowRequest({ ...validRequestDraft, requestedCapabilities: ['prompt_pack'], authoritySourceIds: [], evidenceChunks: [], selectedRuleIds: [] }).ok).toBe(true) })
  it('rejects an unknown request field', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, extra: true } as unknown), 'UNKNOWN_FIELD') })
  it('rejects null request input', () => { expectFailure(buildGeoFlowRequest(null), 'INVALID_INPUT') })
  it('rejects undefined request input', () => { expectFailure(buildGeoFlowRequest(undefined), 'INVALID_INPUT') })
  it('rejects primitive request input', () => { expectFailure(buildGeoFlowRequest('request'), 'INVALID_INPUT') })
  it('rejects array request input', () => { expectFailure(buildGeoFlowRequest([]), 'INVALID_INPUT') })
  it('rejects a throwing request getter', () => { const input = { ...validRequestDraft }; Object.defineProperty(input, 'brief', { get() { throw new Error('getter') } }); expectFailure(buildGeoFlowRequest(input), 'INVALID_INPUT') })
  it('rejects a throwing request proxy', () => { const input = new Proxy({ ...validRequestDraft }, { get(_target, property) { if (property === 'brief') throw new Error('proxy'); return Reflect.get(_target, property) } }); expectFailure(buildGeoFlowRequest(input), 'INVALID_INPUT') })
})

describe('GEOFlow generation contract V1 — evidence and canonicalization', () => {
  it('accepts an evidence chunk whose hash matches normalized reviewedText', () => { expect(buildGeoFlowRequest(validRequestDraft).ok).toBe(true) })
  it('rejects reviewedText mutation with a stale chunkHash', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], reviewedText: 'Changed evidence.' }] }), 'EVIDENCE_CHUNK_HASH_MISMATCH') })
  it('rejects a chunk hash with uppercase hex', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], chunkHash: CHUNK_HASH.toUpperCase() }] }), 'INVALID_HASH') })
  it('rejects duplicate evidence identity', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [validRequestDraft.evidenceChunks[0], validRequestDraft.evidenceChunks[0]] }), 'DUPLICATE_EVIDENCE_IDENTITY') })
  it('rejects evidence from an unallowlisted source', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], sourceId: 'source-2' }] }), 'CITATION_OUTSIDE_APPROVED_EVIDENCE') })
  it('rejects evidence with an unknown field', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], extra: true }] } as unknown), 'UNKNOWN_FIELD') })
  it('rejects a malformed reviewedText control character', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], reviewedText: 'bad\u0000text' }] }), 'INVALID_INPUT') })
  it('rejects an oversized evidence aggregate', () => { const chunk = { ...validRequestDraft.evidenceChunks[0], chunkId: 'chunk-2', reviewedText: 'x'.repeat(12001), chunkHash: HASH_A }; expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [chunk] }), 'LIMIT_EXCEEDED') })
  it('rejects an evidence chunk over the reviewedText per-chunk bound', () => { const chunk = { ...validRequestDraft.evidenceChunks[0], reviewedText: 'x'.repeat(12001), chunkHash: HASH_A }; expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [chunk] }), 'LIMIT_EXCEEDED') })
  it('rejects more than fifty evidence chunks', () => { const chunks = Array.from({ length: 51 }, (_, index) => ({ ...validRequestDraft.evidenceChunks[0], chunkId: `chunk-${index}`, chunkHash: CHUNK_HASH })); expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: chunks }), 'LIMIT_EXCEEDED') })
  it('rejects a non-array evidence collection', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: {} }), 'INVALID_INPUT') })
  it('rejects an invalid timestamp shape', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, createdAt: '2026-08-25' }), 'INVALID_TIMESTAMP') })
  it('rejects an invalid calendar date', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, createdAt: '2026-02-30T04:00:00Z' }), 'INVALID_TIMESTAMP') })
  it('canonicalizes timezone timestamps to UTC', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.createdAt).toBe('2026-08-24T20:00:00.000Z') })
  it('rejects uppercase evidence snapshot hash', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceSnapshotHash: HASH_A.toUpperCase() }), 'INVALID_HASH') })
  it('rejects non-hex evidence snapshot hash', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceSnapshotHash: 'g'.repeat(64) }), 'INVALID_HASH') })
  it('rejects a reviewedText NUL in response artifact', () => { expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ bodyMarkdown: 'bad\u0000body', bodyHash: HASH_A }) }), validRequest), 'INVALID_INPUT') })
  it('canonicalizes object keys independently of insertion order', () => { const a = canonicalizeContractValue({ a: 1, b: 2 }); const b = canonicalizeContractValue({ b: 2, a: 1 }); expect(a).toEqual(b) })
  it('canonicalizes nested object keys independently of insertion order', () => { expect(canonicalizeContractValue({ outer: { z: 1, a: 2 } })).toEqual(canonicalizeContractValue({ outer: { a: 2, z: 1 } })) })
  it('preserves order-sensitive arrays', () => { expect(canonicalizeContractValue(['a', 'b'])).not.toEqual(canonicalizeContractValue(['b', 'a'])) })
  it('distinguishes numeric array order', () => { expect(canonicalizeContractValue([1, 2])).not.toEqual(canonicalizeContractValue([2, 1])) })
  it('rejects undefined in canonical values', () => { expectFailure(canonicalizeContractValue({ value: undefined }), 'INVALID_INPUT') })
  it('rejects NaN in canonical values', () => { expectFailure(canonicalizeContractValue({ value: Number.NaN }), 'INVALID_INPUT') })
  it('rejects Infinity in canonical values', () => { expectFailure(canonicalizeContractValue({ value: Number.POSITIVE_INFINITY }), 'INVALID_INPUT') })
  it('rejects functions in canonical values', () => { expectFailure(canonicalizeContractValue({ value: () => true }), 'INVALID_INPUT') })
  it('rejects symbols in canonical values', () => { expectFailure(canonicalizeContractValue({ value: Symbol('x') }), 'INVALID_INPUT') })
  it('rejects bigint in canonical values', () => { expectFailure(canonicalizeContractValue({ value: BigInt(1) }), 'INVALID_INPUT') })
  it('rejects Date in canonical values', () => { expectFailure(canonicalizeContractValue({ value: new Date(0) }), 'INVALID_INPUT') })
  it('rejects Map in canonical values', () => { expectFailure(canonicalizeContractValue({ value: new Map() }), 'INVALID_INPUT') })
  it('rejects Set in canonical values', () => { expectFailure(canonicalizeContractValue({ value: new Set() }), 'INVALID_INPUT') })
  it('rejects a circular canonical value', () => { const value: Record<string, unknown> = {}; value.self = value; expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('rejects a throwing canonical getter', () => { const value = {}; Object.defineProperty(value, 'bad', { enumerable: true, get() { throw new Error('getter') } }); expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('rejects a throwing canonical proxy', () => { const value = new Proxy({ value: 1 }, { get() { throw new Error('proxy') } }); expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('request fingerprint is deterministic across repeated builds', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest(clone(validRequestDraft)); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).toBe(b.value.requestFingerprint) })
  it('request fingerprint changes when request identity changes', () => { const a = buildGeoFlowRequest(validRequestDraft); const b = buildGeoFlowRequest({ ...validRequestDraft, requestId: 'req-002' }); expect(a.ok && b.ok).toBe(true); if (a.ok && b.ok) expect(a.value.requestFingerprint).not.toBe(b.value.requestFingerprint) })
  it('canonicalRequestFingerprint returns the computed request fingerprint', () => { const result = canonicalRequestFingerprint(validRequestDraft); expect(result).toEqual({ ok: true, value: validRequest.requestFingerprint }) })
  it('validateGeoFlowRequest accepts the builder output', () => { expect(validateGeoFlowRequest(validRequest).ok).toBe(true) })
  it('validateGeoFlowRequest rejects a mutated brief fingerprint', () => { expectFailure(validateGeoFlowRequest({ ...validRequest, briefFingerprint: HASH_B }), 'BRIEF_FINGERPRINT_MISMATCH') })
  it('validateGeoFlowRequest rejects a mutated request fingerprint', () => { expectFailure(validateGeoFlowRequest({ ...validRequest, requestFingerprint: HASH_B }), 'REQUEST_FINGERPRINT_MISMATCH') })
  it('validateGeoFlowRequest rejects an unknown key', () => { expectFailure(validateGeoFlowRequest({ ...validRequest, extra: true }), 'UNKNOWN_FIELD') })
  it('validateGeoFlowRequest returns a detached normalized copy', () => { const input = clone(validRequest); const result = validateGeoFlowRequest(input); expect(result.ok).toBe(true); if (result.ok) expect(result.value).not.toBe(input) })
})

describe('GEOFlow generation contract V1 — idempotency and response union', () => {
  it('resolves a missing idempotency record as new_request', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, null); expect(result).toMatchObject({ ok: true, value: { resolution: 'new_request' } }) })
  it('resolves matching idempotency as replay', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }); expect(result).toMatchObject({ ok: true, value: { resolution: 'replay' } }) })
  it('rejects matching key with a different fingerprint as collision', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: HASH_B }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }), 'IDEMPOTENCY_COLLISION') })
  it('resolves a different key as new_request', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: 'idem-002', requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }); expect(result).toMatchObject({ ok: true, value: { resolution: 'new_request' } }) })
  it('rejects an idempotency unknown field', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint, extra: true }, null), 'UNKNOWN_FIELD') })
  it('rejects an idempotency malformed key', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: 'bad key', requestFingerprint: validRequest.requestFingerprint }, null), 'INVALID_INPUT') })
  it('rejects an idempotency malformed hash', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: 'not-a-hash' }, null), 'INVALID_HASH') })
  it('rejects malformed stored idempotency state', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: 'bad key', requestFingerprint: validRequest.requestFingerprint }), 'INVALID_INPUT') })
  it('accepts a queued progress response', () => { expect(validateGeoFlowResponse(makeProgressResponse(validRequest, 'queued'), validRequest).ok).toBe(true) })
  it('accepts a running progress response', () => { expect(validateGeoFlowResponse(makeProgressResponse(validRequest, 'running'), validRequest).ok).toBe(true) })
  it('accepts a retry_wait response with retry metadata', () => { expect(validateGeoFlowResponse(makeRetryResponse(), validRequest).ok).toBe(true) })
  it('accepts a blocked failure response', () => { expect(validateGeoFlowResponse(makeFailureResponse(validRequest, 'blocked'), validRequest).ok).toBe(true) })
  it('accepts a failed failure response', () => { expect(validateGeoFlowResponse(makeFailureResponse(), validRequest).ok).toBe(true) })
  it('accepts a draft_ready candidate response', () => { expect(validateGeoFlowResponse(makeDraftResponse(validRequest, { status: 'draft_ready' }), validRequest).ok).toBe(true) })
  it('accepts a review_required candidate response', () => { expect(validateGeoFlowResponse(validResponse, validRequest).ok).toBe(true) })
  it('rejects a progress response with contentArtifact', () => { expectFailure(validateGeoFlowResponse({ ...makeProgressResponse(), contentArtifact: validContentArtifact }, validRequest), 'UNKNOWN_FIELD') })
  it('rejects a failure response with contentArtifact', () => { expectFailure(validateGeoFlowResponse({ ...makeFailureResponse(), contentArtifact: validContentArtifact }, validRequest), 'UNKNOWN_FIELD') })
  it('rejects a draft result with missing contentArtifact', () => { const input = { ...validResponse } as unknown as Record<string, unknown>; delete input.contentArtifact; expectFailure(validateGeoFlowResponse(input, validRequest), 'UNKNOWN_FIELD') })
  it('rejects an unknown response status', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, status: 'approved' }, validRequest), 'UNKNOWN_STATE') })
  it('rejects a publishing response status', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, status: 'publishing' }, validRequest), 'UNKNOWN_STATE') })
  it('rejects a published response status', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, status: 'published' }, validRequest), 'UNKNOWN_STATE') })
  it('rejects a response request ID mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ requestId: 'req-other' }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response owner mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ ownerUserId: 999 }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response client mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ clientId: 999 }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response job mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ jobId: 999 }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response evidence snapshot mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ evidenceSnapshotHash: HASH_B }), validRequest), 'EVIDENCE_SNAPSHOT_MISMATCH') })
  it('rejects a response brief fingerprint mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ draftIdentity: { ...validResponse.draftIdentity, briefFingerprint: HASH_B } }), validRequest), 'BRIEF_FINGERPRINT_MISMATCH') })
  it('rejects an external article identity mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ externalArticleKey: 'article-other', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'article-other' } }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response content type mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ contentType: 'faq' }) }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response language mismatch', () => { expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ language: 'zh-hant' }) }), validRequest), 'IDENTITY_MISMATCH') })
  it('rejects completedAt before request createdAt', () => { expectFailure(validateGeoFlowResponse(responseWith({ completedAt: '2026-08-24T19:59:59Z' }), validRequest), 'RESPONSE_TIME_INVALID') })
  it('rejects a bodyMarkdown mutation with stale bodyHash', () => { expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ bodyMarkdown: 'mutated body' }) }), validRequest), 'CONTENT_HASH_MISMATCH') })
  it('accepts exact bodyMarkdown bytes without whitespace rewrite', () => { const body = '  exact\nmarkdown  '; const result = validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ bodyMarkdown: body, bodyHash: sha256(body) }) }), validRequest); expect(result.ok).toBe(true); if (result.ok && (result.value.status === 'draft_ready' || result.value.status === 'review_required')) expect(result.value.contentArtifact.bodyMarkdown).toBe(body) })
  it('rejects bodyMarkdown over 200000 UTF-8 bytes', () => { const body = 'x'.repeat(200001); expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ bodyMarkdown: body, bodyHash: sha256(body) }) }), validRequest), 'LIMIT_EXCEEDED') })
  it('rejects a response uppercase body hash', () => { expectFailure(validateGeoFlowResponse(responseWith({ contentArtifact: artifactWith({ bodyHash: BODY_HASH.toUpperCase() }) }), validRequest), 'INVALID_HASH') })
  it('rejects a response citation outside approved evidence', () => { expectFailure(validateGeoFlowResponse(responseWith({ citationBindings: [{ ...validResponse.citationBindings[0], chunkId: 'other-chunk' }] }), validRequest), 'CITATION_OUTSIDE_APPROVED_EVIDENCE') })
  it('rejects an applied rule outside selection', () => { expectFailure(validateGeoFlowResponse(responseWith({ appliedRuleIds: ['unselected-rule'] }), validRequest), 'APPLIED_RULE_OUTSIDE_SELECTION') })
  it('rejects an empty applied rule result for AutoGEO', () => { expectFailure(validateGeoFlowResponse(responseWith({ appliedRuleIds: [] }), validRequest), 'REQUIRED_RULE_MISSING') })
  it('rejects an incomplete applied rule result for AutoGEO', () => { expectFailure(validateGeoFlowResponse(responseWith({ appliedRuleIds: ['direct-answer-first'] }), validRequest), 'APPLIED_RULE_OUTSIDE_SELECTION') })
  it('rejects a zero-citation knowledge result', () => { expectFailure(validateGeoFlowResponse(responseWith({ citationBindings: [] }), validRequest), 'REQUIRED_EVIDENCE_MISSING') })
  it('accepts a provider response for qwen_generation', () => { const request = makeRequest({ requestedCapabilities: ['qwen_generation'], selectedRuleIds: [], authoritySourceIds: [], evidenceChunks: [] }); const result = validateGeoFlowResponse(makeDraftResponse(request, { providerProvenance: { provider: 'qwen', model: 'qwen-max', mode: 'provider', fallbackReason: null }, citationBindings: [], appliedRuleIds: [], limitations: [] }), request); expect(result.ok).toBe(true) })
  it('rejects deterministic scaffold for qwen_generation', () => { const request = makeRequest({ requestedCapabilities: ['qwen_generation'], selectedRuleIds: [], authoritySourceIds: [], evidenceChunks: [] }); expectFailure(validateGeoFlowResponse(makeDraftResponse(request, { citationBindings: [], appliedRuleIds: [], limitations: [] }), request), 'PROVIDER_PROVENANCE_MISSING') })
  it('rejects a non-Qwen provider for qwen_generation', () => { const request = makeRequest({ requestedCapabilities: ['qwen_generation'], selectedRuleIds: [], authoritySourceIds: [], evidenceChunks: [] }); expectFailure(validateGeoFlowResponse(makeDraftResponse(request, { providerProvenance: { provider: 'synthetic-provider', model: 'model', mode: 'provider', fallbackReason: null }, citationBindings: [], appliedRuleIds: [], limitations: [] }), request), 'PROVIDER_PROVENANCE_MISSING') })
  it('accepts deterministic scaffold with fixed limitation', () => { expect(validResponse.providerProvenance.mode).toBe('deterministic_scaffold'); expect(validResponse.limitations).toContain(DETERMINISTIC_SCAFFOLD_LIMITATION) })
  it('rejects deterministic scaffold with an external provider label', () => { expectFailure(validateGeoFlowResponse(responseWith({ providerProvenance: { provider: 'provider', model: 'none', mode: 'deterministic_scaffold', fallbackReason: null } }), validRequest), 'PROVIDER_PROVENANCE_MISSING') })
  it('accepts reference fallback with a bounded reason', () => { const request = makeRequest({ requestedCapabilities: ['prompt_pack'], selectedRuleIds: [], authoritySourceIds: [], evidenceChunks: [] }); const result = validateGeoFlowResponse(makeDraftResponse(request, { providerProvenance: { provider: 'reference_fallback', model: 'none', mode: 'reference_fallback', fallbackReason: 'Provider unavailable.' }, citationBindings: [], appliedRuleIds: [], limitations: [] }), request); expect(result.ok).toBe(true) })
  it('rejects reference fallback without a reason', () => { const request = makeRequest({ requestedCapabilities: ['prompt_pack'], selectedRuleIds: [], authoritySourceIds: [], evidenceChunks: [] }); expectFailure(validateGeoFlowResponse(makeDraftResponse(request, { providerProvenance: { provider: 'reference_fallback', model: 'none', mode: 'reference_fallback', fallbackReason: null }, citationBindings: [], appliedRuleIds: [], limitations: [] }), request), 'PROVIDER_PROVENANCE_MISSING') })
  it('rejects missing provider provenance fields', () => { expectFailure(validateGeoFlowResponse(responseWith({ providerProvenance: { provider: '', model: 'model', mode: 'provider', fallbackReason: null } }), validRequest), 'INVALID_INPUT') })
  it('rejects unknown response fields', () => { expectFailure(validateGeoFlowResponse(responseWith({ extra: true }), validRequest), 'UNKNOWN_FIELD') })
  it('does not return the raw response object reference', () => { const input = clone(validResponse); const result = validateGeoFlowResponse(input, validRequest); expect(result.ok).toBe(true); if (result.ok) expect(result.value).not.toBe(input) })
  it('does not return raw evidence body in failure metadata', () => { const result = validateGeoFlowResponse(responseWith({ citationBindings: [{ ...validResponse.citationBindings[0], chunkId: 'not-approved' }] }), validRequest); expectFailure(result, 'CITATION_OUTSIDE_APPROVED_EVIDENCE'); expect(JSON.stringify(result)).not.toContain('Approved evidence text') })
  it('does not return raw signature or provider error in failure metadata', () => { const result = validateGeoFlowResponse(responseWith({ providerProvenance: { provider: '', model: '', mode: 'provider', fallbackReason: 'secret stack error' } }), validRequest); expectFailure(result, 'INVALID_INPUT'); expect(JSON.stringify(result)).not.toContain('secret stack error') })
})

describe('GEOFlow generation contract V1 — URL and status policy', () => {
  it('accepts a public HTTPS URL', () => { expect(validatePublicHttpsUrl('https://example.com/evidence')).toEqual({ ok: true, value: 'https://example.com/evidence' }) })
  it('rejects HTTP', () => { expectFailure(validatePublicHttpsUrl('http://example.com/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects FTP', () => { expectFailure(validatePublicHttpsUrl('ftp://example.com/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects file URLs', () => { expectFailure(validatePublicHttpsUrl('file:///tmp/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects data URLs', () => { expectFailure(validatePublicHttpsUrl('data:text/plain,evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects javascript URLs', () => { expectFailure(validatePublicHttpsUrl('javascript:alert(1)'), 'INVALID_PUBLIC_URL') })
  it('rejects URL credentials', () => { expectFailure(validatePublicHttpsUrl('https://user:pass@example.com/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects URL fragments', () => { expectFailure(validatePublicHttpsUrl('https://example.com/evidence#fragment'), 'INVALID_PUBLIC_URL') })
  it('rejects non-443 ports', () => { expectFailure(validatePublicHttpsUrl('https://example.com:8443/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects localhost', () => { expectFailure(validatePublicHttpsUrl('https://localhost/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects local host suffix', () => { expectFailure(validatePublicHttpsUrl('https://service.local/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects internal host suffix', () => { expectFailure(validatePublicHttpsUrl('https://service.internal/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects onion host suffix', () => { expectFailure(validatePublicHttpsUrl('https://hiddenservice.onion/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects a single-label host', () => { expectFailure(validatePublicHttpsUrl('https://example/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects a malformed URL', () => { expectFailure(validatePublicHttpsUrl('not a url'), 'INVALID_PUBLIC_URL') })
  it('rejects a private IPv4', () => { expectFailure(validatePublicHttpsUrl('https://192.168.1.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects a loopback IPv4', () => { expectFailure(validatePublicHttpsUrl('https://127.0.0.1/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects a link-local IPv4', () => { expectFailure(validatePublicHttpsUrl('https://169.254.1.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects CGNAT IPv4', () => { expectFailure(validatePublicHttpsUrl('https://100.64.0.1/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects benchmark IPv4', () => { expectFailure(validatePublicHttpsUrl('https://198.18.0.1/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects 198.51.100.0/24', () => { expectFailure(validatePublicHttpsUrl('https://198.51.100.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects 192.0.2.0/24', () => { expectFailure(validatePublicHttpsUrl('https://192.0.2.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects 203.0.113.0/24', () => { expectFailure(validatePublicHttpsUrl('https://203.0.113.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects multicast IPv4', () => { expectFailure(validatePublicHttpsUrl('https://224.0.0.1/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 unspecified', () => { expectFailure(validatePublicHttpsUrl('https://[::]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 loopback', () => { expectFailure(validatePublicHttpsUrl('https://[::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 private ULA', () => { expectFailure(validatePublicHttpsUrl('https://[fd00::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 link-local', () => { expectFailure(validatePublicHttpsUrl('https://[fe80::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 discard 100::/64', () => { expectFailure(validatePublicHttpsUrl('https://[100::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 documentation range', () => { expectFailure(validatePublicHttpsUrl('https://[2001:db8::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv4-mapped private IPv6', () => { expectFailure(validatePublicHttpsUrl('https://[::ffff:192.168.1.1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv4-mapped loopback IPv6', () => { expectFailure(validatePublicHttpsUrl('https://[::ffff:7f00:1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects encoded token query parameter name', () => { expectFailure(validatePublicHttpsUrl('https://example.com/evidence?%74oken=value'), 'INVALID_PUBLIC_URL') })
  it('rejects encoded api_key query parameter name', () => { expectFailure(validatePublicHttpsUrl('https://example.com/evidence?api%5Fkey=value'), 'INVALID_PUBLIC_URL') })
  it('accepts a benign query parameter', () => { expect(validatePublicHttpsUrl('https://example.com/evidence?section=one').ok).toBe(true) })
  it('does not perform DNS lookup for URL policy', () => { expect(validatePublicHttpsUrl('https://does-not-resolve.example/evidence').ok).toBe(true) })
  it('maps queued to awaiting_generation', () => { expect(mapGeoFlowStatusToDiscoveryStack('queued')).toEqual({ ok: true, value: 'awaiting_generation' }) })
  it('maps running to awaiting_generation', () => { expect(mapGeoFlowStatusToDiscoveryStack('running')).toEqual({ ok: true, value: 'awaiting_generation' }) })
  it('maps draft_ready to awaiting_review', () => { expect(mapGeoFlowStatusToDiscoveryStack('draft_ready')).toEqual({ ok: true, value: 'awaiting_review' }) })
  it('maps review_required to awaiting_review', () => { expect(mapGeoFlowStatusToDiscoveryStack('review_required')).toEqual({ ok: true, value: 'awaiting_review' }) })
  it('maps blocked to blocked', () => { expect(mapGeoFlowStatusToDiscoveryStack('blocked')).toEqual({ ok: true, value: 'blocked' }) })
  it('maps failed to failed', () => { expect(mapGeoFlowStatusToDiscoveryStack('failed')).toEqual({ ok: true, value: 'failed' }) })
  it('maps retry_wait to retry_wait', () => { expect(mapGeoFlowStatusToDiscoveryStack('retry_wait')).toEqual({ ok: true, value: 'retry_wait' }) })
  it('rejects GEOFlow approved mapping', () => { expectFailure(mapGeoFlowStatusToDiscoveryStack('approved'), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects GEOFlow publishing mapping', () => { expectFailure(mapGeoFlowStatusToDiscoveryStack('publishing'), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects GEOFlow published mapping', () => { expectFailure(mapGeoFlowStatusToDiscoveryStack('published'), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects unknown GEOFlow mapping', () => { expectFailure(mapGeoFlowStatusToDiscoveryStack('unknown'), 'UNKNOWN_STATE') })
  it('maps awaiting_generation to running', () => { expect(mapDiscoveryStackStatusToGeoFlow('awaiting_generation')).toEqual({ ok: true, value: 'running' }) })
  it('maps awaiting_review to review_required', () => { expect(mapDiscoveryStackStatusToGeoFlow('awaiting_review')).toEqual({ ok: true, value: 'review_required' }) })
  it('maps blocked to GEOFlow blocked', () => { expect(mapDiscoveryStackStatusToGeoFlow('blocked')).toEqual({ ok: true, value: 'blocked' }) })
  it('maps failed to GEOFlow failed', () => { expect(mapDiscoveryStackStatusToGeoFlow('failed')).toEqual({ ok: true, value: 'failed' }) })
  it('maps retry_wait to GEOFlow retry_wait', () => { expect(mapDiscoveryStackStatusToGeoFlow('retry_wait')).toEqual({ ok: true, value: 'retry_wait' }) })
  it('rejects ready_to_publish mapping', () => { expectFailure(mapDiscoveryStackStatusToGeoFlow('ready_to_publish'), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects publishing mapping', () => { expectFailure(mapDiscoveryStackStatusToGeoFlow('publishing'), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects delivered mapping', () => { expectFailure(mapDiscoveryStackStatusToGeoFlow('delivered'), 'UNTRUSTED_DELIVERY_STATE') })
  it('accepts queued to running', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'queued', to: 'running', explicitRetry: false }).ok).toBe(true) })
  it('accepts running to draft_ready', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'running', to: 'draft_ready', explicitRetry: false }).ok).toBe(true) })
  it('accepts running to review_required', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'running', to: 'review_required', explicitRetry: false }).ok).toBe(true) })
  it('accepts draft_ready to review_required', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'draft_ready', to: 'review_required', explicitRetry: false }).ok).toBe(true) })
  it('accepts review_required to blocked', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'review_required', to: 'blocked', explicitRetry: false }).ok).toBe(true) })
  it('accepts retry_wait to queued only with explicit retry', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'retry_wait', to: 'queued', explicitRetry: true }).ok).toBe(true) })
  it('accepts failed to queued only with explicit retry', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'failed', to: 'queued', explicitRetry: true }).ok).toBe(true) })
  it('rejects retry_wait to queued without explicit retry', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'retry_wait', to: 'queued', explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects failed to running even with explicit retry', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'failed', to: 'running', explicitRetry: true }), 'INVALID_STATUS_TRANSITION') })
  it('rejects blocked to approved', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'blocked', to: 'approved', explicitRetry: false }), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects published rollback state', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'published', to: 'running', explicitRetry: false }), 'UNTRUSTED_DELIVERY_STATE') })
  it('rejects unknown transition state', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'unknown', to: 'running', explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects transition unknown field', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'queued', to: 'running', explicitRetry: false, extra: true }), 'UNKNOWN_FIELD') })
})

describe('GEOFlow generation contract V1 — combined status events and lineage', () => {
  it('accepts initial queued event without previous state', () => { const result = validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }); expect(result.ok).toBe(true) })
  it('rejects initial running event without previous state', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'running'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('accepts queued to running event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'queued', request: validRequest, response: makeProgressResponse(validRequest, 'running'), explicitRetry: false }).ok).toBe(true) })
  it('accepts running to draft_ready event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: makeDraftResponse(validRequest, { status: 'draft_ready' }), explicitRetry: false }).ok).toBe(true) })
  it('accepts running to review_required event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: validResponse, explicitRetry: false }).ok).toBe(true) })
  it('accepts draft_ready to review_required event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'draft_ready', request: validRequest, response: validResponse, explicitRetry: false }).ok).toBe(true) })
  it('accepts review_required to blocked event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'review_required', request: validRequest, response: makeFailureResponse(validRequest, 'blocked'), explicitRetry: false }).ok).toBe(true) })
  it('accepts retry_wait to queued with explicit retry', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'retry_wait', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: true }).ok).toBe(true) })
  it('accepts failed to queued with explicit retry', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'failed', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: true }).ok).toBe(true) })
  it('rejects retry_wait to queued without explicit retry', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'retry_wait', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects running to queued', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects an event with unknown previous state', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'unknown', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects an event with a published response', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'publishing', request: validRequest, response: { ...validResponse, status: 'published' }, explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects an event with invalid request lineage', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: { ...validRequest, requestFingerprint: HASH_B }, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'REQUEST_FINGERPRINT_MISMATCH') })
  it('verifies a candidate response lineage', () => { const result = verifyGeoFlowLineage(validRequest, validResponse); expect(result.ok).toBe(true) })
  it('verifies a progress response lineage without content artifact', () => { expect(verifyGeoFlowLineage(validRequest, makeProgressResponse()).ok).toBe(true) })
  it('verifies a failure response lineage without content artifact', () => { expect(verifyGeoFlowLineage(validRequest, makeFailureResponse()).ok).toBe(true) })
  it('rejects candidate lineage with wrong article identity', () => { expectFailure(verifyGeoFlowLineage(validRequest, responseWith({ externalArticleKey: 'wrong', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'wrong' } })), 'IDENTITY_MISMATCH') })
  it('derives stable article identity from calendar entry and deliverable', () => { expect(deriveExternalArticleKey(validRequest)).toBe('article-101-303') })
  it('candidate identity matches request brief fingerprint', () => { expect(validResponse.draftIdentity.briefFingerprint).toBe(validRequest.briefFingerprint) })
  it('candidate identity does not use title as article identity', () => { expect(deriveExternalArticleKey(validRequest)).not.toContain(validRequest.brief.title) })
  it('response status remains candidate review_required', () => { expect(validResponse.status).toBe('review_required') })
  it('failure metadata contains only fixed code and retryable flag', () => { const failure = makeFailureResponse(); expect(Object.keys(failure.failure).sort()).toEqual(['code', 'retryable']) })
  it('progress metadata contains observedAt rather than completedAt', () => { const progress = makeProgressResponse(); expect('observedAt' in progress).toBe(true); expect('completedAt' in progress).toBe(false) })
  it('draft result contains content artifact rather than legacy top-level body fields', () => { expect('contentArtifact' in validResponse).toBe(true); expect('bodyMarkdown' in validResponse).toBe(false) })
  it('content artifact uses the fixed schema version', () => { expect(validResponse.contentArtifact.schemaVersion).toBe(CONTENT_ARTIFACT_SCHEMA_VERSION) })
})

describe('GEOFlow generation contract V1 — fixed HMAC envelope planner', () => {
  it('plans an envelope from request without bodyHash input', () => { const result = planSigningEnvelope(validEnvelopeInput); expect(result.ok).toBe(true); if (result.ok) expect(result.value.bodyHash).toMatch(/^[0-9a-f]{64}$/u) })
  it('computes bodyHash from canonical request bytes', () => { const canonical = canonicalizeContractValue(validRequest); const envelope = plannedEnvelope(); expect(canonical.ok).toBe(true); if (canonical.ok) expect(envelope.bodyHash).toBe(sha256(canonical.value)) })
  it('rejects caller-supplied bodyHash planner field', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, bodyHash: HASH_A }), 'UNKNOWN_FIELD') })
  it('rejects missing keyId planner field', () => { const input = { ...validEnvelopeInput } as Record<string, unknown>; delete input.keyId; expectFailure(planSigningEnvelope(input), 'UNKNOWN_FIELD') })
  it('uses fixed hmac-sha256 algorithm', () => { const envelope = plannedEnvelope(); expect(envelope.algorithm).toBe(SIGNING_ALGORITHM) })
  it('uses fixed POST method', () => { const envelope = plannedEnvelope(); expect(envelope.method).toBe(SIGNING_METHOD) })
  it('uses fixed generation-jobs path', () => { const envelope = plannedEnvelope(); expect(envelope.path).toBe(SIGNING_PATH) })
  it('uses caller-injected timestamp', () => { const envelope = plannedEnvelope({ timestamp: '2026-08-25T04:03:00+08:00' }); expect(envelope.timestamp).toBe('2026-08-24T20:03:00.000Z') })
  it('uses caller-injected nonce', () => { const envelope = plannedEnvelope({ nonce: 'Z'.repeat(32) }); expect(envelope.nonce).toBe('Z'.repeat(32)) })
  it('rejects a short nonce', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, nonce: 'short' }), 'INVALID_INPUT') })
  it('rejects a nonce with non-base64url punctuation', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, nonce: `${'N'.repeat(31)}!` }), 'INVALID_INPUT') })
  it('rejects an overlong nonce', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, nonce: 'N'.repeat(129) }), 'INVALID_INPUT') })
  it('rejects a keyId with secret-like punctuation', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, keyId: 'token=secret' }), 'INVALID_OPAQUE_IDENTIFIER') })
  it('canonical signing input starts with algorithm', () => { const envelope = plannedEnvelope(); expect(envelope.canonicalSigningInput.startsWith(`${SIGNING_ALGORITHM}\n`)).toBe(true) })
  it('canonical signing input includes method and path', () => { const envelope = plannedEnvelope(); expect(envelope.canonicalSigningInput.split('\n').slice(0, 3)).toEqual([SIGNING_ALGORITHM, SIGNING_METHOD, SIGNING_PATH]) })
  it('canonical signing input has fixed field count', () => { expect(plannedEnvelope().canonicalSigningInput.split('\n')).toHaveLength(13) })
  it('canonical signing input binds request fingerprint', () => { const envelope = plannedEnvelope(); expect(envelope.canonicalSigningInput).toContain(validRequest.requestFingerprint) })
  it('canonical signing input binds body hash', () => { const envelope = plannedEnvelope(); expect(envelope.canonicalSigningInput).toContain(envelope.bodyHash) })
  it('canonical signing input binds keyId', () => { const envelope = plannedEnvelope(); expect(envelope.canonicalSigningInput.endsWith('\nkey-1')).toBe(true) })
  it('canonical builder uses exact newline ordering', () => { const envelope = plannedEnvelope(); expect(buildCanonicalSigningInput(envelope as never)).toBe(envelope.canonicalSigningInput) })
  it('rejects an envelope extra field', () => { expectFailure(verifySigningEnvelope({ ...plannedEnvelope(), extra: true }, 'a'.repeat(64), signingContext()), 'UNKNOWN_FIELD') })
  it('rejects an envelope algorithm mutation', () => { expectFailure(verifySigningEnvelope({ ...plannedEnvelope(), algorithm: 'sha256' }, 'a'.repeat(64), signingContext()), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects an envelope method mutation', () => { expectFailure(verifySigningEnvelope({ ...plannedEnvelope(), method: 'PUT' }, 'a'.repeat(64), signingContext()), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects an envelope path mutation', () => { expectFailure(verifySigningEnvelope({ ...plannedEnvelope(), path: '/other' }, 'a'.repeat(64), signingContext()), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects an envelope request identity mutation', () => { const envelope = plannedEnvelope({ request: makeRequest({ requestId: 'req-002' }) }); expectFailure(verifySigningEnvelope(envelope, 'a'.repeat(64), signingContext()), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects a body hash mutation after canonical input update', () => { const envelope = plannedEnvelope(); const bodyHash = HASH_A; const mutated = { ...envelope, bodyHash, canonicalSigningInput: buildCanonicalSigningInput({ ...envelope, bodyHash }) }; expectFailure(verifySigningEnvelope(mutated, 'a'.repeat(64), signingContext()), 'CONTENT_HASH_MISMATCH') })
  it('accepts a valid synthetic signature verifier', () => { expect(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext()).ok).toBe(true) })
  it('rejects uppercase signature format', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'A'.repeat(64), signingContext()), 'INVALID_INPUT') })
  it('rejects short signature format', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(63), signingContext()), 'INVALID_INPUT') })
  it('rejects a signature with punctuation', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), `${'a'.repeat(63)}!`, signingContext()), 'INVALID_INPUT') })
  it('rejects a signature verifier mismatch', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ signatureVerifier: () => false })), 'IDENTITY_MISMATCH') })
  it('rejects a signature verifier exception', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ signatureVerifier: () => { throw new Error('signature') } })), 'IDENTITY_MISMATCH') })
  it('rejects sender context mismatch', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ expectedSender: 'other-sender' })), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects receiver context mismatch', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ expectedReceiver: 'other-receiver' })), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects keyId context mismatch', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ expectedKeyId: 'other-key' })), 'SIGNATURE_CONTEXT_MISMATCH') })
  it('rejects an expired timestamp', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ verificationTime: '2026-08-25T04:00:00Z', maxClockSkewSeconds: 60 })), 'SIGNATURE_EXPIRED') })
  it('rejects a future timestamp outside skew', () => { expectFailure(verifySigningEnvelope(plannedEnvelope({ timestamp: '2026-08-25T04:04:00Z' }), 'a'.repeat(64), signingContext({ verificationTime: '2026-08-25T04:02:00Z', maxClockSkewSeconds: 60 })), 'SIGNATURE_EXPIRED') })
  it('rejects a reused nonce', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ nonceFreshnessVerifier: () => false })), 'NONCE_REPLAYED') })
  it('rejects a throwing nonce verifier', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ nonceFreshnessVerifier: () => { throw new Error('nonce') } })), 'NONCE_REPLAYED') })
  it('rejects maxClockSkewSeconds below one', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ maxClockSkewSeconds: 0 })), 'INVALID_INPUT') })
  it('rejects maxClockSkewSeconds above 300', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ maxClockSkewSeconds: 301 })), 'INVALID_INPUT') })
  it('rejects context unknown fields', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ extra: true })), 'UNKNOWN_FIELD') })
  it('rejects a malformed verification time', () => { expectFailure(verifySigningEnvelope(plannedEnvelope(), 'a'.repeat(64), signingContext({ verificationTime: 'tomorrow' })), 'INVALID_TIMESTAMP') })
  it('does not expose a secret field in envelope output', () => { expect('secret' in plannedEnvelope()).toBe(false) })
  it('does not expose authorization in envelope output', () => { expect('authorization' in plannedEnvelope()).toBe(false) })
  it('rejects a planner unknown field instead of ignoring it', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, secret: 'not-a-secret' }), 'UNKNOWN_FIELD') })
  it('accepts canonical signing input from fixed core', () => { const envelope = plannedEnvelope(); expect(buildCanonicalSigningInput(envelope as never).split('\n')[0]).toBe(SIGNING_ALGORITHM) })
})


describe('GEOFlow generation contract V1 — combined status events and lineage', () => {
  it('accepts initial queued event without previous state', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }).ok).toBe(true) })
  it('rejects initial running event without previous state', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'running'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('accepts queued to running event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'queued', request: validRequest, response: makeProgressResponse(validRequest, 'running'), explicitRetry: false }).ok).toBe(true) })
  it('accepts running to draft_ready event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: makeDraftResponse(validRequest, { status: 'draft_ready' }), explicitRetry: false }).ok).toBe(true) })
  it('accepts running to review_required event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: validResponse, explicitRetry: false }).ok).toBe(true) })
  it('accepts draft_ready to review_required event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'draft_ready', request: validRequest, response: validResponse, explicitRetry: false }).ok).toBe(true) })
  it('accepts review_required to blocked event', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'review_required', request: validRequest, response: makeFailureResponse(validRequest, 'blocked'), explicitRetry: false }).ok).toBe(true) })
  it('accepts retry_wait to queued with explicit retry', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'retry_wait', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: true }).ok).toBe(true) })
  it('accepts failed to queued with explicit retry', () => { expect(validateGeoFlowStatusEventForStoredState({ previousStatus: 'failed', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: true }).ok).toBe(true) })
  it('rejects retry_wait to queued without explicit retry', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'retry_wait', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects running to queued', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects an event with unknown previous state', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'unknown', request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects an event with a published response', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: { ...validResponse, status: 'published' }, explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects an event with request fingerprint mismatch', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: { ...validRequest, requestFingerprint: HASH_B }, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false }), 'REQUEST_FINGERPRINT_MISMATCH') })
  it('rejects an event with response request mismatch', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'queued', request: validRequest, response: { ...makeProgressResponse(validRequest, 'running'), requestId: 'other' }, explicitRetry: false }), 'IDENTITY_MISMATCH') })
  it('rejects an event with evidence mismatch', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: responseWith({ evidenceSnapshotHash: HASH_B }), explicitRetry: false }), 'EVIDENCE_SNAPSHOT_MISMATCH') })
  it('rejects an event with candidate article identity mismatch', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: responseWith({ externalArticleKey: 'other', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'other' } }), explicitRetry: false }), 'IDENTITY_MISMATCH') })
  it('rejects an event with an applied rule outside selection', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: responseWith({ appliedRuleIds: ['not-selected'] }), explicitRetry: false }), 'APPLIED_RULE_OUTSIDE_SELECTION') })
  it('rejects a status event unknown field', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: false, extra: true }), 'UNKNOWN_FIELD') })
  it('rejects a status event null response', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: null, explicitRetry: false }), 'INVALID_INPUT') })
  it('rejects a status event nonboolean retry flag', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: makeProgressResponse(validRequest, 'queued'), explicitRetry: 'yes' }), 'INVALID_INPUT') })
  it('accepts a verified candidate lineage', () => { const result = verifyGeoFlowLineage(validRequest, validResponse); expect(result.ok).toBe(true) })
  it('accepts progress lineage without a content artifact', () => { expect(verifyGeoFlowLineage(validRequest, makeProgressResponse()).ok).toBe(true) })
  it('accepts failure lineage without a content artifact', () => { expect(verifyGeoFlowLineage(validRequest, makeFailureResponse()).ok).toBe(true) })
  it('rejects candidate lineage with wrong external article key', () => { expectFailure(verifyGeoFlowLineage(validRequest, responseWith({ externalArticleKey: 'other', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'other' } })), 'IDENTITY_MISMATCH') })
  it('derives the stable article key from server IDs', () => { expect(deriveExternalArticleKey(validRequest)).toBe('article-101-303') })
  it('does not derive article identity from brief title', () => { expect(deriveExternalArticleKey(validRequest)).not.toContain(validRequest.brief.title) })
  it('keeps candidate status review_required', () => { expect(validResponse.status).toBe('review_required') })
  it('keeps failure state separate from draft result', () => { expect('failure' in makeFailureResponse()).toBe(true); expect('contentArtifact' in makeFailureResponse()).toBe(false) })
  it('keeps progress state separate from draft result', () => { expect('observedAt' in makeProgressResponse()).toBe(true); expect('contentArtifact' in makeProgressResponse()).toBe(false) })
  it('keeps retry state separate from failure state', () => { expect('retry' in makeRetryResponse()).toBe(true); expect('failure' in makeRetryResponse()).toBe(false) })
  it('requires fixed candidate artifact schema version', () => { expect(validResponse.contentArtifact.schemaVersion).toBe(CONTENT_ARTIFACT_SCHEMA_VERSION) })
  it('preserves exact candidate body newline', () => { expect(validResponse.contentArtifact.bodyMarkdown).toBe(BODY_MARKDOWN) })
  it('preserves exact candidate body hash', () => { expect(validResponse.contentArtifact.bodyHash).toBe(BODY_HASH) })
  it('uses lowercase candidate body hash', () => { expect(validResponse.contentArtifact.bodyHash).toMatch(/^[0-9a-f]{64}$/u) })
  it('uses lowercase chunk hash', () => { expect(validRequest.evidenceChunks[0]?.chunkHash).toMatch(/^[0-9a-f]{64}$/u) })
  it('lineage success retains validated request evidence for correlation', () => { const result = verifyGeoFlowLineage(validRequest, validResponse); expect(result.ok).toBe(true); if (result.ok) expect(result.value.request.evidenceChunks).toHaveLength(1) })
  it('does not expose stack text in event failures', () => { const result = validateGeoFlowStatusEventForStoredState({ previousStatus: null, request: validRequest, response: { ...makeProgressResponse(validRequest, 'queued'), observedAt: 'invalid' }, explicitRetry: false }); expectFailure(result, 'INVALID_TIMESTAMP'); expect(JSON.stringify(result)).not.toContain('Error') })
  it('rejects terminal delivery vocabulary in a response', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, status: 'delivered' }, validRequest), 'UNKNOWN_STATE') })
  it('rejects terminal delivery vocabulary in a status event', () => { expectFailure(validateGeoFlowStatusEventForStoredState({ previousStatus: 'running', request: validRequest, response: { ...validResponse, status: 'delivered' }, explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects a response with missing external project identity', () => { expectFailure(validateGeoFlowResponse(responseWith({ externalProjectKey: '' }), validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects a response with missing external task identity', () => { expectFailure(validateGeoFlowResponse(responseWith({ externalTaskKey: '' }), validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects a response with missing external job identity', () => { expectFailure(validateGeoFlowResponse(responseWith({ externalJobKey: '' }), validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects a response with missing external article identity', () => { expectFailure(validateGeoFlowResponse(responseWith({ externalArticleKey: '', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: '' } }), validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
})
