import { describe, expect, it } from 'vitest'
import {
  GEOFLOW_PROTOCOL_VERSION,
  buildCanonicalSigningInput,
  buildGeoFlowRequest,
  canonicalRequestFingerprint,
  deriveExternalArticleKey,
  mapDiscoveryStackStatusToGeoFlow,
  mapGeoFlowStatusToDiscoveryStack,
  planSigningEnvelope,
  resolveGeoFlowIdempotency,
  validateGeoFlowRequest,
  validateGeoFlowResponse,
  validatePublicHttpsUrl,
  validateResponseForRequest,
  verifyGeoFlowLineage,
  verifyPublishedGeoFlowLineage,
  verifySigningEnvelope,
  verifyStatusTransition,
} from '../server/geoflow-integration'
import { canonicalizeContractValue } from '../server/geoflow-integration/fingerprint'
import { makeResponse, validEnvelopeInput, validRequest, validRequestDraft, validResponse, HASH_A, HASH_B, HASH_C } from './fixtures/geoflow-integration/fixtures'

function clone<T>(value: T): T { return JSON.parse(JSON.stringify(value)) as T }
function expectFailure(result: { ok: boolean; reason?: string }, reason: string): void { expect(result.ok).toBe(false); if (!result.ok) expect(result.reason).toBe(reason) }

describe('GEOFlow integration contract V1', () => {
  it('accepts the canonical article draft', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.requestFingerprint).toMatch(/^[0-9a-f]{64}$/u) })
  it('accepts faq content type', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, contentType: 'faq' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.contentType).toBe('faq') })
  it('accepts service_page content type', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, contentType: 'service_page' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.contentType).toBe('service_page') })
  it('accepts zh-hant language', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, language: 'zh-hant' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.language).toBe('zh-hant') })
  it('accepts revision generation mode', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, generationMode: 'revision' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.generationMode).toBe('revision') })
  it('canonicalizes a timezone timestamp to UTC', () => { const result = buildGeoFlowRequest(validRequestDraft); expect(result.ok).toBe(true); if (result.ok) expect(result.value.createdAt).toBe('2026-08-24T20:00:00.000Z') })
  it('normalizes NFKC and whitespace in human evidence text', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], reviewedText: '  Ａpproved\t evidence  ' }] }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.evidenceChunks[0]?.reviewedText).toBe('Approved evidence') })
  it('deduplicates and sorts set-like rule ids', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, selectedRuleIds: ['z-rule', 'a-rule', 'z-rule'] }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.selectedRuleIds).toEqual(['a-rule', 'z-rule']) })
  it('deduplicates and sorts authority source ids', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, authoritySourceIds: ['source-2', 'source-1', 'source-2'] }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.authoritySourceIds).toEqual(['source-1', 'source-2']) })
  it('keeps order-sensitive evidence chunks in order', () => { const second = { ...validRequestDraft.evidenceChunks[0], sourceId: 'source-2', artifactId: 'artifact-2', chunkId: 'chunk-2', reviewedText: 'Second evidence.' }; const result = buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [second, validRequestDraft.evidenceChunks[0]] }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.evidenceChunks.map(chunk => chunk.chunkId)).toEqual(['chunk-2', 'chunk-1']) })
  it('rejects an unknown request key', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, unexpected: true }); expectFailure(result, 'UNKNOWN_FIELD') })
  it('rejects null request input', () => { expectFailure(buildGeoFlowRequest(null), 'INVALID_INPUT') })
  it('rejects undefined request input', () => { expectFailure(buildGeoFlowRequest(undefined), 'INVALID_INPUT') })
  it('rejects an array request input', () => { expectFailure(buildGeoFlowRequest([]), 'INVALID_INPUT') })
  it('rejects a primitive request input', () => { expectFailure(buildGeoFlowRequest('request'), 'INVALID_INPUT') })
  it('rejects malformed nested evidence', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{}] }), 'UNKNOWN_FIELD') })
  it('rejects an extra evidence key', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], secret: 'x' }] }), 'UNKNOWN_FIELD') })
  it('rejects a throwing request getter', () => { const input = { ...validRequestDraft }; Object.defineProperty(input, 'requestId', { get() { throw new Error('getter') } }); expectFailure(buildGeoFlowRequest(input), 'INVALID_INPUT') })
  it('rejects a proxy that throws during ownKeys', () => { const input = new Proxy({ ...validRequestDraft }, { ownKeys() { throw new Error('proxy') } }); expectFailure(buildGeoFlowRequest(input), 'UNKNOWN_FIELD') })
  it('rejects an unsupported protocol version', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, protocolVersion: 'discoverystack-geoflow-v2' }), 'INVALID_PROTOCOL_VERSION') })
  it('uses the fixed protocol version', () => { expect(GEOFLOW_PROTOCOL_VERSION).toBe('discoverystack-geoflow-v1') })
  it('rejects an empty request id', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestId: '' }), 'INVALID_INPUT') })
  it('rejects an overlong request id', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestId: 'r'.repeat(129) }), 'INVALID_INPUT') })
  it('rejects an overlong idempotency key', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, idempotencyKey: 'i'.repeat(129) }), 'INVALID_INPUT') })
  it('rejects zero owner identity', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, ownerUserId: 0 }), 'INVALID_INPUT') })
  it('rejects fractional client identity', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, clientId: 1.5 }), 'INVALID_INPUT') })
  it('rejects a non-lowercase evidence hash', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceSnapshotHash: HASH_A.toUpperCase() }), 'INVALID_HASH') })
  it('rejects a short brief fingerprint', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, briefFingerprint: 'abc' }), 'INVALID_HASH') })
  it('rejects a timestamp without timezone', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, createdAt: '2026-08-25T04:00:00' }), 'INVALID_TIMESTAMP') })
  it('rejects an impossible calendar date', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, createdAt: '2026-02-30T04:00:00Z' }), 'INVALID_TIMESTAMP') })
  it('rejects an invalid timezone offset', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, createdAt: '2026-08-25T04:00:00+24:00' }), 'INVALID_TIMESTAMP') })
  it('rejects an HTTP evidence locator', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'http://example.com/evidence' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects an ftp evidence locator', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'ftp://example.com/evidence' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects a file evidence locator', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'file:///tmp/evidence' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects URL credentials', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'https://user:pass@example.com/evidence' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects credential-like query content', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'https://example.com/evidence?token=secret' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects URL fragments', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], locator: 'https://example.com/evidence#fragment' }] }), 'INVALID_PUBLIC_URL') })
  it('rejects localhost', () => { expectFailure(validatePublicHttpsUrl('https://localhost/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects a private IPv4 address', () => { expectFailure(validatePublicHttpsUrl('https://192.168.1.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects a loopback IPv4 address', () => { expectFailure(validatePublicHttpsUrl('https://127.0.0.1/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects a link-local IPv4 address', () => { expectFailure(validatePublicHttpsUrl('https://169.254.10.5/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects a documentation special-use IPv4 address', () => { expectFailure(validatePublicHttpsUrl('https://203.0.113.10/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 loopback', () => { expectFailure(validatePublicHttpsUrl('https://[::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects IPv6 documentation special-use space', () => { expectFailure(validatePublicHttpsUrl('https://[2001:db8::1]/evidence'), 'PRIVATE_OR_SPECIAL_TARGET') })
  it('rejects an onion hostname', () => { expectFailure(validatePublicHttpsUrl('https://hiddenservice.onion/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects a single-label hostname', () => { expectFailure(validatePublicHttpsUrl('https://example/evidence'), 'INVALID_PUBLIC_URL') })
  it('rejects a non-443 port', () => { expectFailure(validatePublicHttpsUrl('https://example.com:8443/evidence'), 'INVALID_PUBLIC_URL') })
  it('accepts a public HTTPS URL', () => { const result = validatePublicHttpsUrl('https://example.com/evidence'); expect(result).toEqual({ ok: true, value: 'https://example.com/evidence' }) })
  it('rejects a per-chunk reviewed text over 12,000 characters', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], reviewedText: 'x'.repeat(12_001) }] }), 'LIMIT_EXCEEDED') })
  it('rejects aggregate reviewed text over 120,000 characters', () => { const chunks = Array.from({ length: 11 }, (_, index) => ({ ...validRequestDraft.evidenceChunks[0], chunkId: `chunk-${index}`, reviewedText: 'x'.repeat(12_000) })); expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: chunks }), 'LIMIT_EXCEEDED') })
  it('rejects more than 50 evidence chunks', () => { const chunks = Array.from({ length: 51 }, (_, index) => ({ ...validRequestDraft.evidenceChunks[0], chunkId: `chunk-${index}` })); expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: chunks }), 'LIMIT_EXCEEDED') })
  it('rejects more than 30 selected rules', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, selectedRuleIds: Array.from({ length: 31 }, (_, index) => `rule-${index}`) }), 'LIMIT_EXCEEDED') })
  it('rejects more than 50 authorities', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, authoritySourceIds: Array.from({ length: 51 }, (_, index) => `source-${index}`), evidenceChunks: [] }), 'LIMIT_EXCEEDED') })
  it('rejects an unknown requested capability', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestedCapabilities: ['unknown_capability'] }), 'INVALID_INPUT') })
  it('rejects a non-array requested capability field', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, requestedCapabilities: 'publication' }), 'INVALID_INPUT') })
  it('rejects an evidence chunk from an unapproved authority', () => { expectFailure(buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [{ ...validRequestDraft.evidenceChunks[0], sourceId: 'not-allowlisted' }] }), 'CITATION_OUTSIDE_APPROVED_EVIDENCE') })
  it('rejects an empty evidence chunk list only when downstream policy requires evidence', () => { const result = buildGeoFlowRequest({ ...validRequestDraft, evidenceChunks: [] }); expect(result.ok).toBe(true) })
  it('rejects a non-plain request object', () => { expectFailure(buildGeoFlowRequest(new Date()), 'INVALID_INPUT') })
  it('rejects a Date in canonical JSON', () => { expectFailure(canonicalizeContractValue(new Date()), 'INVALID_INPUT') })
  it('rejects a Map in canonical JSON', () => { expectFailure(canonicalizeContractValue(new Map()), 'INVALID_INPUT') })
  it('rejects a Set in canonical JSON', () => { expectFailure(canonicalizeContractValue(new Set()), 'INVALID_INPUT') })
  it('rejects NaN in canonical JSON', () => { expectFailure(canonicalizeContractValue(Number.NaN), 'INVALID_INPUT') })
  it('rejects Infinity in canonical JSON', () => { expectFailure(canonicalizeContractValue(Number.POSITIVE_INFINITY), 'INVALID_INPUT') })
  it('rejects a function in canonical JSON', () => { expectFailure(canonicalizeContractValue(() => undefined), 'INVALID_INPUT') })
  it('rejects a symbol in canonical JSON', () => { expectFailure(canonicalizeContractValue(Symbol('x')), 'INVALID_INPUT') })
  it('rejects a bigint in canonical JSON', () => { expectFailure(canonicalizeContractValue(BigInt(1)), 'INVALID_INPUT') })
  it('rejects a circular canonical object', () => { const value: Record<string, unknown> = {}; value.self = value; expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('rejects a throwing canonical getter', () => { const value = {}; Object.defineProperty(value, 'bad', { enumerable: true, get() { throw new Error('getter') } }); expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('rejects a canonical proxy ownKeys exception', () => { const value = new Proxy({ field: 'x' }, { ownKeys() { throw new Error('proxy') } }); expectFailure(canonicalizeContractValue(value), 'INVALID_INPUT') })
  it('produces stable canonical object key ordering', () => { const first = canonicalizeContractValue({ b: 2, a: 1 }); const second = canonicalizeContractValue({ a: 1, b: 2 }); expect(first).toEqual(second) })
  it('preserves order-sensitive arrays in canonical JSON', () => { const first = canonicalizeContractValue(['a', 'b']); const second = canonicalizeContractValue(['b', 'a']); expect(first.ok && second.ok ? first.value === second.value : false).toBe(false) })
  it('changes request fingerprint when a server identity changes', () => { const first = canonicalRequestFingerprint(validRequestDraft); const second = canonicalRequestFingerprint({ ...validRequestDraft, jobId: 506 }); expect(first.ok && second.ok ? first.value !== second.value : false).toBe(true) })
  it('rejects a request fingerprint with uppercase hex', () => { const input = { ...validRequest, requestFingerprint: validRequest.requestFingerprint.toUpperCase() }; expectFailure(validateGeoFlowRequest(input), 'INVALID_HASH') })
  it('accepts the computed request fingerprint', () => { expect(validateGeoFlowRequest(validRequest)).toEqual({ ok: true, value: validRequest }) })
  it('rejects a mutated request fingerprint', () => { expectFailure(validateGeoFlowRequest({ ...validRequest, requestFingerprint: HASH_B }), 'REQUEST_FINGERPRINT_MISMATCH') })
  it('resolves a missing idempotency record as new_request', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, null); expect(result).toMatchObject({ ok: true, value: { resolution: 'new_request' } }) })
  it('resolves same key and fingerprint as replay', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }); expect(result).toMatchObject({ ok: true, value: { resolution: 'replay' } }) })
  it('rejects same key with a different fingerprint as collision', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: HASH_B }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }), 'IDEMPOTENCY_COLLISION') })
  it('resolves a different key as new_request', () => { const result = resolveGeoFlowIdempotency({ idempotencyKey: 'new-key', requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }); expect(result).toMatchObject({ ok: true, value: { resolution: 'new_request' } }) })
  it('rejects an idempotency unknown key', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint, extra: true }, null), 'UNKNOWN_FIELD') })
  it('rejects malformed stored idempotency state', () => { expectFailure(resolveGeoFlowIdempotency({ idempotencyKey: validRequest.idempotencyKey, requestFingerprint: validRequest.requestFingerprint }, { idempotencyKey: validRequest.idempotencyKey }), 'UNKNOWN_FIELD') })
  it('maps queued to awaiting_generation', () => { expect(mapGeoFlowStatusToDiscoveryStack('queued')).toEqual({ ok: true, value: 'awaiting_generation' }) })
  it('maps published to delivered', () => { expect(mapGeoFlowStatusToDiscoveryStack('published')).toEqual({ ok: true, value: 'delivered' }) })
  it('maps blocked to blocked', () => { expect(mapGeoFlowStatusToDiscoveryStack('blocked')).toEqual({ ok: true, value: 'blocked' }) })
  it('maps ready_to_publish to approved', () => { expect(mapDiscoveryStackStatusToGeoFlow('ready_to_publish')).toEqual({ ok: true, value: 'approved' }) })
  it('maps delivered to published', () => { expect(mapDiscoveryStackStatusToGeoFlow('delivered')).toEqual({ ok: true, value: 'published' }) })
  it('rejects unknown GEOFlow status mapping', () => { expectFailure(mapGeoFlowStatusToDiscoveryStack('success'), 'UNKNOWN_STATE') })
  it('accepts queued to running', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'queued', to: 'running', explicitRetry: false })).toMatchObject({ ok: true }) })
  it('accepts publishing to published', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'publishing', to: 'published', explicitRetry: false })).toMatchObject({ ok: true }) })
  it('rejects blocked to approved', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'blocked', to: 'approved', explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('rejects published rollback', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'published', to: 'running', explicitRetry: true }), 'INVALID_STATUS_TRANSITION') })
  it('rejects failed to running without explicit retry', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'failed', to: 'running', explicitRetry: false }), 'INVALID_STATUS_TRANSITION') })
  it('accepts failed to running with explicit retry', () => { expect(verifyStatusTransition({ machine: 'geoflow', from: 'failed', to: 'running', explicitRetry: true })).toMatchObject({ ok: true }) })
  it('rejects a published transition that does not start from publishing', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'running', to: 'published', explicitRetry: false }), 'UNTRUSTED_PUBLISHED_RESULT') })
  it('rejects an unknown transition state', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'unknown', to: 'running', explicitRetry: false }), 'UNKNOWN_STATE') })
  it('rejects a transition with an unknown field', () => { expectFailure(verifyStatusTransition({ machine: 'geoflow', from: 'queued', to: 'running', explicitRetry: false, extra: true }), 'UNKNOWN_FIELD') })
  it('accepts a canonical response', () => { expect(validateGeoFlowResponse(validResponse, validRequest)).toMatchObject({ ok: true }) })
  it('rejects a response unknown key', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, extra: true }, validRequest), 'UNKNOWN_FIELD') })
  it('rejects a response request id mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, requestId: 'different' }, validRequest), 'REQUEST_FINGERPRINT_MISMATCH') })
  it('rejects a response owner mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, ownerUserId: 999 }, validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response client mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, clientId: 999 }, validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response job mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, jobId: 999 }, validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response evidence snapshot mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, evidenceSnapshotHash: HASH_B }, validRequest), 'EVIDENCE_SNAPSHOT_MISMATCH') })
  it('rejects a response brief fingerprint mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, draftIdentity: { ...validResponse.draftIdentity, briefFingerprint: HASH_C } }, validRequest), 'BRIEF_FINGERPRINT_MISMATCH') })
  it('rejects a response external article identity mismatch', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, externalArticleKey: 'article-other', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'article-other' } }, validRequest), 'IDENTITY_MISMATCH') })
  it('rejects a response missing external article identity', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, externalArticleKey: '', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: '' } }, validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects an external article URL as an opaque identifier', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, externalArticleKey: 'https://evil.example/article', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'https://evil.example/article' } }, validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects whitespace in an external project key', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, externalProjectKey: 'project with space' }, validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects secret-like punctuation in an external task key', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, externalTaskKey: 'token=secret' }, validRequest), 'INVALID_OPAQUE_IDENTIFIER') })
  it('rejects a response citation outside approved evidence', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, citationBindings: [{ ...validResponse.citationBindings[0], chunkId: 'not-approved' }] }, validRequest), 'CITATION_OUTSIDE_APPROVED_EVIDENCE') })
  it('rejects an applied rule outside selection', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, appliedRuleIds: ['unselected-rule'] }, validRequest), 'APPLIED_RULE_OUTSIDE_SELECTION') })
  it('rejects missing provider provenance', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, providerProvenance: { provider: '', model: '', mode: 'provider', fallbackReason: null } }, validRequest), 'INVALID_INPUT') })
  it('rejects a fallback provider without a fallback reason', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, providerProvenance: { provider: 'provider', model: 'model', mode: 'reference_fallback', fallbackReason: null } }, validRequest), 'PROVIDER_PROVENANCE_MISSING') })
  it('rejects a published response with wrong article identity as untrusted', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, status: 'published', externalArticleKey: 'wrong', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'wrong' } }, validRequest), 'UNTRUSTED_PUBLISHED_RESULT') })
  it('rejects a response with an uppercase content hash', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, contentHash: HASH_A.toUpperCase() }, validRequest), 'INVALID_HASH') })
  it('rejects an overlong response limitation', () => { expectFailure(validateGeoFlowResponse({ ...validResponse, limitations: ['x'.repeat(501)] }, validRequest), 'LIMIT_EXCEEDED') })
  it('validates response through the request wrapper', () => { expect(validateResponseForRequest(validResponse, validRequest)).toMatchObject({ ok: true }) })
  it('derives a stable external article key from request lineage', () => { expect(deriveExternalArticleKey(validRequest)).toBe('article-101-303') })
  it('verifies complete response lineage', () => { expect(verifyGeoFlowLineage(validRequest, validResponse)).toMatchObject({ ok: true }) })
  it('rejects complete lineage when external article key is wrong', () => { expectFailure(verifyGeoFlowLineage(validRequest, { ...validResponse, externalArticleKey: 'article-wrong', draftIdentity: { ...validResponse.draftIdentity, externalArticleKey: 'article-wrong' } }), 'IDENTITY_MISMATCH') })
  it('requires published status for published lineage verifier', () => { expectFailure(verifyPublishedGeoFlowLineage(validRequest, validResponse), 'UNTRUSTED_PUBLISHED_RESULT') })
  it('accepts published lineage with matching identity', () => { expect(verifyPublishedGeoFlowLineage(validRequest, makeResponse(validRequest, { status: 'published' }))).toMatchObject({ ok: true }) })
  it('builds a signing input with exactly one newline per field boundary', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expect(envelope.value.canonicalSigningInput).toBe([GEOFLOW_PROTOCOL_VERSION, validRequest.requestId, validRequest.idempotencyKey, validRequest.requestFingerprint, HASH_C, '2026-08-25T04:02:00.000Z', 'synthetic-nonce-001', 'discoverystack-control-plane', 'geoflow-content-engine'].join('\n')) })
  it('canonicalizes injected signing timestamp', () => { const result = planSigningEnvelope({ ...validEnvelopeInput, timestamp: '2026-08-25T12:02:00+08:00' }); expect(result.ok).toBe(true); if (result.ok) expect(result.value.timestamp).toBe('2026-08-25T04:02:00.000Z') })
  it('keeps injected nonce deterministic', () => { const result = planSigningEnvelope(validEnvelopeInput); expect(result.ok).toBe(true); if (result.ok) expect(result.value.nonce).toBe('synthetic-nonce-001') })
  it('does not include a secret field in the envelope', () => { const result = planSigningEnvelope(validEnvelopeInput); expect(result.ok).toBe(true); if (result.ok) expect(Object.keys(result.value)).not.toContain('secret') })
  it('rejects a planner extra field', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, secret: 'not-accepted' }), 'UNKNOWN_FIELD') })
  it('rejects a planner uppercase body hash', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, bodyHash: HASH_C.toUpperCase() }), 'INVALID_HASH') })
  it('rejects a planner fixed timestamp fallback omission', () => { expectFailure(planSigningEnvelope({ ...validEnvelopeInput, timestamp: undefined }), 'INVALID_TIMESTAMP') })
  it('verifies a synthetic envelope signature', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expect(verifySigningEnvelope(envelope.value, 'synthetic-signature', (input, signature) => input === envelope.value.canonicalSigningInput && signature === 'synthetic-signature')).toEqual({ ok: true, value: true }) })
  it('rejects a synthetic envelope signature mismatch', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expectFailure(verifySigningEnvelope(envelope.value, 'wrong', () => false), 'IDENTITY_MISMATCH') })
  it('rejects an envelope canonical input mutation', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expectFailure(verifySigningEnvelope({ ...envelope.value, canonicalSigningInput: `${envelope.value.canonicalSigningInput}\nmutated` }, 'synthetic-signature', () => true), 'INVALID_INPUT') })
  it('rejects an envelope protocol mutation', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expectFailure(verifySigningEnvelope({ ...envelope.value, protocolVersion: 'discoverystack-geoflow-v2' }, 'synthetic-signature', () => true), 'INVALID_PROTOCOL_VERSION') })
  it('rejects an envelope verifier exception', () => { const envelope = planSigningEnvelope(validEnvelopeInput); expect(envelope.ok).toBe(true); if (envelope.ok) expectFailure(verifySigningEnvelope(envelope.value, 'synthetic-signature', () => { throw new Error('verifier') }), 'IDENTITY_MISMATCH') })
  it('builds the canonical signing input from a typed core', () => { expect(buildCanonicalSigningInput({ protocolVersion: GEOFLOW_PROTOCOL_VERSION, requestId: 'r', idempotencyKey: 'i', requestFingerprint: HASH_A, bodyHash: HASH_B, timestamp: '2026-08-25T00:00:00.000Z', nonce: 'n', sender: 's', receiver: 'r' })).toBe(`${GEOFLOW_PROTOCOL_VERSION}\nr\ni\n${HASH_A}\n${HASH_B}\n2026-08-25T00:00:00.000Z\nn\ns\nr`) })
  it('returns normalized response without the input object reference', () => { const input = clone(validResponse); const result = validateGeoFlowResponse(input, validRequest); expect(result.ok).toBe(true); if (result.ok) expect(result.value).not.toBe(input) })
  it('does not return raw evidence text in failure metadata', () => { const result = validateGeoFlowResponse({ ...validResponse, citationBindings: [{ ...validResponse.citationBindings[0], chunkId: 'not-approved' }] }, validRequest); expectFailure(result, 'CITATION_OUTSIDE_APPROVED_EVIDENCE'); expect(JSON.stringify(result)).not.toContain('Approved evidence text') })
  it('does not return raw request object reference', () => { const input = clone(validRequest); const result = validateGeoFlowRequest(input); expect(result.ok).toBe(true); if (result.ok) expect(result.value).not.toBe(input) })
})
