import { describe, expect, it } from 'vitest'
import { createContentOperationsDeliveredPublicationSource } from '../server/intervention-loop/content-operations-source'
import { notifyInterventionLoopOutcomeAssessed } from '../server/intervention-loop/content-operations-hook'
import { createInMemoryInterventionLoopRepository, runInterventionLoopTick } from '../server/intervention-loop'

const owner = 1
function delivered(id = 30) { return { entry: { id, status: 'delivered', updatedAt: new Date('2026-09-01T00:00:00.000Z'), contentHash: 'c'.repeat(64), publicationPath: '/articles/a' }, job: { briefId: 4 }, draft: { id: 5 }, publicationRun: { id: 11, stage: 'publication', state: 'succeeded', completedAt: new Date('2026-09-01T00:00:00.000Z') }, publicationTarget: { id: 55, targetOrigin: 'https://client.example' }, publicationAttempt: { status: 'delivered', runId: 11, targetId: 55, receiptFingerprint: 'a'.repeat(64), publicationUrl: 'https://client.example/articles/a', publicationContentHash: 'c'.repeat(64) } } as any }
describe('content-operations intervention bridge', () => {
  it('projects only resolvable delivered publications with a validated receipt', async () => { const primary = delivered(); const repository = { async listEntries() { return [primary.entry, { ...primary.entry, id: 31, status: 'planned' }, { ...primary.entry, id: 32 }] }, async resolveDeliveredPublication(_owner: number, entryId: number) { if (entryId === 32) throw new Error('stale'); return entryId === 30 ? primary : null } } as any; const publications = await createContentOperationsDeliveredPublicationSource(repository).listDeliveredPublications(owner, 50); expect(publications).toEqual([expect.objectContaining({ entryId: 30, targetId: 55, publicationUrl: 'https://client.example/articles/a', receiptFingerprint: 'a'.repeat(64), deliveredAt: new Date('2026-09-01T00:00:00.000Z') })]) })
  it('never throws when outcome linking cannot obtain a repository', async () => { await expect(notifyInterventionLoopOutcomeAssessed(owner, { entryId: 30, targetId: 55, assessmentFingerprint: 'a'.repeat(64), assessmentStatus: 'measured' })).resolves.toMatchObject({ ok: false }) })
  it('auto-registers a delivered entry only once across bounded ticks', async () => { const repository = createInMemoryInterventionLoopRepository(); const source = createContentOperationsDeliveredPublicationSource({ async listEntries() { return [delivered().entry] }, async resolveDeliveredPublication() { return delivered() } } as any); const deps = { repository, deliveredPublications: source, linkResolver: { async resolveBrief() { return { id: 4 } }, async resolveDraft() { return { id: 5, jobId: 1, contentHash: 'c'.repeat(64) } }, async resolveEntry() { return { id: 30 } } }, baselineProvider: { async readInventoryHash() { return null } }, pageMetricsPuller: async () => ({ status: 'unknown' as const, reasonCode: 'not_configured' as const }), urlInspector: async () => ({ status: 'unknown' as const, reasonCode: 'not_configured' as const }), clock: { now: () => new Date('2026-09-02T00:00:00.000Z') } }; expect((await runInterventionLoopTick(owner, deps)).autoRegistered).toBe(1); expect((await runInterventionLoopTick(owner, deps)).autoRegistered).toBe(0); expect(await repository.listInterventions(owner)).toHaveLength(1) })
})
