import { describe, expect, it } from 'vitest'
import { createMemoryMediaVaultRepository } from '../server/managed-sites/media-vault/memory-repository'
import { completeMediaUpload, requestBulkMediaUploadIntents, requestMediaUploadIntent, updateMediaGovernance } from '../server/managed-sites/media-vault/service'
import { createMemoryMediaStorage, resolveProductionMediaStorage } from '../server/managed-sites/media-vault/storage'
import { createDeterministicTestImageProcessor, createPassingTestScanner, createUnavailableProductionScanner, hashBytes } from '../server/managed-sites/media-vault/validation'
import type { MediaActor, MediaAssetProjection } from '../server/managed-sites/media-vault/types'
import { createInitialPage } from '../server/managed-sites/page-editor/canonical'
import { compilePageDocument } from '../server/managed-sites/page-editor/compiler'
import { applyPageCommand, createPagePublicationIntent, restorePageVersion } from '../server/managed-sites/page-editor/engine'
import { createMemoryPageEditorRepository } from '../server/managed-sites/page-editor/memory-repository'
import { applyAiProposalToDraft, createMemoryAiBudgetPort, proposeAiWebsiteEdit } from '../server/managed-sites/page-editor/ai'
import { PAGE_COMMAND_VERSION, type PageActor, type PageDocument, type PageMediaBinding } from '../server/managed-sites/page-editor/types'

function png(seed: number, width = 1200, height = 800) { const bytes = Buffer.alloc(48); Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(bytes); Buffer.from('IHDR').copy(bytes, 12); bytes.writeUInt32BE(width, 16); bytes.writeUInt32BE(height, 20); bytes.writeUInt32BE(seed, 40); return bytes }
const mediaActor = (ownerUserId = 1, projectId = 10): MediaActor => ({ ownerUserId, projectId, actorUserId: 99, authority: 'customer_session', role: 'customer_admin' })
const pageActor = (ownerUserId = 1, projectId = 10): PageActor => ({ ownerUserId, projectId, actorUserId: 99, authority: 'customer_session', role: 'customer_admin', canPublish: true })
function mediaDeps(scanner = createPassingTestScanner()) { return { repository: createMemoryMediaVaultRepository(), storage: createMemoryMediaStorage(), scanner, processor: createDeterministicTestImageProcessor() } }
async function readyAssets(count: number, actor = mediaActor()) {
  const deps = mediaDeps()
  const requests = Array.from({ length: count }, (_, index) => {
    const bytes = png(index + 1)
    return { bytes, request: { filename: `case-${index + 1}.png`, declaredMime: 'image/png', declaredBytes: bytes.byteLength, visibility: 'private' as const, idempotencyKey: `e2e-upload-${actor.ownerUserId}-${actor.projectId}-${String(index).padStart(3, '0')}` } }
  })
  const intents = await requestBulkMediaUploadIntents(deps, actor, requests.map(item => item.request)); const assets: MediaAssetProjection[] = []
  for (let index = 0; index < intents.results.length; index++) { const intent = intents.results[index]!; const bytes = requests[index]!.bytes; await deps.storage.putUpload(actor, intent.session.objectKey, bytes, 'image/png'); const completed = await completeMediaUpload(deps, actor, { uploadId: intent.session.uploadId, expectedSha256: hashBytes(bytes) }); const governed = await updateMediaGovernance(deps.repository, actor, { assetId: completed.asset.assetId, visibility: 'public', rightsMetadata: { license: 'customer-confirmed', publishAllowed: true } }); assets.push(governed!) }
  return { deps, assets }
}
function pageWithGallery(asset: MediaAssetProjection, actor = pageActor()): PageDocument { const binding: PageMediaBinding = { bindingId: 'binding_gallery_01', assetId: asset.assetId, assetVersion: asset.version, assetSha256: asset.sha256!, role: 'gallery', alt: '客戶案例', decorative: false, provenance: 'customer' }; return createInitialPage(actor, { pageId: 'page_e2e_home', locale: 'zh-hant', route: '/', contentType: 'home', designThemeId: 'default', designTokenVersion: 'tokens-v1', designTokens: { palette: 'indigo_sand', typeScale: 'editorial', spacing: 'airy', radius: 'soft', maxWidth: 'standard', contrast: 'aa' }, sections: [{ blockId: 'block_gallery_01', type: 'gallery_grid', visible: true, layoutVariant: 'grid', data: { columns: 3, gap: 'balanced', aspect: '4:3', captions: true, lightbox: true, mediaBindingIds: [binding.bindingId] }, mediaBindingIds: [binding.bindingId], schedule: null }, { blockId: 'block_services_01', type: 'services', visible: true, layoutVariant: 'cards', data: { title: '服務', items: [{ id: 'service-1', title: '服務', description: '說明' }] }, mediaBindingIds: [], schedule: null }], seo: { title: '首頁', description: '首頁完整說明。', canonicalPath: '/', noindex: false, ogBindingId: binding.bindingId }, mediaBindings: [binding] }, new Date('2026-08-29T00:00:00Z')) }

describe('managed-site editor mocked E2E V1', () => {
  it('1 bulk upload → process → gallery → preview → governed publish receipt', async () => { const { assets } = await readyAssets(3); const page = pageWithGallery(assets[0]!); const repository = createMemoryPageEditorRepository(); await repository.insertInitial(1, 10, page); const resolve = async (_actor: PageActor, binding: PageMediaBinding) => assets.find(asset => asset.assetId === binding.assetId) || null; const preview = await compilePageDocument({ actor: pageActor(), document: page, resolveMedia: resolve, mode: 'preview' }); expect(preview.blocks[0]?.media[0]?.loading).toBe('lazy'); const publish = await createPagePublicationIntent({ repository, actor: pageActor(), pageId: page.pageId, expectedPageVersion: 1, resolveMedia: resolve, releaseReference: 'release:fixture:1', publicationTargetReference: 'target:fixture:1', idempotencyKey: 'e2e-publish-0001' }); expect(publish).toMatchObject({ deployed: false, externalCalls: false }); expect(publish.receipt.status).toBe('intent_created') })

  it('2 inline text + exact image replacement → mobile projection → publish intent', async () => { const { assets } = await readyAssets(2); const repository = createMemoryPageEditorRepository(); const page = pageWithGallery(assets[0]!); await repository.insertInitial(1, 10, page); const text = await applyPageCommand(repository, pageActor(), page.pageId, { schemaVersion: PAGE_COMMAND_VERSION, type: 'update_text', expectedPageVersion: 1, idempotencyKey: 'e2e-inline-text-01', target: { blockId: 'block_services_01', path: 'data.title' }, payload: '更新服務', reason: 'inline edit' }); const binding = text.page.mediaBindings[0]!; const replaced = await applyPageCommand(repository, pageActor(), page.pageId, { schemaVersion: PAGE_COMMAND_VERSION, type: 'replace_media', expectedPageVersion: 2, idempotencyKey: 'e2e-replace-media-01', target: { bindingId: binding.bindingId }, payload: { ...binding, assetId: assets[1]!.assetId, assetVersion: assets[1]!.version, assetSha256: assets[1]!.sha256, focalPoint: { x: .5, y: .4 } }, reason: 'replace this usage only' }); const artifact = await compilePageDocument({ actor: pageActor(), document: replaced.page, resolveMedia: async (_actor, value) => assets.find(asset => asset.assetId === value.assetId) || null, mode: 'preview' }); expect(artifact.blocks[0]?.responsive.mobile).toBe('grid-max-2'); expect((replaced.page.sections[1]!.data as any).title).toBe('更新服務') })

  it('3 AI 12-image case proposal → customer confirmation → draft publish → rollback', async () => { const { assets } = await readyAssets(12); const initial = pageWithGallery(assets[0]!); const repository = createMemoryPageEditorRepository(); await repository.insertInitial(1, 10, initial); const proposal = await proposeAiWebsiteEdit({ actor: pageActor(), page: initial, request: '把這12張整理成案例區，首頁放6張', approvedMedia: assets, selectedMediaAssetIds: assets.map(asset => asset.assetId), resolveMedia: async (_actor, binding) => assets.find(asset => asset.assetId === binding.assetId) || null, budget: createMemoryAiBudgetPort(), now: new Date('2026-08-29T00:00:00Z') }); const applied = await applyAiProposalToDraft({ repository, actor: pageActor(), proposal, now: new Date('2026-08-29T00:01:00Z') }); const draft = applied.results.at(-1)!.page!; expect(draft.sections.some(block => block.type === 'case_studies')).toBe(true); const published = await createPagePublicationIntent({ repository, actor: pageActor(), pageId: initial.pageId, expectedPageVersion: draft.version, resolveMedia: async (_actor, binding) => assets.find(asset => asset.assetId === binding.assetId) || null, releaseReference: 'release:fixture:2', publicationTargetReference: 'target:fixture:2', idempotencyKey: 'e2e-ai-publish-01' }); expect(published.receipt.status).toBe('intent_created'); const rolledBack = await restorePageVersion(repository, pageActor(), initial.pageId, { version: 1, expectedPageVersion: draft.version, idempotencyKey: 'e2e-ai-rollback-01', reason: 'customer rollback' }); expect(rolledBack.page?.sections.some(block => block.type === 'case_studies')).toBe(false) })

  it('4 malicious upload remains quarantined and cannot enter a public artifact', async () => { const deps = mediaDeps(createUnavailableProductionScanner()); const bytes = png(44); const intent = await requestMediaUploadIntent(deps, mediaActor(), { filename: 'unsafe.png', declaredMime: 'image/png', declaredBytes: bytes.byteLength, visibility: 'public', idempotencyKey: 'e2e-quarantine-01' }); await deps.storage.putUpload(mediaActor(), intent.session.objectKey, bytes, 'image/png'); const result = await completeMediaUpload(deps, mediaActor(), { uploadId: intent.session.uploadId }); expect(result.asset.status).toBe('quarantined'); const fakePage = pageWithGallery({ ...result.asset, rightsMetadata: { ...result.asset.rightsMetadata, publishAllowed: true } }); await expect(compilePageDocument({ actor: pageActor(), document: fakePage, resolveMedia: async () => result.asset, mode: 'publish' })).rejects.toThrow(/ready exact version/i) })

  it('5 two editors get a stale conflict instead of lost updates', async () => { const { assets } = await readyAssets(1); const page = pageWithGallery(assets[0]!); const repository = createMemoryPageEditorRepository(); await repository.insertInitial(1, 10, page); const make = (id: string, value: string) => applyPageCommand(repository, pageActor(), page.pageId, { schemaVersion: PAGE_COMMAND_VERSION, type: 'update_text', expectedPageVersion: 1, idempotencyKey: id, target: { blockId: 'block_services_01', path: 'data.title' }, payload: value, reason: 'concurrent editor' }); const race = await Promise.allSettled([make('e2e-editor-a-01', 'A'), make('e2e-editor-b-01', 'B')]); expect(race.filter(item => item.status === 'fulfilled')).toHaveLength(1); expect(race.filter(item => item.status === 'rejected')).toHaveLength(1); expect((await repository.findCurrent(1, 10, page.pageId))?.version).toBe(2) })

  it('6 missing production storage/provider credential fails closed', () => { expect(() => resolveProductionMediaStorage()).toThrow(/not configured/i); process.env.E2E_EMPTY_S3_CREDENTIAL = ''; expect(() => resolveProductionMediaStorage({ bucket: 'fixture-bucket', region: 'auto', prefix: 'managed-sites', endpoint: 'https://objects.example.test/', credentialReference: 'E2E_EMPTY_S3_CREDENTIAL' })).toThrow(/unresolved/i); delete process.env.E2E_EMPTY_S3_CREDENTIAL })

  it('7 customer A cannot read, discover or bind customer B media', async () => { const { deps, assets } = await readyAssets(1, mediaActor(1, 10)); expect(await deps.repository.findAsset(mediaActor(2, 20), assets[0]!.assetId)).toBeNull(); const page = pageWithGallery(assets[0]!, pageActor(2, 20)); await expect(compilePageDocument({ actor: pageActor(2, 20), document: page, resolveMedia: async () => assets[0]!, mode: 'publish' })).rejects.toThrow(/tenant/i) })
})
