import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { describe, expect, it, vi } from 'vitest'
import { createMemoryMediaVaultRepository } from '../server/managed-sites/media-vault/memory-repository'
import { createS3MediaStorage } from '../server/managed-sites/media-vault/storage'
import { createHttpMediaSecurityScanner } from '../server/managed-sites/media-vault/scanner'
import { createMemoryAiBudgetPort, AI_EDITOR_LIMITS, proposeAiWebsiteEdit } from '../server/managed-sites/page-editor/ai'
import { compilePageDocument } from '../server/managed-sites/page-editor/compiler'
import { canonicalFingerprint } from '../server/managed-sites/page-editor/canonical'
import { createInitialPage } from '../server/managed-sites/page-editor/canonical'
import { executeDrizzlePagePublicationWork, validateAndExecutePublicationWork } from '../server/managed-sites/page-editor/publication-runtime'
import { contentOperationPublicationTargets, managedSiteMediaAssets, managedSiteMediaAssetVersions, managedSiteMediaTagLinks, managedSiteMediaUploadSessions, managedSiteMediaUsageBindings, managedSiteMediaVariants, managedSitePagePublicationAttempts, managedSitePagePublicationReceipts, managedSitePagePublicationWorks, managedSitePages, managedSitePageVersions, managedSiteReleaseProjections } from '../server/database/schema'
import type { MediaAssetProjection } from '../server/managed-sites/media-vault/types'
import type { PageActor } from '../server/managed-sites/page-editor/types'
import type { FirstPartyFetch } from '../server/first-party-publishing/types'

const now = new Date('2026-08-29T00:00:00.000Z')
const actor: PageActor = { ownerUserId: 1, projectId: 10, actorUserId: 7, authority: 'customer_session', role: 'customer_admin', canPublish: true }
const sha = (value: string) => createHash('sha256').update(value).digest('hex')
function asset(overrides: Partial<MediaAssetProjection> = {}): MediaAssetProjection { const digest = sha('asset-v1'); return { ownerUserId: 1, projectId: 10, assetId: 'asset_ready_0001', version: 1, status: 'ready', visibility: 'public', filename: 'hero.jpg', declaredMime: 'image/jpeg', sniffedMime: 'image/jpeg', byteSize: 1024, width: 1600, height: 900, sha256: digest, originalObjectKey: 'tenant/1/site/10/original.jpg', processingFingerprint: sha('processing'), scannerVerdict: 'passed', variants: [{ key: 'small', format: 'webp', width: 640, height: 360, byteSize: 100, sha256: sha('small'), objectKey: 'tenant/1/site/10/small.webp', transformation: { stripMetadata: true, preserveOrientation: true } }, { key: 'large', format: 'webp', width: 1600, height: 900, byteSize: 300, sha256: sha('large'), objectKey: 'tenant/1/site/10/large.webp', transformation: { stripMetadata: true, preserveOrientation: true } }], collectionId: null, tags: [], rightsMetadata: { license: 'customer-confirmed', source: null, photographer: null, consentReference: null, publishAllowed: true, expiresAt: null }, createdAt: now.toISOString(), trashedAt: null, retentionUntil: null, deletedAt: null, ...overrides } }
function page(media = asset()) { return createInitialPage(actor, { pageId: 'page_home_0001', locale: 'zh-hant', route: '/', contentType: 'home', designThemeId: 'default', designTokenVersion: 'tokens-v1', designTokens: { palette: 'indigo_sand', typeScale: 'balanced', spacing: 'balanced', radius: 'soft', maxWidth: 'standard', contrast: 'aa' }, sections: [{ blockId: 'block_hero_0001', type: 'hero', visible: true, layoutVariant: 'split', data: { title: '首頁', description: '測試發布', alignment: 'left' }, mediaBindingIds: ['binding_hero_0001'], schedule: null }], seo: { title: '首頁', description: '測試首頁發布內容', canonicalPath: '/', noindex: false, ogBindingId: 'binding_hero_0001' }, mediaBindings: [{ bindingId: 'binding_hero_0001', assetId: media.assetId, assetVersion: media.version, assetSha256: media.sha256!, role: 'hero', alt: '首頁主圖', decorative: false, provenance: 'customer' }] }, now) }
async function publicationFixture(media = asset()) { const document = page(media); const artifact = await compilePageDocument({ actor, document, resolveMedia: async () => media, mode: 'publish', now }); const work: any = { id: 91, ownerUserId: 1, projectId: 10, clientId: 21, pageId: document.pageId, pageVersion: document.version, releaseId: 31, publicationTargetId: 41, operationKind: 'publish', artifact, artifactBytes: Buffer.byteLength(JSON.stringify(artifact)), artifactFingerprint: artifact.artifactFingerprint, mediaSetFingerprint: artifact.mediaSetFingerprint, pageFingerprint: document.fingerprint, contentHash: canonicalFingerprint(artifact), idempotencyKey: 'publish-hardening-0001', requestFingerprint: sha('request'), status: 'leased', attemptCount: 1, maxAttempts: 5, availableAt: now, leaseOwner: 'worker-1', leaseUntil: new Date(now.getTime() + 60_000), lastErrorCode: null, createdAt: now, updatedAt: now }; const target: any = { id: 41, ownerUserId: 1, clientId: 21, websiteId: 'site-10', targetId: 'target-managed-site-10', destinationPublicationIdentity: 'managed-page-home', framework: 'astro', transport: 'first_party_signed_api', targetOrigin: 'https://customer-site.example.tw', contentRoot: 'src/content', defaultBranch: 'main', repositoryOwner: null, repositoryName: null, endpointPath: '/api/first-party/content-ingest', serviceReference: null, credentialReference: 'hmac-key:managed-site-10', allowedContentTypes: ['article'], allowedLanguages: ['zh-hant'], maximumPayloadBytes: 1_000_000, status: 'active', executionEnabled: true, activeSlot: 1, configurationFingerprint: sha('target'), provenance: {}, idempotencyKey: 'target-fixture-01', createdAt: now, updatedAt: now, revokedAt: null }; return { document, artifact, work, target, media } }

function publicationDatabase(fixture: Awaited<ReturnType<typeof publicationFixture>>) {
  const state: any = { workStatus: 'leased', pageStatus: 'publishing', publishedVersion: 0, versionStatus: 'draft', receiptStatus: 'publishing', attempts: [] }
  const rows = (table: any) => {
    if (table === managedSitePages) return [{ currentDraftVersion: fixture.document.version }]
    if (table === managedSitePageVersions) return [{ document: fixture.document }]
    if (table === contentOperationPublicationTargets) return [fixture.target]
    if (table === managedSiteReleaseProjections) return [{ status: 'approved' }]
    if (table === managedSitePagePublicationWorks) return state.workStatus === 'succeeded' ? [] : [fixture.work]
    if (table === managedSiteMediaAssets) return [{ id: 501, ownerUserId: 1, projectId: 10, assetId: fixture.media.assetId, currentVersion: fixture.media.version, status: fixture.media.status, visibility: fixture.media.visibility, originalFilename: fixture.media.filename, collectionId: null, rightsMetadata: fixture.media.rightsMetadata, createdAt: now, trashedAt: null, retentionUntil: null, deletedAt: null }]
    if (table === managedSiteMediaAssetVersions) return [{ id: 601, declaredMime: fixture.media.declaredMime, sniffedMime: fixture.media.sniffedMime, byteSize: fixture.media.byteSize, width: fixture.media.width, height: fixture.media.height, sha256: fixture.media.sha256, processingFingerprint: fixture.media.processingFingerprint, metadata: { scannerVerdict: fixture.media.scannerVerdict } }]
    if (table === managedSiteMediaUploadSessions) return [{ objectKey: fixture.media.originalObjectKey, declaredMime: fixture.media.declaredMime, declaredBytes: fixture.media.byteSize }]
    if (table === managedSiteMediaVariants) return fixture.media.variants
    if (table === managedSiteMediaTagLinks) return []
    return []
  }
  const database: any = {
    select() {
      let table: any
      const builder: any = { from(value: any) { table = value; return builder }, innerJoin() { return builder }, where() { return builder }, orderBy() { return builder }, limit() { return Promise.resolve(rows(table)) }, then(resolve: any, reject: any) { return Promise.resolve(rows(table)).then(resolve, reject) } }
      return builder
    },
    insert(table: any) {
      return { values(value: any) { if (table === managedSitePagePublicationAttempts) state.attempts.push(value); return Promise.resolve([{ insertId: 1, affectedRows: 1 }]) } }
    },
    update(table: any) {
      return { set(value: any) { return { where() { if (table === managedSitePagePublicationWorks && value.status) state.workStatus = value.status; if (table === managedSitePagePublicationReceipts && value.status) state.receiptStatus = value.status; if (table === managedSitePages) { if (value.status) state.pageStatus = value.status; if (value.publishedVersion) state.publishedVersion = value.publishedVersion } if (table === managedSitePageVersions && value.lifecycleStatus) state.versionStatus = value.lifecycleStatus; if (table === managedSiteMediaUsageBindings) state.oldUsageReleased = true; return Promise.resolve([{ affectedRows: 1 }]) } } } }
    },
    transaction(work: (transaction: any) => Promise<unknown>) { return work(database) },
  }
  return { database, state }
}

describe('managed-site editor P0/P1 hardening', () => {
  it('atomically bounds 25 concurrent media reservations and exact replay without double charge', async () => { const repository = createMemoryMediaVaultRepository({ maxOriginalBytes: 10, maxAssetCount: 10, maxMonthlyUploadBytes: 10, maxMonthlyProcessingCount: 10 }); const scope = { ownerUserId: 1, projectId: 10 }; const attempts = await Promise.allSettled(Array.from({ length: 25 }, (_, index) => repository.transaction(tx => tx.reserveQuota(scope, { idempotencyKey: `quota-${index.toString().padStart(3, '0')}`, requestFingerprint: sha(`quota-${index}`), delta: { originalBytes: 1, assetCount: 1, uploadBytes: 1, processingCount: 1 } })))); expect(attempts.filter(result => result.status === 'fulfilled')).toHaveLength(10); const quota = await repository.getQuota(scope); expect(quota).toMatchObject({ originalBytesUsed: 10, assetCountUsed: 10, monthlyUploadBytesUsed: 10, monthlyProcessingCountUsed: 10 }); const replay = await repository.transaction(tx => tx.reserveQuota(scope, { idempotencyKey: 'quota-000', requestFingerprint: sha('quota-0'), delta: { originalBytes: 1, assetCount: 1, uploadBytes: 1, processingCount: 1 } })); expect(replay.replayed).toBe(true); await expect(repository.transaction(tx => tx.reserveQuota(scope, { idempotencyKey: 'quota-000', requestFingerprint: sha('collision'), delta: { originalBytes: 1, assetCount: 1, uploadBytes: 1, processingCount: 1 } }))).rejects.toMatchObject({ statusCode: 409 }); expect((await repository.getQuota(scope)).assetCountUsed).toBe(10) })

  it('atomically bounds concurrent AI request, token and cost claims with exact replay and release', async () => { const budget = createMemoryAiBudgetPort(); const scope = { ownerUserId: 1, projectId: 10 }; const claims = await Promise.all(Array.from({ length: 125 }, (_, index) => budget.claim(scope, { idempotencyKey: `ai-${index}`, requestFingerprint: sha(`ai-${index}`), estimatedInputTokens: 1, maxOutputTokens: 10, now }))); expect(claims.filter(result => result.allowed)).toHaveLength(AI_EDITOR_LIMITS.requestsPerDay); const replay = await budget.claim(scope, { idempotencyKey: 'ai-0', requestFingerprint: sha('ai-0'), estimatedInputTokens: 1, maxOutputTokens: 10, now }); expect(replay.allowed).toBe(true); await expect(budget.claim(scope, { idempotencyKey: 'ai-0', requestFingerprint: sha('different'), estimatedInputTokens: 1, maxOutputTokens: 10, now })).rejects.toMatchObject({ statusCode: 409 }); const nextDay = new Date('2026-08-30T00:00:00Z'); await budget.claim(scope, { idempotencyKey: 'provider-failure', requestFingerprint: sha('provider-failure'), estimatedInputTokens: 99, maxOutputTokens: 10, now: nextDay }); await budget.release!(scope, { idempotencyKey: 'provider-failure', requestFingerprint: sha('provider-failure'), now: nextDay }); const retry = await budget.claim(scope, { idempotencyKey: 'provider-failure', requestFingerprint: sha('provider-failure'), estimatedInputTokens: 99, maxOutputTokens: 10, now: nextDay }); expect(retry.allowed).toBe(true); const costBudget = createMemoryAiBudgetPort(); const costClaims = await Promise.all(Array.from({ length: 60 }, (_, index) => costBudget.claim(scope, { idempotencyKey: `cost-${index}`, requestFingerprint: sha(`cost-${index}`), estimatedInputTokens: 1, maxOutputTokens: AI_EDITOR_LIMITS.maxOutputTokens, now }))); expect(costClaims.filter(result => result.allowed)).toHaveLength(Math.floor(AI_EDITOR_LIMITS.costMicrosPerDay / ((AI_EDITOR_LIMITS.maxOutputTokens + 1) * AI_EDITOR_LIMITS.costMicrosPerTokenCeiling))) })

  it('makes AI proposal idempotency an exact durable replay and fails collision closed', async () => { const budget = createMemoryAiBudgetPort(); const input = { actor, page: page(), request: '首頁主圖換成這張，文字靠左', approvedMedia: [asset()], resolveMedia: async () => asset(), budget, selectedMediaAssetIds: [asset().assetId], idempotencyKey: 'ai-exact-replay-0001', now }; const first = await proposeAiWebsiteEdit(input); const replay = await proposeAiWebsiteEdit(input); expect(replay).toEqual(first); await expect(proposeAiWebsiteEdit({ ...input, request: '把案例移到服務前' })).rejects.toMatchObject({ statusCode: 409 }) })

  it('returns all S3 signed upload headers and exposes Head metadata for exact completion verification', async () => { process.env.MEDIA_S3_TEST_CREDENTIAL = JSON.stringify({ accessKeyId: 'fixture', secretAccessKey: 'fixture-secret' }); const send = vi.fn(async command => { const name = command.constructor.name; if (name === 'HeadObjectCommand') return { ContentLength: 123, ContentType: 'image/png', Metadata: { uploadid: 'upload-1', ownerid: '1', projectid: '10' }, ETag: '"etag"' }; return {} }); const presign = vi.fn(async () => 'https://objects.customer-assets.tw/signed'); const storage = createS3MediaStorage({ configuration: { bucket: 'fixture-bucket', region: 'auto', prefix: 'managed-sites', endpoint: 'https://objects.customer-assets.tw/', credentialReference: 'MEDIA_S3_TEST_CREDENTIAL' }, client: { send } as any, presign: presign as any }); const authorization = await storage.createUploadIntent({ ownerUserId: 1, projectId: 10, uploadId: 'upload-1', objectKey: 'media/owners/1/projects/10/uploads/asset0001.png', byteSize: 123, contentType: 'image/png', expiresAt: new Date(Date.now() + 60_000) }); expect(authorization.requiredHeaders).toEqual({ 'content-type': 'image/png', 'content-length': '123', 'x-amz-meta-uploadid': 'upload-1', 'x-amz-meta-ownerid': '1', 'x-amz-meta-projectid': '10' }); const head = await storage.completeUpload({ ownerUserId: 1, projectId: 10, uploadId: 'upload-1', objectKey: 'media/owners/1/projects/10/uploads/asset0001.png', byteSize: 123, contentType: 'image/png' }); expect(head).toMatchObject({ byteSize: 123, contentType: 'image/png', metadata: { uploadid: 'upload-1', ownerid: '1', projectid: '10' } }); delete process.env.MEDIA_S3_TEST_CREDENTIAL })

  it('fails S3 health and object lookup closed on redirect/provider errors without leaking credentials', async () => { process.env.MEDIA_S3_TEST_CREDENTIAL = JSON.stringify({ accessKeyId: 'fixture', secretAccessKey: 'fixture-secret' }); const storage = createS3MediaStorage({ configuration: { bucket: 'fixture-bucket', region: 'auto', prefix: 'managed-sites', endpoint: 'https://objects.customer-assets.tw/', credentialReference: 'MEDIA_S3_TEST_CREDENTIAL' }, client: { send: vi.fn(async () => { throw Object.assign(new Error('redirect with fixture-secret'), { $metadata: { httpStatusCode: 307 } }) }) } as any, presign: vi.fn() as any }); await expect(storage.healthCheck()).resolves.toMatchObject({ ready: false, reason: 'health_request_failed' }); await expect(storage.headObject({ ownerUserId: 1, projectId: 10, objectKey: 'media/owners/1/projects/10/uploads/asset0001.png' })).rejects.toThrow('Media storage lookup failed.'); delete process.env.MEDIA_S3_TEST_CREDENTIAL })

  it.each(['http://scanner.customer.tw/scan', 'https://localhost/scan', 'https://10.0.0.1/scan', 'https://[::1]/scan', 'https://scanner.onion/scan', 'https://scanner.example/scan', 'https://user:pass@scanner.customer.tw/scan', 'https://scanner.customer.tw/scan?token=x'])('rejects unsafe fixed scanner authority %s', endpoint => { expect(() => createHttpMediaSecurityScanner({ endpoint, credentialReference: 'MEDIA_SCANNER_TEST_CREDENTIAL', fetchImpl: vi.fn() as any })).toThrow(/approved HTTPS authority/i) })

  it('rejects scanner redirects with manual redirect and never follows endpoint drift', async () => { process.env.MEDIA_SCANNER_TEST_CREDENTIAL = 'fixture-scanner-secret'; const fetchImpl = vi.fn(async () => new Response('', { status: 302, headers: { location: 'https://elsewhere.customer.tw/scan' } })); const scanner = createHttpMediaSecurityScanner({ endpoint: 'https://scanner.customer-security.tw/v1/scan', credentialReference: 'MEDIA_SCANNER_TEST_CREDENTIAL', fetchImpl }); await expect(scanner.scan({ bytes: new Uint8Array([1]), sha256: sha('one'), tenant: { ownerUserId: 1, projectId: 10 } })).rejects.toThrow(/redirect/i); expect(fetchImpl).toHaveBeenCalledTimes(1); expect((fetchImpl.mock.calls[0] as any)?.[1]).toMatchObject({ redirect: 'manual' }); delete process.env.MEDIA_SCANNER_TEST_CREDENTIAL })

  it('executes the existing first-party signed executor and accepts only its exact verified receipt', async () => { const fixture = await publicationFixture(); const fetchImpl = vi.fn(async (_url: string, init: any) => { const body = JSON.parse(init.body); return { status: 201, headers: {}, text: async () => JSON.stringify({ publicationId: body.publicationId, contentHash: body.contentHash, remoteRevision: 'revision-managed-001' }) } }) as unknown as FirstPartyFetch; const result = await validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => fixture.media, now, dependencies: { fetchImpl, serverCredentialResolver: async () => ({ ok: true, value: 'fixture-signing-secret' }), nonceProvider: () => 'nonce-managed-001' } }); expect(result).toMatchObject({ status: 'delivered', publicationId: `deliverable-managed-page-${fixture.document.pageId}-v1`, contentHash: fixture.work.contentHash }); expect(fetchImpl).toHaveBeenCalledTimes(1) })

  it('runs the production Drizzle publication application path through verified delivery and durable published state', async () => { const fixture = await publicationFixture(); const { database, state } = publicationDatabase(fixture); const fetchImpl = vi.fn(async (_url: string, init: any) => { const body = JSON.parse(init.body); return { status: 201, headers: {}, text: async () => JSON.stringify({ publicationId: body.publicationId, contentHash: body.contentHash, remoteRevision: 'revision-managed-e2e-001' }) } }) as unknown as FirstPartyFetch; const result = await executeDrizzlePagePublicationWork(fixture.work, { database, now, dependencies: { fetchImpl, serverCredentialResolver: async () => ({ ok: true, value: 'fixture-signing-secret' }), nonceProvider: () => 'nonce-managed-e2e-001' } }); expect(result).toMatchObject({ status: 'succeeded', externalCalls: true, attemptNumber: 1 }); expect(fetchImpl).toHaveBeenCalledTimes(1); expect(state).toMatchObject({ workStatus: 'succeeded', pageStatus: 'published', publishedVersion: fixture.document.version, versionStatus: 'published', receiptStatus: 'succeeded', oldUsageReleased: true }); expect(state.attempts).toHaveLength(1); expect(state.attempts[0]).toMatchObject({ status: 'delivered', requestFingerprint: fixture.work.requestFingerprint, publicationTargetId: fixture.work.publicationTargetId }) })

  it('blocks stale page/media, expired rights, revoked target and receipt mismatch before publishing', async () => { const fixture = await publicationFixture(); await expect(validateAndExecutePublicationWork({ work: fixture.work, page: { ...fixture.document, fingerprint: sha('stale') }, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => fixture.media, now, dependencies: {} as any })).rejects.toMatchObject({ reasonCode: 'STALE_PAGE_VERSION' }); await expect(validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => ({ ...fixture.media, sha256: sha('changed') }), now, dependencies: {} as any })).rejects.toThrow(/ready exact version/i); await expect(validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => ({ ...fixture.media, rightsMetadata: { ...fixture.media.rightsMetadata, expiresAt: '2026-08-28T00:00:00Z' } }), now, dependencies: {} as any })).rejects.toThrow(/rights-expired/i); await expect(validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: { ...fixture.target, status: 'revoked' }, releaseStatus: 'approved', resolveMedia: async () => fixture.media, now, dependencies: {} as any })).rejects.toMatchObject({ reasonCode: 'TARGET_REVOKED' }); const mismatch = await validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => fixture.media, now, dependencies: {} as any, executor: async () => ({ status: 'delivered', remoteState: 'updated', publicationId: 'wrong', contentHash: fixture.work.contentHash, remoteRevision: 'revision', artifactFingerprint: fixture.artifact.artifactFingerprint, idempotencyKey: sha('wrong') }) }); expect(mismatch).toMatchObject({ status: 'blocked', code: 'RESPONSE_INVALID' }) })

  it('preserves retryable first-party failures and has explicit replay/partial-success durable guards', async () => { const fixture = await publicationFixture(); const retry = await validateAndExecutePublicationWork({ work: fixture.work, page: fixture.document, target: fixture.target, releaseStatus: 'approved', resolveMedia: async () => fixture.media, now, dependencies: {} as any, executor: async () => ({ status: 'retryable_failure', code: 'REMOTE_RATE_LIMITED', reasons: ['bounded retry'] }) }); expect(retry).toMatchObject({ status: 'retryable_failure', code: 'REMOTE_RATE_LIMITED' }); const source = readFileSync('server/managed-sites/page-editor/publication-runtime.ts', 'utf8'); expect(source).toContain("result.status === 'retryable_failure' && work.attemptCount"); expect(source).toContain("ne(managedSitePagePublicationWorks.status, 'succeeded')"); expect(source).toContain('if (!unfinished.length)'); expect(source).toContain('providerReceiptReference: terminalSuccess ? receiptFingerprint : null'); expect(source).toContain("operationKind === 'rollback'") })

  it('commits AI proposal, budget claim and cost ledger in one transaction and applies proposals atomically', () => { const repository = readFileSync('server/managed-sites/page-editor/ai-repository-drizzle.ts', 'utf8'); const route = readFileSync('server/api/managed-sites/editor/ai/propose.post.ts', 'utf8'); expect(repository).toContain('saveAiProposalAndCommitBudget'); expect(repository).toContain('return database.transaction'); expect(repository).toContain('await saveAiProposal(actor, proposal, transaction)'); expect(repository).toContain('createDrizzleAiBudgetPort(joinedDatabase).commit!'); expect(repository).toContain(".for('update')"); expect(repository).toContain('applyAiProposalToDraft({ repository: joined'); expect(route).toContain('deferBudgetCommit: true'); expect(route).toContain('saveAiProposalAndCommitBudget') })

  it('keeps current draft and last published media in use until all targets verify success', () => { const repository = readFileSync('server/managed-sites/page-editor/repository-drizzle.ts', 'utf8'); const runtime = readFileSync('server/managed-sites/page-editor/publication-runtime.ts', 'utf8'); expect(repository).toContain('publishedVersion: managedSitePages.publishedVersion'); expect(repository).toContain('ne(managedSiteMediaUsageBindings.pageVersion, identity?.publishedVersion || 0)'); expect(runtime).toContain('if (!unfinished.length)'); expect(runtime).toContain('ne(managedSiteMediaUsageBindings.pageVersion, work.pageVersion)') })

  it('connects actual thumbnail, bulk upload, cancellation, crop, restore and version-history UI controls', () => { const editor = readFileSync('pages/customer/managed-sites/editor.vue', 'utf8'); expect(editor).toContain('asset.thumbnailAuthorization.url'); expect(editor).toContain('body: { requests: selected.map'); expect(editor).toContain('cancelUpload(String(name))'); expect(editor).toContain('@click="cropAndUse(asset)"'); expect(editor).toContain('@click="restoreAsset(asset)"'); expect(editor).toContain('@click="showAssetHistory(asset)"') })

  it('keeps signed thumbnails ephemeral and out of PageDocument/source authority', () => { const workspace = readFileSync('server/api/managed-sites/editor/workspace.get.ts', 'utf8'); const editor = readFileSync('pages/customer/managed-sites/editor.vue', 'utf8'); const canonical = readFileSync('server/managed-sites/page-editor/canonical.ts', 'utf8'); expect(workspace).toContain("new Date(now.getTime() + 5 * 60 * 1000)"); expect(workspace).toContain('originalObjectKey: undefined'); expect(editor).toContain('asset.thumbnailAuthorization.url'); expect(editor).toContain('thumbnailUrl(binding)'); expect(canonical).not.toContain('thumbnailAuthorization'); expect(canonical).not.toContain('signedUrl') })
})
