import { describe, expect, it } from 'vitest'
import { createMemoryEditorSchedulerPort, runEditorSchedulerTick, type EditorJobHandlers, type EditorSchedulerJob } from '../server/managed-sites/page-editor/scheduler'

const now = new Date('2026-08-29T00:00:00Z')
function job(index: number, overrides: Partial<EditorSchedulerJob> = {}): EditorSchedulerJob { return { jobId: `job-${index}`, ownerUserId: 1, projectId: 10, kind: 'media_processing', attempt: 0, availableAt: now.toISOString(), leaseUntil: null, stateFingerprint: `${index}`.repeat(64).slice(0, 64), ...overrides } }
const handlers = (fail = false): EditorJobHandlers => ({ media_processing: async () => { if (fail) throw Object.assign(new Error('fail'), { reasonCode: 'SCANNER_UNAVAILABLE' }); return { outcome: 'processed', externalCalls: false } }, scheduled_visibility: async () => ({ outcome: 'visibility_projected', externalCalls: false }), orphan_upload_expiry: async () => ({ outcome: 'expired', externalCalls: false }), trash_retention: async () => ({ outcome: 'owner_confirmation_required', externalCalls: false }), publish_retry: async () => ({ outcome: 'governed_retry_intent', externalCalls: false }) })
describe('managed-site editor scheduler V1', () => {
  it('leases bounded work and emits deterministic receipts', async () => { const memory = createMemoryEditorSchedulerPort([job(1), job(2, { kind: 'scheduled_visibility' })]); const result = await runEditorSchedulerTick(memory.port, handlers(), now); expect(result).toMatchObject({ claimed: 2, tenants: 1, bounded: true, externalCalls: false }); expect(memory.events.every(event => event.status === 'succeeded' && /^[a-f0-9]{64}$/.test(event.receipt.fingerprint))).toBe(true) })
  it('retries with bounded backoff, stale leases recover, and max attempts block', async () => { const memory = createMemoryEditorSchedulerPort([job(1), job(2, { attempt: 5 }), job(3, { leaseUntil: new Date(now.getTime() + 60_000).toISOString() })]); const result = await runEditorSchedulerTick(memory.port, handlers(true), now); expect(result.claimed).toBe(2); expect(memory.events.map(event => event.status)).toEqual(['retry_wait', 'blocked']); expect(memory.jobs.some(item => item.jobId === 'job-3')).toBe(true); const recovered = await runEditorSchedulerTick(memory.port, handlers(), new Date(now.getTime() + 120_000)); expect(recovered.claimed).toBeGreaterThan(0) })
  it('claims fairly across at most 20 tenants, 10 jobs each, with no concurrent duplicate lease', async () => { const seed = Array.from({ length: 25 }, (_, tenant) => Array.from({ length: 12 }, (_, index) => job(tenant * 100 + index, { ownerUserId: tenant + 1, projectId: tenant + 100 }))).flat(); const memory = createMemoryEditorSchedulerPort(seed); const input = { now, maxTenants: 20, maxPerTenant: 10, leaseUntil: new Date(now.getTime() + 120_000) }; const [first, second] = await Promise.all([memory.port.claim(input), memory.port.claim(input)]); expect(first).toHaveLength(200); expect(second).toHaveLength(40); const firstIds = new Set(first.map(item => item.jobId)); expect(second.every(item => !firstIds.has(item.jobId))).toBe(true); expect(new Set([...first, ...second].map(item => item.jobId)).size).toBe(first.length + second.length); expect(new Set(first.map(item => `${item.ownerUserId}:${item.projectId}`)).size).toBe(20); expect(Math.max(...[...new Set(first.map(item => `${item.ownerUserId}:${item.projectId}`))].map(tenant => first.filter(item => `${item.ownerUserId}:${item.projectId}` === tenant).length))).toBe(10) })
  it('executes a governed publish retry and truthfully reports the external executor call', async () => { const memory = createMemoryEditorSchedulerPort([job(1, { kind: 'publish_retry' })]); const result = await runEditorSchedulerTick(memory.port, { ...handlers(), publish_retry: async () => ({ outcome: 'publication_succeeded', externalCalls: true }) }, now); expect(result).toMatchObject({ claimed: 1, externalCalls: true, governedExternalCalls: 1 }); expect(result.receipts[0]).toMatchObject({ kind: 'publish_retry', status: 'succeeded', externalCalls: true }) })
  it('does not retain a success receipt when durable success finalization rolls back', async () => { const memory = createMemoryEditorSchedulerPort([job(1)]); const port = { ...memory.port, async succeed() { throw Object.assign(new Error('transaction rolled back'), { reasonCode: 'RECEIPT_TRANSACTION_ROLLBACK' }) } }; const result = await runEditorSchedulerTick(port, handlers(), now); expect(result.receipts).toEqual([expect.objectContaining({ status: 'retry_wait', reasonCode: 'RECEIPT_TRANSACTION_ROLLBACK' })]); expect(memory.events).toEqual([expect.objectContaining({ status: 'retry_wait' })]); expect(memory.jobs).toHaveLength(1) })
})
