import { describe, expect, it } from 'vitest'
import { createMemoryMediaVaultRepository } from '../server/managed-sites/media-vault/memory-repository'
import { completeMediaUpload, createMediaTransformationVersion, createPrivateMediaRead, permanentlyDeleteMediaAsset, requestBulkMediaUploadIntents, requestMediaReplacementIntent, requestMediaUploadIntent, restoreMediaAsset, retryMediaProcessing, trashMediaAsset, updateMediaGovernance } from '../server/managed-sites/media-vault/service'
import { createMemoryMediaStorage } from '../server/managed-sites/media-vault/storage'
import { createDeterministicTestImageProcessor, createPassingTestScanner, createUnavailableProductionScanner, hashBytes, inspectMediaBytes, validateTransformation, validateUploadDeclaration } from '../server/managed-sites/media-vault/validation'
import type { MediaActor, MediaSecurityScanner } from '../server/managed-sites/media-vault/types'
import sharp from 'sharp'
import { createSharpMediaImageProcessor } from '../server/managed-sites/media-vault/sharp-processor'
import { createHttpMediaSecurityScanner } from '../server/managed-sites/media-vault/scanner'

function png(width = 1200, height = 800, suffix = ''): Uint8Array {
  const bytes = Buffer.alloc(40 + suffix.length); Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]).copy(bytes, 0); Buffer.from('IHDR').copy(bytes, 12); bytes.writeUInt32BE(width, 16); bytes.writeUInt32BE(height, 20); Buffer.from(suffix).copy(bytes, 40); return bytes
}
const actor = (ownerUserId = 1, projectId = 10, role: MediaActor['role'] = 'customer_admin'): MediaActor => ({ ownerUserId, projectId, actorUserId: 99, authority: 'customer_session', role })
function dependencies(options: { quota?: any; scanner?: MediaSecurityScanner } = {}) { const repository = createMemoryMediaVaultRepository(options.quota); const storage = createMemoryMediaStorage(); return { repository, storage, scanner: options.scanner || createPassingTestScanner(), processor: createDeterministicTestImageProcessor() } }
async function uploadReady(deps: ReturnType<typeof dependencies>, mediaActor = actor(), bytes = png(), key = `upload-${Math.random().toString(36).slice(2)}-001`) {
  const intent = await requestMediaUploadIntent(deps, mediaActor, { filename: 'photo.png', declaredMime: 'image/png', declaredBytes: bytes.byteLength, visibility: 'public', idempotencyKey: key }); await deps.storage.putUpload(mediaActor, intent.session.objectKey, bytes, 'image/png'); return completeMediaUpload(deps, mediaActor, { uploadId: intent.session.uploadId, expectedSha256: hashBytes(bytes) })
}

describe('managed-site multi-tenant media vault V1', () => {
  it('uses the real server codec for exact dimensions, WebP/AVIF variants and metadata-free outputs', async () => {
    const source = await sharp({ create: { width: 1600, height: 900, channels: 4, background: '#4d5dad' } }).withMetadata({ orientation: 6 }).jpeg().toBuffer(); const processor = createSharpMediaImageProcessor(); const inspection = await processor.inspect(source); expect(inspection).toMatchObject({ mime: 'image/jpeg', width: 900, height: 1600, orientation: 6 }); const variants = await processor.produceVariants({ bytes: source, inspection, transformation: { rotation: 0, stripMetadata: true, preserveOrientation: true, crop: { x: 0, y: 100, width: 900, height: 600, aspect: '3:2' }, focalPoint: { x: .5, y: .5 } } }); expect(variants.map(item => [item.key, item.format, item.width, item.height])).toEqual([['thumbnail', 'webp', 240, 160], ['small', 'webp', 640, 427], ['medium', 'webp', 900, 600], ['large', 'avif', 900, 600], ['original_policy', 'jpeg', 900, 600]]); for (const variant of variants) { expect(variant.sha256).toBe(hashBytes(variant.bytes)); const metadata = await sharp(variant.bytes).metadata(); expect(metadata.exif).toBeUndefined() }
  })
  it('keeps scanner credentials server-only and bounds redirects, retries and response schema', async () => {
    process.env.TEST_MEDIA_SCANNER_TOKEN = 'scanner-test-token-not-a-real-secret'; let calls = 0; const scanner = createHttpMediaSecurityScanner({ endpoint: 'https://scanner.example.test/v1/scan', credentialReference: 'TEST_MEDIA_SCANNER_TOKEN', fetchImpl: (async (_url: any, init: any) => { calls++; expect(init.headers.authorization).toBe('Bearer scanner-test-token-not-a-real-secret'); return calls === 1 ? new Response('{}', { status: 429 }) : new Response(JSON.stringify({ verdict: 'passed', reasonCode: null, scannerReference: 'fixture:clean' }), { status: 200 }) }) as any }); await expect(scanner.scan({ bytes: png(), sha256: 'a'.repeat(64), tenant: actor() })).resolves.toMatchObject({ verdict: 'passed', scannerReference: 'fixture:clean' }); expect(calls).toBe(2); expect(() => createHttpMediaSecurityScanner({ endpoint: 'https://127.0.0.1/scan', credentialReference: 'TEST_MEDIA_SCANNER_TOKEN' })).toThrow(/approved HTTPS/i); delete process.env.TEST_MEDIA_SCANNER_TOKEN
  })
  it('issues a short-lived server-owned upload, validates bytes, strips through the processor and records exact variants', async () => {
    const deps = dependencies(); const bytes = png(1600, 900, 'safe'); const result = await uploadReady(deps, actor(), bytes, 'upload-ready-0001')
    expect(result.asset).toMatchObject({ status: 'ready', sniffedMime: 'image/png', width: 1600, height: 900, sha256: hashBytes(bytes), scannerVerdict: 'passed' }); expect(result.asset.variants.map(item => item.key)).toEqual(['thumbnail', 'small', 'medium', 'large', 'original_policy']); expect(result.asset.variants.every(item => item.sha256 === hashBytes(Buffer.concat([Buffer.from(bytes), Buffer.from(`\nDS-MOCK-VARIANT:${item.key}:${item.width}x${item.height}:${JSON.stringify(item.transformation)}`)])))).toBe(true)
    const read = await createPrivateMediaRead(deps.storage, deps.repository, actor(), result.asset.assetId); expect(read).toMatchObject({ method: 'GET', cacheControl: 'private, no-store' }); expect((await deps.repository.listEvents(actor(), result.asset.assetId)).map(item => item.eventType)).toContain('media_ready')
  })

  it.each([
    ['double extension', () => validateUploadDeclaration({ filename: 'photo.exe.png', declaredMime: 'image/png', declaredBytes: 30 })],
    ['SVG script', () => inspectMediaBytes(Buffer.from('<svg><script>alert(1)</script></svg>'))],
    ['ZIP/polyglot', () => inspectMediaBytes(Buffer.concat([Buffer.from('PK\x03\x04'), Buffer.alloc(40)]))],
    ['image bomb', () => inspectMediaBytes(png(12_000, 12_000))],
    ['crop out of bounds', () => validateTransformation({ crop: { x: 900, y: 0, width: 200, height: 20, aspect: 'free' } }, 1000, 800)],
  ])('rejects %s fail closed', (_label, action) => { expect(action).toThrow() })

  it('rejects wrong magic, MIME, size and claimed hash without making the asset ready', async () => {
    const deps = dependencies(); const bytes = png(); const intent = await requestMediaUploadIntent(deps, actor(), { filename: 'photo.png', declaredMime: 'image/png', declaredBytes: bytes.byteLength, visibility: 'public', idempotencyKey: 'wrong-magic-0001' }); const fake = Buffer.alloc(bytes.byteLength, 1); await deps.storage.putUpload(actor(), intent.session.objectKey, fake, 'image/png'); await expect(completeMediaUpload(deps, actor(), { uploadId: intent.session.uploadId, expectedSha256: 'a'.repeat(64) })).rejects.toThrow(); expect((await deps.repository.findAsset(actor(), intent.session.assetId))?.status).toBe('quarantined')
    const sizeIntent = await requestMediaUploadIntent(deps, actor(), { filename: 'other.png', declaredMime: 'image/png', declaredBytes: bytes.byteLength + 1, visibility: 'private', idempotencyKey: 'wrong-size-0001' }); await deps.storage.putUpload(actor(), sizeIntent.session.objectKey, bytes, 'image/png'); await expect(completeMediaUpload(deps, actor(), { uploadId: sizeIntent.session.uploadId })).rejects.toThrow(/size/i)
  })

  it('quarantines when a production scanner is unavailable or blocks content and never creates a public-ready projection', async () => {
    const unavailable = dependencies({ scanner: createUnavailableProductionScanner() }); const first = await uploadReady(unavailable, actor(), png(), 'scanner-missing-01'); expect(first.asset).toMatchObject({ status: 'quarantined', scannerVerdict: 'not_configured', variants: [] })
    const blocked = dependencies({ scanner: { async scan() { return { verdict: 'blocked', reasonCode: 'MALWARE', scannerReference: 'mock:block' } } } }); const second = await uploadReady(blocked, actor(), png(), 'scanner-blocked-01'); expect(second.asset.status).toBe('quarantined'); await expect(createPrivateMediaRead(blocked.storage, blocked.repository, actor(), second.asset.assetId)).rejects.toThrow()
  })

  it('requires explicit rights before public visibility and can retry quarantined bytes without changing the immutable original', async () => {
    const deps = dependencies({ scanner: createUnavailableProductionScanner() }); const quarantined = await uploadReady(deps, actor(), png(900, 600, 'retry'), 'scanner-retry-0001'); expect(quarantined.asset.status).toBe('quarantined'); await expect(updateMediaGovernance(deps.repository, actor(), { assetId: quarantined.asset.assetId, visibility: 'public', rightsMetadata: { publishAllowed: false } })).rejects.toThrow(/publish-allowed/i)
    const retry = await retryMediaProcessing({ ...deps, scanner: createPassingTestScanner() }, actor(), { assetId: quarantined.asset.assetId, transformation: { focalPoint: { x: .25, y: .75 } } }); expect(retry).toMatchObject({ retried: true, ready: true }); expect(retry.asset).toMatchObject({ status: 'ready', sha256: quarantined.asset.sha256, scannerVerdict: 'passed' }); const governed = await updateMediaGovernance(deps.repository, actor(), { assetId: quarantined.asset.assetId, visibility: 'public', rightsMetadata: { license: 'customer-owned', publishAllowed: true } }); expect(governed?.rightsMetadata).toMatchObject({ license: 'customer-owned', publishAllowed: true }); const originalRead = await createPrivateMediaRead(deps.storage, deps.repository, actor(), quarantined.asset.assetId, 'original'); expect(originalRead).toMatchObject({ method: 'GET', cacheControl: 'private, no-store' }); await expect(retryMediaProcessing({ ...deps, scanner: createPassingTestScanner() }, actor(), { assetId: quarantined.asset.assetId })).rejects.toThrow(/Only quarantined/i)
  })

  it('replaces media through an append-only asset version and preserves the prior ready version on rejected replacement', async () => {
    const deps = dependencies(); const original = await uploadReady(deps, actor(), png(1200, 800, 'v1'), 'replacement-base-01'); const nextBytes = png(1600, 900, 'v2'); const replacement = await requestMediaReplacementIntent(deps, actor(), original.asset.assetId, { filename: 'updated.png', declaredMime: 'image/png', declaredBytes: nextBytes.byteLength, visibility: 'private', idempotencyKey: 'replacement-intent-01' }); await deps.storage.putUpload(actor(), replacement.session.objectKey, nextBytes, 'image/png'); const completed = await completeMediaUpload(deps, actor(), { uploadId: replacement.session.uploadId, expectedSha256: hashBytes(nextBytes) }); expect(completed.asset).toMatchObject({ assetId: original.asset.assetId, version: 2, filename: 'updated.png', status: 'ready', visibility: 'private', sha256: hashBytes(nextBytes) }); expect(completed.asset.sha256).not.toBe(original.asset.sha256)
    const blockedBytes = png(400, 400, 'blocked-v3'); const blockedIntent = await requestMediaReplacementIntent(deps, actor(), original.asset.assetId, { filename: 'blocked.png', declaredMime: 'image/png', declaredBytes: blockedBytes.byteLength, visibility: 'public', idempotencyKey: 'replacement-intent-02' }); await deps.storage.putUpload(actor(), blockedIntent.session.objectKey, blockedBytes, 'image/png'); const blocked = await completeMediaUpload({ ...deps, scanner: createUnavailableProductionScanner() }, actor(), { uploadId: blockedIntent.session.uploadId }); expect(blocked).toMatchObject({ replacementRejected: true }); expect(blocked.asset).toMatchObject({ version: 2, status: 'ready', sha256: hashBytes(nextBytes) })
  })

  it('creates a bounded crop/focal derived version while retaining the immutable original hash', async () => {
    const deps = dependencies(); const original = await uploadReady(deps, actor(), png(1600, 900, 'crop-source'), 'crop-source-0001'); const derived = await createMediaTransformationVersion(deps, actor(), { assetId: original.asset.assetId, aspect: '1:1', focalPoint: { x: .8, y: .4 }, rotation: 0, expectedAssetVersion: 1, idempotencyKey: 'crop-transform-0001' }); expect(derived.asset).toMatchObject({ version: 2, width: 900, height: 900, sha256: original.asset.sha256, originalObjectKey: original.asset.originalObjectKey }); expect(derived.asset?.variants.every(item => item.transformation.crop?.aspect === '1:1')).toBe(true); const replay = await createMediaTransformationVersion(deps, actor(), { assetId: original.asset.assetId, aspect: '1:1', focalPoint: { x: .8, y: .4 }, rotation: 0, expectedAssetVersion: 1, idempotencyKey: 'crop-transform-0001' }); expect(replay.replayed).toBe(true); await expect(createMediaTransformationVersion(deps, actor(), { assetId: original.asset.assetId, aspect: '16:9', focalPoint: { x: .5, y: .5 }, rotation: 0, expectedAssetVersion: 1, idempotencyKey: 'crop-transform-0002' })).rejects.toThrow(/stale/i)
  })

  it('enforces bulk bounds and plan quota before issuing object authority', async () => {
    const deps = dependencies({ quota: { maxAssetCount: 1, maxOriginalBytes: 1000, maxMonthlyUploadBytes: 1000, maxMonthlyProcessingCount: 1 } }); const request = { filename: 'photo.png', declaredMime: 'image/png', declaredBytes: png().byteLength, visibility: 'private' as const, idempotencyKey: 'bulk-item-0001' }; await expect(requestBulkMediaUploadIntents(deps, actor(), [{ ...request }, { ...request, idempotencyKey: 'bulk-item-0002' }])).rejects.toThrow(/quota/i); await expect(requestBulkMediaUploadIntents(deps, actor(), Array.from({ length: 26 }, (_, index) => ({ ...request, idempotencyKey: `bulk-item-${String(index).padStart(4, '0')}` })))).rejects.toThrow(/1–25/)
  })

  it('handles idempotent replay, collision, concurrent complete and same-tenant dedupe without a cross-tenant oracle', async () => {
    const deps = dependencies(); const bytes = png(); const request = { filename: 'photo.png', declaredMime: 'image/png', declaredBytes: bytes.byteLength, visibility: 'public' as const, idempotencyKey: 'idempotent-upload-01' }; const first = await requestMediaUploadIntent(deps, actor(), request); const replay = await requestMediaUploadIntent(deps, actor(), request); expect(replay.replayed).toBe(true); await expect(requestMediaUploadIntent(deps, actor(), { ...request, filename: 'other.png' })).rejects.toThrow(/collided/i)
    await deps.storage.putUpload(actor(), first.session.objectKey, bytes, 'image/png'); const race = await Promise.allSettled([completeMediaUpload(deps, actor(), { uploadId: first.session.uploadId }), completeMediaUpload(deps, actor(), { uploadId: first.session.uploadId })]); expect(race.filter(item => item.status === 'fulfilled')).toHaveLength(1); expect(race.filter(item => item.status === 'rejected')).toHaveLength(1)
    const duplicate = await uploadReady(deps, actor(), bytes, 'dedupe-same-tenant'); expect(duplicate.deduplicated).toBe(true); expect(duplicate.asset.assetId).toBe(first.session.assetId)
    const tenantB = await uploadReady(deps, actor(2, 20), bytes, 'dedupe-other-tenant'); expect(tenantB.deduplicated).toBe(false); expect(tenantB.asset.assetId).not.toBe(first.session.assetId); expect(await deps.repository.findAsset(actor(2, 20), first.session.assetId)).toBeNull()
  })

  it('expires upload sessions and prevents caller tenant crossover', async () => {
    const deps = dependencies(); const now = new Date('2026-08-29T00:00:00Z'); const intent = await requestMediaUploadIntent(deps, actor(), { filename: 'photo.png', declaredMime: 'image/png', declaredBytes: png().byteLength, visibility: 'private', idempotencyKey: 'expired-upload-001' }, now); await deps.storage.putUpload(actor(), intent.session.objectKey, png(), 'image/png'); await expect(completeMediaUpload(deps, actor(), { uploadId: intent.session.uploadId }, new Date(now.getTime() + 11 * 60 * 1000))).rejects.toThrow(/expired/i); await expect(completeMediaUpload(deps, actor(2, 20), { uploadId: intent.session.uploadId })).rejects.toThrow(/not found/i)
  })

  it('requires trash, retention, no active usage and explicit elevated confirmation for permanent deletion', async () => {
    const deps = dependencies(); const ready = await uploadReady(deps); const trashed = await trashMediaAsset(deps.repository, actor(), ready.asset.assetId, new Date('2026-07-01T00:00:00Z')); expect(trashed?.status).toBe('trashed'); expect((await restoreMediaAsset(deps.repository, actor(), ready.asset.assetId, new Date('2026-07-02T00:00:00Z')))?.status).toBe('ready'); await trashMediaAsset(deps.repository, actor(), ready.asset.assetId, new Date('2026-07-01T00:00:00Z')); await deps.repository.setActiveUsageCount(actor(), ready.asset.assetId, 1); await expect(permanentlyDeleteMediaAsset(deps, actor(), { assetId: ready.asset.assetId, confirmation: `DELETE:${ready.asset.assetId}` }, new Date('2026-08-02T00:00:00Z'))).rejects.toThrow(/in-use/i); await deps.repository.setActiveUsageCount(actor(), ready.asset.assetId, 0); const deleted = await permanentlyDeleteMediaAsset(deps, actor(), { assetId: ready.asset.assetId, confirmation: `DELETE:${ready.asset.assetId}` }, new Date('2026-08-02T00:00:00Z')); expect(deleted.asset?.status).toBe('deleted'); expect(deleted.receipt.metadata.objectCount).toBe(6)
  })
})
