import { describe, expect, it } from 'vitest'
import { createMemoryEditorSchedulerPort, runEditorSchedulerTick, type EditorJobHandlers, type EditorSchedulerJob } from '../server/managed-sites/page-editor/scheduler'

const now = new Date('2026-08-29T00:00:00Z')
function job(index: number, overrides: Partial<EditorSchedulerJob> = {}): EditorSchedulerJob { return { jobId: `job-${index}`, ownerUserId: 1, projectId: 10, kind: 'media_processing', attempt: 0, availableAt: now.toISOString(), leaseUntil: null, stateFingerprint: `${index}`.repeat(64).slice(0, 64), ...overrides } }
const handlers = (fail = false): EditorJobHandlers => ({ media_processing: async () => { if (fail) throw Object.assign(new Error('fail'), { reasonCode: 'SCANNER_UNAVAILABLE' }); return { outcome: 'processed', externalCalls: false } }, scheduled_visibility: async () => ({ outcome: 'visibility_projected', externalCalls: false }), orphan_upload_expiry: async () => ({ outcome: 'expired', externalCalls: false }), trash_retention: async () => ({ outcome: 'owner_confirmation_required', externalCalls: false }), publish_retry: async () => ({ outcome: 'governed_retry_intent', externalCalls: false }) })
describe('managed-site editor scheduler V1', () => {
  it('leases bounded work and emits deterministic receipts', async () => { const memory = createMemoryEditorSchedulerPort([job(1), job(2, { kind: 'scheduled_visibility' })]); const result = await runEditorSchedulerTick(memory.port, handlers(), now); expect(result).toMatchObject({ claimed: 2, tenants: 1, bounded: true, externalCalls: false }); expect(memory.events.every(event => event.status === 'succeeded' && /^[a-f0-9]{64}$/.test(event.receipt.fingerprint))).toBe(true) })
  it('retries with bounded backoff, stale leases recover, and max attempts block', async () => { const memory = createMemoryEditorSchedulerPort([job(1), job(2, { attempt: 5 }), job(3, { leaseUntil: new Date(now.getTime() + 60_000).toISOString() })]); const result = await runEditorSchedulerTick(memory.port, handlers(true), now); expect(result.claimed).toBe(2); expect(memory.events.map(event => event.status)).toEqual(['retry_wait', 'blocked']); expect(memory.jobs.some(item => item.jobId === 'job-3')).toBe(true); const recovered = await runEditorSchedulerTick(memory.port, handlers(), new Date(now.getTime() + 120_000)); expect(recovered.claimed).toBeGreaterThan(0) })
})
