import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const config = readFileSync(join(root, 'nuxt.config.ts'), 'utf8')
const oauth = readFileSync(join(root, 'server/utils/oauth.ts'), 'utf8')
const auth = readFileSync(join(root, 'server/utils/auth.ts'), 'utf8')
const privateConfigProbe = readFileSync(join(root, 'server/api/__private-config.get.ts'), 'utf8')
const login = readFileSync(join(root, 'server/api/auth/login.get.ts'), 'utf8')
const callback = readFileSync(join(root, 'server/api/auth/callback.get.ts'), 'utf8')
const releaseProbe = readFileSync(join(root, 'server/api/__release.get.ts'), 'utf8')
const auditLab = readFileSync(join(root, 'pages/audit-lab.vue'), 'utf8')
const mlLab = readFileSync(join(root, 'pages/ml-lab-preview.vue'), 'utf8')
const dockerfile = readFileSync(join(root, '..', 'Dockerfile'), 'utf8')

describe('OAuth frontend-origin contract', () => {
  it('requires a configured HTTPS allowlist origin rather than trusting a request host', () => {
    expect(config).toContain("discoveryStackOauthAllowedOrigin: process.env.NUXT_DISCOVERY_STACK_OAUTH_ALLOWED_ORIGIN || process.env.OAUTH_ALLOWED_ORIGIN || ''")
    expect(oauth).toContain("const configuredOrigin = typeof config.discoveryStackOauthAllowedOrigin === 'string' ? config.discoveryStackOauthAllowedOrigin : ''")
    expect(oauth).toContain('new URL(configuredOrigin).origin')
    expect(oauth).toContain("allowedOrigin.startsWith('https://')")
    expect(oauth).not.toContain('getRequestURL(event).origin')
  })

  it('binds the requested frontend origin, OAuth state, and callback URI to the same allowlist value', () => {
    expect(login).toContain('beginOAuthLogin(event, origin)')
    expect(login).toContain("setHeader(event, 'Cache-Control', 'no-store, max-age=0')")
    expect(login).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Release', OAUTH_NITRO_RELEASE)")
    expect(login).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Route', 'nuxt-origin-allowlist-v1')")
    expect(oauth).toContain("if (requestedOrigin !== allowedOrigin)")
    expect(oauth).toContain('const redirectUri = `${allowedOrigin}/api/oauth/callback`')
    expect(oauth).toContain('const expectedRedirect = `${allowedOrigin}/api/oauth/callback`')
    expect(readFileSync(join(root, 'server/api/oauth/callback.get.ts'), 'utf8')).toContain("export { default } from '../auth/callback.get'")
    expect(oauth).toContain('parsed.nonce !== expectedNonce')
    expect(oauth).toContain("providerClient.post<{ accessToken?: string }>('/webdev.v1.WebDevAuthPublicService/ExchangeToken'")
    expect(oauth).toContain("clientId: appId, grantType: 'authorization_code', code, redirectUri: statePayload.redirectUri")
    expect(oauth).not.toContain("clientId: appId, grantType: 'authorization_code', code, state")
  })

  it('uses a short-lived Secure cross-site state cookie only for the OAuth callback and never exposes its nonce', () => {
    expect(oauth).toContain("sameSite: 'none'")
    expect(oauth).toContain("maxAge: OAUTH_STATE_MAX_AGE_SECONDS")
    expect(oauth).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-State', expectedNonce ? 'cookie-present' : 'cookie-missing')")
    expect(oauth).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-State', expectedNonce)")
  })

  it('reads owner session secrets only on the server at request time when hosting injects them after build', () => {
    expect(auth).toContain("process.env.NUXT_SESSION_SECRET || process.env.JWT_SECRET || ''")
    expect(auth).toContain("process.env.JWT_SECRET || ''")
    expect(auth).toContain("const SESSION_COOKIE = '__Host-discoverystack-session'")
    expect(auth).toContain("httpOnly: true, secure: true, sameSite: 'lax'")
  })

  it('uses a persistent admin role as the revocable single-owner allowlist without emitting an open ID', () => {
    expect(auth).toContain("return user?.role === 'admin'")
    expect(auth).toContain("!await isAdminOpenId(user.openId)")
    expect(auth).toContain("!await isAdminOpenId(payload.openId)")
    expect(callback).toContain("role: 'user', lastSignedIn: new Date()")
    expect(callback).not.toContain('X-DiscoveryStack-OAuth-Owner')
  })

  it('offers a secret-free server configuration probe for secure deployment validation', () => {
    expect(privateConfigProbe).toContain("setHeader(event, 'Cache-Control', 'no-store, max-age=0')")
    expect(privateConfigProbe).toContain("setHeader(event, 'X-DiscoveryStack-Private-Config', hasSessionSecret && hasOwnerOpenId ? 'ready' : 'missing')")
    expect(privateConfigProbe).toContain("process.env.NUXT_SESSION_SECRET")
    expect(privateConfigProbe).toContain("process.env.NUXT_OWNER_OPEN_ID")
    expect(privateConfigProbe).not.toContain('return { sessionSecret')
    expect(privateConfigProbe).not.toContain('return { ownerOpenId')
  })

  it('mints the browser origin only in the explicit Audit Lab sign-in click handler', () => {
    expect(auditLab).toContain('const origin = window.location.origin')
    expect(auditLab).toContain('window.location.assign(`/api/auth/login?origin=${encodeURIComponent(origin)}`)')
    expect(auditLab).toContain('@click="startAuditSignIn"')
  })

  it('keeps the owner-only Audit Lab and ML Workbench controls in Traditional Chinese without changing safety codes', () => {
    expect(auditLab).toContain('人工審核')
    expect(auditLab).toContain('受政策控管的公開來源')
    expect(auditLab).toContain('儲存人工審核')
    expect(auditLab).toContain("collecting_public_examples: '持續收集公開範例'")
    expect(auditLab).toContain("not_ready: '尚未就緒'")
    expect(auditLab).toContain("owner_research: '擁有者研究'")
    expect(auditLab).toContain('儲存此記錄<strong>不會啟動爬蟲</strong>')
    expect(auditLab).toContain('displayLabel(assessment.assessmentStatus)')
    expect(auditLab).toContain('SEO／GEO 多維人工標註')
    expect(auditLab).toContain('核准訓練 manifest')
    expect(mlLab).toContain('機器學習工作台')
    expect(mlLab).toContain('啟動受限抓取')
    expect(mlLab).toContain('執行 Hugging Face 訓練')
    expect(mlLab).toContain('開發模式 · 至少 100 筆樣本、每個階段至少 10 筆')
    expect(mlLab).toContain('已核准公開資料集')
    expect(mlLab).toContain('尚未有訓練執行')
    expect(mlLab).toContain("TRAINING_GATE_NOT_MET: '未達訓練門檻'")
    expect(mlLab).not.toContain('ML Workbench · DiscoveryStack')
  })

  it('keeps callback failure diagnostics free of codes, tokens, and account data', () => {
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Callback', stage)")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Callback', 'complete')")
    expect(callback).toContain('const user = await exchangeOAuthCode(')
    expect(callback).toContain('(nextStage) => { stage = nextStage }')
    expect(callback).toContain('(failure) => { providerFailure.value = failure }')
    expect(callback).not.toContain('X-DiscoveryStack-OAuth-Owner')
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Provider-Error', providerFailure.value.kind)")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Provider-Status', String(providerFailure.value.status))")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Provider-Reason', providerFailure.value.reason)")
    expect(callback).toContain('providerError: providerFailure.value.kind')
    expect(callback).toContain('providerStatus: providerFailure.value.status')
    expect(callback).toContain('providerReason: providerFailure.value.reason')
    expect(callback).toContain("type SessionFailureKind = 'owner_mismatch' | 'configuration' | 'jwt_session' | 'unknown'")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Session-Error', sessionFailure)")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Session-Status', String(sessionStatus))")
    expect(callback).toContain('return { error: callbackFailureMessage(stage), sessionError: sessionFailure, sessionStatus }')
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Owner', user.openId)")
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Callback', code)")
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Callback', user.email)")
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Callback', exchange.accessToken)")
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Provider-Status', error.response.data)")
    expect(callback).not.toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Provider-Reason', error.response.data)")
    expect(callback).not.toContain('providerStatus: error.response.data')
    expect(callback).not.toContain('providerReason: error.response.data')
    expect(callback).not.toContain('providerResponse:')
    expect(callback).toContain("console.error(`[DiscoveryStack OAuth] callback failed at stage=${stage}; status=${statusCode}; session=${sessionFailure || 'none'}; error=${errorName}`)")
    expect(callback).not.toContain('console.error(error)')
    expect(callback).not.toContain('console.error(code)')
    expect(callback).not.toContain('console.error(user.email)')
  })

  it('bounds provider calls so a failed provider cannot leave the callback without a response', () => {
    expect(oauth).toContain("import axios from 'axios'")
    expect(oauth).not.toContain('$fetch<')
    expect(oauth).toContain('const OAUTH_PROVIDER_TIMEOUT_MS = 25_000')
    expect(oauth).toContain("const providerClient = axios.create({ baseURL: serverUrl, timeout: OAUTH_PROVIDER_TIMEOUT_MS })")
    expect(oauth).toContain("providerClient.post<{ accessToken?: string }>('/webdev.v1.WebDevAuthPublicService/ExchangeToken'")
    expect(oauth).toContain("providerClient.post<{ openId?: string, name?: string, email?: string, platform?: string, loginMethod?: string }>('/webdev.v1.WebDevAuthPublicService/GetUserInfo'")
    expect(oauth).not.toContain("headers: { Accept: 'application/json', 'Content-Type': 'application/json' }")
    expect(oauth).toContain("export type OAuthProviderRejectionReason = 'invalid_client' | 'invalid_redirect_uri' | 'invalid_authorization_code' | 'unauthenticated'")
    expect(oauth).toContain('function classifyProviderRejectionReason(body: unknown): OAuthProviderRejectionReason | null')
    expect(oauth).toContain('classifyProviderRejectionReason(error.response.data)')
    expect(oauth).toContain("if (error.code === 'ECONNABORTED' || error.code === 'ETIMEDOUT') return { kind: 'timeout', status, reason: null }")
    expect(oauth).toContain("if (error.response) return { kind: 'response', status, reason: classifyProviderRejectionReason(error.response.data) }")
    expect(oauth).toContain("let exchangeStatus: number | null = null")
    expect(oauth).toContain("onProviderError?.({ kind: 'response', status: exchangeStatus, reason: null })")
    expect(oauth).toContain("let identityStatus: number | null = null")
    expect(oauth).toContain("onProviderError?.({ kind: 'response', status: identityStatus, reason: null })")
    expect(callback).toContain("setHeader(event, 'Cache-Control', 'no-store, max-age=0')")
    expect(callback).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Release', OAUTH_NITRO_RELEASE)")
    expect(callback).toContain("if ((stage === 'token' || stage === 'identity') && providerError) return 400")
    expect(callback).toContain("return { error: 'Private sign-in could not be completed.' }")
    expect(callback).toContain('callbackStatusCode(error, stage, providerFailure.value)')
    expect(callback).toContain('setResponseStatus(event, statusCode)')
    expect(callback).toContain('return { error: callbackFailureMessage(stage) }')
  })

  it('requires the production image to build a clean Nitro artifact with the current OAuth release marker', () => {
    expect(dockerfile).toContain('rm -rf .nuxt .output')
    expect(dockerfile).toContain("grep -R -q 'nitro-public-intelligence-20260818-r17-immutable-readiness-ssr' .output/server")
    expect(dockerfile).toContain('CMD ["node", ".output/server/index.mjs"]')
  })

  it('marks private Audit Lab SSR pages as non-cacheable so owner-specific readiness cannot serve stale HTML', () => {
    expect(config).toContain("'/audit-lab': { headers: { 'X-Robots-Tag': 'noindex, nofollow, noarchive', 'Cache-Control': 'private, no-store, max-age=0' } }")
    expect(config).toContain("'/audit-lab/**': { headers: { 'X-Robots-Tag': 'noindex, nofollow, noarchive', 'Cache-Control': 'private, no-store, max-age=0' } }")
  })

  it('exposes a no-store Nuxt-only release probe without deployment secrets', () => {
    expect(releaseProbe).toContain("setHeader(event, 'Cache-Control', 'no-store, max-age=0')")
    expect(releaseProbe).toContain("setHeader(event, 'X-DiscoveryStack-OAuth-Release', OAUTH_NITRO_RELEASE)")
    expect(releaseProbe).toContain("setHeader(event, 'X-DiscoveryStack-Handler', 'nitro')")
    expect(releaseProbe).toContain("return { release: OAUTH_NITRO_RELEASE, handler: 'nitro' }")
    expect(releaseProbe).not.toContain('process.env.')
  })
})
