import { describe, expect, it } from 'vitest'
import { admitAggregateOutcome, createFrappeContentTargetProjection } from '../server/system-factory/governance'
import { acceptInvitation, issueInvitation, revokeInvitation } from '../server/system-factory/invitation'

describe('invitation and GEO/content governance', () => {
  it('stores only hashed token/email and accepts exactly once', () => { const issued = issueInvitation({ ownerId: 'owner:1', tenantId: 'tenant:1', email: 'Customer@Example.COM', roleKey: 'crm_viewer', healthyReceiptFingerprint: 'a'.repeat(64), now: new Date('2030-01-01T00:00:00.000Z'), token: 'token-value-which-is-at-least-thirty-two-characters' }); expect(JSON.stringify(issued.record)).not.toContain('Customer@'); expect(JSON.stringify(issued.record)).not.toContain(issued.token); const accepted = acceptInvitation(issued.record, issued.token, new Date('2030-01-01T01:00:00.000Z')); expect(accepted.status).toBe('accepted'); expect(() => acceptInvitation(accepted, issued.token)).toThrow() })
  it('rejects expired, revoked, wrong-token and pre-health invitations', () => { expect(() => issueInvitation({ ownerId: 'owner:1', tenantId: 'tenant:1', email: 'customer@example.com', roleKey: 'viewer', healthyReceiptFingerprint: '', token: 'token-value-which-is-at-least-thirty-two-characters' })).toThrow(/health/i); const issued = issueInvitation({ ownerId: 'owner:1', tenantId: 'tenant:1', email: 'customer@example.com', roleKey: 'viewer', healthyReceiptFingerprint: 'a'.repeat(64), now: new Date('2030-01-01T00:00:00.000Z'), token: 'token-value-which-is-at-least-thirty-two-characters' }); expect(() => acceptInvitation(issued.record, 'wrong-token-value-which-is-at-least-thirty-two')).toThrow(); expect(() => acceptInvitation(issued.record, issued.token, new Date('2030-01-05T00:00:00.000Z'))).toThrow(/expired/i); const revoked = revokeInvitation(issued.record); expect(() => acceptInvitation(revoked, issued.token)).toThrow() })
  it('admits only consented, PII-governed aggregate outcomes with denominator and limitations', () => { const admitted = admitAggregateOutcome({ ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', systemTenantId: 'tenant:1', consentReceiptFingerprint: 'a'.repeat(64), piiAdmissionReceiptFingerprint: 'b'.repeat(64), purpose: 'geo_aggregate_outcome_evaluation', retentionUntil: '2031-01-01T00:00:00.000Z', aggregationWindow: { start: '2030-01-01T00:00:00.000Z', end: '2030-02-01T00:00:00.000Z' }, numerator: 2, denominator: 20, source: 'consented aggregate appointments', limitations: ['Observational aggregate; no causal or ROI claim.'] }); expect(admitted).toMatchObject({ privateRecordsIncluded: false, predictionIsVerifiedOutcome: false }); expect(admitted.admissionFingerprint).toMatch(/^[a-f0-9]{64}$/u) })
  it('blocks ungoverned CRM outcomes and keeps Frappe content write disabled behind publication authority', () => { expect(() => admitAggregateOutcome({ ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', systemTenantId: 'tenant:1', consentReceiptFingerprint: '', piiAdmissionReceiptFingerprint: '', purpose: 'geo_aggregate_outcome_evaluation', retentionUntil: '2031-01-01T00:00:00.000Z', aggregationWindow: { start: '2030-01-01T00:00:00.000Z', end: '2030-02-01T00:00:00.000Z' }, numerator: 1, denominator: 1, source: 'raw crm records', limitations: [] })).toThrow(); const projection = createFrappeContentTargetProjection({ ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', systemTenantId: 'tenant:1', contentOperationTargetId: 'target:1', contentHash: 'c'.repeat(64), evidenceSnapshotHash: 'd'.repeat(64) }); expect(projection).toMatchObject({ executionEnabled: false, routeAuthority: 'content_operations_publication_routing', requiresPublicationReceipt: true }) })
})
