import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { compileSystemSpec } from '../server/system-factory/compiler'
import { createGuidedSystemSpec } from '../server/system-factory/planner'

describe('Frappe app, provenance and UI contracts', () => {
  it('keeps exact upstream lock and digest synchronized with Nuxt provenance', () => { const lock = JSON.parse(readFileSync(join(process.cwd(), '../infrastructure/frappe/UPSTREAM.lock.json'), 'utf8')); const registry = readFileSync(join(process.cwd(), 'server/system-factory/provenance.ts'), 'utf8'); expect(lock.frappe).toMatchObject({ tag: 'v16.32.0', commit: '5cba016e86b54b57f34a3864282b92300ef20fb0', license: 'MIT' }); expect(lock.erpnext).toMatchObject({ tag: 'v16.33.0', commit: 'b24c9eba551905e256e336ff170a91a92d197a2f', license: 'GPL-3.0-only' }); expect(lock.image.embeddedApps).toEqual({ frappe: { version: '16.31.0', commit: null, commitVerifiedInImage: false }, erpnext: { version: '16.33.0', commit: lock.erpnext.commit, commitVerifiedInImage: true } }); expect(registry).toContain(lock.image.indexDigest); expect(readFileSync(join(process.cwd(), '../infrastructure/frappe/compose.yaml'), 'utf8')).toContain(lock.image.indexDigest) })

  it.skipIf(!existsSync('/usr/bin/python3') && !existsSync('/usr/local/bin/python3'))('keeps TypeScript/Python compiled-spec golden parity for DocTypes and roles', () => { const spec = createGuidedSystemSpec({ requirements: '建立輕量 CRM 系統。', businessType: 'service', industry: 'consulting', preferredTemplate: 'light_crm', identity: { specId: 'spec-parity', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: null, systemTenantId: 'tenant:1', locale: 'zh-hant', timezone: 'Asia/Taipei', currency: 'TWD' } }); const ts = compileSystemSpec(spec); const script = `import json,sys; sys.path.insert(0, ${JSON.stringify(join(process.cwd(), '../services/frappe/discovery_stack'))}); from discovery_stack.compiler import compile_spec; print(json.dumps(compile_spec(json.loads(sys.stdin.read())), ensure_ascii=False))`; const py = JSON.parse(execFileSync('python3', ['-c', script], { input: JSON.stringify(spec), encoding: 'utf8', env: { ...process.env, PYTHONDONTWRITEBYTECODE: '1' } })); const tsCore = ts.units.filter(unit => unit.kind === 'doctype' || unit.kind === 'role').map((unit: any) => unit.kind === 'doctype' ? { kind: unit.kind, key: unit.key, source: unit.source, fields: unit.fields } : { kind: unit.kind, key: unit.key, permissions: unit.permissions }); expect(py.units).toEqual(tsCore) })

  it('shows preview warnings, all workbench sections and one owner navigation entry', () => { const page = readFileSync(join(process.cwd(), 'pages/audit-lab/system-factory.vue'), 'utf8'); for (const marker of ['INTERACTIVE PREVIEW / NOT DEPLOYED', 'synthetic demo data', 'Quote / Payment', 'Provisioning timeline', 'Health', 'Users / Roles / Invitations', 'Integrations', 'Upgrade / Backup / Rollback', 'Audit / Receipts / Advanced', 'unauthorized', 'retry_wait', 'collision', 'stale']) expect(page).toContain(marker); const layout = readFileSync(join(process.cwd(), 'layouts/owner.vue'), 'utf8'); expect(layout.match(/>系統工廠</gu)).toHaveLength(1) })

  it('keeps public Astro source free of Frappe/ERPNext browser imports', () => { const publicPackage = readFileSync(join(process.cwd(), '../public-site/package.json'), 'utf8'); expect(publicPackage).not.toMatch(/frappe|erpnext/iu); const lock = readFileSync(join(process.cwd(), '../public-site/pnpm-lock.yaml'), 'utf8'); expect(lock).not.toMatch(/\bfrappe\b|\berpnext\b/iu) })
})
