import { readFileSync, readdirSync, statSync } from 'node:fs'
import { join, relative } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = join(process.cwd(), '../services/frappe/discovery_stack')
function files(directory: string): string[] { return readdirSync(directory).flatMap(entry => { const path = join(directory, entry); return statSync(path).isDirectory() ? files(path) : [path] }) }

describe('DiscoveryStack Frappe app security and permission matrix', () => {
  it('provides app metadata, deterministic patch/fixtures and no ERPNext core fork', () => { const paths = files(root).map(path => relative(root, path)); for (const required of ['discovery_stack/hooks.py', 'discovery_stack/modules.txt', 'discovery_stack/patches.txt', 'discovery_stack/fixtures/role.json']) expect(paths).toContain(required); expect(paths.some(path => path.startsWith('erpnext/'))).toBe(false) })
  it('verifies raw hash and signature before nonce write or payload use', () => { const source = readFileSync(join(root, 'discovery_stack/envelope.py'), 'utf8'); const bodyCheck = source.indexOf('calculated_hash'); const signatureCheck = source.indexOf('hmac.compare_digest(expected, signature)'); const payloadParse = source.indexOf('json.loads(raw)'); const nonceWrite = source.indexOf('frappe.get_doc'); expect(bodyCheck).toBeGreaterThan(0); expect(signatureCheck).toBeGreaterThan(bodyCheck); expect(payloadParse).toBeGreaterThan(signatureCheck); expect(nonceWrite).toBeGreaterThan(payloadParse) })
  it('has tenant identity, compiled spec, publication and append-only audit DocTypes with restricted permissions', () => { const doctypeRoot = join(root, 'discovery_stack/discovery_stack/doctype'); const definitions = files(doctypeRoot).filter(path => path.endsWith('.json')).map(path => JSON.parse(readFileSync(path, 'utf8'))); for (const name of ['DiscoveryStack Tenant Identity', 'DiscoveryStack Compiled System Spec', 'DiscoveryStack Publication Linkage', 'DiscoveryStack System Audit Event', 'DiscoveryStack Envelope Nonce']) expect(definitions.some(value => value.name === name)).toBe(true); for (const definition of definitions) for (const permission of definition.permissions || []) { expect(permission.write).toBe(0); expect(permission.delete).toBe(0) } })
  it('keeps signed endpoints authenticated and apply disabled by default', () => { const source = readFileSync(join(root, 'discovery_stack/api.py'), 'utf8'); expect(source.match(/@frappe\.whitelist\(allow_guest=False\)/gu)?.length).toBeGreaterThanOrEqual(2); expect(source).toContain('DISCOVERYSTACK_FRAPPE_APPLY_ENABLED'); expect(source).toContain('verify_before_lookup_or_write') })
  it('applies only bounded app-owned metadata with durable staged activation and no DDL rollback claim', () => { const source = readFileSync(join(root, 'discovery_stack/executor.py'), 'utf8'); expect(source).toContain('ALLOWED_UNIT_KINDS'); expect(source).toContain('MAX_UNITS = 192'); expect(source).toContain('MAX_FIELDS = 32'); expect(source).toContain('Tenant identity lineage collision.'); expect(source).toContain('Compiled SystemSpec replay collision.'); expect(source).toContain('DiscoveryStack Materialization Run'); expect(source).toContain('DiscoveryStack Materialization Journal'); expect(source).toContain('_compensate_initial_run'); expect(source).toContain('materialization_state = "active"'); expect(source).not.toContain('rollback(save_point='); expect(source).toContain('frappe.db.commit()'); expect(source).not.toMatch(/subprocess|os\.system|eval\(|exec\(|frappe\.db\.sql/iu) })
  it('uses an exact tenant-owned workflow field and a bounded indexed role update', () => { const source = readFileSync(join(root, 'discovery_stack/executor.py'), 'utf8'); expect(source).toContain('def _workflow_fieldname'); expect(source).toContain('"fieldtype": "Select"'); expect(source).toContain('"is_system_generated": 1'); expect(source).toContain('workflow_state_field": field["fieldname"]'); expect(source).not.toContain('workflow_state_field": "status"'); expect(source).toContain('for permission_index, permission in enumerate(expected):'); expect(source).toContain('_inject_crash("permission_replacement")') })
  it('runs smoke through a stable dotted method and preserves its original traceback', () => { const runner = readFileSync(join(root, 'discovery_stack/tests/bench_runner.py'), 'utf8'); const script = readFileSync(join(root, '../../../infrastructure/frappe/disposable-smoke.sh'), 'utf8'); expect(runner).toContain('traceback.print_exc()'); expect(runner).toContain('MATERIALIZATION_SMOKE_FAILED'); expect(script).toContain('discovery_stack.tests.bench_runner.run'); expect(script).toContain('FRAPPE_MATERIALIZATION_SMOKE=FAIL') })
  it('does not compensate a preflight rejection before its durable run exists', () => { const source = readFileSync(join(root, 'discovery_stack/executor.py'), 'utf8'); expect(source).toContain('not injected and frappe.db.exists("DiscoveryStack Materialization Run", run_identity)'); expect(source).toContain('raise frappe.ValidationError("Permission escalation requires reviewed intent.")') })
  it('rejects active replay drift without demoting the verified active run', () => { const source = readFileSync(join(root, 'discovery_stack/executor.py'), 'utf8'); expect(source.match(/if run\.status != "active"/gu)?.length).toBeGreaterThanOrEqual(2); expect(source).toContain('Active materialization replay is drifted.') })
})
