import { describe, expect, it } from 'vitest'
import { compileSystemSpec } from '../server/system-factory/compiler'
import { createMockSystemFactoryProvisioner } from '../server/system-factory/provisioner'
import { testRuntimeAuthority } from '../server/system-factory/runtime-authority'
import { createGuidedSystemSpec } from '../server/system-factory/planner'
import { buildSystemPreview } from '../server/system-factory/preview'
import { MemoryWorkflowRepository, executeProvisioning, executeUpgrade } from '../server/system-factory/workflow'
import { SystemFactoryError } from '../server/system-factory/canonical'

function journey(template: 'light_crm' | 'appointment_booking', existing: boolean) { const spec = createGuidedSystemSpec({ requirements: existing ? '診斷既有網站後加購預約系統。' : '新客戶建立網站與 CRM 互動預覽。', businessType: 'service', industry: 'local business', preferredTemplate: template, identity: { specId: existing ? 'spec-existing' : 'spec-new', ownerId: 'owner:1', clientId: 'client:1', websiteId: existing ? 'website:existing' : 'website:new', managedSiteId: existing ? 'managed-site:10' : null, systemTenantId: 'tenant:1', locale: 'zh-hant', timezone: 'Asia/Taipei', currency: 'TWD' } }); const plan = compileSystemSpec(spec); const preview = buildSystemPreview(spec, plan, { version: 1 }); const repo = new MemoryWorkflowRepository(); repo.seed({ ownerId: 'owner:1', clientId: 'client:1', websiteId: spec.identity.websiteId, managedSiteId: spec.identity.managedSiteId, systemTenantId: 'tenant:1', state: 'provisioning_planned', stateVersion: 7, specFingerprint: plan.specFingerprint, compiledPlanFingerprint: plan.planFingerprint, managedSiteOrderId: 100, verifiedPaymentReceiptFingerprint: 'a'.repeat(64), leaseOwner: null, leaseExpiresAt: null, attempt: 0, maxAttempts: 3, retryEligibleAt: null, healthyReceiptFingerprint: null, invitationReceiptFingerprint: null }); return { spec, plan, preview, repo } }

describe('mocked application E2E', () => {
  it('a) new customer requirements to website+CRM preview, verified payment, provision, health and invitation pending', async () => { const current = journey('light_crm', false); expect(current.preview.deployed).toBe(false); const result = await executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: current.plan, siteName: 'new-site.example.org', credentialReference: 'vault:test', executor: createMockSystemFactoryProvisioner(), repository: current.repo, executionMode: 'mocked' }); expect(result.tenant).toMatchObject({ state: 'invitation_pending' }); expect(result.tenant.healthyReceiptFingerprint).toMatch(/^[a-f0-9]{64}$/u); expect(result.tenant.invitationReceiptFingerprint).toBeNull() })
  it('b) existing-site diagnosis lineage to appointment add-on and provision', async () => { const current = journey('appointment_booking', true); expect(current.spec.identity.managedSiteId).toBe('managed-site:10'); const result = await executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: current.plan, siteName: 'existing-addon.example.org', credentialReference: 'vault:test', executor: createMockSystemFactoryProvisioner(), repository: current.repo, executionMode: 'mocked' }); expect(result.tenant.state).toBe('invitation_pending') })
  it('c) missing credential remains safe and not active', async () => { const current = journey('light_crm', false); const executor: any = createMockSystemFactoryProvisioner(); executor.createSite = async () => { throw new SystemFactoryError('MISSING_CREDENTIAL', 'Server credential reference is unavailable.', 503) }; const result = await executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: current.plan, siteName: 'missing.example.org', credentialReference: 'vault:missing', executor, repository: current.repo, executionMode: 'live' }); expect(result.tenant.state).toBe('retry_wait'); expect(result.tenant.healthyReceiptFingerprint).toBeNull() })
  it('d) concurrent duplicate produces one executor run', async () => { const current = journey('light_crm', false); const calls: string[] = []; const run = () => executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: current.plan, siteName: 'once.example.org', credentialReference: 'vault:test', executor: createMockSystemFactoryProvisioner({ calls }), repository: current.repo, executionMode: 'mocked' }); await Promise.allSettled([run(), run()]); expect(calls.filter(call => call === 'createSite')).toHaveLength(1) })
  it('e) upgrade backup, failure and rollback receipt sequence', async () => { const current = journey('light_crm', false); const upgrade = await executeUpgrade({ context: { ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:new', managedSiteId: null, systemTenantId: 'tenant:1', siteName: 'upgrade.example.org', controlPlaneCredentialReference: 'vault:control', tenantAppCredentialReference: 'vault:hmac', idempotencyKey: 'upgrade-0001', compiledPlan: current.plan, executionMode: 'mocked', runtimeAuthority: testRuntimeAuthority(), targetVersion: 'v16.1.0' }, executor: createMockSystemFactoryProvisioner({ failAt: 'verifyUpgrade' }) }); expect(upgrade.status).toBe('rolled_back') })
})
