import { describe, expect, it } from 'vitest'
import { fingerprint, SystemFactoryError } from '../server/system-factory/canonical'
import { compileSystemSpec } from '../server/system-factory/compiler'
import { createMockControlPlane, createReviewedBenchControlPlaneAdapter } from '../server/system-factory/control-plane'
import { createMockTenantApp, createTenantAppAdapter, TENANT_APP_PATHS, type TenantAppContext } from '../server/system-factory/frappe-adapter'
import { activateSystemInvitation, MemoryInvitationActivationRepository } from '../server/system-factory/invitation-activation'
import { createGuidedSystemSpec } from '../server/system-factory/planner'
import { createMockSystemFactoryProvisioner } from '../server/system-factory/provisioner'
import { MemoryProvisioningRepository, mockedProvisioningContext, runProvisioningTick } from '../server/system-factory/provisioning-scheduler'
import { testRuntimeAuthority } from '../server/system-factory/runtime-authority'
import { executeProvisioningTask } from '../server/system-factory/provisioning-task'
import { acceptInvitationRouteRequest } from '../server/api/system-factory/invitations/accept.post'

function plan() { return compileSystemSpec(createGuidedSystemSpec({ requirements: '建立受治理的預約系統。', businessType: 'service', industry: 'wellness', preferredTemplate: 'appointment_booking', identity: { specId: 'spec-runtime', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', systemTenantId: 'system-tenant-1', locale: 'zh-hant', timezone: 'Asia/Taipei', currency: 'TWD' } })) }
const authority = testRuntimeAuthority('runtime-corrections')
function tenantContext(): TenantAppContext { const compiledPlan = plan(); return { ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', systemTenantId: 'system-tenant-1', siteName: 'tenant.vendor.example.org', credentialReference: 'opaque:hmac', idempotencyKey: 'runtime-test-0001', compiledPlan, runtimeAuthority: authority, executionMode: 'live' } }
function responseFor(body: string, operation: string, extra: Record<string, unknown> = {}) { const parsed = JSON.parse(body); const safe = operation === 'activate_admin_invitation' ? { ...parsed, password: '[REDACTED]' } : parsed; const requestFingerprint = fingerprint(safe); return { message: { ok: true, schemaVersion: 'tenant-app-operation-response-v1', operation, systemTenantId: parsed.systemTenantId, runtimeAuthorityFingerprint: parsed.runtimeAuthorityFingerprint, requestFingerprint, receiptFingerprint: fingerprint({ requestFingerprint, operation }), replayed: false, ...extra } } }

describe('control-plane and tenant-app runtime corrections', () => {
  it('exposes only methods implemented by the custom app and no bench lifecycle paths', () => { expect(Object.keys(TENANT_APP_PATHS).sort()).toEqual(['activate_admin_invitation', 'apply_compiled_spec', 'configure_modules', 'configure_roles', 'health', 'prepare_admin_invitation', 'suspend_tenant']); expect(JSON.stringify(TENANT_APP_PATHS)).not.toMatch(/create_site|install_app|migrate|backup|restore|upgrade/u) })
  it('accepts the exact Frappe message envelope and rejects unknown response fields', async () => { const context = tenantContext(); const credential = { ok: true as const, value: { hmacKey: 'x'.repeat(32), authorizationHeader: 'token opaque-key:opaque-secret' } }; const good = createTenantAppAdapter({ endpointOrigin: 'https://tenant.vendor.example.org', allowedOrigins: ['https://tenant.vendor.example.org'], sender: 'nuxt', receiver: 'frappe', keyId: 'key:1', credentialResolver: async () => credential, liveEnabled: true, fetchImpl: async (_url, init) => new Response(JSON.stringify(responseFor(String(init?.body), 'health', { healthy: true })), { status: 200 }) }); await expect(good.health(context)).resolves.toMatchObject({ healthy: true, externalCalls: true }); const bad = createTenantAppAdapter({ endpointOrigin: 'https://tenant.vendor.example.org', allowedOrigins: ['https://tenant.vendor.example.org'], sender: 'nuxt', receiver: 'frappe', keyId: 'key:1', credentialResolver: async () => credential, liveEnabled: true, fetchImpl: async (_url, init) => new Response(JSON.stringify({ ...responseFor(String(init?.body), 'health', { healthy: true }), unknown: true }), { status: 200 }) }); await expect(bad.health(context)).rejects.toThrow(/envelope/i) })
  it.each([[401, 'authority'], [403, 'authority'], [409, 'authority'], [429, 'retryable'], [500, 'retryable']])('fails closed for tenant-app HTTP %i', async (status, message) => { const adapter = createTenantAppAdapter({ endpointOrigin: 'https://tenant.vendor.example.org', allowedOrigins: ['https://tenant.vendor.example.org'], sender: 'nuxt', receiver: 'frappe', keyId: 'key:1', credentialResolver: async () => ({ ok: true, value: { hmacKey: 'x'.repeat(32), authorizationHeader: 'token opaque-key:opaque-secret' } }), liveEnabled: true, fetchImpl: async () => new Response('{}', { status: Number(status) }) }); await expect(adapter.health(tenantContext())).rejects.toThrow(String(message)) })
  it('rejects malformed, redirect-like transport and timeout outcomes', async () => { const base = { endpointOrigin: 'https://tenant.vendor.example.org', allowedOrigins: ['https://tenant.vendor.example.org'], sender: 'nuxt', receiver: 'frappe', keyId: 'key:1', credentialResolver: async () => Promise.resolve({ ok: true as const, value: { hmacKey: 'x'.repeat(32), authorizationHeader: 'token opaque-key:opaque-secret' } }), liveEnabled: true }; await expect(createTenantAppAdapter({ ...base, fetchImpl: async () => new Response('not-json', { status: 200 }) }).health(tenantContext())).rejects.toThrow(/malformed/i); await expect(createTenantAppAdapter({ ...base, fetchImpl: async () => { throw new TypeError('redirect') } }).health(tenantContext())).rejects.toThrow(/transport/i); const timeout = createTenantAppAdapter({ ...base, timeoutMs: 500, fetchImpl: async (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(new DOMException('aborted', 'AbortError')))) }); await expect(timeout.health(tenantContext())).rejects.toThrow(/timed out/i) }, 2_000)
  it('rejects control-plane unknown fields and request collisions', async () => { const context = { systemTenantId: 'system-tenant-1', siteName: 'tenant.vendor.example.org', credentialReference: 'opaque:control', idempotencyKey: 'control-test-0001', runtimeAuthority: authority, executionMode: 'live' as const }; const adapter = createReviewedBenchControlPlaneAdapter({ liveEnabled: true, transport: { async execute(request) { return { schemaVersion: 'system-factory-bench-response-v1', operation: request.operation, systemTenantId: request.systemTenantId, requestFingerprint: '0'.repeat(64), runtimeAuthorityFingerprint: request.runtimeAuthorityFingerprint, status: 'succeeded', replayed: false, exactResponseIdentity: 'wrong', outputFingerprint: 'a'.repeat(64) } } } }); await expect(adapter.createSite(context)).rejects.toThrow(/mismatched|malformed/i); const calls: string[] = []; await createMockControlPlane({ calls }).createSite({ ...context, executionMode: 'mocked' }); expect(calls).toEqual(['create_site']) })
})

describe('durable scheduler and invitation activation', () => {
  it('runs all eligible plan steps through the real task scheduler and stops invitation-pending', async () => { const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); const calls: string[] = []; const result = await executeProvisioningTask({ enabled: true, repository: repo, controlPlane: createMockControlPlane(), tenantApp: createMockTenantApp(), workerId: 'worker:task' }); expect(result).toMatchObject({ claimed: 1, executed: 7, completed: 1 }); expect(repo.runs.get(1)).toMatchObject({ status: 'completed', completed: ['create_site', 'install_app', 'apply_compiled_spec', 'create_roles_permissions', 'configure_modules', 'health_check', 'create_admin_invitation'] }); expect(calls).toEqual([]) })
  it('allows only one worker to execute a concurrently claimed step sequence', async () => { const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); const calls: string[] = []; const provisioner = createMockSystemFactoryProvisioner({ calls }); await Promise.all([runProvisioningTick({ repository: repo, provisioner, workerId: 'worker:a' }), runProvisioningTick({ repository: repo, provisioner, workerId: 'worker:b' })]); expect(calls.filter(call => call === 'createSite')).toHaveLength(1); expect(repo.runs.get(1)?.receipts).toHaveLength(7) })
  it('keeps a long control-plane operation leased beyond the former 120 second window', async () => { let current = new Date('2030-01-01T00:00:00Z').getTime(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve }); const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); const provisioner = createMockSystemFactoryProvisioner(); const original = provisioner.createSite; let calls = 0; provisioner.createSite = async input => { calls++; await gate; return original(input) }; const first = runProvisioningTick({ repository: repo, provisioner, workerId: 'worker:long', now: new Date(current), clock: () => new Date(current), maxStepsPerTenant: 1 }); await new Promise(resolve => setTimeout(resolve, 0)); current += 121_000; const second = await runProvisioningTick({ repository: repo, provisioner: createMockSystemFactoryProvisioner(), workerId: 'worker:early', now: new Date(current), clock: () => new Date(current), maxStepsPerTenant: 1 }); expect(second.claimed).toBe(0); expect(calls).toBe(1); release(); await first; expect(repo.runs.get(1)?.completed).toEqual(['create_site']) })
  it('rejects an expired old worker commit and recovers through the same provider idempotency key', async () => { let current = new Date('2030-01-01T00:00:00Z').getTime(); let release!: () => void; const gate = new Promise<void>(resolve => { release = resolve }); const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); const firstProvisioner = createMockSystemFactoryProvisioner(); const secondProvisioner = createMockSystemFactoryProvisioner(); const firstCreate = firstProvisioner.createSite; const secondCreate = secondProvisioner.createSite; const keys: string[] = []; firstProvisioner.createSite = async input => { keys.push(input.idempotencyKey); await gate; return firstCreate(input) }; secondProvisioner.createSite = async input => { keys.push(input.idempotencyKey); return { ...await secondCreate(input), replayed: true } }; const first = runProvisioningTick({ repository: repo, provisioner: firstProvisioner, workerId: 'worker:expired', now: new Date(current), clock: () => new Date(current), maxStepsPerTenant: 1 }); await new Promise(resolve => setTimeout(resolve, 0)); current += 360_002; const recovered = await runProvisioningTick({ repository: repo, provisioner: secondProvisioner, workerId: 'worker:recovery', now: new Date(current), clock: () => new Date(current), maxStepsPerTenant: 1 }); expect(recovered).toMatchObject({ claimed: 1, executed: 1 }); release(); const [settled] = await Promise.allSettled([first]); expect(settled.status).toBe('rejected'); expect(keys).toEqual(['system-run-1:create_site', 'system-run-1:create_site']); expect(repo.runs.get(1)?.completed).toEqual(['create_site']); expect(repo.runs.get(1)?.receipts).toHaveLength(1); expect(repo.runs.get(1)?.attempts.map(item => item.status)).toEqual(['retry_wait', 'succeeded']) })
  it('enforces distinct tenant and per-tenant bounds even when a tenant has multiple runs', async () => { const contexts = [mockedProvisioningContext({ runRowId: 1, tenantRowId: 1, compiledPlan: plan(), authority }), mockedProvisioningContext({ runRowId: 2, tenantRowId: 1, compiledPlan: plan(), authority }), ...Array.from({ length: 24 }, (_, index) => mockedProvisioningContext({ runRowId: index + 3, tenantRowId: index + 2, compiledPlan: plan(), authority }))]; const repo = new MemoryProvisioningRepository(contexts); const result = await runProvisioningTick({ repository: repo, provisioner: createMockSystemFactoryProvisioner(), workerId: 'worker:bounds', now: new Date('2030-01-01'), maxTenants: 20, maxStepsPerTenant: 1, maxTotalSteps: 100 }); expect(result).toMatchObject({ claimed: 20, executed: 20 }); expect(repo.runs.get(1)?.completed).toEqual(['create_site']); expect(repo.runs.get(2)?.completed).toEqual([]) })
  it('recovers stale leases and applies bounded exponential retry', async () => { const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); const run = repo.runs.get(1)!; run.status = 'processing'; run.leaseOwner = 'dead'; run.leaseExpiresAt = new Date('2029-01-01'); const first = await runProvisioningTick({ repository: repo, provisioner: createMockSystemFactoryProvisioner({ failAt: 'installApp' }), workerId: 'worker:new', now: new Date('2030-01-01') }); expect(first).toMatchObject({ claimed: 1, retryWait: 1 }); expect(run.retryEligibleAt?.getTime()).toBe(new Date('2030-01-01').getTime() + 30_000); const second = await runProvisioningTick({ repository: repo, provisioner: createMockSystemFactoryProvisioner(), workerId: 'worker:retry', now: new Date('2030-01-01T00:00:31Z') }); expect(second.completed).toBe(1) })
  it('does not retain a fake success when the receipt transaction rolls back', async () => { const repo = new MemoryProvisioningRepository([mockedProvisioningContext({ compiledPlan: plan(), authority })]); repo.failCommitOnce = true; const result = await runProvisioningTick({ repository: repo, provisioner: createMockSystemFactoryProvisioner(), workerId: 'worker:rollback' }); expect(result.retryWait).toBe(1); expect(repo.runs.get(1)?.completed).toEqual([]); expect(repo.runs.get(1)?.receipts).toEqual([]) })
  it('activates once, persists no password, and creates a hashed customer session', async () => { const token = 't'.repeat(48); const email = 'customer@example.org'; const compiledPlan = plan(); const context = { invitationRowId: 1, invitationId: 'invite-1', ownerUserRowId: 1, tenantRowId: 1, systemTenantId: 'system-tenant-1', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', managedSiteProjectId: 1, principalEmail: email, principalEmailHash: fingerprint({ email }), roleKey: 'booking_viewer', compiledPlan, tenantAppCredentialReference: 'opaque:hmac', siteName: 'tenant.vendor.example.org', authority, maxAttempts: 3 } as const; const repository = new MemoryInvitationActivationRepository({ context, token }); const result = await activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0001', repository, tenantApp: createMockTenantApp(), authority, executionMode: 'mocked', workerId: 'invite:a' }); expect(result.accepted).toBe(true); expect(repository.invitation).toMatchObject({ status: 'accepted' }); expect(repository.invitation.sessions[0]).toMatch(/^[a-f0-9]{64}$/u); expect(JSON.stringify(repository.invitation)).not.toContain('StrongPassword123') })
  it('executes the direct invitation route request contract instead of returning fixed 503', async () => { const token = 'r'.repeat(48); const email = 'route@example.org'; const context = { invitationRowId: 1, invitationId: 'invite-route', ownerUserRowId: 1, tenantRowId: 1, systemTenantId: 'system-tenant-1', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', managedSiteProjectId: 1, principalEmail: email, principalEmailHash: fingerprint({ email }), roleKey: 'booking_viewer', compiledPlan: plan(), tenantAppCredentialReference: 'opaque:hmac', siteName: 'tenant.vendor.example.org', authority, maxAttempts: 3 } as const; const repository = new MemoryInvitationActivationRepository({ context, token }); const result = await acceptInvitationRouteRequest({ token, email, password: 'StrongPassword123', idempotencyKey: 'route-accept-0001' }, { repository, tenantApp: createMockTenantApp(), authority }); expect(result).toMatchObject({ accepted: true, invitationId: 'invite-route' }); expect(repository.invitation.status).toBe('accepted') })
  it('fails invalid, expired, used, weak, mismatched and concurrent invitation accepts closed', async () => { const token = 'z'.repeat(48); const email = 'customer@example.org'; const context = { invitationRowId: 1, invitationId: 'invite-2', ownerUserRowId: 1, tenantRowId: 1, systemTenantId: 'system-tenant-1', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', managedSiteProjectId: 1, principalEmail: email, principalEmailHash: fingerprint({ email }), roleKey: 'booking_viewer', compiledPlan: plan(), tenantAppCredentialReference: 'opaque:hmac', siteName: 'tenant.vendor.example.org', authority, maxAttempts: 3 } as const; const expired = new MemoryInvitationActivationRepository({ context, token, expiresAt: new Date('2029-01-01') }); await expect(activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0002', repository: expired, tenantApp: createMockTenantApp(), authority, executionMode: 'mocked', workerId: 'invite:x', now: new Date('2030-01-01') })).rejects.toThrow(/invalid|expired/i); const repo = new MemoryInvitationActivationRepository({ context, token }); await expect(activateSystemInvitation({ token, email, password: 'weak', idempotencyKey: 'accept-test-0003', repository: repo, tenantApp: createMockTenantApp(), authority, executionMode: 'mocked', workerId: 'invite:x' })).rejects.toThrow(/password/i); const slow = createMockTenantApp(); const original = slow.activateAdminInvitation; slow.activateAdminInvitation = async value => { await new Promise(resolve => setTimeout(resolve, 25)); return original(value) }; const calls = [activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0004', repository: repo, tenantApp: slow, authority, executionMode: 'mocked', workerId: 'invite:a' }), activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0004', repository: repo, tenantApp: slow, authority, executionMode: 'mocked', workerId: 'invite:b' })]; const settled = await Promise.allSettled(calls); expect(settled.filter(item => item.status === 'fulfilled')).toHaveLength(1); await expect(activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0004', repository: repo, tenantApp: createMockTenantApp(), authority, executionMode: 'mocked', workerId: 'invite:c' })).rejects.toThrow(/invalid|expired/i) })
  it('blocks activation receipt tenant, role, principal and user drift', async () => { const token = 'q'.repeat(48); const email = 'customer@example.org'; const context = { invitationRowId: 1, invitationId: 'invite-3', ownerUserRowId: 1, tenantRowId: 1, systemTenantId: 'system-tenant-1', ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: 'managed-site:1', managedSiteProjectId: 1, principalEmail: email, principalEmailHash: fingerprint({ email }), roleKey: 'booking_viewer', compiledPlan: plan(), tenantAppCredentialReference: 'opaque:hmac', siteName: 'tenant.vendor.example.org', authority, maxAttempts: 3 } as const; const repo = new MemoryInvitationActivationRepository({ context, token }); const tenant = createMockTenantApp(); const original = tenant.activateAdminInvitation; tenant.activateAdminInvitation = async value => ({ ...await original(value), roleKey: 'booking_manager' }); await expect(activateSystemInvitation({ token, email, password: 'StrongPassword123', idempotencyKey: 'accept-test-0005', repository: repo, tenantApp: tenant, authority, executionMode: 'mocked', workerId: 'invite:a' })).rejects.toThrow(/mismatched/i); expect(repo.invitation.status).toBe('pending') })
})
