import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { compileSystemSpec } from '../server/system-factory/compiler'
import { fingerprint, SystemFactoryError } from '../server/system-factory/canonical'
import { createMockFrappeProvisioner, type FrappeProvisionerPort } from '../server/system-factory/frappe-adapter'
import { createGuidedSystemSpec } from '../server/system-factory/planner'
import { buildSystemPreview } from '../server/system-factory/preview'
import { MemoryWorkflowRepository, applyVerifiedTransition, executeProvisioning, executeUpgrade } from '../server/system-factory/workflow'

function compiled(existing = false) { return compileSystemSpec(createGuidedSystemSpec({ requirements: existing ? '既有網站加購預約管理系統。' : '新客戶需要 CRM 系統與網站預覽。', businessType: 'service', industry: 'consulting', preferredTemplate: existing ? 'appointment_booking' : 'light_crm', identity: { specId: existing ? 'spec-existing' : 'spec-new', ownerId: 'owner:1', clientId: 'client:1', websiteId: existing ? 'website:existing' : 'website:new', managedSiteId: existing ? 'managed-site:10' : null, systemTenantId: 'tenant:1', locale: 'zh-hant', timezone: 'Asia/Taipei', currency: 'TWD' } })) }
function repository(plan = compiled()) { const repo = new MemoryWorkflowRepository(); repo.seed({ ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:new', managedSiteId: null, systemTenantId: 'tenant:1', state: 'provisioning_planned', stateVersion: 1, specFingerprint: plan.specFingerprint, compiledPlanFingerprint: plan.planFingerprint, managedSiteOrderId: 10, verifiedPaymentReceiptFingerprint: 'a'.repeat(64), leaseOwner: null, leaseExpiresAt: null, attempt: 0, maxAttempts: 3, retryEligibleAt: null, healthyReceiptFingerprint: null, invitationReceiptFingerprint: null }); return repo }

describe('durable provisioning and upgrade contracts', () => {
  it('keeps preview synthetic and invokes no executor', () => { const plan = compiled(); const spec = JSON.parse(plan.canonicalSpecJson); const preview = buildSystemPreview(spec, plan, { version: 1, now: new Date('2030-01-01T00:00:00.000Z') }); expect(preview).toMatchObject({ previewOnly: true, deployed: false, connectedToProductionErp: false, containsProductionData: false, noProductionDataMarker: 'SYNTHETIC_DEMO_DATA_ONLY' }) })

  it('blocks unpaid or mismatched spec before executor', async () => { const plan = compiled(); const repo = repository(plan); const tenant = await repo.getTenant('owner:1', 'tenant:1'); repo.tenants.set('owner:1:tenant:1', { ...tenant!, verifiedPaymentReceiptFingerprint: null }); const calls: string[] = []; await expect(executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: plan, siteName: 'site', credentialReference: 'vault:test', executor: createMockFrappeProvisioner({ calls }), repository: repo, executionMode: 'mocked' })).rejects.toThrow(/payment/i); expect(calls).toEqual([]) })

  it('concurrent duplicate claims invoke executor exactly once', async () => { const plan = compiled(); const repo = repository(plan); const calls: string[] = []; const run = () => executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: plan, siteName: 'site', credentialReference: 'vault:test', executor: createMockFrappeProvisioner({ calls }), repository: repo, executionMode: 'mocked', now: new Date('2030-01-01T00:00:00.000Z') }); const results = await Promise.allSettled([run(), run()]); expect(results.filter(item => item.status === 'fulfilled')).toHaveLength(1); expect(calls).toEqual(['createSite', 'installApp', 'applyCompiledSpec', 'createRolesAndPermissions', 'configureModules', 'healthCheck', 'createAdminInvitation']); expect((await repo.getTenant('owner:1', 'tenant:1'))?.state).toBe('active') })

  it('recovers stale lease and handles bounded retry/partial failure', async () => { const plan = compiled(); const repo = repository(plan); const tenant = await repo.getTenant('owner:1', 'tenant:1'); repo.tenants.set('owner:1:tenant:1', { ...tenant!, leaseOwner: 'dead-worker', leaseExpiresAt: '2029-01-01T00:00:00.000Z' }); expect(await repo.claim('owner:1', 'tenant:1', 'new-worker', new Date('2030-01-01T00:00:00.000Z'), 1000)).toBe('stale_recovered'); await repo.release('owner:1', 'tenant:1', 'new-worker', {}); const result = await executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: plan, siteName: 'site', credentialReference: 'vault:test', executor: createMockFrappeProvisioner({ failAt: 'installApp' }), repository: repo, executionMode: 'mocked', now: new Date('2030-01-01T00:00:00.000Z') }); expect(result.tenant.state).toBe('retry_wait'); expect(result.tenant.retryEligibleAt).not.toBeNull(); expect(result.receipts.at(-1)?.status).toBe('failed') })

  it('fails health closed and never creates invitation', async () => { const plan = compiled(); const repo = repository(plan); const calls: string[] = []; const result = await executeProvisioning({ ownerId: 'owner:1', tenantId: 'tenant:1', compiledPlan: plan, siteName: 'site', credentialReference: 'vault:test', executor: createMockFrappeProvisioner({ unhealthyAt: 'healthCheck', calls }), repository: repo, executionMode: 'mocked' }); expect(result.tenant.state).toBe('retry_wait'); expect(calls).not.toContain('createAdminInvitation'); expect(result.tenant.invitationReceiptFingerprint).toBeNull() })

  it('uses verified stored events for suspend/reactivate and protects terminal transitions', async () => { const plan = compiled(); const repo = repository(plan); const tenant = await repo.getTenant('owner:1', 'tenant:1'); repo.tenants.set('owner:1:tenant:1', { ...tenant!, state: 'active' }); const event = (type: string, id: number) => ({ eventId: `event-${id}`, type, ownerId: 'owner:1', clientId: 'client:1', systemTenantId: 'tenant:1', verified: true as const, authorityFingerprint: fingerprint({ type, id }), payloadFingerprint: fingerprint({ payload: id }), occurredAt: new Date().toISOString() }); expect((await applyVerifiedTransition(repo, 'owner:1', 'tenant:1', event('suspended', 1))).state).toBe('suspended'); expect((await applyVerifiedTransition(repo, 'owner:1', 'tenant:1', event('reactivated', 2))).state).toBe('active'); await applyVerifiedTransition(repo, 'owner:1', 'tenant:1', event('deprovision_requested', 3)); await applyVerifiedTransition(repo, 'owner:1', 'tenant:1', event('deprovision_completed', 4)); await expect(applyVerifiedTransition(repo, 'owner:1', 'tenant:1', event('reactivated', 5))).rejects.toThrow() })

  it('backs up before upgrade and records rollback after failure', async () => { const plan = compiled(); const calls: string[] = []; const executor = createMockFrappeProvisioner({ failAt: 'applyUpgrade', calls }); const result = await executeUpgrade({ context: { ownerId: 'owner:1', clientId: 'client:1', websiteId: 'website:1', managedSiteId: null, systemTenantId: 'tenant:1', siteName: 'site', credentialReference: 'vault:test', idempotencyKey: 'upgrade-0001', compiledPlan: plan, executionMode: 'mocked', targetVersion: 'v16-next-reviewed' }, executor }); expect(result.status).toBe('rolled_back'); expect(calls).toEqual(['planUpgrade', 'backupBeforeUpgrade', 'applyUpgrade', 'rollbackUpgrade']) })

  it('contains no user-controlled shell execution path', () => { const source = readFileSync(new URL('../server/system-factory/frappe-adapter.ts', import.meta.url), 'utf8'); expect(source).not.toMatch(/child_process|execFile|spawn|shell\s*:/u); expect(source).not.toContain('userCommand') })
})
