import { afterEach, describe, expect, it, vi } from 'vitest'
import { activateWeeklyReviewConfig, pauseWeeklyReviewConfig, issueLineBindingInvite, claimLineBindingInvite, createReviewRequest, deriveReviewTokens, getReviewByReadToken, reviewFromVerifiedLine, getApprovedReviewForPromotion, reopenReviewRequest } from '../server/weekly-content/service'
import { weeklyConsentAllowsPublication, assertWeeklyPublicationConsent, assertWeeklyWorkflowActive } from '../server/weekly-content/publication-guard'
import { createWeeklyContentRepositoryFromDatabase, WeeklyWebhookInboxRaceError } from '../server/weekly-content/repository'
import { WeeklyFixture, WEEKLY_NOW, WEEKLY_KEY, sha } from './fixtures/weekly-content/repository'
const SENDER='U'+ '1'.repeat(32)
const identity=(id:string)=>({lineUserId:SENDER,webhookEventId:id,semanticFingerprint:sha(id)})
const configInput={ownerUserId:1,clientId:1,publicationTargetId:3,policyId:'policy-1',idempotencyKey:'weekly-activate'}
async function bound(){const f=new WeeklyFixture();await activateWeeklyReviewConfig(configInput,f.deps());const invite=await issueLineBindingInvite({ownerUserId:1,clientId:1},f.deps());await claimLineBindingInvite({...identity('bind-1'),invitationToken:invite.invitationToken},f.deps());return {f,invite}}
async function ready(){const {f}=await bound();await createReviewRequest({ownerUserId:1,clientId:1,entryId:8},f.deps());const request=f.state.requests[0]!;return {f,request,...deriveReviewTokens(request,WEEKLY_KEY)}}
const approve=(requestId:string,actionToken:string,id='decision-1')=>({...identity(id),requestId,actionToken,decision:'approved' as const})
afterEach(()=>vi.unstubAllEnvs())
describe('durable weekly customer review',()=>{
  it('disabled or missing token key performs zero repository work',async()=>{const f=new WeeklyFixture();await expect(activateWeeklyReviewConfig(configInput,{...f.deps(),featureEnabled:false})).rejects.toThrow('WEEKLY_APPROVAL_DISABLED');await expect(issueLineBindingInvite({ownerUserId:1,clientId:1},{...f.deps(),tokenKey:''})).rejects.toThrow('WEEKLY_REVIEW_TOKEN_KEY_NOT_CONFIGURED');expect(f.repository.findClient).not.toHaveBeenCalled();expect(f.state.config).toBeNull()})
  it('activation is owner-scoped and exact idempotency cannot change target/policy/TTL',async()=>{const f=new WeeklyFixture();await expect(activateWeeklyReviewConfig({...configInput,ownerUserId:2},f.deps())).rejects.toThrow('WEEKLY_CLIENT_NOT_AVAILABLE');const result=await activateWeeklyReviewConfig(configInput,f.deps());expect(result.config.requireCustomerApproval).toBe(true);expect((await activateWeeklyReviewConfig(configInput,f.deps())).replayed).toBe(true);await expect(activateWeeklyReviewConfig({...configInput,reviewTtlHours:24},f.deps())).rejects.toThrow('WEEKLY_CONFIG_IDEMPOTENCY_COLLISION')})
  it.each(['cadence','owner-review'] as const)('does not invent owner authority for %s policies',async(kind)=>{const f=new WeeklyFixture();if(kind==='cadence')f.state.policy.cadenceDays=3;else f.state.policy.requireApprovedForDelivery=true;await expect(activateWeeklyReviewConfig(configInput,f.deps())).rejects.toThrow('WEEKLY_OWNER_POLICY_NOT_READY');expect(f.state.config).toBeNull()})
  it('one-time invitation binds only the verified private sender and never leaks recipient into config',async()=>{const {f,invite}=await bound();expect(f.state.invites[0]!.tokenHash).toBe(sha(invite.invitationToken));expect(f.state.invites[0]).not.toHaveProperty('invitationToken');const replay=await claimLineBindingInvite({...identity('bind-2'),invitationToken:invite.invitationToken},f.deps());expect(replay.status).toBe('replayed');await expect(claimLineBindingInvite({...identity('bind-3'),lineUserId:'U'+'2'.repeat(32),invitationToken:invite.invitationToken},f.deps())).rejects.toThrow('WEEKLY_INVITATION_ALREADY_USED');const config=await activateWeeklyReviewConfig(configInput,f.deps());expect(JSON.stringify(config)).not.toContain(SENDER)})
  it('expires invitations exactly at TTL and new invitation invalidates the previous token',async()=>{const f=new WeeklyFixture();await activateWeeklyReviewConfig(configInput,f.deps());const first=await issueLineBindingInvite({ownerUserId:1,clientId:1},f.deps());await issueLineBindingInvite({ownerUserId:1,clientId:1},f.deps());await expect(claimLineBindingInvite({...identity('first'),invitationToken:first.invitationToken},f.deps())).rejects.toThrow('WEEKLY_INVITATION_EXPIRED');const current=await issueLineBindingInvite({ownerUserId:1,clientId:1},f.deps());await expect(claimLineBindingInvite({...identity('late'),invitationToken:current.invitationToken},{...f.deps(),now:new Date(current.expiresAt)})).rejects.toThrow('WEEKLY_INVITATION_EXPIRED')})
  it('creates one exact durable request/outbox and previews read without any consent or queue write',async()=>{const {f,request,readToken,actionToken}=await ready();const replay=await createReviewRequest({ownerUserId:1,clientId:1,entryId:8},f.deps());expect(replay.replayed).toBe(true);expect(f.state.requests).toHaveLength(1);expect(f.state.outbox).toHaveLength(1);const view=await getReviewByReadToken({requestId:request.requestId,readToken},f.deps());expect(view.title).toBe(f.state.draft.title);expect(JSON.stringify(view)).not.toContain(SENDER);expect(JSON.stringify(view)).not.toContain(actionToken);expect(f.state.consents).toHaveLength(0);expect(f.state.queued).toBe(0);await expect(reviewFromVerifiedLine(approve(request.requestId,readToken),f.deps())).rejects.toThrow('WEEKLY_ACTION_TOKEN_INVALID')})
  it('rejects new requests until V4 machine review really passed',async()=>{const {f}=await bound();f.state.draft.machineAuthorizationValid=false;await expect(createReviewRequest({ownerUserId:1,clientId:1,entryId:8},f.deps())).rejects.toThrow('WEEKLY_MACHINE_REVIEW_NOT_READY');expect(f.state.outbox).toHaveLength(0)})
  it('one client cannot have another live review for a changed draft',async()=>{const {f}=await ready();f.state.draft.draftId++;f.state.draft.contentHash='b'.repeat(64);await expect(createReviewRequest({ownerUserId:1,clientId:1,entryId:8},f.deps())).rejects.toThrow('WEEKLY_CLIENT_ALREADY_HAS_OPEN_REVIEW');expect(f.state.outbox).toHaveLength(1)})
  it('verified sender and action token must both match; token key rotation fails closed',async()=>{const {f,request,actionToken,readToken}=await ready();await expect(reviewFromVerifiedLine({...approve(request.requestId,actionToken),lineUserId:'U'+'2'.repeat(32)},f.deps())).rejects.toThrow('WEEKLY_LINE_SENDER_MISMATCH');await expect(reviewFromVerifiedLine(approve(request.requestId,actionToken),{...f.deps(),tokenKey:WEEKLY_KEY+'changed'})).rejects.toThrow('WEEKLY_REVIEW_TOKEN_KEY_CHANGED');await expect(getReviewByReadToken({requestId:request.requestId,readToken},{...f.deps(),tokenKey:WEEKLY_KEY+'changed'})).rejects.toThrow('WEEKLY_REVIEW_TOKEN_KEY_CHANGED');expect(f.state.consents).toHaveLength(0)})
  it('concurrent same signed event commits one consent/queue; different semantic payload fails closed',async()=>{const {f,request,actionToken}=await ready();const input=approve(request.requestId,actionToken);const result=await Promise.all([reviewFromVerifiedLine(input,f.deps()),reviewFromVerifiedLine(input,f.deps())]);expect(result.map(value=>value.status).sort()).toEqual(['approved','replayed']);expect(f.state.consents).toHaveLength(1);expect(f.state.queued).toBe(1);await expect(reviewFromVerifiedLine({...input,semanticFingerprint:sha('different')},f.deps())).rejects.toThrow('WEEKLY_LINE_EVENT_COLLISION');expect(f.state.consents).toHaveLength(1)})
  it('a second signed event cannot append approval twice',async()=>{const {f,request,actionToken}=await ready();await reviewFromVerifiedLine(approve(request.requestId,actionToken),f.deps());expect((await reviewFromVerifiedLine(approve(request.requestId,actionToken,'decision-2'),f.deps())).status).toBe('replayed');expect(f.state.consents).toHaveLength(1);expect(f.state.queued).toBe(1)})
  it('customer changes withdraw earlier consent before reservation and cannot re-approve the unchanged revision',async()=>{const {f,request,actionToken}=await ready();await reviewFromVerifiedLine(approve(request.requestId,actionToken),f.deps());await reviewFromVerifiedLine({...approve(request.requestId,actionToken,'change-1'),decision:'changes_requested'},f.deps());expect(f.state.consents.map(row=>row.decision)).toEqual(['approved','changes_requested']);await expect(getApprovedReviewForPromotion({ownerUserId:1,requestId:request.requestId},f.deps())).rejects.toThrow('WEEKLY_CUSTOMER_APPROVAL_REQUIRED');await expect(reviewFromVerifiedLine(approve(request.requestId,actionToken,'approve-again'),f.deps())).rejects.toThrow('WEEKLY_DECISION_ALREADY_FINAL')})
  it('customer changes after publication reservation cannot pretend to undo a begun external write',async()=>{const {f,request,actionToken}=await ready();await reviewFromVerifiedLine(approve(request.requestId,actionToken),f.deps());f.state.reserved=true;await expect(reviewFromVerifiedLine({...approve(request.requestId,actionToken,'late-changes'),decision:'changes_requested'},f.deps())).rejects.toThrow('WEEKLY_PUBLICATION_ALREADY_RESERVED');expect(f.state.consents).toHaveLength(1)})
  it.each(['draft','version','language','type','hash','evidence','target','policy','binding','risk','paused','expired'] as const)('rejects consent when current %s is no longer exact',async(kind)=>{const {f,request,actionToken}=await ready();const altered={...f.deps()};if(kind==='draft')f.state.draft.draftId++;if(kind==='version')f.state.draft.draftVersion++;if(kind==='language')f.state.draft.language='en';if(kind==='type')f.state.draft.contentType='faq';if(kind==='hash')f.state.draft.contentHash='b'.repeat(64);if(kind==='evidence')f.state.draft.evidenceSnapshotHash='b'.repeat(64);if(kind==='target')f.state.target.configurationFingerprint='b'.repeat(64);if(kind==='policy')f.state.policy.configurationFingerprint='b'.repeat(64);if(kind==='binding')f.state.binding!.status='revoked';if(kind==='risk')f.state.draft.riskGateStatus='blocked';if(kind==='paused')await pauseWeeklyReviewConfig({ownerUserId:1,clientId:1,status:'paused'},f.deps());if(kind==='expired')altered.now=request.expiresAt;await expect(reviewFromVerifiedLine(approve(request.requestId,actionToken),altered)).rejects.toThrow('WEEKLY_REQUEST_EXPIRED_OR_CHANGED');expect(f.state.consents).toHaveLength(0)})
  it('publication requires latest exact customer consent and current owner policy together',async()=>{const {f,request,actionToken}=await ready();await reviewFromVerifiedLine(approve(request.requestId,actionToken),f.deps());const draft=(await f.repository.getDraft(1,1,8))!;expect(weeklyConsentAllowsPublication(f.state.requests[0]!,f.state.consents[0]!,f.state.config!,f.state.binding!,draft,WEEKLY_NOW)).toBe(true);draft.policy!.authorizedByOwnerUserId=2;expect(weeklyConsentAllowsPublication(f.state.requests[0]!,f.state.consents[0]!,f.state.config!,f.state.binding!,draft,WEEKLY_NOW)).toBe(false)})
  it('race after rollback uses only a fresh exact inbox winner, with no new consent',async()=>{const {f,request,actionToken}=await ready();const input=approve(request.requestId,actionToken);await reviewFromVerifiedLine(input,f.deps());const original=f.repository.transaction;f.repository.transaction=async()=>{throw new WeeklyWebhookInboxRaceError({cause:new Error('wrapped mysql duplicate')})};expect((await reviewFromVerifiedLine(input,f.deps())).status).toBe('replayed');await expect(reviewFromVerifiedLine({...input,semanticFingerprint:sha('collision')},f.deps())).rejects.toThrow('WEEKLY_LINE_EVENT_COLLISION');f.repository.transaction=original;expect(f.state.consents).toHaveLength(1)})
  it('only exact webhook unique-key duplicates are translated, including driver cause wrappers',async()=>{for(const key of ['weekly_webhook_event_uq','weekly_outbox_request_uq']){const cause={code:'ER_DUP_ENTRY',errno:1062,message:`Duplicate entry for key 'weeklyContentWebhookInbox.${key}'`};const failure=new Error('Drizzle failed',{cause});const db={insert:()=>({values:()=>({$returningId:async()=>{throw failure}})})};const repo=createWeeklyContentRepositoryFromDatabase(db);const run=repo.insertInbox({eventHash:sha('event'),payloadFingerprint:sha('payload'),status:'processed',resultCode:'CUSTOMER_APPROVED'});if(key==='weekly_webhook_event_uq')await expect(run).rejects.toBeInstanceOf(WeeklyWebhookInboxRaceError);else await expect(run).rejects.toBe(failure)}})
  it('legacy clients do not touch weekly tables; required clients with feature off cannot publish',async()=>{const from=vi.fn();let required=false;const tx={select:()=>({from:(table:unknown)=>{from(table);return {where:()=>({for:()=>({limit:async()=>[{id:1,ownerUserId:1,requireCustomerApproval:required}]})})}}})};const input={ownerUserId:1,clientId:1,entryId:8,jobId:9,draftId:10,targetId:3,contentHash:sha('body'),evidenceSnapshotHash:sha('evidence'),startedAt:WEEKLY_NOW};vi.stubEnv('NUXT_WEEKLY_CONTENT_APPROVAL_ENABLED','false');await assertWeeklyPublicationConsent(tx,input);expect(from).toHaveBeenCalledTimes(1);required=true;await expect(assertWeeklyPublicationConsent(tx,input)).rejects.toThrow('WEEKLY_CUSTOMER_APPROVAL_REQUIRED');expect(from).toHaveBeenCalledTimes(2)})
  it('expired review needs explicit owner reopen, new tokens/outbox, and same-key retries reuse one new request',async()=>{const {f,request,readToken}=await ready();const deps={...f.deps(),now:request.expiresAt};await expect(createReviewRequest({ownerUserId:1,clientId:1,entryId:8},deps)).rejects.toThrow('WEEKLY_REVIEW_EXPIRED');const input={ownerUserId:1,clientId:1,entryId:8,idempotencyKey:'owner-explicit-reopen'};const responses=await Promise.all([reopenReviewRequest(input,deps),reopenReviewRequest(input,deps)]);expect(responses.map(value=>value.replayed).sort()).toEqual([false,true]);expect(f.state.requests).toHaveLength(2);expect(f.state.requests[0]!.status).toBe('revoked');expect(f.state.requests[1]!.requestId).not.toBe(request.requestId);expect(deriveReviewTokens(f.state.requests[1]!,WEEKLY_KEY).readToken).not.toBe(readToken);expect(f.state.outbox).toHaveLength(2);expect(f.state.consents).toHaveLength(0);expect((await createReviewRequest({ownerUserId:1,clientId:1,entryId:8},deps)).request.requestId).toBe(f.state.requests[1]!.requestId)})
  it('owner can reopen failed notification but cannot refresh an unchanged customer revision request',async()=>{const {f,request,actionToken}=await ready();f.state.outbox[0]!.status='failed';const result=await reopenReviewRequest({ownerUserId:1,clientId:1,entryId:8,idempotencyKey:'failed-notification'},f.deps());expect(result.replayed).toBe(false);expect(f.state.requests[0]!.status).toBe('revoked');const newRequest=f.state.requests[1]!,tokens=deriveReviewTokens(newRequest,WEEKLY_KEY);await reviewFromVerifiedLine({...approve(newRequest.requestId,tokens.actionToken),decision:'changes_requested'},f.deps());await expect(reopenReviewRequest({ownerUserId:1,clientId:1,entryId:8,idempotencyKey:'forbidden-refresh'},{...f.deps(),now:newRequest.expiresAt})).rejects.toThrow('WEEKLY_REVIEW_CANNOT_REOPEN');expect(f.state.consents).toHaveLength(1);expect(f.state.requests).toHaveLength(2);await expect(reviewFromVerifiedLine(approve(request.requestId,actionToken,'old-request'),f.deps())).rejects.toThrow('WEEKLY_REVIEW_REVOKED')})
  it.each(['reserved','changed','live'] as const)('reopen fails closed for %s original review',async(kind)=>{const {f,request,actionToken}=await ready();const deps={...f.deps(),now:request.expiresAt};if(kind==='reserved'){await reviewFromVerifiedLine(approve(request.requestId,actionToken),f.deps());f.state.reserved=true}if(kind==='changed'){f.state.draft.draftId++;f.state.draft.contentHash='b'.repeat(64)}if(kind==='live')deps.now=WEEKLY_NOW;await expect(reopenReviewRequest({ownerUserId:1,clientId:1,entryId:8,idempotencyKey:'blocked-reopen'},deps)).rejects.toThrow(kind==='reserved'?'WEEKLY_PUBLICATION_ALREADY_RESERVED':kind==='changed'?'WEEKLY_REOPEN_DRAFT_CHANGED':'WEEKLY_REVIEW_CANNOT_REOPEN');expect(f.state.requests).toHaveLength(1);expect(f.state.outbox).toHaveLength(1);expect(f.state.requests[0]!.status).not.toBe('revoked')})
  it('workflow disabled stops before any database lookup',async()=>{const select=vi.fn();vi.stubEnv('NUXT_WEEKLY_CONTENT_APPROVAL_ENABLED','false');await expect(assertWeeklyWorkflowActive({select},{ownerUserId:1,clientId:1,now:WEEKLY_NOW})).rejects.toThrow('WEEKLY_CONFIG_NOT_ACTIVE');expect(select).not.toHaveBeenCalled()})
})
