import { describe, expect, it } from 'vitest'
import { matchesCurrentV4ReservationAuthority, matchesPublishedV4DeliveredAuthority, createContentOperationsRepositoryFromDatabase, type ContentOperationsRepository } from '../server/content-operations/repository'
import { getTableName } from 'drizzle-orm'
import type { ContentOperationMachineAuthorizationRow } from '../server/content-operations/types'
import { stableFingerprint } from '../server/content-operations/normalization'
import { weeklyPolicy, weeklyTarget, WEEKLY_NOW, WEEKLY_HASH } from './fixtures/weekly-content/repository'
function boundary(){
  const policy=weeklyPolicy(),target=weeklyTarget()
  const base={authorizationVersion:'machine-authorization-v2',authorizationId:'machine-fixture',policy:{policyId:policy.policyId,policyVersion:policy.policyVersion,configurationFingerprint:policy.configurationFingerprint,ownerUserId:1,clientId:1,websiteId:'website-1'},candidate:{candidateId:'entry-8:draft-10',contentHash:WEEKLY_HASH,contentType:'article',locale:'zh-hant'},content:{draftId:'10',contentHash:WEEKLY_HASH},evidence:{snapshotHash:WEEKLY_HASH,status:'approved_fresh'},quality:{status:'passed',fingerprint:WEEKLY_HASH},target:{websiteId:'website-1',targetRowId:3,destinationId:'primary',configurationFingerprint:target.configurationFingerprint,identityVerified:true},lineage:{entryId:8,jobId:9,draftId:'10',entityProfileFingerprint:WEEKLY_HASH,queryOwnershipFingerprint:WEEKLY_HASH},decision:{action:'publish'}}
  const fingerprint=stableFingerprint(base)
  const authorization:ContentOperationMachineAuthorizationRow={id:11,authorizationId:'machine-fixture',ownerUserId:1,clientId:1,websiteId:'website-1',entryId:8,jobId:9,draftId:10,publicationTargetId:3,policyId:policy.policyId,policyVersion:policy.policyVersion,candidateId:'entry-8:draft-10',contentHash:WEEKLY_HASH,evidenceSnapshotHash:WEEKLY_HASH,policyFingerprint:policy.configurationFingerprint,entityProfileFingerprint:WEEKLY_HASH,queryOwnershipFingerprint:WEEKLY_HASH,riskClass:'general',riskFingerprint:WEEKLY_HASH,qualityStatus:'passed',qualityFingerprint:WEEKLY_HASH,targetId:'primary',authorizationPayload:{...base,authorizationFingerprint:fingerprint},authorizationFingerprint:fingerprint,status:'executing',decidedAt:WEEKLY_NOW,authorizationExpiresAt:new Date(WEEKLY_NOW.getTime()+900000),claimedAt:WEEKLY_NOW,revokedAt:null,createdAt:WEEKLY_NOW}
  const input={ownerUserId:1,clientId:1,entryId:8,jobId:9,draftId:10,targetId:3,contentHash:WEEKLY_HASH,evidenceSnapshotHash:WEEKLY_HASH,startedAt:WEEKLY_NOW,authorityReference:fingerprint}
  return {authorization,policy,target,input}
}
describe('V4 fingerprints require durable current authority',()=>{
  it('exact executing record is recognized without a fake human review',()=>{const {authorization,policy,target,input}=boundary();expect(matchesCurrentV4ReservationAuthority(authorization,policy,target,input)).toBe(true);expect(matchesCurrentV4ReservationAuthority(null,policy,target,input)).toBe(false)})
  it.each(['unclaimed','expired','revoked','owner','job','draft','target','content','evidence','policy','target-binding','payload'] as const)('fails closed when %s changes before the actual transaction',kind=>{const {authorization,policy,target,input}=boundary();if(kind==='unclaimed')authorization.status='authorized';if(kind==='expired')authorization.authorizationExpiresAt=WEEKLY_NOW;if(kind==='revoked')authorization.revokedAt=WEEKLY_NOW;if(kind==='owner')authorization.ownerUserId=2;if(kind==='job')authorization.jobId=99;if(kind==='draft')authorization.draftId++;if(kind==='target')authorization.publicationTargetId=4;if(kind==='content')authorization.contentHash='b'.repeat(64);if(kind==='evidence')authorization.evidenceSnapshotHash='b'.repeat(64);if(kind==='policy')policy.status='paused';if(kind==='target-binding')target.configurationFingerprint='b'.repeat(64);if(kind==='payload')authorization.authorizationPayload={...authorization.authorizationPayload as object,decision:{action:'repair'}};expect(matchesCurrentV4ReservationAuthority(authorization,policy,target,input)).toBe(false)})
  it.each(['valid','unclaimed','risk','owner-rejection'] as const)('actual reservation reads durable authority and original risk/review before any ledger for %s',async(kind)=>{
    const {authorization,policy,target,input}=boundary()
    if(kind==='unclaimed')authorization.status='authorized'
    const sentinel=new Error('all authority guards passed; ledger deliberately stopped')
    const reads:string[]=[],locks:string[]=[]
    const rows=new Map<string,unknown[]>([['seoGeoContentJobs',[{id:9,ownerUserId:1}]],['contentOperationMachineAuthorizations',[authorization]],['contentOperationAutopilotPolicies',[policy]],['contentOperationPublicationTargets',[target]],['seoGeoContentReviews',kind==='owner-rejection'?[{id:20,decision:'changes_requested'}]:[]],['seoGeoContentRiskGates',[{id:6,status:kind==='risk'?'blocked':'passed'}]],['contentOperationClients',[{id:1,ownerUserId:1,requireCustomerApproval:false}]]])
    const tx={select:()=>({from:(table:Parameters<typeof getTableName>[0])=>{const name=getTableName(table);reads.push(name);const chain={where:(_value:unknown)=>chain,orderBy:(_value:unknown)=>chain,for:(_value:string)=>{locks.push(name);return chain},limit:async()=>{if(name==='contentOperationPublicationAttempts')throw sentinel;return rows.get(name)||[]}};return chain}})}
    const database={transaction:async<T>(work:(transaction:typeof tx)=>Promise<T>)=>work(tx)}
    const repo=createContentOperationsRepositoryFromDatabase(database,{currentTime:()=>WEEKLY_NOW})
    const reservation:Parameters<ContentOperationsRepository['reservePublicationAttempt']>[0]={...input,runId:5,leaseToken:'synthetic-lease',mode:'execute',attemptNumber:1,idempotencyKey:'attempt-1',inputFingerprint:WEEKLY_HASH,publicationId:'publication-8',publicationSlug:'article',publicationPath:'content/article.mdx',publicationUrl:null,receiptLedger:null,publicationContentHash:WEEKLY_HASH,reviewId:null,riskGateId:6}
    if(kind==='valid')await expect(repo.reservePublicationAttempt(reservation)).rejects.toBe(sentinel)
    else await expect(repo.reservePublicationAttempt(reservation)).rejects.toThrow(kind==='unclaimed'?'Publication approval changed':kind==='risk'?'Publication risk gate changed':'A newer owner review blocks')
    expect(reads[0]).toBe('seoGeoContentJobs');expect(locks).toContain('seoGeoContentJobs');expect(locks).toContain('contentOperationMachineAuthorizations')
    if(kind!=='valid')expect(reads).not.toContain('contentOperationPublicationAttempts')
  })
  it('published exact historical authority survives only the execution lease, without reopening permission to publish',()=>{const {authorization,policy,target,input}=boundary();authorization.status='published';authorization.authorizationExpiresAt=new Date(WEEKLY_NOW.getTime()-1);expect(matchesPublishedV4DeliveredAuthority(authorization,input)).toBe(true);expect(matchesCurrentV4ReservationAuthority(authorization,policy,target,input)).toBe(false);authorization.status='authorized';expect(matchesPublishedV4DeliveredAuthority(authorization,input)).toBe(false)})
  it.each(['owner','target','body','decision'] as const)('historical delivered proof rejects a changed %s',kind=>{const {authorization,input}=boundary();authorization.status='published';if(kind==='owner')authorization.ownerUserId=2;if(kind==='target')input.targetId=99;if(kind==='body')input.contentHash='b'.repeat(64);if(kind==='decision')authorization.authorizationPayload={...authorization.authorizationPayload as object,decision:{action:'repair'}};expect(matchesPublishedV4DeliveredAuthority(authorization,input)).toBe(false)})
})
