import {readFileSync} from 'node:fs'
import {createApp,createRouter,defineEventHandler,send,setResponseStatus,toWebHandler,type EventHandler} from 'h3'
import {afterAll,afterEach,beforeAll,beforeEach,describe,expect,it,vi} from 'vitest'
import {activateWeeklyReviewConfig,issueLineBindingInvite} from '../server/weekly-content/service'
import {WeeklyFixture,WEEKLY_NOW,WEEKLY_KEY} from './fixtures/weekly-content/repository'
const seams=vi.hoisted(()=>({repository:vi.fn()}))
vi.mock('../server/weekly-content/repository',async original=>({...await original<typeof import('../server/weekly-content/repository')>(),createWeeklyContentRepository:seams.repository}))
const ORIGIN='https://synthetic-weekly.taipei',TOKEN='synthetic.header.signature',USER=`U${'1'.repeat(32)}`
let config:EventHandler,context:EventHandler,confirm:EventHandler,f:WeeklyFixture,invitationToken:string,provider:ReturnType<typeof vi.fn>
beforeAll(async()=>{vi.stubGlobal('defineEventHandler',defineEventHandler);config=(await import('../server/api/weekly-content/connect/config.get')).default;context=(await import('../server/api/weekly-content/connect/context.post')).default;confirm=(await import('../server/api/weekly-content/connect/confirm.post')).default})
beforeEach(async()=>{
 vi.clearAllMocks();vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(WEEKLY_NOW)
 for(const [key,value] of Object.entries({NUXT_WEEKLY_CONTENT_APPROVAL_ENABLED:'true',NUXT_WEEKLY_CONTENT_LIFF_ENABLED:'true',NUXT_WEEKLY_CONTENT_LIFF_ID:'2001234567-Abcd1234',NUXT_WEEKLY_CONTENT_LINE_LOGIN_CHANNEL_ID:'2001234567',NUXT_WEEKLY_CONTENT_TOKEN_KEY:WEEKLY_KEY,NUXT_WEEKLY_CONTENT_REVIEW_ORIGIN:ORIGIN}))vi.stubEnv(key,value)
 f=new WeeklyFixture();await activateWeeklyReviewConfig({ownerUserId:1,clientId:1,publicationTargetId:3,policyId:'policy-1',idempotencyKey:'activate'},f.deps());invitationToken=(await issueLineBindingInvite({ownerUserId:1,clientId:1},f.deps())).invitationToken;seams.repository.mockReturnValue(f.repository)
 provider=vi.fn(async()=>new Response(JSON.stringify({iss:'https://access.line.me',aud:'2001234567',sub:USER,iat:Math.floor(WEEKLY_NOW.getTime()/1000)-100,exp:Math.floor(WEEKLY_NOW.getTime()/1000)+3500}),{headers:{'content-type':'application/json'}}));vi.stubGlobal('fetch',provider)
})
afterEach(()=>{vi.useRealTimers();vi.unstubAllEnvs()})
afterAll(()=>vi.unstubAllGlobals())
function http(){const app=createApp({debug:false,onError:async(error,event)=>{setResponseStatus(event,error.statusCode || 500);await send(event,JSON.stringify({statusCode:error.statusCode,statusMessage:error.statusMessage}),'application/json')}}),router=createRouter();router.get('/api/weekly-content/connect/config',config);router.post('/api/weekly-content/connect/context',context);router.post('/api/weekly-content/connect/confirm',confirm);app.use(router);const web=toWebHandler(app);return async(path:string,body?:unknown,options:{origin?:string|null;contentType?:string;raw?:string}={})=>{const origin=options.origin===undefined?ORIGIN:options.origin,res=await web(new Request(ORIGIN+path,{method:body===undefined?'GET':'POST',headers:{'content-type':options.contentType || 'application/json',...(origin===null?{}:{origin})},...(body===undefined?{}:{body:options.raw ?? JSON.stringify(body)})}));const raw=await res.text();return {res,value:raw?JSON.parse(raw):null}}}
const PATH='/api/weekly-content/connect/context'
describe('LIFF production HTTP routes with in-process synthetic provider/database',()=>{
 it('returns minimal config and private headers without provider/storage construction',async()=>{const {res,value}=await http()('/api/weekly-content/connect/config');expect(value).toEqual({enabled:true,liffId:'2001234567-Abcd1234',origin:ORIGIN,connectPath:'/weekly-content/connect',scopes:['openid']});expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled();expect(res.headers.get('cache-control')).toContain('no-store');expect(res.headers.get('x-robots-tag')).toContain('noindex');expect(res.headers.get('referrer-policy')).toBe('no-referrer')})
 it.each(['false','TRUE',''])('disabled or malformed enable flag %s fails before provider/storage',async flag=>{vi.stubEnv('NUXT_WEEKLY_CONTENT_LIFF_ENABLED',flag);expect((await http()('/api/weekly-content/connect/config')).value).toEqual({enabled:false});expect((await http()(PATH,{idToken:TOKEN})).res.status).toBe(503);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it('missing channel fails closed before provider/storage',async()=>{vi.stubEnv('NUXT_WEEKLY_CONTENT_LINE_LOGIN_CHANNEL_ID','');expect((await http()(PATH,{idToken:TOKEN})).res.status).toBe(503);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it.each([null,'null','https://unrelated.taipei','https://synthetic-weekly.taipei.evil.taipei'])('rejects missing/foreign origin %s before identity lookup',async origin=>{expect((await http()(PATH,{idToken:TOKEN},{origin})).res.status).toBe(403);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it.each(['text/plain','application/x-www-form-urlencoded','application/jsonp'])('rejects non-JSON %s before identity lookup',async contentType=>{expect((await http()(PATH,{idToken:TOKEN},{contentType})).res.status).toBe(403);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it('bounds raw input at 12KiB and rejects malformed JSON before identity/storage',async()=>{const call=http();expect((await call(PATH,{idToken:TOKEN},{raw:JSON.stringify({idToken:TOKEN})+' '.repeat(12288)})).res.status).toBe(413);expect((await call(PATH,null,{raw:'{broken'})).res.status).toBe(422);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it.each([{ownerUserId:1},{clientId:1},{lineUserId:USER},{webhookEventId:'synthetic'}])('rejects browser authority %j before provider/storage',async fields=>{expect((await http()(PATH,{idToken:TOKEN,...fields})).res.status).toBe(422);expect(provider).not.toHaveBeenCalled();expect(seams.repository).not.toHaveBeenCalled()})
 it('displays exact company then actual core confirm, with no private identity/token returned',async()=>{const call=http(),preview=await call(PATH,{idToken:TOKEN,invitationToken});expect(preview.res.status).toBe(200);expect(f.state.binding).toBeNull();const result=await call('/api/weekly-content/connect/confirm',{idToken:TOKEN,invitationToken,confirmationToken:preview.value.confirmationToken,consent:true});expect(result.res.status).toBe(200);expect(result.value).toEqual({status:'bound',company:{displayName:f.state.client.displayName,canonicalSiteOrigin:f.state.client.canonicalSiteOrigin}});expect(f.state.binding?.lineUserId).toBe(USER);for(const privateValue of [TOKEN,USER,WEEKLY_KEY,invitationToken])expect(JSON.stringify(result.value)).not.toContain(privateValue);expect(result.res.headers.get('referrer-policy')).toBe('no-referrer');expect(f.state.consents).toHaveLength(0)})
 it('does not expose provider error prose, raw tokens or internal codes',async()=>{provider.mockResolvedValue(new Response('private-provider-secret',{status:400}));const result=await http()(PATH,{idToken:TOKEN});expect(result.res.status).toBe(401);expect(result.value.statusMessage).toBe('LINE 登入已失效，請重新登入。');expect(JSON.stringify(result.value)).not.toContain('private-provider-secret');expect(JSON.stringify(result.value)).not.toContain('LINE_IDENTITY_INVALID');expect(seams.repository).not.toHaveBeenCalled()})
 it('page loads only official SDK after configuration and keeps auth/invite out of browser persistence/redirects',()=>{const page=readFileSync(new URL('../pages/weekly-content/connect.vue',import.meta.url),'utf8');expect(page).toContain('https://static.line-scdn.net/liff/edge/2/sdk.js');expect(page).toContain('sdk.login({ redirectUri: `${config.origin}/weekly-content/connect` })');expect(page).toContain('sdk?.getIDToken()');expect(page).not.toMatch(/localStorage|sessionStorage|getProfile|getDecodedIDToken|console\./);expect(page.indexOf('if (!result.enabled)')).toBeLessThan(page.indexOf('sdk = await loadSdk()'));expect(page).toContain('consent: true');expect(page).toContain('confirmationToken: context.value.confirmationToken');expect(page).toContain('/brand/searchking-avatar-v1.png');expect(page).toContain('alt="搜尋王"');expect(page).toContain("window.history.replaceState(null, '', '/weekly-content/connect')")})
})
