<script setup lang="ts">
type Metric = { id: string, label: string, before: number, after: number, delta: number, explanation: string }
type Result = {
  original: { title: string, content: string, language: 'en' | 'zh-hant' }
  candidate: { provider: string, providerVersion: string, optimizedTitle: string, optimizedContent: string, appliedRuleIds: string[], safetyNotes: string[], provenance: { execution: 'official-autogeo-api' | 'autogeo-framework-bailian-qwen' | 'reference-fallback', upstreamRepository: string, upstreamRevision: string, rewriteMethod: string, ruleset: string, model: string, usage?: { inputTokens?: number, outputTokens?: number, totalTokens?: number }, fallbackReason?: string } }
  baseline: { totalScore: number }, optimized: { totalScore: number }, comparison: Metric[], summary: string, interpretationLimit: string
}
const form = reactive({ title: '', content: '', language: 'zh-hant' as 'en' | 'zh-hant' })
const state = ref<'idle' | 'running' | 'error' | 'ready'>('idle')
const errorMessage = ref('')
const result = ref<Result | null>(null)
const usesLiveProvider = computed(() => result.value?.candidate.provenance.execution !== 'reference-fallback')
const fallbackLabel = (reason?: string) => ({ 'bailian-not-configured': '尚未完成百煉 Qwen server-side 設定，且 Gemini provider 亦不可用', 'bailian-invalid-configuration': '百煉 endpoint 設定無效；系統未發出 provider request', 'bailian-provider-unavailable': '百鍊 Qwen provider 本次無法提供可用回應', 'provider-output-safety-rejected': 'provider 草稿含原文未支持的商業主張，已安全拒絕並改用 reference fallback', 'autogeo-not-configured': '尚未設定 server-side provider credential', 'autogeo-provider-unavailable': 'provider 本次無法提供可用回應' }[reason || 'bailian-not-configured'])
definePageMeta({ i18n: false, layout: 'owner' })
useHead({ title: '私有 GEO Workbench · DiscoveryStack', meta: [{ name: 'robots', content: 'noindex, nofollow, noarchive' }] })
async function runOptimization() {
  state.value = 'running'; errorMessage.value = ''; result.value = null
  try { result.value = await $fetch<Result>('/api/geo/optimise', { method: 'POST', body: form }); state.value = 'ready' }
  catch (error: unknown) { state.value = 'error'; const status = (error as { status?: number, statusCode?: number }).status ?? (error as { statusCode?: number }).statusCode; errorMessage.value = status === 401 ? '需要 owner 工作階段。請先從私有稽核實驗室登入。' : (error as { data?: { message?: string } }).data?.message || '目前無法完成比較。輸入未被儲存。' }
}
const deltaClass = (metric: Metric) => metric.delta > 0 ? 'metric-up' : metric.delta < 0 ? 'metric-down' : 'metric-flat'
</script>

<template>
  <main class="geo-workbench">
    <header class="geo-header"><NuxtLink class="back-link" to="/audit-lab">← 返回私有稽核實驗室</NuxtLink><p class="eyebrow">OWNER-ONLY · GEO WORKBENCH V1</p><h1>把內容改得<br><em>更清楚、可驗證。</em></h1><p>這是 owner-only 的無資料庫比較流程。完成百煉 Qwen server-side 設定後，會以完整 AutoGEO 官方 prompt／ruleset 執行；未設定或 provider 無法使用時，會明確標示為 reference fallback。原文只在本次 request 中處理，不會儲存或訓練模型。</p></header>
    <section class="geo-panel"><div><p class="eyebrow">INPUT</p><h2>貼入要人工審閱的原文</h2></div><form class="geo-form" @submit.prevent="runOptimization"><label>頁面標題<input v-model.trim="form.title" required maxlength="180" autocomplete="off"></label><label>語言<select v-model="form.language"><option value="zh-hant">繁體中文</option><option value="en">English</option></select></label><label class="wide">原文（不會寫入資料庫）<textarea v-model="form.content" required maxlength="12000" rows="12"></textarea></label><p class="wide">完整 AutoGEO 輸出與 reference fallback 都是人工審閱草稿；不會把 heuristic 分數說成外部搜尋排名，亦不得直接發布未驗證的數據、排名、流量或第三方背書。</p><button type="submit" :disabled="state === 'running'">{{ state === 'running' ? '正在產生可比較版本…' : '產生 GEO 比較版本' }}</button></form><p v-if="state === 'error'" class="error" role="alert">{{ errorMessage }}</p></section>
    <section v-if="result" class="result-stack" aria-live="polite"><div class="score-strip"><div><span>原文 heuristic</span><strong>{{ result.baseline.totalScore }}</strong></div><b>→</b><div><span>優化版 heuristic</span><strong>{{ result.optimized.totalScore }}</strong></div><p>同一組 deterministic heuristic 下的結構比較，不是第三方生成式搜尋成效。</p></div><aside class="provider-note" :class="usesLiveProvider ? 'provider-live' : 'provider-fallback'"><strong>本次改寫來源</strong><p v-if="usesLiveProvider">已使用完整 AutoGEO 官方 <code>{{ result.candidate.provenance.rewriteMethod }}</code> prompt／ruleset 產生草稿；這不是 AutoGEO Mini。</p><p v-else>完整 AutoGEO API 本次未執行（{{ fallbackLabel(result.candidate.provenance.fallbackReason) }}）。目前顯示的是 <code>reference-rules-v1</code> baseline，不是 AutoGEO 生成結果。</p><small>Upstream：{{ result.candidate.provenance.upstreamRepository }}@{{ result.candidate.provenance.upstreamRevision.slice(0,12) }}</small></aside><section class="comparison-grid"><article><p class="eyebrow">ORIGINAL</p><h2>{{ result.original.title }}</h2><pre>{{ result.original.content }}</pre></article><article><p class="eyebrow">RULE-GUIDED VERSION</p><h2>{{ result.candidate.optimizedTitle }}</h2><pre>{{ result.candidate.optimizedContent }}</pre></article></section><section class="geo-panel"><h2>可比較的結構訊號</h2><p class="wide">{{ result.summary }}</p><div class="metric-list wide"><div v-for="metric in result.comparison" :key="metric.id" class="metric-row"><div><strong>{{ metric.label }}</strong><small>{{ metric.explanation }}</small></div><div><span>{{ metric.before }}</span> → <span>{{ metric.after }}</span> <em :class="deltaClass(metric)">{{ metric.delta > 0 ? `+${metric.delta}` : metric.delta }}</em></div></div></div><aside class="wide limit-note"><strong>解讀限制</strong><p>{{ result.interpretationLimit }}</p></aside><aside class="wide safety-note"><strong>套用前人工檢查</strong><ul><li v-for="note in result.candidate.safetyNotes" :key="note">{{ note }}</li></ul></aside></section></section>
  </main>
</template>

<style scoped>
.geo-workbench{--ink:#12211d;--moss:#254b3f;--paper:#f8f6ef;--line:#cad3c9;max-width:1180px;margin:0 auto;padding:3.75rem 1.5rem 6rem;color:var(--ink)}.geo-header{max-width:780px;margin-bottom:3rem}.back-link{color:var(--moss);font-weight:700;text-decoration:none}.eyebrow{color:var(--moss);font-size:.72rem;font-weight:800;letter-spacing:.12em}h1{font-size:clamp(2.8rem,7vw,5.5rem);line-height:.9;letter-spacing:-.065em}h1 em{color:var(--moss);font-family:Georgia,serif;font-weight:400}.geo-panel{display:grid;grid-template-columns:1fr 180px;gap:1rem;margin-top:1.5rem;padding:1.75rem;border:1px solid var(--line);background:var(--paper)}.geo-form{display:grid;grid-column:1/-1;grid-template-columns:1fr 180px;gap:1rem}.wide{grid-column:1/-1}label{display:grid;gap:.45rem;font-size:.84rem;font-weight:700}input,select,textarea{width:100%;box-sizing:border-box;border:1px solid #afbcaf;border-radius:4px;background:#fff;color:var(--ink);font:inherit;padding:.75rem}textarea{resize:vertical;line-height:1.55}button{width:max-content;border:0;border-radius:3px;background:var(--moss);color:#fff;cursor:pointer;font:inherit;font-weight:800;padding:.78rem 1.1rem}button:disabled{cursor:wait;opacity:.65}.error{color:#9b2929;font-weight:700}.result-stack{margin-top:1.5rem}.score-strip{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:1rem;padding:1.25rem 1.5rem;background:var(--moss);color:#fff}.score-strip div{text-align:center}.score-strip span,.score-strip p{color:#d4e5d9}.score-strip strong{display:block;font-size:2.3rem}.score-strip p{grid-column:1/-1;margin:0;text-align:center}.provider-note{margin-top:1rem;padding:1rem;border-left:3px solid #5a6c60;background:#f3f4ef}.provider-live{border-color:#277647;background:#eef7ef}.provider-fallback{border-color:#a47521;background:#fff9eb}.comparison-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-top:1rem}.comparison-grid article{min-width:0;border:1px solid var(--line);padding:1.4rem;background:#f6f2e9}.comparison-grid article+article{background:#edf6ef}.comparison-grid pre{max-height:480px;overflow:auto;white-space:pre-wrap;font:inherit;line-height:1.65}.metric-list{border-top:1px solid var(--line)}.metric-row{display:flex;justify-content:space-between;gap:1rem;padding:1rem 0;border-bottom:1px solid var(--line)}.metric-row small{display:block;margin-top:.3rem}.metric-up{color:#17733d}.metric-down{color:#b33232}.metric-flat{color:#5a6c60}.limit-note,.safety-note{padding:1rem;background:#fffaf0;border-left:3px solid #b58a38}.safety-note{background:#eef5ef;border-color:#4b8660}@media(max-width:700px){.geo-workbench{padding:2.2rem 1rem 4rem}.geo-panel,.geo-form,.comparison-grid{grid-template-columns:1fr}.score-strip{padding:1rem}.metric-row{display:grid}}
</style>
