<script setup lang="ts">
definePageMeta({ layout: 'owner' })
useHead({ title: '改動追蹤｜DiscoveryStack', meta: [{ name: 'robots', content: 'noindex,nofollow,noarchive' }] })
type AnyRow = Record<string, any>
const { data, error, refresh } = await useFetch<any>('/api/interventions/list', { server: false })
const { data: queueData, error: queueError, refresh: refreshQueue } = await useFetch<any>('/api/interventions/refresh-queue?status=open', { server: false })
const { data: experimentData, error: experimentError, refresh: refreshExperiments } = await useFetch<any>('/api/interventions/experiments', { server: false })
const selected = ref<AnyRow | null>(null); const detail = ref<any>(null); const notice = ref(''); const actionError = ref(''); const saving = ref(false)
const statusFilter = ref('')
const form = reactive<any>({ targetUrl: '', changeSummary: '', interventionType: 'content_update', metric: 'clicks', direction: 'increase', impactNote: '', expectedSnippet: '', hypothesis: '', briefId: '', draftId: '', entryId: '', targetId: '', idempotencyKey: crypto.randomUUID() })
const manual = reactive<any>({ windowStart: '', windowEnd: '', clicks: 0, impressions: 0, sampleSize: 0, note: '' })
const queueForm = reactive<any>({ targetUrl: '', interventionId: '', note: '', severity: 'warning', dueAt: '' })
const policy = reactive<any>({ regressionDropPercent: 20, minimumSampleSize: 30, staleAfterDays: 90 })
const experiment = reactive<any>({ name: '', design: 'pre_post', hypothesis: '', primaryMetric: 'clicks', idempotencyKey: crypto.randomUUID() })
const statusLabel: Record<string, string> = { registered: '已登記', deployed: '已上線', recrawl_confirmed: 'Google 已重抓', measured: '已量測', assessed: '已評估', cancelled: '已取消' }
const recrawlLabel: Record<string, string> = { not_checked: '未檢查', unknown: '不知道', confirmed: '已確認' }
const signalLabel: Record<string, string> = { positive_signal: '正向訊號', negative_signal: '負向訊號', no_material_change: '無明顯改變', mixed_signal: '訊號混合', insufficient_data: '資料不足' }
const limitationLabel: Record<string, string> = { RECRAWL_NOT_CONFIRMED: '尚未確認 Google 重抓', sample_below_minimum: '樣本低於門檻', no_control_group: '沒有對照組', no_randomization: '未隨機分組', pre_post_not_experiment: '前後比較不是實驗', short_follow_up_window: '上線後追蹤不到 14 天', deployment_weak_evidence: '上線只有弱證據', recrawl_manual_confirmation: '重抓是手動確認的', mixed_measurement_origins: '成績混用了手動輸入與系統拉的', transition_rows_excluded: '過渡期的成績已排除', baseline_unknown: '上線前的基準不明', small_group: '每組不到 3 個頁面' }
const typeLabel: Record<string, string> = { content_update: '內容更新', new_page: '新頁面', structured_data: '結構化資料', internal_linking: '內部連結', technical: '技術調整', entity_claim: '實體主張', other: '其他' }
function errorStatus(error: any) { return error?.statusCode || error?.status || error?.response?.status || error?.data?.statusCode }
const isUnauthorized = computed(() => [error.value, queueError.value, experimentError.value].some(item => errorStatus(item) === 401 || errorStatus(item) === 403))
function requestFailureMessage(error: any) { const status = errorStatus(error); if (status === 401 || status === 403) return '登入已逾期，請重新登入。'; return error?.data?.statusMessage || error?.statusMessage || error?.message || '請求沒有完成。' }
async function post(path: string, body: any = {}) { saving.value = true; actionError.value = ''; try { const result = await $fetch<any>(path, { method: 'POST', headers: { 'content-type': 'application/json' }, body }); notice.value = '已完成。'; await Promise.all([refresh(), refreshQueue(), refreshExperiments()]); if (selected.value) await load(selected.value.id); return result } catch (error) { actionError.value = requestFailureMessage(error) } finally { saving.value = false } }
async function load(id: number) { try { detail.value = await $fetch(`/api/interventions/${id}`); selected.value = detail.value.intervention } catch (error) { actionError.value = requestFailureMessage(error) } }
async function register() { const expectedImpact = form.impactNote ? { metric: form.metric, direction: form.direction, note: form.impactNote } : { metric: form.metric, direction: form.direction }; const result = await post('/api/interventions/register', { targetUrl: form.targetUrl, changeSummary: form.changeSummary, interventionType: form.interventionType, expectedImpact, expectedSnippet: form.expectedSnippet || undefined, hypothesis: form.hypothesis || undefined, briefId: Number(form.briefId) || undefined, draftId: Number(form.draftId) || undefined, entryId: Number(form.entryId) || undefined, targetId: Number(form.targetId) || undefined, idempotencyKey: form.idempotencyKey }); if (result?.intervention) { form.idempotencyKey = crypto.randomUUID(); await load(result.intervention.id) } }
function deployment(id: number) { const note = window.prompt('請輸入手動確認上線的說明：'); if (note) return post(`/api/interventions/${id}/confirm-deployment`, { note }) }
function recrawl(id: number) { const note = window.prompt('請輸入手動確認 Google 已重抓的說明（必填）：'); if (!note) { actionError.value = '手動確認重抓必須填寫說明。'; return } return post(`/api/interventions/${id}/confirm-recrawl`, { note }) }
</script>

<template>
  <section class="page"><header><p class="eyebrow">PRIVATE / INTERVENTION LOOP</p><h1>改動追蹤</h1><p>逐筆記錄改動、確認上線與 Google 重抓，再以受限的前後比較留下可檢查的訊號。</p></header>
    <section v-if="isUnauthorized" class="card"><p class="error"><strong>需要重新登入</strong><br>登入已逾期，請重新登入。</p></section>
    <template v-else>
    <p v-if="notice" class="notice">{{ notice }}</p><p v-if="actionError" class="error">{{ actionError }}</p>
    <section class="card"><h2>登記新改動</h2><div class="grid"><label>頁面網址<input v-model="form.targetUrl" type="url"></label><label>改動摘要<input v-model="form.changeSummary"></label><label>改動類型<select v-model="form.interventionType"><option value="content_update">內容更新</option><option value="new_page">新頁面</option><option value="structured_data">結構化資料</option><option value="internal_linking">內部連結</option><option value="technical">技術調整</option><option value="entity_claim">實體主張</option><option value="other">其他</option></select></label><label>預期指標<select v-model="form.metric"><option value="clicks">點擊</option><option value="impressions">曝光</option><option value="ctr">CTR</option><option value="averagePosition">平均排名</option></select></label><label>方向<select v-model="form.direction"><option value="increase">增加</option><option value="decrease">降低</option></select></label><label>預期影響備註<input v-model="form.impactNote"></label><label>上線後應看得到的一段文字（提供強證據）<input v-model="form.expectedSnippet"></label><label>假設／說明<input v-model="form.hypothesis"></label><label>關聯 brief id<input v-model="form.briefId" type="number"></label><label>draft id<input v-model="form.draftId" type="number"></label><label>排程項目 id<input v-model="form.entryId" type="number"></label><label>target id<input v-model="form.targetId" type="number"></label></div><button :disabled="saving" @click="register">登記改動</button></section>
    <section class="card"><h2>改動清單</h2><label>狀態篩選<select v-model="statusFilter"><option value="">全部</option><option v-for="(_, value) in statusLabel" :key="value" :value="value">{{ statusLabel[value] }}</option></select></label><button @click="refresh">重新整理</button><table><thead><tr><th>id</th><th>網址</th><th>類型</th><th>狀態</th><th>上線證據</th><th>重抓</th><th>最近拉成績時間</th><th>操作</th></tr></thead><tbody><tr v-for="row in (data?.interventions || []).filter((item: AnyRow) => !statusFilter || item.status === statusFilter)" :key="row.id" @click="load(row.id)"><td>{{ row.id }}</td><td>{{ row.normalizedUrl }}</td><td>{{ typeLabel[row.interventionType] || row.interventionType }}</td><td>{{ statusLabel[row.status] }}</td><td>{{ row.deployEvidenceLevel === 'strong' ? '強證據' : row.deployEvidenceLevel === 'weak' ? '弱證據' : '—' }} {{ row.deployEvidenceSource || '' }}</td><td>{{ recrawlLabel[row.recrawlStatus] }} {{ row.recrawlSource || '' }}</td><td>{{ row.lastMetricsPullAt || '—' }}</td><td><button :disabled="saving || row.status !== 'registered'" title="僅已登記的改動可檢查上線" @click.stop="post(`/api/interventions/${row.id}/check-deployment`)">現在就檢查</button><button :disabled="saving || row.status !== 'registered'" @click.stop="deployment(row.id)">手動確認上線</button><button :disabled="saving || row.status !== 'deployed'" @click.stop="post(`/api/interventions/${row.id}/check-recrawl`)">問 Google 是否重抓</button><button :disabled="saving || row.status !== 'deployed'" @click.stop="recrawl(row.id)">手動確認重抓</button><button :disabled="saving" @click.stop="post(`/api/interventions/${row.id}/pull-metrics`)">拉成績</button><button :disabled="saving || row.recrawlStatus !== 'confirmed'" :title="row.recrawlStatus !== 'confirmed' ? '要先確認 Google 已重抓' : ''" @click.stop="post(`/api/interventions/${row.id}/measure`)">量測</button><button :disabled="saving || row.status !== 'measured'" @click.stop="post(`/api/interventions/${row.id}/assess`)">評估</button><button :disabled="saving || ['assessed','cancelled'].includes(row.status)" @click.stop="post(`/api/interventions/${row.id}/cancel`, { note: 'owner_cancelled' })">取消</button></td></tr></tbody></table>
      <div v-if="selected" class="inline"><h3>貼成績：#{{ selected.id }}</h3><label>起<input v-model="manual.windowStart" type="date"></label><label>迄<input v-model="manual.windowEnd" type="date"></label><label>點擊<input v-model.number="manual.clicks" type="number"></label><label>曝光<input v-model.number="manual.impressions" type="number"></label><label>樣本數<input v-model.number="manual.sampleSize" type="number"></label><label>備註<input v-model="manual.note"></label><button @click="post(`/api/interventions/${selected.id}/measurements`, { source: 'google_search_console', windowStart: manual.windowStart, windowEnd: manual.windowEnd, metrics: { clicks: manual.clicks, impressions: manual.impressions }, sampleSize: manual.sampleSize, note: manual.note || undefined })">貼成績</button></div>
    </section>
    <section v-if="detail" class="card"><h2>詳細資料 #{{ detail.intervention.id }}</h2><h3>事件紀錄</h3><ol><li v-for="event in detail.events" :key="event.id">{{ event.eventType }} → {{ event.toStatus || '維持狀態' }}｜{{ event.occurredAt }}｜{{ JSON.stringify(event.evidence) }}</li></ol><h3>成績列表</h3><ul><li v-for="measurement in detail.measurements" :key="measurement.id"><b>{{ measurement.origin === 'manual' ? '手動輸入' : '系統拉的' }}</b> {{ measurement.windowStart }} ～ {{ measurement.windowEnd }}：{{ measurement.metrics }}</li></ul><h3>評估結果</h3><article v-for="result in detail.results" :key="result.id" class="result"><p>n（前／後）：{{ result.sampleSizeBaseline }}／{{ result.sampleSizeFollowUp }}；判讀：{{ signalLabel[result.signal] || result.signal }}</p><p>限制：{{ result.limitations.map((x: string) => limitationLabel[x] || x).join('、') }}</p><blockquote>{{ result.causalStatement }}</blockquote></article></section>
    <section class="card"><h2>需要重新處理的頁面</h2><ul><li v-for="item in queueData?.items || []" :key="item.id">{{ item.severity }}｜{{ item.reasonRule }}｜{{ item.reasonText }}｜{{ item.recommendedAction }}｜{{ item.dueAt }} <button @click="post(`/api/interventions/refresh-queue/${item.id}/status`, { status: 'in_progress' })">處理中</button><button @click="post(`/api/interventions/refresh-queue/${item.id}/status`, { status: 'done' })">完成</button><button @click="post(`/api/interventions/refresh-queue/${item.id}/status`, { status: 'dismissed' })">略過</button></li></ul><div class="inline"><label>網址或改動 id<input v-model="queueForm.targetUrl"></label><label>改動 id<input v-model="queueForm.interventionId" type="number"></label><label>原因<input v-model="queueForm.note"></label><label>嚴重度<select v-model="queueForm.severity"><option>info</option><option>warning</option><option>critical</option></select></label><label>到期日<input v-model="queueForm.dueAt" type="datetime-local"></label><button @click="post('/api/interventions/refresh-queue', { ...queueForm, interventionId: Number(queueForm.interventionId) || undefined, targetUrl: queueForm.targetUrl || undefined, dueAt: queueForm.dueAt || undefined })">加入</button></div></section>
    <section class="card"><h2>規則設定</h2><p>退步門檻 %、最少樣本數、多久算過期（天）。</p><div class="inline"><label>退步門檻 %<input v-model.number="policy.regressionDropPercent" type="number"></label><label>最少樣本數<input v-model.number="policy.minimumSampleSize" type="number"></label><label>多久算過期（天）<input v-model.number="policy.staleAfterDays" type="number"></label><button @click="post('/api/interventions/refresh-policy', policy)">儲存規則</button></div></section>
    <section class="card"><h2>實驗</h2><div class="inline"><label>名稱<input v-model="experiment.name"></label><label>設計<select v-model="experiment.design"><option value="pre_post">前後比較</option><option value="grouped">分組</option></select></label><label>假設<input v-model="experiment.hypothesis"></label><label>主要指標<select v-model="experiment.primaryMetric"><option value="clicks">點擊</option><option value="impressions">曝光</option><option value="ctr">CTR</option><option value="averagePosition">平均排名</option></select></label><button @click="post('/api/interventions/experiments', experiment)">建立實驗</button></div><ul><li v-for="item in experimentData?.experiments || []" :key="item.id">#{{ item.id }} {{ item.name }}（{{ item.design === 'pre_post' ? '前後比較' : '分組' }}）<button @click="post(`/api/interventions/experiments/${item.id}/conclude`)">結束並計算</button></li></ul><p>附加改動：請由 API 使用改動 id 與組別 treatment（實驗組）或 control（對照組）。</p></section>
    <footer><a href="/api/interventions/export" target="_blank">匯出資料集（JSON）</a><button :disabled="saving" @click="post('/api/interventions/tick')">立刻跑一次排程</button></footer>
    </template>
  </section>
</template>
<style scoped>
.page{max-width:1280px;margin:auto;padding:2rem}.eyebrow{letter-spacing:.12em;color:#58708d;font-size:.75rem}.card{margin-top:1.25rem;padding:1.25rem;background:#fff;border:1px solid #dbe3ed;border-radius:.75rem;overflow:auto}.grid,.inline{display:flex;flex-wrap:wrap;gap:.75rem}.grid label,.inline label{display:grid;gap:.25rem;min-width:12rem;flex:1}input,select,button{font:inherit;padding:.45rem}button{cursor:pointer}button:disabled{cursor:not-allowed;opacity:.5}table{width:100%;border-collapse:collapse;margin-top:1rem}th,td{padding:.55rem;border-bottom:1px solid #e5ebf1;text-align:left;vertical-align:top}.notice{color:#17633a}.error{color:#aa2537}.result{border-left:4px solid #6d8eae;padding-left:1rem}blockquote{background:#edf3f8;padding:.75rem;margin:0}footer{display:flex;gap:1rem;margin:2rem 0}@media(max-width:760px){.page{padding:1rem}table{font-size:.8rem}}
</style>
