<script setup lang="ts">
definePageMeta({ layout: 'owner' })
useHead({ title: '知識基礎｜DiscoveryStack', meta: [{ name: 'robots', content: 'noindex,nofollow,noarchive' }] })

type Entity = { id: number, canonicalName: string, entityType: string, status: string, canonicalUri: string | null }
type Source = { id: number, title: string | null, canonicalUrl: string, sourceClass: string }
type Claim = { id: number, statement: string, claimType: string, status: string }
type Dispute = { id: number, claimAId: number, claimBId: number, status: string, detectionReason: string }
type MergeCandidate = { id: number, sourceEntityId: number, targetEntityId: number, matchMethod: string, status: string }
type Gap = { type: string, briefId?: number }
const tabs = ['實體', '來源', '主張', '矛盾待審', '合併待審', '設定與待補'] as const
const activeTab = ref<typeof tabs[number]>('實體')
const { data: entitiesData, error, pending, refresh: refreshEntities } = await useFetch<{ entities: Entity[] }>('/api/knowledge/entities', { server: false })
const { data: sourcesData, refresh: refreshSources } = await useFetch<{ sources: Source[] }>('/api/knowledge/sources', { server: false })
const { data: claimsData, refresh: refreshClaims } = await useFetch<{ claims: Claim[] }>('/api/knowledge/claims', { server: false })
const { data: disputesData, refresh: refreshDisputes } = await useFetch<{ disputes: Dispute[] }>('/api/knowledge/disputes?status=open', { server: false })
const { data: candidatesData, refresh: refreshCandidates } = await useFetch<{ mergeCandidates: MergeCandidate[] }>('/api/knowledge/merge-candidates?status=pending', { server: false })
const { data: gapsData, refresh: refreshGaps } = await useFetch<{ gaps: Gap[] }>('/api/knowledge/gaps', { server: false })
const entities = computed(() => entitiesData.value?.entities || [])
const sources = computed(() => sourcesData.value?.sources || [])
const claims = computed(() => claimsData.value?.claims || [])
const disputes = computed(() => disputesData.value?.disputes || [])
const candidates = computed(() => candidatesData.value?.mergeCandidates || [])
const gaps = computed(() => gapsData.value?.gaps || [])
const isUnauthorized = computed(() => (error.value as { statusCode?: number } | null)?.statusCode === 401)
const saving = ref(false)
const notice = ref('')
const actionError = ref('')
const entityDetail = ref<Record<string, unknown> | null>(null)
const structuredData = ref<Record<string, unknown> | null>(null)
const entityForm = reactive({ entityType: 'Organization', canonicalName: '', canonicalUri: '', summary: '' })
const aliasForm = reactive({ entityId: 0, alias: '', locale: '' })
const externalIdForm = reactive({ entityId: 0, idType: '', idValue: '' })
const linkForm = reactive({ briefId: 0, entityId: 0, role: 'author' })
const sourceForm = reactive({ canonicalUrl: '', title: '', sourceClass: 'official documentation', notes: '' })
const sourceVersionForm = reactive({ sourceId: 0, contentHash: '', retrievedAt: '', excerpt: '' })
const claimForm = reactive({ statement: '', claimType: 'product capabilities', entityIds: '' })
const evidenceForm = reactive({ claimId: 0, sourceVersionId: 0, relation: 'supports', locator: '', contentHash: '', reviewNotes: '' })
const transitionForm = reactive({ claimId: 0, toStatus: 'source_backed', reason: '' })
const disputeForm = reactive({ claimAId: 0, claimBId: 0, reason: '' })
const resolveForm = reactive({ disputeId: 0, resolution: 'both_stand', resolutionNote: '', retractClaimId: 0 })
const mergeForm = reactive({ sourceEntityId: 0, targetEntityId: 0, candidateId: 0, reason: '' })
const undoForm = reactive({ mergeEventId: 0, reason: '' })
const publisherForm = reactive({ organizationEntityId: 0 })
const previewForm = reactive({ briefId: 0, draftId: 0, siteOrigin: '' })
const entityTypes = ['Person', 'Organization', 'Brand', 'Product', 'Service', 'Concept', 'Topic', 'Location', 'Author', 'Research', 'Dataset', 'Claim', 'Source', 'Article', 'Question', 'Event', 'Statistic']
const claimTypes = ['statistics', 'pricing', 'laws and regulations', 'medical / financial / legal claims', 'product capabilities', 'research findings', 'competitive comparisons', 'first-party measurements', 'time-sensitive facts']
const show = (value: unknown) => JSON.stringify(value, null, 2)
const ownerReadFetch = $fetch as unknown as (path: string) => Promise<Record<string, unknown>>
async function refreshAll() { await Promise.all([refreshEntities(), refreshSources(), refreshClaims(), refreshDisputes(), refreshCandidates(), refreshGaps()]) }
async function request(path: string, body?: Record<string, unknown>, method: 'POST' | 'DELETE' = 'POST') { saving.value = true; notice.value = ''; actionError.value = ''; try { const result = await $fetch<Record<string, unknown>>(path, { method, ...(body === undefined ? {} : { body }) }); notice.value = '已寫入 owner-scoped 紀錄。'; await refreshAll(); return result } catch (caught) { actionError.value = caught instanceof Error ? caught.message : '操作失敗；沒有以假資料補足。'; return null } finally { saving.value = false } }
async function createEntity() { await request('/api/knowledge/entities', { entityType: entityForm.entityType, canonicalName: entityForm.canonicalName, ...(entityForm.canonicalUri ? { canonicalUri: entityForm.canonicalUri } : {}), ...(entityForm.summary ? { summary: entityForm.summary } : {}) }); entityForm.canonicalName = ''; entityForm.canonicalUri = ''; entityForm.summary = '' }
async function loadEntity(id: number) { entityDetail.value = await ownerReadFetch(`/api/knowledge/entities/${id}`) }
async function addAlias() { await request(`/api/knowledge/entities/${aliasForm.entityId}/aliases`, { alias: aliasForm.alias, ...(aliasForm.locale ? { locale: aliasForm.locale } : {}) }) }
async function addExternalId() { await request(`/api/knowledge/entities/${externalIdForm.entityId}/external-ids`, { idType: externalIdForm.idType, idValue: externalIdForm.idValue }) }
async function linkEntity() { await request('/api/knowledge/content-entity-links', { ...linkForm }) }
async function createSource() { await request('/api/knowledge/sources', { canonicalUrl: sourceForm.canonicalUrl, title: sourceForm.title, sourceClass: sourceForm.sourceClass, notes: sourceForm.notes }) }
async function addSourceVersion() { await request(`/api/knowledge/sources/${sourceVersionForm.sourceId}/versions`, { contentHash: sourceVersionForm.contentHash, retrievedAt: sourceVersionForm.retrievedAt, ...(sourceVersionForm.excerpt ? { excerpt: sourceVersionForm.excerpt } : {}) }) }
async function createClaim() { const entityIds = claimForm.entityIds.split(',').map(value => Number(value.trim())).filter(Number.isSafeInteger); await request('/api/knowledge/claims', { statement: claimForm.statement, claimType: claimForm.claimType, entityIds }) }
async function addEvidence() { await request(`/api/knowledge/claims/${evidenceForm.claimId}/evidence`, { sourceVersionId: evidenceForm.sourceVersionId, relation: evidenceForm.relation, locator: evidenceForm.locator, contentHash: evidenceForm.contentHash, ...(evidenceForm.reviewNotes ? { reviewNotes: evidenceForm.reviewNotes } : {}) }) }
async function transitionClaim() { await request(`/api/knowledge/claims/${transitionForm.claimId}/transition`, { toStatus: transitionForm.toStatus, reason: transitionForm.reason }) }
async function createDispute() { await request('/api/knowledge/disputes', { ...disputeForm }) }
async function resolveDispute() { await request(`/api/knowledge/disputes/${resolveForm.disputeId}/resolve`, { resolution: resolveForm.resolution, resolutionNote: resolveForm.resolutionNote, ...(resolveForm.retractClaimId > 0 ? { retractClaimId: resolveForm.retractClaimId } : {}) }) }
async function mergeEntities() { await request('/api/knowledge/merges', { sourceEntityId: mergeForm.sourceEntityId, targetEntityId: mergeForm.targetEntityId, reason: mergeForm.reason, ...(mergeForm.candidateId > 0 ? { candidateId: mergeForm.candidateId } : {}) }) }
async function undoMerge() { await request(`/api/knowledge/merges/${undoForm.mergeEventId}/undo`, { reason: undoForm.reason }) }
async function setPublisher() { await request('/api/knowledge/publisher-settings', { ...publisherForm }) }
async function composePreview() { const result = await request('/api/knowledge/structured-data-preview', { ...(previewForm.briefId > 0 ? { briefId: previewForm.briefId } : { draftId: previewForm.draftId }), siteOrigin: previewForm.siteOrigin }); structuredData.value = result }
</script>

<template>
  <main class="knowledge-page">
    <section class="hero"><div><NuxtLink to="/audit-lab" class="back-link">← 返回私有稽核實驗室</NuxtLink><p class="eyebrow">OWNER-ONLY · KNOWLEDGE FOUNDATION</p><h1>可追溯的<br><em>知識紀錄。</em></h1><p>手動登錄來源與版本；矛盾只會進入人工裁決，合併保留原始紀錄與轉指。沒有資料時保持空白，不推測。</p></div><button type="button" :disabled="saving" @click="refreshAll">重新載入</button></section>
    <section v-if="pending" class="state-card"><strong>Loading</strong><span>正在讀取 owner-scoped knowledge workspace。</span></section>
    <section v-else-if="isUnauthorized" class="state-card blocked"><strong>Unauthorized · owner-only</strong><span>這個工作台僅接受既有 owner session。</span></section>
    <section v-else-if="error" class="state-card error"><strong>Unavailable</strong><span>{{ error.message || '知識資料庫尚不可用。' }}</span><small>會 fail closed，不會用示範資料替代。</small></section>
    <template v-else>
      <div class="tabs"><button v-for="tab in tabs" :key="tab" :class="{ active: activeTab === tab }" type="button" @click="activeTab = tab">{{ tab }}</button></div>
      <p v-if="notice" class="notice">{{ notice }}</p><p v-if="actionError" class="error-note">{{ actionError }}</p>
      <section v-if="activeTab === '實體'" class="grid"><article class="panel"><h2>建立實體</h2><form @submit.prevent="createEntity"><label>類型<select v-model="entityForm.entityType"><option v-for="type in entityTypes" :key="type">{{ type }}</option></select></label><label>名稱<input v-model.trim="entityForm.canonicalName" required maxlength="255"></label><label>Canonical URI（選填）<input v-model.trim="entityForm.canonicalUri" type="url"></label><label>摘要（選填）<textarea v-model.trim="entityForm.summary" rows="3"></textarea></label><button :disabled="saving">建立並檢查候選合併</button></form></article><article class="panel"><h2>實體列表／明細</h2><p v-if="!entities.length" class="empty">尚無實體。</p><ul v-else><li v-for="entity in entities" :key="entity.id"><button type="button" class="text-button" @click="loadEntity(entity.id)">#{{ entity.id }} {{ entity.canonicalName }}</button><small>{{ entity.entityType }} · {{ entity.status }}</small></li></ul><pre v-if="entityDetail">{{ show(entityDetail) }}</pre></article><article class="panel"><h2>別名、外部 ID、內容連結</h2><form @submit.prevent="addAlias"><label>Entity ID<input v-model.number="aliasForm.entityId" type="number" min="1" required></label><label>別名<input v-model.trim="aliasForm.alias" required></label><label>Locale<input v-model.trim="aliasForm.locale"></label><button :disabled="saving">新增別名</button></form><form @submit.prevent="addExternalId"><label>Entity ID<input v-model.number="externalIdForm.entityId" type="number" min="1" required></label><label>ID 類型<input v-model.trim="externalIdForm.idType" required></label><label>ID 值<input v-model.trim="externalIdForm.idValue" required></label><button :disabled="saving">新增外部 ID</button></form><form @submit.prevent="linkEntity"><label>Brief ID<input v-model.number="linkForm.briefId" type="number" min="1" required></label><label>Entity ID<input v-model.number="linkForm.entityId" type="number" min="1" required></label><label>角色<select v-model="linkForm.role"><option>author</option><option>about</option><option>mentions</option></select></label><button :disabled="saving">連結內容實體</button></form></article></section>
      <section v-else-if="activeTab === '來源'" class="grid"><article class="panel"><h2>手動登錄來源</h2><form @submit.prevent="createSource"><label>HTTPS URL<input v-model.trim="sourceForm.canonicalUrl" type="url" required></label><label>標題<input v-model.trim="sourceForm.title"></label><label>來源類別<select v-model="sourceForm.sourceClass"><option>official documentation</option><option>government</option><option>academic / peer-reviewed</option><option>primary research</option><option>first-party company data</option><option>major publication</option><option>secondary media</option><option>expert publication</option><option>blog</option><option>forum</option><option>social</option><option>unknown</option></select></label><label>備註<textarea v-model.trim="sourceForm.notes" rows="2"></textarea></label><button :disabled="saving">登錄來源</button></form></article><article class="panel"><h2>加入固定版本</h2><form @submit.prevent="addSourceVersion"><label>Source ID<input v-model.number="sourceVersionForm.sourceId" type="number" min="1" required></label><label>SHA-256<input v-model.trim="sourceVersionForm.contentHash" required pattern="[a-f0-9]{64}"></label><label>擷取時間<input v-model="sourceVersionForm.retrievedAt" type="datetime-local" required></label><label>摘要<textarea v-model.trim="sourceVersionForm.excerpt" rows="3"></textarea></label><button :disabled="saving">新增版本</button></form></article><article class="panel"><h2>已登錄來源</h2><p v-if="!sources.length" class="empty">尚無手動來源。</p><ul v-else><li v-for="source in sources" :key="source.id">#{{ source.id }} {{ source.title || source.canonicalUrl }}<small>{{ source.sourceClass }}</small></li></ul></article></section>
      <section v-else-if="activeTab === '主張'" class="grid"><article class="panel"><h2>建立主張</h2><form @submit.prevent="createClaim"><label>陳述<textarea v-model.trim="claimForm.statement" rows="3" required></textarea></label><label>類型<select v-model="claimForm.claimType"><option v-for="type in claimTypes" :key="type">{{ type }}</option></select></label><label>實體 IDs（逗號分隔）<input v-model.trim="claimForm.entityIds" required placeholder="1, 2"></label><button :disabled="saving">建立未驗證主張</button></form></article><article class="panel"><h2>加入證據／狀態轉換</h2><form @submit.prevent="addEvidence"><label>Claim ID<input v-model.number="evidenceForm.claimId" type="number" min="1" required></label><label>Source version ID<input v-model.number="evidenceForm.sourceVersionId" type="number" min="1" required></label><label>關係<select v-model="evidenceForm.relation"><option>supports</option><option>contradicts</option><option>contextualizes</option><option>supersedes</option></select></label><label>Locator<input v-model.trim="evidenceForm.locator" required></label><label>SHA-256<input v-model.trim="evidenceForm.contentHash" required pattern="[a-f0-9]{64}"></label><button :disabled="saving">新增證據</button></form><form @submit.prevent="transitionClaim"><label>Claim ID<input v-model.number="transitionForm.claimId" type="number" min="1" required></label><label>狀態<select v-model="transitionForm.toStatus"><option>source_backed</option><option>independently_confirmed</option><option>first_party_measured</option><option>expired</option><option>unverified</option><option>retracted</option></select></label><label>理由<input v-model.trim="transitionForm.reason" required></label><button :disabled="saving">人工轉換</button></form></article><article class="panel"><h2>主張列表</h2><p v-if="!claims.length" class="empty">尚無主張。</p><ul v-else><li v-for="claim in claims" :key="claim.id">#{{ claim.id }} {{ claim.statement }}<small>{{ claim.claimType }} · {{ claim.status }}</small></li></ul></article></section>
      <section v-else-if="activeTab === '矛盾待審'" class="grid"><article class="panel"><h2>人工建立矛盾</h2><form @submit.prevent="createDispute"><label>Claim A<input v-model.number="disputeForm.claimAId" type="number" min="1" required></label><label>Claim B<input v-model.number="disputeForm.claimBId" type="number" min="1" required></label><label>原因<textarea v-model.trim="disputeForm.reason" required rows="3"></textarea></label><button :disabled="saving">建立待審矛盾</button></form></article><article class="panel"><h2>人工裁決</h2><form @submit.prevent="resolveDispute"><label>Dispute ID<input v-model.number="resolveForm.disputeId" type="number" min="1" required></label><label>決定<select v-model="resolveForm.resolution"><option>kept_a</option><option>kept_b</option><option>both_stand</option><option>other</option></select></label><label>裁決說明<textarea v-model.trim="resolveForm.resolutionNote" required rows="3"></textarea></label><label>撤回 Claim（選填）<input v-model.number="resolveForm.retractClaimId" type="number" min="0"></label><button :disabled="saving">寫入裁決</button></form></article><article class="panel"><h2>開放矛盾</h2><p v-if="!disputes.length" class="empty">沒有待人工裁決的矛盾。</p><ul v-else><li v-for="dispute in disputes" :key="dispute.id">#{{ dispute.id }} Claim {{ dispute.claimAId }} ↔ {{ dispute.claimBId }}<small>{{ dispute.detectionReason }}</small></li></ul></article></section>
      <section v-else-if="activeTab === '合併待審'" class="grid"><article class="panel"><h2>候選合併</h2><p v-if="!candidates.length" class="empty">沒有待審合併候選。</p><ul v-else><li v-for="candidate in candidates" :key="candidate.id">#{{ candidate.id }} {{ candidate.sourceEntityId }} → {{ candidate.targetEntityId }}<small>{{ candidate.matchMethod }}</small></li></ul></article><article class="panel"><h2>合併（保留原紀錄與轉指）</h2><form @submit.prevent="mergeEntities"><label>來源 Entity<input v-model.number="mergeForm.sourceEntityId" type="number" min="1" required></label><label>目標 Entity<input v-model.number="mergeForm.targetEntityId" type="number" min="1" required></label><label>Candidate ID（選填）<input v-model.number="mergeForm.candidateId" type="number" min="0"></label><label>理由<textarea v-model.trim="mergeForm.reason" required rows="3"></textarea></label><button :disabled="saving">確認合併</button></form></article><article class="panel"><h2>一鍵還原最後合併</h2><form @submit.prevent="undoMerge"><label>Merge event ID<input v-model.number="undoForm.mergeEventId" type="number" min="1" required></label><label>還原理由<textarea v-model.trim="undoForm.reason" required rows="3"></textarea></label><button :disabled="saving">還原合併</button></form></article></section>
      <section v-else class="grid"><article class="panel"><h2>主要公司實體</h2><form @submit.prevent="setPublisher"><label>Organization / Brand Entity ID<input v-model.number="publisherForm.organizationEntityId" type="number" min="1" required></label><button :disabled="saving">指定 Publisher</button></form></article><article class="panel"><h2>待補清單</h2><p v-if="!gaps.length" class="empty">目前沒有可判定的待補項目。</p><ul v-else><li v-for="(gap, index) in gaps" :key="index">{{ gap.type }}<small v-if="gap.briefId">brief #{{ gap.briefId }}</small></li></ul></article><article class="panel"><h2>JSON-LD 預覽</h2><form @submit.prevent="composePreview"><label>Brief ID（或 Draft ID）<input v-model.number="previewForm.briefId" type="number" min="0" placeholder="Brief ID"></label><label>Draft ID<input v-model.number="previewForm.draftId" type="number" min="0" placeholder="僅當未填 Brief"></label><label>可信 HTTPS origin<input v-model.trim="previewForm.siteOrigin" type="url" required placeholder="https://example.com"></label><button :disabled="saving">組成預覽</button></form><pre v-if="structuredData">{{ show(structuredData) }}</pre><p v-else class="empty">尚未組成；不會臆造公司、作者或 canonical origin。</p></article></section>
    </template>
  </main>
</template>

<style scoped>
.knowledge-page{max-width:1240px;margin:0 auto;padding:2rem 1.25rem 4rem;color:#172033}.hero{display:flex;justify-content:space-between;gap:2rem;align-items:start;padding:2rem;border-radius:20px;background:linear-gradient(130deg,#f4f8ff,#f8fafc)}.hero h1{font-size:clamp(2.2rem,5vw,4rem);line-height:1;margin:.35rem 0}.hero em{color:#2254aa}.hero p{max-width:720px;line-height:1.7}.eyebrow{font-size:.75rem;font-weight:800;letter-spacing:.1em;color:#52627a}.back-link{color:#2254aa}.tabs{display:flex;flex-wrap:wrap;gap:.5rem;margin:1.5rem 0}.tabs button,.hero button,button{border:0;border-radius:8px;padding:.62rem .85rem;background:#213f7a;color:#fff;font:inherit;cursor:pointer}.tabs button{background:#e8edf6;color:#26354f}.tabs button.active{background:#213f7a;color:#fff}button:disabled{opacity:.55;cursor:not-allowed}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1rem}.panel,.state-card{padding:1.2rem;border:1px solid #dbe3ef;border-radius:14px;background:#fff}.panel h2{margin-top:0;font-size:1.1rem}.state-card{display:grid;gap:.3rem;margin-top:1.2rem}.blocked{border-color:#c98a20}.error,.error-note{color:#9e2634}.notice{color:#146b48;font-weight:700}form{display:grid;gap:.65rem;margin-bottom:1rem}label{display:grid;gap:.25rem;font-size:.88rem;font-weight:700}input,select,textarea{box-sizing:border-box;width:100%;padding:.55rem;border:1px solid #b9c5d7;border-radius:7px;font:inherit;font-weight:400}ul{padding-left:1.1rem;display:grid;gap:.65rem}li{display:grid;gap:.15rem}small{color:#5a6880}.text-button{padding:0;background:none;color:#2254aa;text-align:left;font-weight:700}.empty{color:#65738a}pre{max-height:320px;overflow:auto;padding:.8rem;border-radius:8px;background:#111b2f;color:#e6edf8;font-size:.75rem;white-space:pre-wrap}@media (max-width:640px){.hero{display:grid;padding:1.25rem}.knowledge-page{padding:1rem}}
</style>
