<script setup lang="ts">
// This page owns explicit response DTOs; the runtime remains Nuxt's same-origin fetch.
const fetchWeekly=$fetch as <T=unknown>(path:string,options?:{method?:'GET'|'POST';body?:Record<string,unknown>})=>Promise<T>
definePageMeta({i18n:false,layout:'owner'})
useHead({title:'客戶 LINE 與文章服務｜搜尋王'})
type Client={id:number;displayName:string;canonicalSiteOrigin:string;status:string;lineBound:boolean;requiresCustomerApproval:boolean}
type Config={clientId:number;status:string;lineBound:boolean;reviewTtlHours:number;publicationTargetId:number}
type Policy={policyId:string;clientId:number;publicationTargetId:number;status:string;expiresAt:string;policyVersion:string}
type Request={requestId:string;clientId:number;entryId:number;status:string;expiresAt:string;notificationStatus:string|null;notificationError:string|null;publicationStatus?:string|null;title?:string|null}
type Workspace={readiness:{enabled:boolean;lineConfigured:boolean;schedulerEnabled:boolean};clients:Client[];configs:Config[];requests:Request[];policies:Policy[];plans:Array<{id:number;title:string;status:string}>;calendars:Array<{id:number;clientId:number;status:string;hasPendingArticle:boolean}>}
const empty:Workspace={readiness:{enabled:false,lineConfigured:false,schedulerEnabled:false},clients:[],configs:[],requests:[],policies:[],plans:[],calendars:[]}
const {data,pending,error,refresh}=await useAsyncData('weekly-content-workspace',()=>fetchWeekly<Workspace>('/api/weekly-content/workspace'),{default:()=>empty,server:false})
const workspace=computed(()=>data.value || empty)
const selected=ref('');const policyId=ref('');const planId=ref('');const startDate=ref(new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()))
const publishLocalTime=ref('10:00');const monthlyArticleLimit=ref(4);const busy=ref(false);const notice=ref('');const failed=ref(false)
type Invitation={purpose:'identity_binding';invitationToken:string;expiresAt:string;connectUrl:string}
const invitation=ref<Invitation|null>(null)
const replacementOpen=ref(false);const replacementConfirmed=ref(false)
type ReviewTest={requestId:string;title:string;status:'pending'|'approved'|'changes_requested'|'revoked';notificationStatus:'queued'|'processing'|'sent'|'retry_wait'|'failed'|'cancelled'|null;expiresAt:string;createdAt:string}
type ReviewTestAttempt={idempotencyKey:string;requestId:string|null;state:'idle'|'uncertain'|'retryable'|'submitted';reloadedAfterUncertain:boolean}
const reviewTestTitle=ref('');const reviewTestBody=ref('');const reviewTestConfirmed=ref(false);const reviewTestBusy=ref(false);const reviewTestLoading=ref(false);const reviewTestsLoaded=ref(false);const reviewTestNotice=ref('');const reviewTestFailed=ref(false);const reviewTests=ref<ReviewTest[]>([])
const reviewTestSendState=ref<ReviewTestAttempt['state']>('idle');const reviewTestReloadedAfterUncertain=ref(false);const reviewTestAttempts=new Map<string,ReviewTestAttempt>();let reviewTestLoadVersion=0
const current=computed(()=>workspace.value.clients.find(c=>String(c.id)===selected.value))
const config=computed(()=>workspace.value.configs.find(c=>String(c.clientId)===selected.value))
const policies=computed(()=>workspace.value.policies.filter(p=>String(p.clientId)===selected.value && p.status==='enabled' && p.policyVersion==='governed-autopilot-policy-v4' && Date.parse(p.expiresAt)>Date.now()))
const hasCalendar=computed(()=>workspace.value.calendars.some(c=>String(c.clientId)===selected.value && c.hasPendingArticle))
const reviewTestPayload=()=>({title:reviewTestTitle.value.trim(),body:reviewTestBody.value.trim()})
const reviewTestPayloadSignature=()=>JSON.stringify([reviewTestPayload().title,reviewTestPayload().body])
function resetReviewTestState(){reviewTestLoadVersion+=1;reviewTestTitle.value='';reviewTestBody.value='';reviewTestConfirmed.value=false;reviewTestLoading.value=false;reviewTestsLoaded.value=false;reviewTestNotice.value='';reviewTestFailed.value=false;reviewTests.value=[];reviewTestSendState.value='idle';reviewTestReloadedAfterUncertain.value=false;reviewTestAttempts.clear()}
watch([reviewTestTitle,reviewTestBody],()=>{reviewTestConfirmed.value=false;const attempt=reviewTestAttempts.get(reviewTestPayloadSignature());reviewTestSendState.value=attempt?.state || 'idle';reviewTestReloadedAfterUncertain.value=attempt?.reloadedAfterUncertain || false;reviewTestNotice.value='';reviewTestFailed.value=false})
watch(selected,()=>{policyId.value='';planId.value='';invitation.value=null;replacementOpen.value=false;replacementConfirmed.value=false;notice.value='';resetReviewTestState();if(selected.value)void loadReviewTests()})
const name=(id:number)=>workspace.value.clients.find(c=>c.id===id)?.displayName || '客戶'
const time=(iso:string)=>new Date(iso).toLocaleString('zh-TW',{timeZone:'Asia/Taipei'})
const requestStatus=(r:Request)=>r.publicationStatus==='awaiting_site_review'?'網站已收稿；發布結果請至內容工作台核驗':['delivered','completed'].includes(r.publicationStatus || '')?'已發佈':r.status==='changes_requested'?'客戶要求修改':r.status==='revoked'?'送審已取消':Date.parse(r.expiresAt)<=Date.now()?'送審已過期':r.status==='approved'?'已同意，等待發佈':'等待客戶確認'
const deliveryStatus=(r:Request)=>r.notificationStatus==='sent'?'LINE 已接受通知':r.notificationStatus==='failed'?'LINE 通知失敗':r.notificationStatus==='cancelled'?'通知已取消':'等待傳送'
async function act(action:()=>Promise<unknown>,message:string,failureMessage='這一步尚未完成。請檢查客戶的發文規則、網站設定與系統連線後再試。'){busy.value=true;failed.value=false;notice.value='';try{await action();notice.value=message;await refresh()}catch{failed.value=true;notice.value=failureMessage}finally{busy.value=false}}
async function addDo(){await act(async()=>{await fetchWeekly('/api/weekly-content/do-alignment',{method:'POST',body:{}})},'Do Alignment 已加入，可先核對網站並綁定 LINE。每週文章仍需另外核准設定。')}
const activationKeys=new Map<string,string>()
async function requireApproval(){if(!current.value)return;await act(()=>fetchWeekly(`/api/weekly-content/clients/${current.value!.id}/require-approval`,{method:'POST',body:{consent:true}}),'已設定這位客戶每篇文章都要本人同意。接著可設定每週寫作與發文規則。')}
async function activate(){const p=policies.value.find(p=>p.policyId===policyId.value);if(!p||!current.value)return;const key=`${current.value.id}:${p.policyId}`;let idempotencyKey=activationKeys.get(key);if(!idempotencyKey){idempotencyKey=crypto.randomUUID();activationKeys.set(key,idempotencyKey)}await act(()=>fetchWeekly(`/api/weekly-content/clients/${current.value!.id}/activate`,{method:'POST',body:{publicationTargetId:p.publicationTargetId,policyId:p.policyId,reviewTtlHours:72,idempotencyKey}}),'每週文章送審已設定。寄稿仍需有效 LINE 綁定、核准選題與文章預算。')}
async function invite(){if(!current.value||current.value.status!=='active'||current.value.lineBound||invitation.value)return;await act(async()=>{invitation.value=await fetchWeekly<Invitation>(`/api/weekly-content/clients/${current.value!.id}/invitation`,{method:'POST',body:{}})},'請把下方入口與一次性邀請碼私下交給這位客戶。這一步只綁定身分。','這一步尚未完成。請確認客戶仍有效，並檢查 LINE 連線與邀請設定後再試。')}
function openReplacement(){if(!current.value||current.value.status!=='active'||!current.value.lineBound||invitation.value||reviewTestBusy.value)return;replacementConfirmed.value=false;replacementOpen.value=true}
function cancelReplacement(){replacementOpen.value=false;replacementConfirmed.value=false}
async function replaceLineRecipient(){if(!current.value||current.value.status!=='active'||!current.value.lineBound||!replacementConfirmed.value||invitation.value||reviewTestBusy.value)return;let replacementReturned=false;await act(async()=>{invitation.value=await fetchWeekly<Invitation>(`/api/weekly-content/clients/${current.value!.id}/replace-line-binding`,{method:'POST',body:{confirmation:'REPLACE_LINE_RECIPIENT'}});replacementReturned=true;replacementOpen.value=false;replacementConfirmed.value=false;resetReviewTestState()},'舊 LINE 的公司存取權已撤銷，所有舊邀請碼已失效。請立即把下方新邀請碼私下交給新的收件人；文章服務、排程與發佈狀態沒有改變。','目前無法確認 LINE 收件人是否已完成更換。請先按「更新進度」重新讀取狀態；若顯示尚未綁定，再產生一組新的邀請，且不要沿用舊邀請碼。文章服務、排程與發佈狀態不受影響。');if(!replacementReturned){replacementOpen.value=false;replacementConfirmed.value=false}}
const reviewTestDecisionStatus=(test:ReviewTest)=>test.status==='approved'?'客戶已同意測試稿':test.status==='changes_requested'?'客戶要求修改':test.status==='revoked'?'送審已取消':Date.parse(test.expiresAt)<=Date.now()?'已過期':'等待回覆'
const reviewTestNotificationStatus=(test:ReviewTest)=>test.notificationStatus==='sent'?'LINE 已接受通知':test.notificationStatus==='processing'?'正在嘗試 LINE 傳送':test.notificationStatus==='retry_wait'?'LINE 尚未接受通知，可安全重試':test.notificationStatus==='failed'?'LINE 通知失敗':test.notificationStatus==='cancelled'?'LINE 通知已取消':'等待 LINE 傳送'
async function loadReviewTests(){const client=current.value;if(!client?.lineBound){reviewTests.value=[];reviewTestsLoaded.value=false;return}const version=++reviewTestLoadVersion;reviewTestLoading.value=true;reviewTestFailed.value=false;try{const result=await fetchWeekly<{tests:ReviewTest[]}>(`/api/weekly-content/clients/${client.id}/review-tests`);if(version!==reviewTestLoadVersion||current.value?.id!==client.id)return;reviewTests.value=result.tests;reviewTestsLoaded.value=true;const attempt=reviewTestAttempts.get(reviewTestPayloadSignature()),known=attempt?.requestId?result.tests.find(test=>test.requestId===attempt.requestId):null;if(attempt&&known){attempt.state=known.status==='pending'&&Date.parse(known.expiresAt)>Date.now()&&known.notificationStatus==='retry_wait'?'retryable':'submitted';attempt.reloadedAfterUncertain=false;reviewTestSendState.value=attempt.state;reviewTestReloadedAfterUncertain.value=false;reviewTestNotice.value=attempt.state==='retryable'?'測試稿仍等待 LINE 接受通知；可使用同一識別碼安全重試。':'測試送審進度已更新。'}else if(attempt?.state==='uncertain'){attempt.reloadedAfterUncertain=true;reviewTestReloadedAfterUncertain.value=true;reviewTestNotice.value='已重新讀取測試進度。若剛才的結果仍不明，可用同一識別碼安全重試；系統會在伺服器端核對同一份內容，避免建立重複請求。'}else{reviewTestNotice.value='測試送審進度已更新。'}}catch{if(version!==reviewTestLoadVersion||current.value?.id!==client.id)return;reviewTestsLoaded.value=false;reviewTestFailed.value=true;reviewTestNotice.value='目前無法更新測試進度。請稍後再試；在狀態確認前不要重複傳送。'}finally{if(version===reviewTestLoadVersion)reviewTestLoading.value=false}}
async function sendReviewTest(){const client=current.value,payload=reviewTestPayload(),signature=reviewTestPayloadSignature();if(!client||client.status!=='active'||!client.lineBound||!reviewTestConfirmed.value||!payload.title||payload.title.length>160||!payload.body||payload.body.length>12000||reviewTestBusy.value||busy.value)return;const existing=reviewTestAttempts.get(signature);const state=existing?.state || 'idle';if(state==='idle'&&!reviewTestsLoaded.value)return;if(!['idle','retryable'].includes(state) && !(state==='uncertain'&&existing?.reloadedAfterUncertain))return;const attempt:ReviewTestAttempt=existing || {idempotencyKey:crypto.randomUUID(),requestId:null,state:'idle',reloadedAfterUncertain:false};reviewTestAttempts.set(signature,attempt);reviewTestBusy.value=true;reviewTestFailed.value=false;reviewTestNotice.value='';try{const result=await fetchWeekly<{test:ReviewTest;replayed:boolean}>(`/api/weekly-content/clients/${client.id}/review-test`,{method:'POST',body:{...payload,idempotencyKey:attempt.idempotencyKey,confirmation:'SEND_REVIEW_TEST'}});if(current.value?.id!==client.id)return;reviewTests.value=[result.test,...reviewTests.value.filter(test=>test.requestId!==result.test.requestId)];reviewTestsLoaded.value=true;attempt.requestId=result.test.requestId;attempt.state=result.test.notificationStatus==='retry_wait'?'retryable':'submitted';attempt.reloadedAfterUncertain=false;reviewTestSendState.value=attempt.state;reviewTestReloadedAfterUncertain.value=false;reviewTestConfirmed.value=false;reviewTestNotice.value=result.test.notificationStatus==='sent'?'LINE 已接受這次通知請求；這不代表客戶已收到或已閱讀。請在下方等待客戶回覆。':attempt.state==='retryable'?'測試送審已建立，但 LINE 尚未接受通知。確認狀態後，可使用同一識別碼安全重試。':result.test.notificationStatus==='failed'?'測試送審已建立，但 LINE 通知已失敗，不能在這裡重試。請更新進度，不要重複建立另一筆。':'測試送審已建立，系統正在嘗試交給 LINE。請更新進度，不要重複建立另一筆。'}catch{if(current.value?.id!==client.id)return;attempt.state='uncertain';attempt.reloadedAfterUncertain=false;reviewTestSendState.value='uncertain';reviewTestReloadedAfterUncertain.value=false;reviewTestConfirmed.value=false;reviewTestFailed.value=true;reviewTestNotice.value='傳送結果目前無法確認。識別碼已保留；請先更新測試進度，再決定是否用同一識別碼安全重試，不要直接重複傳送。'}finally{reviewTestBusy.value=false}}
async function createCalendar(){if(!current.value||!planId.value)return;await act(()=>fetchWeekly(`/api/weekly-content/clients/${current.value!.id}/calendar`,{method:'POST',body:{productionPlanId:Number(planId.value),startDate:startDate.value,publishLocalTime:publishLocalTime.value,monthlyArticleLimit:monthlyArticleLimit.value}}),'每週寄稿時間已排好。系統會依序使用這份計畫中核准的選題。')}
const reopenKeys=new Map<string,string>()
const canReopen=(r:Request)=>!['delivered','completed','publishing','awaiting_site_review'].includes(r.publicationStatus || '') && ['pending','approved'].includes(r.status) && (Date.parse(r.expiresAt)<=Date.now() || (r.status==='pending' && ['failed','cancelled'].includes(r.notificationStatus || '')))
async function reopen(r:Request){let idempotencyKey=reopenKeys.get(r.requestId);if(!idempotencyKey){idempotencyKey=crypto.randomUUID();reopenKeys.set(r.requestId,idempotencyKey)}await act(()=>fetchWeekly(`/api/weekly-content/entries/${r.entryId}/reopen`,{method:'POST',body:{clientId:r.clientId,idempotencyKey}}),'同一篇文章已重新送審。客戶需要在新的通知再次確認。')}
async function pause(){if(!current.value)return;await act(()=>fetchWeekly(`/api/weekly-content/clients/${current.value!.id}/pause`,{method:'POST',body:{status:'paused'}}),'這位客戶的每週送審與發文已暫停。')}
</script>
<template>
  <div class="weekly-page">
    <header><p class="brand">搜尋王 · 客戶內容服務</p><h1>客戶 LINE 與文章服務</h1><p>先核對公司與網站、連結客戶 LINE。每週文章服務需要另外設定與核准；每篇文章仍要客戶同意才會發佈。</p></header>
    <section class="flow" aria-label="文章流程"><span>1 每週選題與寫稿</span><span>2 內容與 SEO 檢查</span><span>3 LINE 客戶確認</span><span>4 發佈到客戶網站</span></section>
    <p v-if="pending" role="status">正在載入客戶設定…</p><p v-else-if="error" class="error" role="alert">目前無法讀取設定，請先登入後台並確認系統已完成部署。</p>
    <p v-if="notice" :class="{error:failed}" role="status">{{notice}}</p>
    <section v-if="!workspace.readiness.enabled" class="card"><h2>客戶連結尚未開放</h2><p>完成版本部署、資料庫更新與 LINE 連線設定後，才能產生身分綁定邀請。綁定完成後，每週寫稿與發文仍需另外啟用及核准。</p><p>第一位客戶：Do Alignment。LINE 官方帳號：搜尋王（@453ojflc）。</p></section>
    <template v-else>
      <section class="card"><h2>客戶與連線狀態</h2><p>{{workspace.readiness.lineConfigured?'LINE 連線設定已填妥，實際收發仍需驗收。':'LINE 連線設定尚未完成。'}} {{workspace.readiness.schedulerEnabled?'文章排程開關已開啟；各客戶仍需有效規則及核准。':'每週文章排程尚未啟用。'}}</p><button :disabled="busy || reviewTestBusy" @click="addDo">加入第一位客戶：Do Alignment</button><label>選擇客戶<select v-model="selected" :disabled="busy || reviewTestBusy"><option value="">請選擇</option><option v-for="c in workspace.clients" :key="c.id" :value="String(c.id)">{{c.displayName}}</option></select></label></section>
      <section v-if="current" class="card identity-card">
        <h2>{{current.displayName}} 的 LINE 身分連結</h2><p>{{current.canonicalSiteOrigin}}</p>
        <p v-if="current.status!=='active'">這位客戶目前未啟用，不能產生新邀請。</p>
        <p v-else>{{current.lineBound?'客戶 LINE 已綁定（身分已連結）':'客戶 LINE 尚未綁定'}}</p>
        <p>這一步只確認公司與 LINE 身分，不會啟用每週寫稿、安排寄稿或授權文章發佈。</p>
        <button v-if="!current.lineBound && !invitation" :disabled="busy || current.status!=='active'" @click="invite">產生客戶 LINE 綁定邀請</button>
        <button v-else-if="current.lineBound && !invitation" :disabled="busy || reviewTestBusy || current.status!=='active'" class="danger" @click="openReplacement">更換 LINE 收件人並產生新邀請</button>
        <div v-if="replacementOpen" class="replace-panel" role="dialog" aria-modal="false" aria-labelledby="replace-line-title">
          <h3 id="replace-line-title">確認更換 LINE 收件人</h3>
          <p><strong>完成確認後，現在綁定的 LINE 會立即失去 {{current.displayName}} 的存取權，所有尚未使用的舊邀請碼也會立即失效。</strong></p>
          <p>系統只會產生一組新的十分鐘邀請碼。這項操作不會啟用、停用或更改文章服務、排程與文章發佈狀態。</p>
          <label class="confirm-check"><input v-model="replacementConfirmed" type="checkbox">我確認要撤銷目前 LINE 的存取權，並產生新的收件人邀請</label>
          <button :disabled="busy || reviewTestBusy || !replacementConfirmed" class="danger" @click="replaceLineRecipient">確認更換並產生新邀請</button>
          <button :disabled="busy" class="secondary" @click="cancelReplacement">取消</button>
        </div>
        <div v-if="invitation" class="invite"><p>請客戶加入「搜尋王」好友（@453ojflc），開啟下方入口，登入 LINE 後貼上邀請碼。確認公司名稱與網站正確，再同意連結身分。邀請只對應這位客戶，有效十分鐘。</p><a :href="invitation.connectUrl" target="_blank" rel="noopener noreferrer">開啟 LINE 客戶綁定</a><p>一次性邀請碼（請私下交給指定客戶）：</p><code>{{invitation.invitationToken}}</code><p>有效至 {{time(invitation.expiresAt)}}</p><p>綁定後，文章服務與費用範圍仍需另外核准；每篇原稿都需要客戶另行同意。</p></div>
      </section>
      <section v-if="current && current.lineBound" class="card review-test-card"><h2>{{current.displayName}} 的單篇測試送審</h2>
        <p><strong>只測試閱讀、同意與退回，測試同意不會發布文章。</strong></p><p>這不會啟用每週文章服務、排程或任何文章發佈。測試稿只會以純文字顯示給目前綁定的客戶 LINE。</p>
        <form @submit.prevent="sendReviewTest">
          <label>測試稿標題<input v-model="reviewTestTitle" type="text" maxlength="160" autocomplete="off" required><small>{{reviewTestTitle.length}}／160</small></label>
          <label>測試稿正文<textarea v-model="reviewTestBody" maxlength="12000" rows="14" required></textarea><small>{{reviewTestBody.length}}／12000</small></label>
          <label class="confirm-check"><input v-model="reviewTestConfirmed" type="checkbox">我確認將這份測試稿傳給目前綁定的客戶 LINE</label>
          <button v-if="reviewTestSendState==='idle'" :disabled="busy || reviewTestBusy || reviewTestLoading || !reviewTestsLoaded || !reviewTestConfirmed || !reviewTestTitle.trim() || !reviewTestBody.trim() || current.status!=='active'" type="submit">傳送測試稿到客戶 LINE</button>
          <button v-else-if="reviewTestSendState==='retryable' || (reviewTestSendState==='uncertain' && reviewTestReloadedAfterUncertain)" :disabled="busy || reviewTestBusy || reviewTestLoading || !reviewTestConfirmed || current.status!=='active'" type="submit">使用同一識別碼安全重試</button>
        </form>
        <p v-if="reviewTestNotice" :class="{error:reviewTestFailed}" role="status">{{reviewTestNotice}}</p>
        <p v-if="reviewTestSendState==='uncertain' && !reviewTestReloadedAfterUncertain"><strong>請先更新測試進度；在確認前不會開放重試。</strong></p>
        <div class="test-progress"><h3>測試送審進度</h3><p>「LINE 已接受通知」只表示 LINE 平台接受傳送請求，不代表客戶已收到、已閱讀或已作出決定。</p><p v-if="!reviewTests.length">目前沒有測試送審紀錄。</p><ul v-else><li v-for="test in reviewTests" :key="test.requestId"><strong>{{test.title}}</strong><span>{{reviewTestNotificationStatus(test)}} · {{reviewTestDecisionStatus(test)}}</span><span>建立時間 {{time(test.createdAt)}} · 回覆期限 {{time(test.expiresAt)}}</span></li></ul><button :disabled="busy || reviewTestBusy || reviewTestLoading" class="secondary" type="button" @click="loadReviewTests">{{reviewTestLoading?'正在更新…':'更新測試進度'}}</button></div>
      </section>
      <section v-if="current" class="card"><h2>{{current.displayName}} 的每週文章服務</h2>
        <p v-if="config">{{config.status==='active'?'每週文章送審已啟用':'每週文章服務已暫停'}} · 客戶有 {{config.reviewTtlHours}} 小時確認文章</p><p v-else>每週文章服務尚未啟用。LINE 身分綁定不會代替文章規則或費用核准。</p>
        <div v-if="!config || config.status!=='active'"><div v-if="!current.requiresCustomerApproval"><p>先設定這位客戶的文章要經本人確認。啟用後，所有發文入口都會要求有效的 LINE 同意。</p><button :disabled="busy || current.status!=='active'" @click="requireApproval">我同意改用客戶確認後才發文</button></div><label>使用已核准的寫作與發文規則<select v-model="policyId"><option value="">請選擇</option><option v-for="p in policies" :key="p.policyId" :value="p.policyId">每週文章規則 · 有效至 {{time(p.expiresAt)}}</option></select></label><p v-if="!policies.length">還沒有有效的寫作規則。請先設定網站、可引用資料、品牌語氣和文章預算。</p><NuxtLink to="/audit-lab/content-operations/strategy">設定選題與品牌資料</NuxtLink><NuxtLink to="/audit-lab/content-operations">設定網站與發文規則</NuxtLink><button :disabled="busy || !policyId || current.status!=='active'" @click="activate">啟用每週文章送審</button></div>
        <template v-else>
          <form v-if="!hasCalendar" @submit.prevent="createCalendar"><h3>排好第一篇與之後的每週文章</h3><label>核准的選題計畫<select v-model="planId" required><option value="">請選擇</option><option v-for="p in workspace.plans" :key="p.id" :value="String(p.id)">{{p.title}}</option></select></label><label>第一篇日期<input v-model="startDate" type="date" required></label><label>寄稿時間<input v-model="publishLocalTime" type="time" required></label><label>每月最多文章數<input v-model.number="monthlyArticleLimit" type="number" min="1" max="5" required></label><button :disabled="busy || !planId" type="submit">安排每週寄稿</button></form>
          <p v-else>每週計畫已建立。一次只處理一篇；選題用完、資料過期或客戶要求修改時，會等待管理者處理。</p><button class="secondary" :disabled="busy" @click="pause">暫停這位客戶的文章服務</button>
        </template>
      </section>
      <section class="card"><h2>文章進度</h2><p v-if="!workspace.requests.length">第一篇文章完成內容檢查後，會在這裡顯示。</p><ul v-else><li v-for="r in workspace.requests" :key="r.requestId"><strong>{{name(r.clientId)}} · {{r.title || '送審文章'}}</strong><span>{{requestStatus(r)}} · {{deliveryStatus(r)}}</span><span>確認期限 {{time(r.expiresAt)}}</span><button v-if="canReopen(r)" class="secondary" :disabled="busy" @click="reopen(r)">重新寄送同一篇文章</button></li></ul><button :disabled="busy || pending" class="secondary" @click="refresh()">更新進度</button></section>
    </template>
    <section class="card"><h2>怎樣算完成 GEO／SEO？</h2><p>文章會先確認來源、標題、內文結構與網站發文格式。發佈後，再檢查網址、搜尋引擎收錄條件與實際成效。文章通過內容檢查，不能直接代表 Google 已收錄或 AI 搜尋已引用。</p><NuxtLink to="/audit-lab/site-evidence">檢查網站 SEO</NuxtLink><NuxtLink to="/audit-lab/measurement-operations">查看搜尋與流量成效</NuxtLink><NuxtLink to="/audit-lab/llm-visibility">查看 AI 搜尋觀測</NuxtLink></section>
  </div>
</template>
<style scoped>
.weekly-page{max-width:1080px;margin:auto;padding:40px 24px;font-size:18px;line-height:1.7}h1{font-size:36px;margin:6px 0}h2{font-size:24px}h3{font-size:20px}.brand{color:#365da0;font-weight:700}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.flow span,.card{background:white;border:1px solid #d9e2ef;border-radius:12px;padding:20px}.card{margin:20px 0}.card a{display:inline-block;margin:8px 18px 8px 0;color:#315da7}.error{background:#fff0ee;color:#9b2e21;padding:16px;border-radius:8px}label{display:grid;gap:6px;margin:16px 0;max-width:600px}select,input,textarea{font:inherit;padding:10px;border:1px solid #aebcd0;border-radius:6px}textarea{resize:vertical;min-height:260px}button{font:inherit;border:0;border-radius:8px;padding:10px 18px;background:#295d9b;color:white;margin:8px 12px 8px 0;cursor:pointer}button:disabled{opacity:.55;cursor:not-allowed}.secondary{background:#e6ecf5;color:#23436b}.danger{background:#9b2e21}.replace-panel{margin-top:16px;padding:18px;border:2px solid #c76053;border-radius:10px;background:#fff6f4}.replace-panel h3{margin-top:0;color:#7e271d}.confirm-check{display:flex;align-items:flex-start;gap:10px;max-width:760px}.confirm-check input{width:20px;height:20px;margin-top:6px;padding:0;flex:0 0 auto}.invite{padding:16px;background:#eff5ff;border-radius:8px}.test-progress{margin-top:20px;padding-top:14px;border-top:1px solid #d9e2ef}code{overflow-wrap:anywhere}li{display:grid;gap:4px;padding:18px 0;border-bottom:1px solid #d9e2ef}ul{padding:0;list-style:none}@media(max-width:700px){.flow{grid-template-columns:1fr 1fr}.weekly-page{padding:24px 16px}h1{font-size:30px}}
</style>
