CREATE TABLE `contentOperationAutopilotPolicies` (
  `id` int AUTO_INCREMENT NOT NULL,
  `ownerUserId` int NOT NULL,
  `clientId` int NOT NULL,
  `publicationTargetId` int NOT NULL,
  `policyId` varchar(96) NOT NULL,
  `policyVersion` varchar(96) NOT NULL,
  `authorizedByOwnerUserId` int NOT NULL,
  `status` enum('enabled','paused','revoked') NOT NULL DEFAULT 'enabled',
  `authorizedAt` timestamp NOT NULL,
  `expiresAt` timestamp NOT NULL,
  `revokedAt` timestamp NULL,
  `allowedContentTypes` json NOT NULL,
  `allowedLanguages` json NOT NULL,
  `requireApprovedForDelivery` boolean NOT NULL DEFAULT true,
  `requirePassedRiskGate` boolean NOT NULL DEFAULT true,
  `configurationFingerprint` varchar(128) NOT NULL,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE now(),
  CONSTRAINT `content_operation_autopilot_policy_id_unique` UNIQUE(`policyId`),
  CONSTRAINT `content_operation_autopilot_owner_target_unique` UNIQUE(`ownerUserId`,`publicationTargetId`),
  CONSTRAINT `content_operation_autopilot_owner_fk` FOREIGN KEY (`ownerUserId`) REFERENCES `users`(`id`),
  CONSTRAINT `content_operation_autopilot_authorized_by_owner_fk` FOREIGN KEY (`authorizedByOwnerUserId`) REFERENCES `users`(`id`),
  CONSTRAINT `content_operation_autopilot_client_fk` FOREIGN KEY (`clientId`) REFERENCES `contentOperationClients`(`id`),
  CONSTRAINT `content_operation_autopilot_target_fk` FOREIGN KEY (`publicationTargetId`) REFERENCES `contentOperationPublicationTargets`(`id`)
);
CREATE INDEX `content_operation_autopilot_owner_status_idx` ON `contentOperationAutopilotPolicies` (`ownerUserId`,`status`,`expiresAt`);
