CREATE TABLE `weeklyContentReviewTests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` varchar(36) NOT NULL,
	`ownerUserId` int NOT NULL,
	`clientId` int NOT NULL,
	`bindingId` int NOT NULL,
	`bindingFingerprint` varchar(64) NOT NULL,
	`sourceLabel` varchar(40) NOT NULL,
	`title` varchar(160) NOT NULL,
	`body` text NOT NULL,
	`contentHash` varchar(64) NOT NULL,
	`requestFingerprint` varchar(64) NOT NULL,
	`idempotencyKey` varchar(128) NOT NULL,
	`readTokenHash` varchar(64) NOT NULL,
	`actionTokenHash` varchar(64) NOT NULL,
	`status` enum('pending','approved','changes_requested','revoked') NOT NULL DEFAULT 'pending',
	`decisionEventHash` varchar(64),
	`decisionActorFingerprint` varchar(64),
	`decisionFingerprint` varchar(64),
	`decidedAt` timestamp,
	`notificationStatus` enum('queued','processing','sent','retry_wait','failed','cancelled') NOT NULL DEFAULT 'queued',
	`notificationAttemptCount` int NOT NULL DEFAULT 0,
	`notificationLeaseToken` varchar(96),
	`notificationLeaseExpiresAt` timestamp,
	`notificationRetryEligibleAt` timestamp,
	`notificationRetryKey` varchar(36) NOT NULL,
	`notificationPayloadFingerprint` varchar(64),
	`notificationProviderMessageId` varchar(128),
	`notificationErrorCode` varchar(80),
	`notificationSentAt` timestamp,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weeklyContentReviewTests_id` PRIMARY KEY(`id`),
	CONSTRAINT `weekly_review_test_request_uq` UNIQUE(`requestId`),
	CONSTRAINT `weekly_review_test_owner_key_uq` UNIQUE(`ownerUserId`,`clientId`,`idempotencyKey`)
);
--> statement-breakpoint
CREATE INDEX `weekly_review_test_owner_client_idx` ON `weeklyContentReviewTests` (`ownerUserId`,`clientId`,`id`);--> statement-breakpoint
CREATE INDEX `weekly_review_test_binding_status_idx` ON `weeklyContentReviewTests` (`ownerUserId`,`clientId`,`bindingId`,`status`);
