import { signEnvelope } from './hmac'
import { fingerprint, normalizeText, SystemFactoryError } from './canonical'
import type { CompiledSystemPlan } from './compiler'
import type { OperationReceipt } from './control-plane'
import { assertLiveRuntimeAuthority, type SystemFactoryRuntimeAuthority } from './runtime-authority'

export type TenantAppCredentialMaterial = { hmacKey: string; authorizationHeader: string }
export type OpaqueCredential = { ok: true; value: TenantAppCredentialMaterial } | { ok: false; reason: 'missing' | 'revoked' | 'unavailable' }
export type CredentialResolver = (reference: string) => Promise<OpaqueCredential>
export const TENANT_APP_OPERATIONS = ['apply_compiled_spec', 'configure_roles', 'configure_modules', 'health', 'prepare_admin_invitation', 'activate_admin_invitation', 'suspend_tenant'] as const
export type TenantAppOperation = typeof TENANT_APP_OPERATIONS[number]
export type TenantAppContext = { ownerId: string; clientId: string; websiteId: string | null; managedSiteId: string | null; systemTenantId: string; siteName: string; credentialReference: string; idempotencyKey: string; compiledPlan: CompiledSystemPlan; runtimeAuthority: SystemFactoryRuntimeAuthority; executionMode: 'mocked' | 'live' }
export type ActivateInvitationInput = TenantAppContext & { invitationId: string; principalEmail: string; principalEmailHash: string; roleKey: string; password: string }
export type ActivationReceipt = OperationReceipt & { invitationId: string; principalIdentityHash: string; userIdentityHash: string; roleKey: string }
export type TenantAppPort = { applyCompiledSpec(input: TenantAppContext): Promise<OperationReceipt>; configureRoles(input: TenantAppContext): Promise<OperationReceipt>; configureModules(input: TenantAppContext): Promise<OperationReceipt>; health(input: TenantAppContext): Promise<OperationReceipt & { healthy: boolean }>; prepareAdminInvitation(input: TenantAppContext): Promise<OperationReceipt>; activateAdminInvitation(input: ActivateInvitationInput): Promise<ActivationReceipt>; suspendTenant(input: TenantAppContext): Promise<OperationReceipt> }

export const TENANT_APP_PATHS: Record<TenantAppOperation, string> = {
  apply_compiled_spec: '/api/method/discovery_stack.api.apply_compiled_spec',
  configure_roles: '/api/method/discovery_stack.api.configure_roles',
  configure_modules: '/api/method/discovery_stack.api.configure_modules',
  health: '/api/method/discovery_stack.api.health',
  prepare_admin_invitation: '/api/method/discovery_stack.api.prepare_admin_invitation',
  activate_admin_invitation: '/api/method/discovery_stack.api.activate_admin_invitation',
  suspend_tenant: '/api/method/discovery_stack.api.suspend_tenant',
}

const SPECIAL_HOST = /(?:^|\.)(?:localhost|local|internal|invalid|test|example)$/u
function ipv4Special(host: string): boolean { const parts = host.split('.').map(Number); if (parts.length !== 4 || parts.some(part => !Number.isInteger(part) || part < 0 || part > 255)) return false; const first = parts[0]!; return first === 0 || first === 10 || first === 127 || first >= 224 || (first === 169 && parts[1] === 254) || (first === 172 && parts[1]! >= 16 && parts[1]! <= 31) || (first === 192 && parts[1] === 168) || (first === 100 && parts[1]! >= 64 && parts[1]! <= 127) }
export function assertPublicFrappeOrigin(value: string, allowlist: readonly string[]): string { let url: URL; try { url = new URL(value) } catch { throw new SystemFactoryError('FRAPPE_ORIGIN', 'Frappe origin is invalid.', 503) }; const host = url.hostname.toLocaleLowerCase('en-US').replace(/^\[|\]$/gu, '').replace(/\.$/u, ''); if (url.protocol !== 'https:' || url.username || url.password || url.pathname !== '/' || url.search || url.hash || (url.port && url.port !== '443') || SPECIAL_HOST.test(host) || ipv4Special(host) || host === '::1' || /^(?:fc|fd|fe8|fe9|fea|feb)/u.test(host.replace(/:/gu, ''))) throw new SystemFactoryError('FRAPPE_ORIGIN', 'Frappe origin must be an allowlisted public HTTPS origin.', 503); const origins = new Set(allowlist.map(candidate => new URL(candidate).origin)); if (!origins.has(url.origin)) throw new SystemFactoryError('FRAPPE_ORIGIN', 'Frappe origin is outside the server allowlist.', 503); return url.origin }

function exactKeys(value: unknown, keys: readonly string[]): value is Record<string, unknown> { return Boolean(value && typeof value === 'object' && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype && Object.keys(value).sort().join(',') === [...keys].sort().join(',')) }
function transportFailure(error: unknown): never { if (error instanceof SystemFactoryError) throw error; if (error instanceof DOMException && error.name === 'AbortError') throw new SystemFactoryError('TENANT_APP_TIMEOUT', 'Tenant app request timed out.', 504); throw new SystemFactoryError('TENANT_APP_TRANSPORT', 'Tenant app transport failed.', 502) }

export function createTenantAppAdapter(options: { endpointOrigin: string; allowedOrigins: string[]; sender: string; receiver: string; keyId: string; credentialResolver: CredentialResolver; liveEnabled: boolean; expectedAuthorityFingerprint?: string; fetchImpl?: typeof fetch; timeoutMs?: number; maximumResponseBytes?: number }): TenantAppPort {
  const origin = assertPublicFrappeOrigin(options.endpointOrigin, options.allowedOrigins); const fetchImpl = options.fetchImpl || fetch; const timeoutMs = Math.min(Math.max(options.timeoutMs || 15_000, 500), 30_000); const maximumResponseBytes = Math.min(Math.max(options.maximumResponseBytes || 262_144, 1024), 1_048_576)
  async function invoke(operation: TenantAppOperation, input: TenantAppContext | ActivateInvitationInput): Promise<any> {
    if (input.executionMode !== 'live' || !options.liveEnabled) throw new SystemFactoryError('TENANT_APP_DISABLED', 'Live tenant-app execution is disabled.', 503)
    assertLiveRuntimeAuthority(input.runtimeAuthority, options.expectedAuthorityFingerprint)
    const credential = await options.credentialResolver(input.credentialReference); if (!credential.ok) throw new SystemFactoryError('MISSING_CREDENTIAL', 'Server credential reference is unavailable.', 503)
    const path = TENANT_APP_PATHS[operation]
    const common = { schemaVersion: 'tenant-app-operation-v1', operation, ownerId: input.ownerId, clientId: input.clientId, websiteId: input.websiteId, managedSiteId: input.managedSiteId, systemTenantId: input.systemTenantId, siteName: input.siteName, idempotencyKey: input.idempotencyKey, compiledPlanFingerprint: input.compiledPlan.planFingerprint, specFingerprint: input.compiledPlan.specFingerprint, runtimeAuthorityFingerprint: input.runtimeAuthority.authorityFingerprint }
    const bodyObject: Record<string, unknown> = { ...common }
    if (operation === 'apply_compiled_spec') bodyObject.compiledPlan = input.compiledPlan
    if (operation === 'activate_admin_invitation') { const activation = input as ActivateInvitationInput; Object.assign(bodyObject, { invitationId: normalizeText(activation.invitationId, 'Invitation id', 128), principalEmail: normalizeText(activation.principalEmail, 'Invitation email', 320).toLocaleLowerCase('en-US'), principalEmailHash: activation.principalEmailHash, roleKey: normalizeText(activation.roleKey, 'Role key', 64), password: activation.password }) }
    if (credential.value.hmacKey.length < 32 || !/^(?:token|Bearer) [^\s]{8,512}$/u.test(credential.value.authorizationHeader)) throw new SystemFactoryError('MISSING_CREDENTIAL', 'Server credential reference is unavailable.', 503)
    const body = JSON.stringify(bodyObject); const signed = signEnvelope({ method: 'POST', path, rawBody: body, sender: options.sender, receiver: options.receiver, keyId: options.keyId, key: credential.value.hmacKey }); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs)
    try {
      const response = await fetchImpl(`${origin}${path}`, { method: 'POST', redirect: 'error', signal: controller.signal, headers: { 'content-type': 'application/json', authorization: credential.value.authorizationHeader, 'idempotency-key': input.idempotencyKey, 'x-ds-timestamp': signed.timestamp, 'x-ds-nonce': signed.nonce, 'x-ds-sender': signed.sender, 'x-ds-receiver': signed.receiver, 'x-ds-key-id': signed.keyId, 'x-ds-body-sha256': signed.bodySha256, 'x-ds-signature': signed.signature }, body })
      const contentLength = Number(response.headers.get('content-length') || 0); if (!Number.isFinite(contentLength) || contentLength < 0 || contentLength > maximumResponseBytes) throw new SystemFactoryError('TENANT_APP_RESPONSE_BOUND', 'Tenant app response exceeds its bound.', 409)
      const text = await response.text(); if (Buffer.byteLength(text) > maximumResponseBytes) throw new SystemFactoryError('TENANT_APP_RESPONSE_BOUND', 'Tenant app response exceeds its bound.', 409)
      if (response.status === 429 || response.status >= 500) throw new SystemFactoryError(response.status === 429 ? 'TENANT_APP_RATE_LIMIT' : 'TENANT_APP_RETRYABLE_5XX', 'Tenant app returned a retryable status.', response.status)
      if ([401, 403, 409].includes(response.status)) throw new SystemFactoryError(`TENANT_APP_${response.status}`, 'Tenant app rejected authority or lineage.', response.status)
      if (!response.ok) throw new SystemFactoryError('TENANT_APP_STATUS', 'Tenant app returned an unsupported status.', 409)
      let outer: unknown; try { outer = JSON.parse(text) } catch { throw new SystemFactoryError('TENANT_APP_MALFORMED', 'Tenant app response is malformed.', 409) }
      if (!exactKeys(outer, ['message'])) throw new SystemFactoryError('TENANT_APP_MALFORMED', 'Tenant app response envelope is malformed.', 409)
      const data = outer.message
      const keys = operation === 'activate_admin_invitation' ? ['ok', 'schemaVersion', 'operation', 'systemTenantId', 'runtimeAuthorityFingerprint', 'requestFingerprint', 'receiptFingerprint', 'replayed', 'invitationId', 'principalIdentityHash', 'userIdentityHash', 'roleKey'] : ['ok', 'schemaVersion', 'operation', 'systemTenantId', 'runtimeAuthorityFingerprint', 'requestFingerprint', 'receiptFingerprint', 'replayed', ...(operation === 'health' ? ['healthy'] : [])]
      if (!exactKeys(data, keys) || data.ok !== true || data.schemaVersion !== 'tenant-app-operation-response-v1' || data.operation !== operation || data.systemTenantId !== input.systemTenantId || data.runtimeAuthorityFingerprint !== input.runtimeAuthority.authorityFingerprint || typeof data.replayed !== 'boolean' || !/^[a-f0-9]{64}$/u.test(String(data.requestFingerprint)) || !/^[a-f0-9]{64}$/u.test(String(data.receiptFingerprint))) throw new SystemFactoryError('TENANT_APP_MISMATCH', 'Tenant app response identity is mismatched.', 409)
      const safeRequest = operation === 'activate_admin_invitation' ? { ...bodyObject, password: '[REDACTED]' } : bodyObject; const requestFingerprint = fingerprint(safeRequest)
      if (data.requestFingerprint !== requestFingerprint) throw new SystemFactoryError('TENANT_APP_REQUEST_COLLISION', 'Tenant app request fingerprint is mismatched.', 409)
      const responseFingerprint = fingerprint(data); const base: OperationReceipt = { schemaVersion: 'system-factory-operation-receipt-v1', operation, systemTenantId: input.systemTenantId, status: 'succeeded', replayed: data.replayed as boolean, requestFingerprint, responseFingerprint, receiptFingerprint: String(data.receiptFingerprint), exactResponseIdentity: `${response.status}:${String(data.receiptFingerprint)}`, runtimeAuthorityFingerprint: input.runtimeAuthority.authorityFingerprint, externalCalls: true, sanitizedMetadata: { remoteStatus: response.status, endpoint: operation } }
      if (operation === 'health') { if (typeof data.healthy !== 'boolean') throw new SystemFactoryError('TENANT_APP_MALFORMED', 'Tenant health response is malformed.', 409); return { ...base, healthy: data.healthy } }
      if (operation === 'activate_admin_invitation') { for (const field of ['invitationId', 'principalIdentityHash', 'userIdentityHash', 'roleKey'] as const) if (typeof data[field] !== 'string') throw new SystemFactoryError('TENANT_APP_MALFORMED', 'Tenant activation response is malformed.', 409); return { ...base, invitationId: data.invitationId, principalIdentityHash: data.principalIdentityHash, userIdentityHash: data.userIdentityHash, roleKey: data.roleKey } }
      return base
    } catch (error) { transportFailure(error) } finally { clearTimeout(timer) }
  }
  return { applyCompiledSpec: input => invoke('apply_compiled_spec', input), configureRoles: input => invoke('configure_roles', input), configureModules: input => invoke('configure_modules', input), health: input => invoke('health', input), prepareAdminInvitation: input => invoke('prepare_admin_invitation', input), activateAdminInvitation: input => invoke('activate_admin_invitation', input), suspendTenant: input => invoke('suspend_tenant', input) }
}

export function createMockTenantApp(options: { calls?: string[]; failAt?: TenantAppOperation; unhealthy?: boolean } = {}): TenantAppPort {
  const invoke = async (operation: TenantAppOperation, input: TenantAppContext | ActivateInvitationInput) => { options.calls?.push(operation); if (options.failAt === operation) throw new SystemFactoryError('MOCK_RETRYABLE_5XX', 'Injected tenant-app failure.', 502); const safeRequest = { operation, tenant: input.systemTenantId, plan: input.compiledPlan.planFingerprint, idempotencyKey: input.idempotencyKey, ...(operation === 'activate_admin_invitation' ? { invitationId: (input as ActivateInvitationInput).invitationId, principalEmailHash: (input as ActivateInvitationInput).principalEmailHash, roleKey: (input as ActivateInvitationInput).roleKey } : {}) }; const requestFingerprint = fingerprint(safeRequest); const receiptFingerprint = fingerprint({ requestFingerprint, authority: input.runtimeAuthority.authorityFingerprint }); const base: any = { schemaVersion: 'system-factory-operation-receipt-v1', operation, systemTenantId: input.systemTenantId, status: 'succeeded', replayed: false, requestFingerprint, responseFingerprint: fingerprint({ receiptFingerprint, operation }), receiptFingerprint, exactResponseIdentity: `mock-tenant:${operation}:${receiptFingerprint.slice(0, 24)}`, runtimeAuthorityFingerprint: input.runtimeAuthority.authorityFingerprint, externalCalls: false, sanitizedMetadata: { mocked: true } }; if (operation === 'health') return { ...base, healthy: options.unhealthy !== true }; if (operation === 'activate_admin_invitation') { const activation = input as ActivateInvitationInput; return { ...base, invitationId: activation.invitationId, principalIdentityHash: activation.principalEmailHash, userIdentityHash: fingerprint({ tenant: activation.systemTenantId, email: activation.principalEmail.toLocaleLowerCase('en-US') }), roleKey: activation.roleKey } }; return base }
  return { applyCompiledSpec: input => invoke('apply_compiled_spec', input), configureRoles: input => invoke('configure_roles', input), configureModules: input => invoke('configure_modules', input), health: input => invoke('health', input), prepareAdminInvitation: input => invoke('prepare_admin_invitation', input), activateAdminInvitation: input => invoke('activate_admin_invitation', input), suspendTenant: input => invoke('suspend_tenant', input) }
}
