import { randomBytes, scryptSync } from 'node:crypto'
import { fingerprint, normalizeText, SystemFactoryError } from './canonical'
import type { CompiledSystemPlan } from './compiler'
import type { ActivationReceipt, TenantAppPort } from './frappe-adapter'
import type { SystemFactoryRuntimeAuthority } from './runtime-authority'

export type ActivationContext = { activationRunRowId: number; activationRunId: string; invitationRowId: number; invitationId: string; ownerUserRowId: number; tenantRowId: number; systemTenantId: string; ownerId: string; clientId: string; websiteId: string | null; managedSiteId: string; managedSiteProjectId: number; principalEmail: string; principalEmailHash: string; roleKey: string; compiledPlan: CompiledSystemPlan; tenantAppCredentialReference: string; siteName: string; authority: SystemFactoryRuntimeAuthority; attemptNumber: number; maxAttempts: number; leaseOwner: string; idempotencyKey: string }
export type ActivationClaimInput = { tokenHash: string; principalEmail: string; principalEmailHash: string; idempotencyKey: string; leaseOwner: string; now: Date; leaseExpiresAt: Date; authority: SystemFactoryRuntimeAuthority; executionMode: 'mocked' | 'live' }
export interface InvitationActivationRepositoryPort {
  claim(input: ActivationClaimInput): Promise<ActivationContext>
  complete(context: ActivationContext, receipt: ActivationReceipt, sessionTokenHash: string, now: Date): Promise<void>
  fail(context: ActivationContext, failure: { code: string; retryAt: Date | null; blocked: boolean }, now: Date): Promise<void>
}

function password(input: unknown): string { const value = String(input || ''); if (value.length < 14 || value.length > 256 || !/[A-Z]/u.test(value) || !/[a-z]/u.test(value) || !/[0-9]/u.test(value)) throw new SystemFactoryError('WEAK_PASSWORD', 'Initial password does not meet the bounded strength contract.'); scryptSync(value, 'system-factory-memory-only-strength-check', 32); return value }
function idempotencyKey(value: unknown): string { const result = normalizeText(value, 'Idempotency key', 128); if (!/^[A-Za-z0-9][A-Za-z0-9:._-]{7,127}$/u.test(result)) throw new SystemFactoryError('INVALID_IDEMPOTENCY_KEY', 'Idempotency key is invalid.'); return result }
function classify(error: unknown, attempt: number, maxAttempts: number, now: Date) { const code = error instanceof SystemFactoryError ? error.code : 'ACTIVATION_FAILURE'; const status = error instanceof SystemFactoryError ? error.statusCode : 500; const retryable = (status === 429 || status >= 500) && !['RUNTIME_AUTHORITY_UNAPPROVED', 'AUTHORITY_DRIFT', 'MISSING_CREDENTIAL', 'TENANT_APP_DISABLED'].includes(code) && attempt < maxAttempts; return { code, blocked: !retryable, retryAt: retryable ? new Date(now.getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, attempt - 1))) : null } }

export async function activateSystemInvitation(input: { token: unknown; email: unknown; password: unknown; idempotencyKey: unknown; repository: InvitationActivationRepositoryPort; tenantApp: TenantAppPort; authority: SystemFactoryRuntimeAuthority; executionMode: 'mocked' | 'live'; workerId: string; now?: Date }) {
  const now = input.now || new Date(); const token = normalizeText(input.token, 'Invitation token', 256); if (token.length < 32) throw new SystemFactoryError('INVITATION_INVALID', 'System invitation is invalid or expired.', 404)
  const principalEmail = normalizeText(input.email, 'Invitation email', 320).toLocaleLowerCase('en-US'); if (!/^\S+@\S+\.\S+$/u.test(principalEmail)) throw new SystemFactoryError('INVITATION_INVALID', 'System invitation is invalid or expired.', 404)
  const secretPassword = password(input.password); const key = idempotencyKey(input.idempotencyKey); const tokenHash = fingerprint({ token }); const principalEmailHash = fingerprint({ email: principalEmail })
  const context = await input.repository.claim({ tokenHash, principalEmail, principalEmailHash, idempotencyKey: key, leaseOwner: input.workerId, now, leaseExpiresAt: new Date(now.getTime() + 120_000), authority: input.authority, executionMode: input.executionMode })
  try {
    const receipt = await input.tenantApp.activateAdminInvitation({ ownerId: context.ownerId, clientId: context.clientId, websiteId: context.websiteId, managedSiteId: context.managedSiteId, systemTenantId: context.systemTenantId, siteName: context.siteName, credentialReference: context.tenantAppCredentialReference, idempotencyKey: context.idempotencyKey, compiledPlan: context.compiledPlan, runtimeAuthority: context.authority, executionMode: input.executionMode, invitationId: context.invitationId, principalEmail: context.principalEmail, principalEmailHash: context.principalEmailHash, roleKey: context.roleKey, password: secretPassword })
    if (receipt.systemTenantId !== context.systemTenantId || receipt.invitationId !== context.invitationId || receipt.principalIdentityHash !== context.principalEmailHash || receipt.userIdentityHash !== fingerprint({ tenant: context.systemTenantId, email: context.principalEmail }) || receipt.roleKey !== context.roleKey || receipt.runtimeAuthorityFingerprint !== context.authority.authorityFingerprint) throw new SystemFactoryError('ACTIVATION_RECEIPT_MISMATCH', 'Tenant activation receipt identity is mismatched.', 409)
    const sessionToken = randomBytes(32).toString('base64url'); await input.repository.complete(context, receipt, fingerprint({ token: sessionToken }), new Date()); return { accepted: true as const, invitationId: context.invitationId, systemTenantId: context.systemTenantId, sessionToken, replayed: receipt.replayed }
  } catch (error) { await input.repository.fail(context, classify(error, context.attemptNumber, context.maxAttempts, now), new Date()); throw error }
}

type MemoryInvitation = { context: Omit<ActivationContext, 'activationRunRowId' | 'activationRunId' | 'attemptNumber' | 'leaseOwner' | 'idempotencyKey'>; tokenHash: string; status: 'pending' | 'accepted' | 'revoked' | 'expired'; expiresAt: Date; run: null | { id: number; publicId: string; key: string; inputFingerprint: string; status: 'processing' | 'retry_wait' | 'blocked' | 'completed'; leaseOwner: string; leaseExpiresAt: Date; attempt: number }; sessions: string[] }
export class MemoryInvitationActivationRepository implements InvitationActivationRepositoryPort {
  readonly invitation: MemoryInvitation
  constructor(input: { context: MemoryInvitation['context']; token: string; expiresAt?: Date }) { this.invitation = { context: input.context, tokenHash: fingerprint({ token: input.token }), status: 'pending', expiresAt: input.expiresAt || new Date(Date.now() + 3600_000), run: null, sessions: [] } }
  async claim(input: ActivationClaimInput) { const item = this.invitation; if (item.tokenHash !== input.tokenHash || item.status !== 'pending' || item.expiresAt <= input.now || item.context.principalEmailHash !== input.principalEmailHash) throw new SystemFactoryError('INVITATION_INVALID', 'System invitation is invalid or expired.', 404); const fp = fingerprint({ invitationId: item.context.invitationId, principalEmailHash: input.principalEmailHash, idempotencyKey: input.idempotencyKey }); if (item.run && item.run.key === input.idempotencyKey && item.run.inputFingerprint !== fp) throw new SystemFactoryError('ACTIVATION_COLLISION', 'Activation idempotency key collided.', 409); if (item.run && item.run.status === 'processing' && item.run.leaseExpiresAt > input.now) throw new SystemFactoryError('ACTIVATION_CLAIMED', 'Invitation activation is already processing.', 409); if (!item.run) item.run = { id: 1, publicId: `activation-${item.context.invitationId}`, key: input.idempotencyKey, inputFingerprint: fp, status: 'processing', leaseOwner: input.leaseOwner, leaseExpiresAt: input.leaseExpiresAt, attempt: 1 }; else { item.run.status = 'processing'; item.run.leaseOwner = input.leaseOwner; item.run.leaseExpiresAt = input.leaseExpiresAt; item.run.attempt++ }; return { ...item.context, activationRunRowId: item.run.id, activationRunId: item.run.publicId, attemptNumber: item.run.attempt, leaseOwner: item.run.leaseOwner, idempotencyKey: item.run.key }; }
  async complete(context: ActivationContext, _receipt: ActivationReceipt, sessionTokenHash: string) { const run = this.invitation.run; if (!run || run.status !== 'processing' || run.leaseOwner !== context.leaseOwner || this.invitation.status !== 'pending') throw new SystemFactoryError('ACTIVATION_CAS', 'Activation completion lost its claim.', 409); this.invitation.status = 'accepted'; run.status = 'completed'; this.invitation.sessions.push(sessionTokenHash) }
  async fail(context: ActivationContext, failure: { retryAt: Date | null; blocked: boolean }) { const run = this.invitation.run; if (run && run.status === 'processing' && run.leaseOwner === context.leaseOwner) run.status = failure.blocked ? 'blocked' : 'retry_wait' }
}
