import { and, eq, lte, or } from 'drizzle-orm'
import type { MySql2Database } from 'drizzle-orm/mysql2'
import * as schema from '../database/schema'
import { MANAGED_SITE_SESSION_TTL_MS } from '../managed-sites/types'
import { fingerprint, SystemFactoryError } from './canonical'
import type { CompiledSystemPlan } from './compiler'
import type { ActivationReceipt } from './frappe-adapter'
import type { ActivationClaimInput, ActivationContext, InvitationActivationRepositoryPort } from './invitation-activation'

type Db = MySql2Database<typeof schema>
function affected(result: any): number { return Number(result?.[0]?.affectedRows || 0) }
function inserted(result: any): number { const id = Number(result?.[0]?.insertId); if (!Number.isSafeInteger(id) || id < 1) throw new SystemFactoryError('DATABASE_INSERT', 'Activation record could not be created.', 500); return id }
function portalRole(roleKey: string): 'administrator' | 'editor' | 'reviewer' | 'analyst' { if (roleKey.includes('manager') || roleKey === 'system_manager') return 'administrator'; if (roleKey.includes('viewer')) return 'analyst'; if (roleKey.includes('support')) return 'reviewer'; return 'editor' }

export class DrizzleInvitationActivationRepository implements InvitationActivationRepositoryPort {
  constructor(private readonly db: Db) {}
  async claim(input: ActivationClaimInput): Promise<ActivationContext> {
    const [invitation] = await this.db.select().from(schema.systemAdminInvitations).where(eq(schema.systemAdminInvitations.tokenHash, input.tokenHash)).limit(1)
    if (!invitation || invitation.status !== 'pending' || invitation.expiresAt <= input.now || invitation.principalEmailHash !== input.principalEmailHash) throw new SystemFactoryError('INVITATION_INVALID', 'System invitation is invalid or expired.', 404)
    const [[tenant], [binding], [plan], refs] = await Promise.all([this.db.select().from(schema.systemTenants).where(and(eq(schema.systemTenants.id, invitation.systemTenantId), eq(schema.systemTenants.ownerUserId, invitation.ownerUserId))).limit(1), this.db.select().from(schema.systemTenantBindings).where(and(eq(schema.systemTenantBindings.systemTenantId, invitation.systemTenantId), eq(schema.systemTenantBindings.ownerUserId, invitation.ownerUserId))).limit(1), this.db.select().from(schema.systemProvisioningPlans).where(and(eq(schema.systemProvisioningPlans.systemTenantId, invitation.systemTenantId), eq(schema.systemProvisioningPlans.ownerUserId, invitation.ownerUserId), eq(schema.systemProvisioningPlans.status, 'invitation_pending'))).limit(1), this.db.select().from(schema.systemConnectionRefs).where(and(eq(schema.systemConnectionRefs.systemTenantId, invitation.systemTenantId), eq(schema.systemConnectionRefs.ownerUserId, invitation.ownerUserId), eq(schema.systemConnectionRefs.status, 'active')))])
    if (!tenant || tenant.state !== 'invitation_pending' || !tenant.healthyReceiptFingerprint || !binding?.managedSiteProjectId || !plan) throw new SystemFactoryError('ACTIVATION_LINEAGE', 'Healthy invitation-pending tenant lineage is incomplete.', 409)
    const [version] = await this.db.select().from(schema.systemSpecVersions).where(and(eq(schema.systemSpecVersions.id, plan.systemSpecVersionId), eq(schema.systemSpecVersions.ownerUserId, invitation.ownerUserId))).limit(1); const credential = refs.find(ref => ref.purpose === 'frappe_internal_hmac'); if (!version || !credential) throw new SystemFactoryError('MISSING_CREDENTIAL', 'Tenant app activation credential reference is unavailable.', 503)
    const inputFingerprint = fingerprint({ schemaVersion: 'system-invitation-activation-v1', invitationId: invitation.invitationId, tenant: tenant.systemTenantId, principalEmailHash: input.principalEmailHash, roleKey: invitation.roleKey, idempotencyKey: input.idempotencyKey })
    const runPublicId = `activation-${fingerprint({ invitationId: invitation.invitationId, idempotencyKey: input.idempotencyKey }).slice(0, 32)}`
    let [run] = await this.db.select().from(schema.systemProvisioningRuns).where(and(eq(schema.systemProvisioningRuns.ownerUserId, invitation.ownerUserId), eq(schema.systemProvisioningRuns.idempotencyKey, `activation:${input.idempotencyKey}`))).limit(1)
    if (run && run.inputFingerprint !== inputFingerprint) throw new SystemFactoryError('ACTIVATION_COLLISION', 'Activation idempotency key is bound to another payload.', 409)
    if (!run) { const id = inserted(await this.db.insert(schema.systemProvisioningRuns).values({ runId: runPublicId, ownerUserId: invitation.ownerUserId, systemTenantId: invitation.systemTenantId, planId: plan.id, status: 'queued', attempt: 0, maxAttempts: 3, inputFingerprint, idempotencyKey: `activation:${input.idempotencyKey}` } as any)); [run] = await this.db.select().from(schema.systemProvisioningRuns).where(eq(schema.systemProvisioningRuns.id, id)).limit(1) }
    if (!run) throw new SystemFactoryError('ACTIVATION_RUN', 'Activation run could not be created.', 500)
    const claimable = or(eq(schema.systemProvisioningRuns.status, 'queued'), and(eq(schema.systemProvisioningRuns.status, 'retry_wait'), lte(schema.systemProvisioningRuns.retryEligibleAt, input.now)), and(eq(schema.systemProvisioningRuns.status, 'processing'), lte(schema.systemProvisioningRuns.leaseExpiresAt, input.now)))
    const claimed = await this.db.update(schema.systemProvisioningRuns).set({ status: 'processing', attempt: run.attempt + 1, leaseOwner: input.leaseOwner, leaseExpiresAt: input.leaseExpiresAt, retryEligibleAt: null } as any).where(and(eq(schema.systemProvisioningRuns.id, run.id), eq(schema.systemProvisioningRuns.attempt, run.attempt), claimable)); if (affected(claimed) !== 1) throw new SystemFactoryError('ACTIVATION_CLAIMED', 'Invitation activation is already processing or terminal.', 409)
    return { activationRunRowId: run.id, activationRunId: run.runId, invitationRowId: invitation.id, invitationId: invitation.invitationId, ownerUserRowId: invitation.ownerUserId, tenantRowId: tenant.id, systemTenantId: tenant.systemTenantId, ownerId: `owner:${invitation.ownerUserId}`, clientId: `client:${tenant.clientId}`, websiteId: binding.websiteId, managedSiteId: `managed-site:${binding.managedSiteProjectId}`, managedSiteProjectId: binding.managedSiteProjectId, principalEmail: input.principalEmail, principalEmailHash: invitation.principalEmailHash, roleKey: invitation.roleKey, compiledPlan: version.compiledPlan as CompiledSystemPlan, tenantAppCredentialReference: credential.opaqueReference, siteName: `tenant-${fingerprint({ tenant: tenant.systemTenantId }).slice(0, 24)}.factory.invalid`, authority: input.authority, attemptNumber: run.attempt + 1, maxAttempts: run.maxAttempts, leaseOwner: input.leaseOwner, idempotencyKey: `activate:${invitation.invitationId}` }
  }
  async complete(context: ActivationContext, receipt: ActivationReceipt, sessionTokenHash: string, now: Date) {
    await this.db.transaction(async tx => {
      const [run] = await tx.select().from(schema.systemProvisioningRuns).where(and(eq(schema.systemProvisioningRuns.id, context.activationRunRowId), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, context.leaseOwner), eq(schema.systemProvisioningRuns.attempt, context.attemptNumber))).limit(1); if (!run) throw new SystemFactoryError('ACTIVATION_LEASE_LOST', 'Activation lease is no longer owned.', 409)
      const invitationUpdate = await tx.update(schema.systemAdminInvitations).set({ status: 'accepted', acceptedAt: now } as any).where(and(eq(schema.systemAdminInvitations.id, context.invitationRowId), eq(schema.systemAdminInvitations.status, 'pending'), eq(schema.systemAdminInvitations.principalEmailHash, context.principalEmailHash), eq(schema.systemAdminInvitations.roleKey, context.roleKey))); if (affected(invitationUpdate) !== 1) throw new SystemFactoryError('INVITATION_TERMINAL', 'Invitation is no longer claimable.', 409)
      let [membership] = await tx.select().from(schema.managedSiteMemberships).where(and(eq(schema.managedSiteMemberships.ownerUserId, context.ownerUserRowId), eq(schema.managedSiteMemberships.projectId, context.managedSiteProjectId), eq(schema.managedSiteMemberships.principalEmail, context.principalEmail))).limit(1)
      if (membership && membership.status !== 'active') throw new SystemFactoryError('MEMBERSHIP_REVOKED', 'Managed-site membership is revoked.', 409)
      if (!membership) { const membershipId = inserted(await tx.insert(schema.managedSiteMemberships).values({ ownerUserId: context.ownerUserRowId, projectId: context.managedSiteProjectId, principalEmail: context.principalEmail, userId: null, role: portalRole(context.roleKey), status: 'active', invitedAt: now, acceptedAt: now } as any)); [membership] = await tx.select().from(schema.managedSiteMemberships).where(eq(schema.managedSiteMemberships.id, membershipId)).limit(1) } else await tx.update(schema.managedSiteMemberships).set({ acceptedAt: now, updatedAt: now } as any).where(eq(schema.managedSiteMemberships.id, membership.id))
      if (!membership) throw new SystemFactoryError('MEMBERSHIP_INSERT', 'Managed-site membership could not be established.', 500)
      await tx.update(schema.managedSiteSessions).set({ revokedAt: now } as any).where(and(eq(schema.managedSiteSessions.ownerUserId, context.ownerUserRowId), eq(schema.managedSiteSessions.projectId, context.managedSiteProjectId), eq(schema.managedSiteSessions.membershipId, membership.id)))
      await tx.insert(schema.managedSiteSessions).values({ ownerUserId: context.ownerUserRowId, projectId: context.managedSiteProjectId, membershipId: membership.id, sessionHash: sessionTokenHash, expiresAt: new Date(now.getTime() + MANAGED_SITE_SESSION_TTL_MS), revokedAt: null, lastSeenAt: now } as any)
      const localReceiptFingerprint = fingerprint({ schemaVersion: 'system-activation-receipt-v1', activationRunId: context.activationRunId, invitationId: context.invitationId, providerReceipt: receipt.receiptFingerprint, userIdentityHash: receipt.userIdentityHash, roleKey: receipt.roleKey, authority: context.authority.authorityFingerprint })
      await tx.insert(schema.systemReceipts).values({ receiptId: `system-activation-${localReceiptFingerprint.slice(0, 32)}`, ownerUserId: context.ownerUserRowId, systemTenantId: context.tenantRowId, runId: context.activationRunRowId, receiptType: 'activate_admin_invitation', status: receipt.replayed ? 'replayed' : 'verified', requestFingerprint: receipt.requestFingerprint, responseFingerprint: receipt.responseFingerprint, exactResponseIdentity: receipt.exactResponseIdentity, metadata: { invitationId: context.invitationId, principalEmailHash: context.principalEmailHash, roleKey: context.roleKey, userIdentityHash: receipt.userIdentityHash, runtimeAuthorityFingerprint: context.authority.authorityFingerprint, passwordStored: false }, receiptFingerprint: localReceiptFingerprint, createdAt: now } as any)
      const [tenant] = await tx.select().from(schema.systemTenants).where(and(eq(schema.systemTenants.id, context.tenantRowId), eq(schema.systemTenants.state, 'invitation_pending'))).limit(1); if (!tenant) throw new SystemFactoryError('TENANT_STATE_DRIFT', 'Tenant is no longer invitation-pending.', 409)
      const tenantUpdate = await tx.update(schema.systemTenants).set({ state: 'active', stateVersion: tenant.stateVersion + 1, invitationReceiptFingerprint: localReceiptFingerprint, projectionFingerprint: fingerprint({ previous: tenant.projectionFingerprint, state: 'active', localReceiptFingerprint }) } as any).where(and(eq(schema.systemTenants.id, tenant.id), eq(schema.systemTenants.stateVersion, tenant.stateVersion), eq(schema.systemTenants.state, 'invitation_pending'))); if (affected(tenantUpdate) !== 1) throw new SystemFactoryError('TENANT_CAS', 'Tenant activation lost its compare-and-swap.', 409)
      await tx.update(schema.systemSpecs).set({ status: 'active' } as any).where(and(eq(schema.systemSpecs.id, tenant.systemSpecId), eq(schema.systemSpecs.ownerUserId, context.ownerUserRowId)))
      const eventFingerprint = fingerprint({ invitationId: context.invitationId, previousState: 'invitation_pending', nextState: 'active', localReceiptFingerprint }); await tx.insert(schema.systemEvents).values({ eventId: `system-activated-${eventFingerprint.slice(0, 32)}`, ownerUserId: context.ownerUserRowId, systemTenantId: context.tenantRowId, previousState: 'invitation_pending', nextState: 'active', eventType: 'admin_invitation_activated', authorityFingerprint: context.authority.authorityFingerprint, payloadFingerprint: localReceiptFingerprint, eventFingerprint, occurredAt: now } as any)
      const runUpdate = await tx.update(schema.systemProvisioningRuns).set({ status: 'completed', leaseOwner: null, leaseExpiresAt: null, completedAt: now } as any).where(and(eq(schema.systemProvisioningRuns.id, run.id), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, context.leaseOwner))); if (affected(runUpdate) !== 1) throw new SystemFactoryError('ACTIVATION_RUN_CAS', 'Activation completion lost its run claim.', 409)
    })
  }
  async fail(context: ActivationContext, failure: { code: string; retryAt: Date | null; blocked: boolean }, now: Date) { await this.db.update(schema.systemProvisioningRuns).set({ status: failure.blocked ? 'blocked' : 'retry_wait', retryEligibleAt: failure.retryAt, leaseOwner: null, leaseExpiresAt: null, updatedAt: now } as any).where(and(eq(schema.systemProvisioningRuns.id, context.activationRunRowId), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, context.leaseOwner), eq(schema.systemProvisioningRuns.attempt, context.attemptNumber))) }
}
