import { and, asc, eq, gt, lte, or, sql } from 'drizzle-orm'
import type { MySql2Database } from 'drizzle-orm/mysql2'
import * as schema from '../database/schema'
import { fingerprint, SystemFactoryError } from './canonical'
import type { CompiledSystemPlan } from './compiler'
import type { OperationReceipt } from './control-plane'
import type { DurableProvisioningRepositoryPort, ProvisioningAttempt, ProvisioningClaim, ProvisioningFailure, ProvisioningOperation, ProvisioningRunContext } from './provisioning-scheduler'
import { PROVISIONING_OPERATIONS } from './provisioning-scheduler'
import type { SystemFactoryRuntimeAuthority } from './runtime-authority'

type Db = MySql2Database<typeof schema>
function affected(result: any): number { return Number(result?.[0]?.affectedRows || 0) }
function rowId(result: any): number { const value = Number(result?.[0]?.insertId); if (!Number.isSafeInteger(value) || value < 1) throw new SystemFactoryError('DATABASE_INSERT', 'Durable provisioning insert failed.', 500); return value }
function exactSteps(value: unknown): boolean { return Array.isArray(value) && value.length === PROVISIONING_OPERATIONS.length && value.every((step, index) => step && typeof step === 'object' && (step as any).operation === PROVISIONING_OPERATIONS[index] && (step as any).ordinal === index + 1) }
function duplicateEntry(error: unknown): boolean { const value = error as { code?: unknown; errno?: unknown }; return value?.code === 'ER_DUP_ENTRY' || Number(value?.errno) === 1062 }

export function eligibleProvisioningRunsQuery(now: Date, limit: number) {
  const boundedLimit = Math.max(1, Math.min(limit, 20))
  return sql`
    SELECT MIN(candidate.runRowId) AS runRowId, candidate.tenantRowId
    FROM (
      (SELECT MIN(id) AS runRowId, systemTenantId AS tenantRowId FROM systemProvisioningRuns WHERE status = 'queued' GROUP BY systemTenantId)
      UNION ALL
      (SELECT MIN(id), systemTenantId FROM systemProvisioningRuns WHERE status = 'retry_wait' AND retryEligibleAt <= ${sql.param(now, schema.systemProvisioningRuns.retryEligibleAt)} GROUP BY systemTenantId)
      UNION ALL
      (SELECT MIN(id), systemTenantId FROM systemProvisioningRuns WHERE status = 'processing' AND leaseExpiresAt <= ${sql.param(now, schema.systemProvisioningRuns.leaseExpiresAt)} GROUP BY systemTenantId)
    ) candidate
    GROUP BY candidate.tenantRowId
    ORDER BY MIN(candidate.runRowId), candidate.tenantRowId
    LIMIT ${boundedLimit}
  `
}

export class DrizzleProvisioningRepository implements DurableProvisioningRepositoryPort {
  constructor(private readonly db: Db, private readonly authority: SystemFactoryRuntimeAuthority) {}
  async listEligible(now: Date, limit: number) {
    // Three covering range scans avoid the OR/index-merge table lookups seen
    // on MariaDB while retaining one round trip and one earliest run/tenant.
    const [rows] = await this.db.execute(eligibleProvisioningRunsQuery(now, limit)) as unknown as [{ runRowId: number | string; tenantRowId: number }[], unknown]
    return rows.map(row => ({ runRowId: Number(row.runRowId), tenantRowId: row.tenantRowId })).filter(row => Number.isSafeInteger(row.runRowId) && row.runRowId > 0)
  }
  async claim(runRowId: number, leaseOwner: string, now: Date, leaseExpiresAt: Date) {
    return this.db.transaction(async tx => { const result = await tx.update(schema.systemProvisioningRuns).set({ status: 'processing', leaseOwner, leaseExpiresAt, retryEligibleAt: null } as any).where(and(eq(schema.systemProvisioningRuns.id, runRowId), or(eq(schema.systemProvisioningRuns.status, 'queued'), and(eq(schema.systemProvisioningRuns.status, 'retry_wait'), lte(schema.systemProvisioningRuns.retryEligibleAt, now)), and(eq(schema.systemProvisioningRuns.status, 'processing'), lte(schema.systemProvisioningRuns.leaseExpiresAt, now))))); if (affected(result) !== 1) return null; await tx.update(schema.systemProvisioningAttempts).set({ status: 'retry_wait', errorCode: 'STALE_LEASE_RECOVERED', errorSummary: 'Prior worker lease expired before completion.', completedAt: now } as any).where(and(eq(schema.systemProvisioningAttempts.runId, runRowId), eq(schema.systemProvisioningAttempts.status, 'processing'))); return { runRowId, leaseOwner, leaseExpiresAt } })
  }
  async renewLease(claim: ProvisioningClaim, now: Date, leaseExpiresAt: Date) { const result = await this.db.update(schema.systemProvisioningRuns).set({ leaseExpiresAt } as any).where(and(eq(schema.systemProvisioningRuns.id, claim.runRowId), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, claim.leaseOwner), eq(schema.systemProvisioningRuns.leaseExpiresAt, claim.leaseExpiresAt), gt(schema.systemProvisioningRuns.leaseExpiresAt, now))); return affected(result) === 1 ? { ...claim, leaseExpiresAt } : null }
  private async owned(claim: ProvisioningClaim, tx: Db = this.db, now?: Date) { const conditions = [eq(schema.systemProvisioningRuns.id, claim.runRowId), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, claim.leaseOwner), eq(schema.systemProvisioningRuns.leaseExpiresAt, claim.leaseExpiresAt)]; if (now) conditions.push(gt(schema.systemProvisioningRuns.leaseExpiresAt, now)); const [run] = await tx.select({ id: schema.systemProvisioningRuns.id, runId: schema.systemProvisioningRuns.runId, ownerUserId: schema.systemProvisioningRuns.ownerUserId, systemTenantId: schema.systemProvisioningRuns.systemTenantId, planId: schema.systemProvisioningRuns.planId, status: schema.systemProvisioningRuns.status, attempt: schema.systemProvisioningRuns.attempt, maxAttempts: schema.systemProvisioningRuns.maxAttempts, leaseOwner: schema.systemProvisioningRuns.leaseOwner, leaseExpiresAt: schema.systemProvisioningRuns.leaseExpiresAt, retryEligibleAt: schema.systemProvisioningRuns.retryEligibleAt, inputFingerprint: schema.systemProvisioningRuns.inputFingerprint, idempotencyKey: schema.systemProvisioningRuns.idempotencyKey, createdAt: schema.systemProvisioningRuns.createdAt }).from(schema.systemProvisioningRuns).where(and(...conditions)).limit(1); if (!run || !run.leaseExpiresAt || run.leaseExpiresAt.getTime() !== claim.leaseExpiresAt.getTime()) throw new SystemFactoryError('LEASE_LOST', 'Provisioning lease is no longer owned.', 409); return run }
  async loadContext(claim: ProvisioningClaim): Promise<ProvisioningRunContext> {
    const run = await this.owned(claim)
    const [[plan], [tenant], [binding], refs] = await Promise.all([
      this.db.select().from(schema.systemProvisioningPlans).where(eq(schema.systemProvisioningPlans.id, run.planId)).limit(1),
      this.db.select().from(schema.systemTenants).where(and(eq(schema.systemTenants.id, run.systemTenantId), eq(schema.systemTenants.ownerUserId, run.ownerUserId))).limit(1),
      this.db.select().from(schema.systemTenantBindings).where(and(eq(schema.systemTenantBindings.systemTenantId, run.systemTenantId), eq(schema.systemTenantBindings.ownerUserId, run.ownerUserId))).limit(1),
      this.db.select().from(schema.systemConnectionRefs).where(and(eq(schema.systemConnectionRefs.systemTenantId, run.systemTenantId), eq(schema.systemConnectionRefs.ownerUserId, run.ownerUserId), eq(schema.systemConnectionRefs.status, 'active'))),
    ])
    const actualVersion = plan ? (await this.db.select().from(schema.systemSpecVersions).where(and(eq(schema.systemSpecVersions.id, plan.systemSpecVersionId), eq(schema.systemSpecVersions.ownerUserId, run.ownerUserId))).limit(1))[0] : null
    if (!plan || !tenant || !binding || !actualVersion || !exactSteps(plan.steps) || tenant.compiledPlanFingerprint !== actualVersion.compiledPlanFingerprint || tenant.specFingerprint !== actualVersion.specFingerprint || run.inputFingerprint !== plan.planFingerprint) throw new SystemFactoryError('PROVISIONING_LINEAGE', 'Stored provisioning lineage is incomplete or mismatched.', 409)
    const control = refs.find(ref => ref.purpose === 'frappe_site_admin'); const tenantApp = refs.find(ref => ref.purpose === 'frappe_internal_hmac'); if (!control || !tenantApp) throw new SystemFactoryError('MISSING_CREDENTIAL', 'Required opaque connection references are unavailable.', 503)
    const siteName = `tenant-${fingerprint({ tenant: tenant.systemTenantId }).slice(0, 24)}.factory.invalid`
    return { runRowId: run.id, runPublicId: run.runId, planRowId: plan.id, ownerUserRowId: run.ownerUserId, tenantRowId: tenant.id, systemSpecRowId: tenant.systemSpecId, runAttempt: run.attempt, maxAttempts: run.maxAttempts, planFingerprint: plan.planFingerprint, ownerId: `owner:${run.ownerUserId}`, clientId: `client:${tenant.clientId}`, websiteId: binding.websiteId, managedSiteId: binding.managedSiteProjectId ? `managed-site:${binding.managedSiteProjectId}` : null, systemTenantId: tenant.systemTenantId, siteName, controlPlaneCredentialReference: control.opaqueReference, tenantAppCredentialReference: tenantApp.opaqueReference, idempotencyKey: run.idempotencyKey, compiledPlan: actualVersion.compiledPlan as CompiledSystemPlan, executionMode: 'live', runtimeAuthority: this.authority }
  }
  async completedOperations(claim: ProvisioningClaim) { await this.owned(claim); const rows = await this.db.select({ operation: schema.systemProvisioningAttempts.operation }).from(schema.systemProvisioningAttempts).where(and(eq(schema.systemProvisioningAttempts.runId, claim.runRowId), eq(schema.systemProvisioningAttempts.status, 'succeeded'))); return rows.map(row => row.operation).filter((value): value is ProvisioningOperation => PROVISIONING_OPERATIONS.includes(value as ProvisioningOperation)) }
  async beginAttempt(claim: ProvisioningClaim, operation: ProvisioningOperation, requestFingerprint: string, now: Date, timeoutMs: number): Promise<ProvisioningAttempt> {
    const run = await this.owned(claim, this.db, now); const prior = await this.db.select({ requestFingerprint: schema.systemProvisioningAttempts.requestFingerprint, status: schema.systemProvisioningAttempts.status, attemptNumber: schema.systemProvisioningAttempts.attemptNumber }).from(schema.systemProvisioningAttempts).where(and(eq(schema.systemProvisioningAttempts.runId, run.id), eq(schema.systemProvisioningAttempts.operation, operation))).orderBy(asc(schema.systemProvisioningAttempts.attemptNumber))
    if (prior.some(item => item.requestFingerprint !== requestFingerprint)) throw new SystemFactoryError('IDEMPOTENCY_COLLISION', 'Provisioning operation payload changed under the same run.', 409)
    if (prior.some(item => item.status === 'succeeded')) throw new SystemFactoryError('IDEMPOTENCY_REPLAY', 'Provisioning operation has already succeeded.', 409)
    const attemptNumber = prior.length + 1; if (attemptNumber > run.maxAttempts) throw new SystemFactoryError('ATTEMPT_EXHAUSTED', 'Provisioning operation exhausted bounded attempts.', 409)
    try { await this.db.insert(schema.systemProvisioningAttempts).values({ ownerUserId: run.ownerUserId, systemTenantId: run.systemTenantId, runId: run.id, operation, attemptNumber, status: 'processing', timeoutMs, requestFingerprint, createdAt: now } as any) } catch (error) {
      if (!duplicateEntry(error)) throw error
      const current = await this.db.select({ requestFingerprint: schema.systemProvisioningAttempts.requestFingerprint, status: schema.systemProvisioningAttempts.status }).from(schema.systemProvisioningAttempts).where(and(eq(schema.systemProvisioningAttempts.runId, run.id), eq(schema.systemProvisioningAttempts.operation, operation), eq(schema.systemProvisioningAttempts.attemptNumber, attemptNumber))).limit(1)
      if (!current[0] || current[0].requestFingerprint !== requestFingerprint) throw new SystemFactoryError('IDEMPOTENCY_COLLISION', 'Concurrent provisioning operation payload changed under the same attempt.', 409)
      throw new SystemFactoryError(current[0].status === 'succeeded' ? 'IDEMPOTENCY_REPLAY' : 'ATTEMPT_IN_PROGRESS', 'Provisioning operation attempt is already claimed.', 409)
    }
    return { operation, attemptNumber, requestFingerprint, startedAt: now }
  }
  async blockClaim(claim: ProvisioningClaim, code: string, now: Date) { const run = await this.owned(claim, this.db, now); const receiptFingerprint = fingerprint({ runId: run.runId, code, authority: this.authority.authorityFingerprint, blockedAt: now.toISOString() }); await this.db.transaction(async tx => { const result = await tx.update(schema.systemProvisioningRuns).set({ status: 'blocked', leaseOwner: null, leaseExpiresAt: null } as any).where(and(eq(schema.systemProvisioningRuns.id, run.id), eq(schema.systemProvisioningRuns.status, 'processing'), eq(schema.systemProvisioningRuns.leaseOwner, claim.leaseOwner), eq(schema.systemProvisioningRuns.leaseExpiresAt, claim.leaseExpiresAt), gt(schema.systemProvisioningRuns.leaseExpiresAt, now))); if (affected(result) !== 1) throw new SystemFactoryError('RUN_CAS', 'Provisioning blocked transition lost its claim.', 409); await tx.insert(schema.systemReceipts).values({ receiptId: `system-blocked-${receiptFingerprint.slice(0, 32)}`, ownerUserId: run.ownerUserId, systemTenantId: run.systemTenantId, runId: run.id, receiptType: 'provisioning_claim', status: 'blocked', requestFingerprint: run.inputFingerprint, responseFingerprint: null, exactResponseIdentity: null, metadata: { code: code.slice(0, 96), authorityFingerprint: this.authority.authorityFingerprint }, receiptFingerprint, createdAt: now } as any) }) }
  async commitSuccess(claim: ProvisioningClaim, context: ProvisioningRunContext, attempt: ProvisioningAttempt, receipt: OperationReceipt, now: Date, terminal: boolean) {
    await this.db.transaction(async tx => {
      const run = await this.owned(claim, tx as Db, now); const updated = await tx.update(schema.systemProvisioningAttempts).set({ status: 'succeeded', responseFingerprint: receipt.responseFingerprint, exactResponseIdentity: receipt.exactResponseIdentity, completedAt: now } as any).where(and(eq(schema.systemProvisioningAttempts.runId, run.id), eq(schema.systemProvisioningAttempts.operation, attempt.operation), eq(schema.systemProvisioningAttempts.attemptNumber, attempt.attemptNumber), eq(schema.systemProvisioningAttempts.status, 'processing'), eq(schema.systemProvisioningAttempts.requestFingerprint, attempt.requestFingerprint))); if (affected(updated) !== 1) throw new SystemFactoryError('ATTEMPT_CAS', 'Provisioning attempt lost its transaction claim.', 409)
      const serverReceiptFingerprint = fingerprint({ schemaVersion: 'durable-provisioning-receipt-v1', operation: attempt.operation, runId: context.runPublicId, attempt: attempt.attemptNumber, requestFingerprint: attempt.requestFingerprint, providerReceiptFingerprint: receipt.receiptFingerprint, responseFingerprint: receipt.responseFingerprint, exactResponseIdentity: receipt.exactResponseIdentity, authority: context.runtimeAuthority })
      await tx.insert(schema.systemReceipts).values({ receiptId: `system-receipt-${serverReceiptFingerprint.slice(0, 32)}`, ownerUserId: run.ownerUserId, systemTenantId: run.systemTenantId, runId: run.id, receiptType: attempt.operation, status: receipt.replayed ? 'replayed' : 'verified', requestFingerprint: attempt.requestFingerprint, responseFingerprint: receipt.responseFingerprint, exactResponseIdentity: receipt.exactResponseIdentity, metadata: { attempt: attempt.attemptNumber, startedAt: attempt.startedAt.toISOString(), completedAt: now.toISOString(), providerReceiptFingerprint: receipt.receiptFingerprint, runtimeAuthority: context.runtimeAuthority, externalCalls: receipt.externalCalls }, receiptFingerprint: serverReceiptFingerprint, createdAt: now } as any)
      const nextState = terminal ? 'invitation_pending' : attempt.operation === 'health_check' ? 'health_checking' : 'provisioning'; const tenantUpdates: any = { state: nextState, stateVersion: undefined, projectionFingerprint: fingerprint({ run: context.runPublicId, operation: attempt.operation, serverReceiptFingerprint }) }; if (attempt.operation === 'health_check') tenantUpdates.healthyReceiptFingerprint = serverReceiptFingerprint; delete tenantUpdates.stateVersion
      const [tenant] = await tx.select().from(schema.systemTenants).where(and(eq(schema.systemTenants.id, run.systemTenantId), eq(schema.systemTenants.ownerUserId, run.ownerUserId))).limit(1); if (!tenant) throw new SystemFactoryError('TENANT_MISSING', 'Provisioning tenant disappeared.', 409); tenantUpdates.stateVersion = tenant.stateVersion + 1
      const tenantResult = await tx.update(schema.systemTenants).set(tenantUpdates).where(and(eq(schema.systemTenants.id, tenant.id), eq(schema.systemTenants.stateVersion, tenant.stateVersion))); if (affected(tenantResult) !== 1) throw new SystemFactoryError('TENANT_CAS', 'Tenant projection lost its compare-and-swap.', 409)
      const specResult = await tx.update(schema.systemSpecs).set({ status: nextState } as any).where(and(eq(schema.systemSpecs.id, context.systemSpecRowId), eq(schema.systemSpecs.ownerUserId, run.ownerUserId))); if (affected(specResult) !== 1) throw new SystemFactoryError('SPEC_CAS', 'System specification projection update did not affect exactly one row.', 409)
      const planResult = await tx.update(schema.systemProvisioningPlans).set({ status: terminal ? 'invitation_pending' : attempt.operation === 'health_check' ? 'health_checking' : 'running' } as any).where(and(eq(schema.systemProvisioningPlans.id, run.planId), eq(schema.systemProvisioningPlans.systemTenantId, run.systemTenantId))); if (affected(planResult) !== 1) throw new SystemFactoryError('PLAN_CAS', 'Provisioning plan projection update did not affect exactly one row.', 409)
      if (terminal) { const done = await tx.update(schema.systemProvisioningRuns).set({ status: 'completed', leaseOwner: null, leaseExpiresAt: null, completedAt: now } as any).where(and(eq(schema.systemProvisioningRuns.id, run.id), eq(schema.systemProvisioningRuns.leaseOwner, claim.leaseOwner), eq(schema.systemProvisioningRuns.leaseExpiresAt, claim.leaseExpiresAt), gt(schema.systemProvisioningRuns.leaseExpiresAt, now), eq(schema.systemProvisioningRuns.status, 'processing'))); if (affected(done) !== 1) throw new SystemFactoryError('RUN_CAS', 'Provisioning run completion lost its claim.', 409) }
    })
  }
  async commitFailure(claim: ProvisioningClaim, context: ProvisioningRunContext, attempt: ProvisioningAttempt, failure: ProvisioningFailure, now: Date) {
    await this.db.transaction(async tx => { const run = await this.owned(claim, tx as Db, now); const attemptUpdate = await tx.update(schema.systemProvisioningAttempts).set({ status: failure.retryable ? 'retry_wait' : 'blocked', errorCode: failure.code, errorSummary: failure.summary, completedAt: now } as any).where(and(eq(schema.systemProvisioningAttempts.runId, run.id), eq(schema.systemProvisioningAttempts.operation, attempt.operation), eq(schema.systemProvisioningAttempts.attemptNumber, attempt.attemptNumber), eq(schema.systemProvisioningAttempts.status, 'processing'), eq(schema.systemProvisioningAttempts.requestFingerprint, attempt.requestFingerprint))); if (affected(attemptUpdate) !== 1) throw new SystemFactoryError('ATTEMPT_CAS', 'Provisioning failure attempt lost its transaction claim.', 409); const next = failure.retryable ? 'retry_wait' : 'blocked'; const runUpdate = await tx.update(schema.systemProvisioningRuns).set({ status: next, attempt: Math.max(run.attempt, attempt.attemptNumber), retryEligibleAt: failure.retryAt, leaseOwner: null, leaseExpiresAt: null } as any).where(and(eq(schema.systemProvisioningRuns.id, run.id), eq(schema.systemProvisioningRuns.leaseOwner, claim.leaseOwner), eq(schema.systemProvisioningRuns.leaseExpiresAt, claim.leaseExpiresAt), gt(schema.systemProvisioningRuns.leaseExpiresAt, now), eq(schema.systemProvisioningRuns.status, 'processing'))); if (affected(runUpdate) !== 1) throw new SystemFactoryError('RUN_CAS', 'Provisioning failure transition lost its claim.', 409); const failureFingerprint = fingerprint({ run: context.runPublicId, operation: attempt.operation, attempt: attempt.attemptNumber, code: failure.code, authority: context.runtimeAuthority.authorityFingerprint }); await tx.insert(schema.systemReceipts).values({ receiptId: `system-failure-${failureFingerprint.slice(0, 32)}`, ownerUserId: run.ownerUserId, systemTenantId: run.systemTenantId, runId: run.id, receiptType: attempt.operation, status: failure.retryable ? 'failed' : 'blocked', requestFingerprint: attempt.requestFingerprint, responseFingerprint: null, exactResponseIdentity: null, metadata: { attempt: attempt.attemptNumber, code: failure.code, retryAt: failure.retryAt?.toISOString() || null, runtimeAuthorityFingerprint: context.runtimeAuthority.authorityFingerprint }, receiptFingerprint: failureFingerprint, createdAt: now } as any) })
  }
}
