import { randomBytes, scryptSync } from 'node:crypto'
import { and, desc, eq, lt, or } from 'drizzle-orm'
import { createError } from 'h3'
import { getDatabase } from '../database'
import { contentOperationClients, managedSiteDraftOrders, managedSitePaymentEvents, managedSitePreviews, managedSiteProjects, managedSiteQuotes, systemAdminInvitations, systemEvents, systemPreviews, systemProvisioningPlans, systemProvisioningRuns, systemReceipts, systemSpecVersions, systemSpecs, systemTenantBindings, systemTenants, systemUpgradeIntents, systemUpgradeReceipts, systemUpgradeRuns } from '../database/schema'
import { compileSystemSpec } from './compiler'
import { fingerprint, normalizeText, SystemFactoryError } from './canonical'
import { planSystemSpec, type SystemPlannerInput, type SystemPlannerPort } from './planner'
import { buildSystemPreview } from './preview'

function databaseRequired() { const database = getDatabase(); if (!database) throw createError({ statusCode: 503, statusMessage: 'System Factory is temporarily unavailable.' }); return database }
function rowId(result: any): number { const id = Number(result?.[0]?.insertId); if (!Number.isSafeInteger(id) || id < 1) throw createError({ statusCode: 500, statusMessage: 'System Factory record could not be created.' }); return id }
function affected(result: any): number { return Number(result?.[0]?.affectedRows || 0) }
function duplicateEntry(error: unknown): boolean { const value = error as { code?: unknown; errno?: unknown }; return value?.code === 'ER_DUP_ENTRY' || Number(value?.errno) === 1062 }
function key(value: unknown, label = 'Idempotency key'): string { const result = normalizeText(value, label, 128); if (!/^[A-Za-z0-9][A-Za-z0-9:._-]{7,127}$/u.test(result)) throw new SystemFactoryError('INVALID_IDEMPOTENCY_KEY', `${label} is invalid.`); return result }

export type CreateSystemDraftInput = Omit<SystemPlannerInput, 'identity'> & { clientId: number; websiteId?: string | null; managedSiteProjectId?: number | null; idempotencyKey: string }

export async function createSystemDraft(ownerUserId: number, input: CreateSystemDraftInput, provider?: SystemPlannerPort) {
  const database = databaseRequired(); const clientId = Number(input.clientId); const managedSiteProjectId = input.managedSiteProjectId === null || input.managedSiteProjectId === undefined ? null : Number(input.managedSiteProjectId); const idempotencyKey = key(input.idempotencyKey)
  if (!Number.isSafeInteger(clientId) || clientId < 1 || (managedSiteProjectId !== null && (!Number.isSafeInteger(managedSiteProjectId) || managedSiteProjectId < 1))) throw new SystemFactoryError('INVALID_LINEAGE', 'Client or Managed Site identity is invalid.')
  const [client] = await database.select().from(contentOperationClients).where(and(eq(contentOperationClients.id, clientId), eq(contentOperationClients.ownerUserId, ownerUserId))).limit(1); if (!client) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped client was not found.' })
  const managedSite = managedSiteProjectId === null ? null : (await database.select().from(managedSiteProjects).where(and(eq(managedSiteProjects.id, managedSiteProjectId), eq(managedSiteProjects.ownerUserId, ownerUserId))).limit(1))[0] || null
  if (managedSiteProjectId !== null && !managedSite) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped Managed Site was not found.' })
  const websiteId = input.websiteId ? normalizeText(input.websiteId, 'Website id', 128) : `content-client:${clientId}`
  const identityFingerprint = fingerprint({ ownerUserId, clientId, websiteId, managedSiteProjectId })
  const [replay] = await database.select().from(systemSpecs).where(and(eq(systemSpecs.ownerUserId, ownerUserId), eq(systemSpecs.creationIdempotencyKey, idempotencyKey))).limit(1)
  if (replay) { if (replay.identityFingerprint !== identityFingerprint) throw createError({ statusCode: 409, statusMessage: 'System draft idempotency key is already bound to different lineage.' }); return { ...await getSystemWorkspace(ownerUserId, replay.id), replayed: true } }
  const specPublicId = `system-spec-${fingerprint({ identityFingerprint, idempotencyKey }).slice(0, 24)}`
  const planned = await planSystemSpec({ requirements: input.requirements, businessType: input.businessType, industry: input.industry, preferredTemplate: input.preferredTemplate, requestedCapabilities: input.requestedCapabilities, version: input.version, parentFingerprint: input.parentFingerprint, identity: { specId: specPublicId, ownerId: `owner:${ownerUserId}`, clientId: `client:${clientId}`, websiteId, managedSiteId: managedSiteProjectId ? `managed-site:${managedSiteProjectId}` : null, systemTenantId: null, locale: 'zh-hant', timezone: client.timeZone, currency: 'TWD' } }, provider)
  const compiled = compileSystemSpec(planned.spec); const preview = buildSystemPreview(planned.spec, compiled, { version: 1 }); const requestFingerprint = fingerprint({ input: { ...input, idempotencyKey: undefined }, mode: planned.mode })
  let created: { specRowId: number; versionRowId: number; previewRowId: number }
  try { created = await database.transaction(async tx => {
    const specRowId = rowId(await tx.insert(systemSpecs).values({ specId: specPublicId, ownerUserId, clientId, websiteId, managedSiteProjectId, activeVersionId: null, status: 'preview_ready', identityFingerprint, creationIdempotencyKey: idempotencyKey } as any))
    const versionRowId = rowId(await tx.insert(systemSpecVersions).values({ ownerUserId, systemSpecId: specRowId, version: planned.spec.version, parentVersionId: null, parentFingerprint: planned.spec.parentFingerprint, schemaVersion: planned.spec.schemaVersion, compilerVersion: compiled.compilerVersion, normalizedSpec: planned.spec, compiledPlan: compiled, specFingerprint: planned.spec.fingerprint, compiledPlanFingerprint: compiled.planFingerprint, requestFingerprint, idempotencyKey: `${idempotencyKey}:version:${planned.spec.version}`, createdByAuthority: planned.mode } as any))
    const previewRowId = rowId(await tx.insert(systemPreviews).values({ previewId: preview.previewId, ownerUserId, systemSpecId: specRowId, systemSpecVersionId: versionRowId, managedSitePreviewId: null, version: preview.version, parentPreviewId: null, specFingerprint: preview.specFingerprint, fixtureFingerprint: preview.fixtureFingerprint, compiledPlanFingerprint: preview.compiledPlanFingerprint, fixtureProjection: preview, status: preview.status, noProductionData: true, expiresAt: new Date(preview.expiresAt) } as any))
    const activeUpdate = await tx.update(systemSpecs).set({ activeVersionId: versionRowId } as any).where(and(eq(systemSpecs.id, specRowId), eq(systemSpecs.ownerUserId, ownerUserId))); if (affected(activeUpdate) !== 1) throw new SystemFactoryError('SPEC_CAS', 'System draft active version was not updated.', 409)
    return { specRowId, versionRowId, previewRowId }
  }) } catch (error) {
    if (!duplicateEntry(error)) throw error
    const [existing] = await database.select().from(systemSpecs).where(and(eq(systemSpecs.ownerUserId, ownerUserId), eq(systemSpecs.creationIdempotencyKey, idempotencyKey))).limit(1)
    if (!existing || existing.identityFingerprint !== identityFingerprint) throw createError({ statusCode: 409, statusMessage: 'System draft concurrency collided with different lineage.' })
    return { ...await getSystemWorkspace(ownerUserId, existing.id), plannerMode: planned.mode, replayed: true }
  }
  return { ...await getSystemWorkspace(ownerUserId, created.specRowId), plannerMode: planned.mode, replayed: false }
}

export async function listSystemWorkspaces(ownerUserId: number, limit = 50, cursor?: { updatedAt: Date; id: number } | null) {
  const database = databaseRequired(); const boundedLimit = Math.max(1, Math.min(limit, 100)); const cursorWhere = cursor ? or(lt(systemSpecs.updatedAt, cursor.updatedAt), and(eq(systemSpecs.updatedAt, cursor.updatedAt), lt(systemSpecs.id, cursor.id))) : undefined
  const rows = await database.select({ id: systemSpecs.id, specId: systemSpecs.specId, clientId: systemSpecs.clientId, websiteId: systemSpecs.websiteId, managedSiteProjectId: systemSpecs.managedSiteProjectId, status: systemSpecs.status, identityFingerprint: systemSpecs.identityFingerprint, createdAt: systemSpecs.createdAt, updatedAt: systemSpecs.updatedAt }).from(systemSpecs).where(cursorWhere ? and(eq(systemSpecs.ownerUserId, ownerUserId), cursorWhere) : eq(systemSpecs.ownerUserId, ownerUserId)).orderBy(desc(systemSpecs.updatedAt), desc(systemSpecs.id)).limit(boundedLimit + 1)
  const page = rows.slice(0, boundedLimit); const last = page.at(-1); return { items: page, nextCursor: rows.length > boundedLimit && last ? Buffer.from(JSON.stringify({ updatedAt: last.updatedAt.toISOString(), id: last.id }), 'utf8').toString('base64url') : null }
}

export async function getSystemWorkspace(ownerUserId: number, systemSpecId: number) {
  const database = databaseRequired(); const [spec] = await database.select().from(systemSpecs).where(and(eq(systemSpecs.ownerUserId, ownerUserId), eq(systemSpecs.id, systemSpecId))).limit(1); if (!spec) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped system was not found.' })
  const [versions, previews, tenants] = await Promise.all([database.select().from(systemSpecVersions).where(and(eq(systemSpecVersions.ownerUserId, ownerUserId), eq(systemSpecVersions.systemSpecId, spec.id))).orderBy(desc(systemSpecVersions.version)).limit(100), database.select().from(systemPreviews).where(and(eq(systemPreviews.ownerUserId, ownerUserId), eq(systemPreviews.systemSpecId, spec.id))).orderBy(desc(systemPreviews.version)).limit(100), database.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemSpecId, spec.id))).limit(1)])
  const tenant = tenants[0] || null; const [bindings, receipts, events, invitations, upgradeIntents, upgradeRuns, upgradeReceipts] = tenant ? await Promise.all([database.select().from(systemTenantBindings).where(and(eq(systemTenantBindings.ownerUserId, ownerUserId), eq(systemTenantBindings.systemTenantId, tenant.id))).limit(1), database.select().from(systemReceipts).where(and(eq(systemReceipts.ownerUserId, ownerUserId), eq(systemReceipts.systemTenantId, tenant.id))).orderBy(desc(systemReceipts.createdAt)).limit(200), database.select().from(systemEvents).where(and(eq(systemEvents.ownerUserId, ownerUserId), eq(systemEvents.systemTenantId, tenant.id))).orderBy(desc(systemEvents.createdAt)).limit(200), database.select().from(systemAdminInvitations).where(and(eq(systemAdminInvitations.ownerUserId, ownerUserId), eq(systemAdminInvitations.systemTenantId, tenant.id))).orderBy(desc(systemAdminInvitations.createdAt)).limit(100), database.select().from(systemUpgradeIntents).where(and(eq(systemUpgradeIntents.ownerUserId, ownerUserId), eq(systemUpgradeIntents.systemTenantId, tenant.id))).orderBy(desc(systemUpgradeIntents.createdAt)).limit(50), database.select().from(systemUpgradeRuns).where(and(eq(systemUpgradeRuns.ownerUserId, ownerUserId), eq(systemUpgradeRuns.systemTenantId, tenant.id))).orderBy(desc(systemUpgradeRuns.createdAt)).limit(50), database.select().from(systemUpgradeReceipts).where(and(eq(systemUpgradeReceipts.ownerUserId, ownerUserId), eq(systemUpgradeReceipts.systemTenantId, tenant.id))).orderBy(desc(systemUpgradeReceipts.createdAt)).limit(100)]) : [[], [], [], [], [], [], []]
  return { system: spec, versions, previews, tenant, binding: bindings[0] || null, receipts, events, invitations: invitations.map(({ tokenHash: _tokenHash, ...safe }) => safe), upgrades: { intents: upgradeIntents, runs: upgradeRuns, receipts: upgradeReceipts }, authority: { commerce: 'managed_site_server_authority', contentPublication: 'content_operations_publication_receipts', payment: 'verified_managed_site_payment_event_only', browserMayMarkPaid: false }, limitations: ['Preview fixtures are synthetic and are not a deployed ERP.', 'No production health is claimed without an exact verified health receipt.', 'Private CRM/ERP records are excluded from GEO/model learning by default.'] }
}

export async function createSystemAdminInvitation(ownerUserId: number, tenantPublicId: string, input: { email: string; roleKey: string; idempotencyKey: string }, now = new Date()) {
  const database = databaseRequired(); const email = normalizeText(input.email, 'Invitation email', 320).toLocaleLowerCase('en-US'); if (!/^\S+@\S+\.\S+$/u.test(email)) throw new SystemFactoryError('INVALID_EMAIL', 'Invitation email is invalid.'); const roleKey = normalizeText(input.roleKey, 'Invitation role', 64); const idempotencyKey = key(input.idempotencyKey); const principalEmailHash = fingerprint({ email }); const requestFingerprint = fingerprint({ tenantPublicId, principalEmailHash, roleKey }); const invitationId = `system-invite-${fingerprint({ ownerUserId, idempotencyKey }).slice(0, 24)}`; const expiresAt = new Date(now.getTime() + 72 * 60 * 60 * 1000); const token = randomBytes(32).toString('base64url'); const tokenHash = fingerprint({ token })
  try {
    await database.transaction(async tx => {
      const [tenant] = await tx.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemTenantId, tenantPublicId))).limit(1); if (!tenant) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped system tenant was not found.' }); if (tenant.state !== 'invitation_pending' && tenant.state !== 'active' || !tenant.healthyReceiptFingerprint) throw createError({ statusCode: 409, statusMessage: 'Healthy tenant state is required before an invitation.' })
      const [version] = await tx.select({ compiledPlan: systemSpecVersions.compiledPlan, compiledPlanFingerprint: systemSpecVersions.compiledPlanFingerprint }).from(systemSpecVersions).where(and(eq(systemSpecVersions.id, tenant.systemSpecVersionId), eq(systemSpecVersions.ownerUserId, ownerUserId))).limit(1); const plan = version?.compiledPlan as any; const role = plan?.materializationManifest?.units?.find((unit: any) => unit?.kind === 'role' && unit?.key === roleKey)
      const [roleReceipt] = await tx.select({ id: systemReceipts.id }).from(systemReceipts).where(and(eq(systemReceipts.ownerUserId, ownerUserId), eq(systemReceipts.systemTenantId, tenant.id), eq(systemReceipts.receiptType, 'create_roles_permissions'))).limit(1)
      if (!version || version.compiledPlanFingerprint !== tenant.compiledPlanFingerprint || !role || !roleReceipt) throw createError({ statusCode: 409, statusMessage: 'Invitation role is not an active materialized role authority.' })
      await tx.insert(systemAdminInvitations).values({ invitationId, ownerUserId, systemTenantId: tenant.id, principalEmailHash, tokenHash, roleKey, idempotencyKey, requestFingerprint, status: 'pending', expiresAt } as any)
    })
  } catch (error) {
    if (!duplicateEntry(error)) throw error
    const [existing] = await database.select().from(systemAdminInvitations).where(and(eq(systemAdminInvitations.ownerUserId, ownerUserId), eq(systemAdminInvitations.idempotencyKey, idempotencyKey))).limit(1)
    if (!existing || existing.requestFingerprint !== requestFingerprint) throw createError({ statusCode: 409, statusMessage: 'Invitation idempotency key is bound to a different request.' })
    return { invitation: { invitationId: existing.invitationId, roleKey: existing.roleKey, status: existing.status, expiresAt: existing.expiresAt }, token: null, replayed: true }
  }
  return { invitation: { invitationId, roleKey, status: 'pending' as const, expiresAt }, token, replayed: false }
}

export async function validateInvitationAcceptance(input: { token: string; password: string }, now = new Date()) {
  const database = databaseRequired(); const token = normalizeText(input.token, 'Invitation token', 256); if (token.length < 32) throw createError({ statusCode: 404, statusMessage: 'System invitation is invalid or expired.' }); const tokenHash = fingerprint({ token }); const [invitation] = await database.select().from(systemAdminInvitations).where(eq(systemAdminInvitations.tokenHash, tokenHash)).limit(1); if (!invitation || invitation.status !== 'pending' || invitation.expiresAt.getTime() <= now.getTime()) throw createError({ statusCode: 404, statusMessage: 'System invitation is invalid or expired.' })
  const password = String(input.password || ''); if (password.length < 14 || password.length > 256 || !/[A-Z]/u.test(password) || !/[a-z]/u.test(password) || !/[0-9]/u.test(password)) throw new SystemFactoryError('WEAK_PASSWORD', 'Initial password does not meet the bounded strength contract.'); scryptSync(password, invitation.tokenHash, 32)
  return { invitationId: invitation.invitationId, systemTenantRowId: invitation.systemTenantId, activationRequired: true as const, passwordStored: false as const }
}

export async function getCustomerSystemStatus(ownerUserId: number, managedSiteProjectId: number) {
  const database = databaseRequired()
  const [spec] = await database.select({ id: systemSpecs.id, specId: systemSpecs.specId, status: systemSpecs.status, activeVersionId: systemSpecs.activeVersionId, updatedAt: systemSpecs.updatedAt }).from(systemSpecs).where(and(eq(systemSpecs.ownerUserId, ownerUserId), eq(systemSpecs.managedSiteProjectId, managedSiteProjectId))).limit(1)
  if (!spec) return { system: null, available: false, message: 'No system service is linked to this Managed Site.' }
  const [tenant] = await database.select({ systemTenantId: systemTenants.systemTenantId, state: systemTenants.state, healthyReceiptFingerprint: systemTenants.healthyReceiptFingerprint, updatedAt: systemTenants.updatedAt }).from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemSpecId, spec.id))).limit(1)
  return { system: { specId: spec.specId, status: spec.status, versionAvailable: Boolean(spec.activeVersionId), tenant: tenant ? { systemTenantId: tenant.systemTenantId, state: tenant.state, healthVerified: Boolean(tenant.healthyReceiptFingerprint), updatedAt: tenant.updatedAt, adminLaunchAvailable: tenant.state === 'active' && Boolean(tenant.healthyReceiptFingerprint), adminLaunchUrl: null } : null }, available: true, privacy: { credentialsExposed: false, administratorCredentialExposed: false, sourceArchiveAvailable: false } }
}

const PROVISIONING_STEPS = ['create_site', 'install_app', 'apply_compiled_spec', 'create_roles_permissions', 'configure_modules', 'health_check', 'create_admin_invitation'] as const

export async function planSystemProvisioning(ownerUserId: number, input: { systemSpecId: number; managedSiteDraftOrderId: number; managedSitePaymentEventId: number; idempotencyKey: string }) {
  const database = databaseRequired(); const idempotencyKey = key(input.idempotencyKey); const systemSpecId = Number(input.systemSpecId); const orderId = Number(input.managedSiteDraftOrderId); const paymentId = Number(input.managedSitePaymentEventId)
  if (![systemSpecId, orderId, paymentId].every(value => Number.isSafeInteger(value) && value > 0)) throw new SystemFactoryError('INVALID_LINEAGE', 'Provisioning lineage identifiers are invalid.')
  const [spec] = await database.select().from(systemSpecs).where(and(eq(systemSpecs.id, systemSpecId), eq(systemSpecs.ownerUserId, ownerUserId))).limit(1); if (!spec || !spec.activeVersionId || !spec.managedSiteProjectId) throw createError({ statusCode: 404, statusMessage: 'Provisionable owner-scoped system was not found.' })
  const [[version], [order], [payment]] = await Promise.all([database.select().from(systemSpecVersions).where(and(eq(systemSpecVersions.id, spec.activeVersionId), eq(systemSpecVersions.ownerUserId, ownerUserId))).limit(1), database.select().from(managedSiteDraftOrders).where(and(eq(managedSiteDraftOrders.id, orderId), eq(managedSiteDraftOrders.ownerUserId, ownerUserId))).limit(1), database.select().from(managedSitePaymentEvents).where(and(eq(managedSitePaymentEvents.id, paymentId), eq(managedSitePaymentEvents.ownerUserId, ownerUserId))).limit(1)])
  if (!version || !order || !payment || order.projectId !== spec.managedSiteProjectId || order.status !== 'payment_verified' || payment.verificationStatus !== 'verified' || payment.draftOrderId !== order.id || payment.previewId !== order.previewId || payment.quoteId !== order.quoteId) throw createError({ statusCode: 409, statusMessage: 'Verified Managed Site payment and order lineage is incomplete or mismatched.' })
  const [[quote], [managedPreview]] = await Promise.all([database.select().from(managedSiteQuotes).where(and(eq(managedSiteQuotes.id, order.quoteId), eq(managedSiteQuotes.ownerUserId, ownerUserId))).limit(1), database.select().from(managedSitePreviews).where(eq(managedSitePreviews.id, order.previewId)).limit(1)])
  if (!quote || !managedPreview || quote.status !== 'locked' || quote.previewId !== managedPreview.id || quote.projectId !== spec.managedSiteProjectId || quote.totalMinor !== payment.amountMinor || quote.currency !== payment.currency || order.paymentIntentReference !== payment.providerReference) throw createError({ statusCode: 409, statusMessage: 'Server quote, preview, order and verified payment do not form exact authority lineage.' })
  const intentFingerprint = fingerprint({ specFingerprint: version.specFingerprint, compiledPlanFingerprint: version.compiledPlanFingerprint, ownerUserId, clientId: spec.clientId, websiteId: spec.websiteId, managedSiteProjectId: spec.managedSiteProjectId, previewId: managedPreview.id, quoteId: quote.id, orderId: order.id, paymentEventFingerprint: payment.eventFingerprint, steps: PROVISIONING_STEPS })
  const [existingPlan] = await database.select().from(systemProvisioningPlans).where(and(eq(systemProvisioningPlans.ownerUserId, ownerUserId), eq(systemProvisioningPlans.idempotencyKey, idempotencyKey))).limit(1)
  if (existingPlan) { if (existingPlan.planFingerprint !== intentFingerprint) throw createError({ statusCode: 409, statusMessage: 'Provisioning idempotency key is bound to a different plan.' }); return { plan: existingPlan, replayed: true } }
  let created: { planId: string; runId: string; systemTenantId: string }
  try { created = await database.transaction(async tx => {
    let [tenant] = await tx.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemSpecId, spec.id))).limit(1)
    if (!tenant) {
      const systemTenantId = `system-tenant-${fingerprint({ spec: spec.specId, intentFingerprint }).slice(0, 24)}`; const projection = { ownerUserId, clientId: spec.clientId, systemSpecId: spec.id, systemSpecVersionId: version.id, systemTenantId, siteNameHash: fingerprint({ systemTenantId, site: 'opaque' }), state: 'payment_verified' as const, stateVersion: 1, specFingerprint: version.specFingerprint, compiledPlanFingerprint: version.compiledPlanFingerprint, verifiedPaymentReceiptFingerprint: payment.eventFingerprint, healthyReceiptFingerprint: null, invitationReceiptFingerprint: null, projectionFingerprint: intentFingerprint }
      const tenantRowId = rowId(await tx.insert(systemTenants).values(projection as any)); [tenant] = await tx.select().from(systemTenants).where(eq(systemTenants.id, tenantRowId)).limit(1)
      await tx.insert(systemTenantBindings).values({ ownerUserId, systemTenantId: tenantRowId, clientId: spec.clientId, websiteId: spec.websiteId, managedSiteProjectId: spec.managedSiteProjectId, managedSitePreviewId: managedPreview.id, managedSiteQuoteId: quote.id, managedSiteDraftOrderId: order.id, managedSitePaymentEventId: payment.id, bindingFingerprint: fingerprint({ ownerUserId, tenantRowId, order: order.id, payment: payment.eventFingerprint }) } as any)
    }
    if (!tenant) throw createError({ statusCode: 500, statusMessage: 'System tenant could not be created.' })
    const planId = `system-plan-${intentFingerprint.slice(0, 24)}`; const planRowId = rowId(await tx.insert(systemProvisioningPlans).values({ planId, ownerUserId, systemTenantId: tenant.id, systemSpecVersionId: version.id, planFingerprint: intentFingerprint, steps: PROVISIONING_STEPS.map((operation, ordinal) => ({ operation, ordinal: ordinal + 1 })), status: 'planned', idempotencyKey } as any)); const runId = `system-run-${fingerprint({ planId, attempt: 0 }).slice(0, 24)}`
    await tx.insert(systemProvisioningRuns).values({ runId, ownerUserId, systemTenantId: tenant.id, planId: planRowId, status: 'queued', attempt: 0, maxAttempts: 3, leaseOwner: null, leaseExpiresAt: null, retryEligibleAt: null, inputFingerprint: intentFingerprint, idempotencyKey: `${idempotencyKey}:run` } as any)
    const tenantUpdate = await tx.update(systemTenants).set({ state: 'provisioning_planned', stateVersion: tenant.stateVersion + 1, projectionFingerprint: fingerprint({ previous: tenant.projectionFingerprint, state: 'provisioning_planned', plan: intentFingerprint }) } as any).where(and(eq(systemTenants.id, tenant.id), eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.stateVersion, tenant.stateVersion))); if (affected(tenantUpdate) !== 1) throw new SystemFactoryError('TENANT_CAS', 'Provisioning tenant state changed concurrently.', 409)
    const specUpdate = await tx.update(systemSpecs).set({ status: 'provisioning_planned' } as any).where(and(eq(systemSpecs.id, spec.id), eq(systemSpecs.ownerUserId, ownerUserId))); if (affected(specUpdate) !== 1) throw new SystemFactoryError('SPEC_CAS', 'Provisioning specification projection was not updated.', 409)
    return { planId, runId, systemTenantId: tenant.systemTenantId }
  }) } catch (error) {
    if (!duplicateEntry(error)) throw error
    const [replayPlan] = await database.select().from(systemProvisioningPlans).where(and(eq(systemProvisioningPlans.ownerUserId, ownerUserId), eq(systemProvisioningPlans.idempotencyKey, idempotencyKey))).limit(1)
    if (!replayPlan || replayPlan.planFingerprint !== intentFingerprint) throw createError({ statusCode: 409, statusMessage: 'Provisioning concurrency collided with different lineage.' })
    return { plan: replayPlan, replayed: true }
  }
  return { plan: { ...created, planFingerprint: intentFingerprint, steps: PROVISIONING_STEPS, status: 'planned' as const }, replayed: false }
}

export async function planSystemUpgrade(ownerUserId: number, tenantPublicId: string, input: { toVersionLockHash: string; idempotencyKey: string }) {
  const database = databaseRequired(); const [tenant] = await database.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemTenantId, tenantPublicId))).limit(1); if (!tenant || tenant.state !== 'active' || !tenant.healthyReceiptFingerprint) throw createError({ statusCode: 409, statusMessage: 'Only a healthy active owner-scoped tenant can plan an upgrade.' })
  const toVersionLockHash = normalizeText(input.toVersionLockHash, 'Target version lock hash', 64); if (!/^[a-f0-9]{64}$/u.test(toVersionLockHash)) throw new SystemFactoryError('INVALID_FINGERPRINT', 'Target version lock hash is invalid.'); const idempotencyKey = key(input.idempotencyKey); const fromVersionLockHash = fingerprint({ compiledPlan: tenant.compiledPlanFingerprint, runtime: 'pinned-current' }); const intentFingerprint = fingerprint({ tenant: tenant.systemTenantId, fromVersionLockHash, toVersionLockHash })
  const [existing] = await database.select().from(systemUpgradeIntents).where(and(eq(systemUpgradeIntents.ownerUserId, ownerUserId), eq(systemUpgradeIntents.idempotencyKey, idempotencyKey))).limit(1); if (existing) { if (existing.intentFingerprint !== intentFingerprint) throw createError({ statusCode: 409, statusMessage: 'Upgrade idempotency key is bound to a different version intent.' }); return { intent: existing, replayed: true } }
  const upgradeIntentId = `upgrade-intent-${intentFingerprint.slice(0, 24)}`; await database.insert(systemUpgradeIntents).values({ upgradeIntentId, ownerUserId, systemTenantId: tenant.id, fromVersionLockHash, toVersionLockHash, reviewedByUserId: ownerUserId, status: 'reviewed', intentFingerprint, idempotencyKey } as any)
  return { intent: { upgradeIntentId, fromVersionLockHash, toVersionLockHash, status: 'reviewed' as const, backupRequired: true, automaticUpdate: false }, replayed: false }
}

export async function requestSystemLifecycle(ownerUserId: number, tenantPublicId: string, input: { action: 'suspend' | 'reactivate' | 'deprovision'; idempotencyKey: string }, now = new Date()) {
  const database = databaseRequired(); const idempotencyKey = key(input.idempotencyKey); const payloadFingerprint = fingerprint({ tenantPublicId, action: input.action }); const eventId = `system-lifecycle-${fingerprint({ ownerUserId, idempotencyKey }).slice(0, 24)}`
  let transition: { previousState: string; nextState: string }
  try { transition = await database.transaction(async tx => {
    const [tenant] = await tx.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemTenantId, tenantPublicId))).limit(1); if (!tenant) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped system tenant was not found.' })
    const allowed = input.action === 'suspend' ? tenant.state === 'active' : input.action === 'reactivate' ? tenant.state === 'suspended' : ['active', 'suspended'].includes(tenant.state); if (!allowed) throw createError({ statusCode: 409, statusMessage: 'Stored tenant state cannot accept this lifecycle intent.' })
    const nextState = input.action === 'suspend' ? 'suspended' : input.action === 'reactivate' ? 'active' : 'deprovision_pending'; const eventFingerprint = fingerprint({ eventId, previousState: tenant.state, nextState, payloadFingerprint, authority: `owner:${ownerUserId}` })
    await tx.insert(systemEvents).values({ eventId, ownerUserId, systemTenantId: tenant.id, previousState: tenant.state, nextState, eventType: `${input.action}_requested`, authorityFingerprint: fingerprint({ ownerUserId, authority: 'owner_session' }), payloadFingerprint, eventFingerprint, occurredAt: now } as any)
    const stateUpdate = await tx.update(systemTenants).set({ state: nextState as any, stateVersion: tenant.stateVersion + 1, projectionFingerprint: fingerprint({ previous: tenant.projectionFingerprint, state: nextState, eventFingerprint }) } as any).where(and(eq(systemTenants.id, tenant.id), eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.stateVersion, tenant.stateVersion), eq(systemTenants.state, tenant.state))); if (affected(stateUpdate) !== 1) throw new SystemFactoryError('TENANT_CAS', 'Tenant lifecycle changed concurrently.', 409)
    return { previousState: tenant.state, nextState }
  }) } catch (error) {
    if (!duplicateEntry(error)) throw error
    const [existing] = await database.select().from(systemEvents).where(eq(systemEvents.eventId, eventId)).limit(1); if (!existing || existing.payloadFingerprint !== payloadFingerprint) throw createError({ statusCode: 409, statusMessage: 'Lifecycle intent idempotency collision.' }); return { intent: existing, replayed: true }
  }
  return { intent: { eventId, action: input.action, previousState: transition.previousState, state: transition.nextState, executorInvoked: false, nextSafeAction: 'server_scheduler_requires_opaque_credential_and_fixed_executor' }, replayed: false }
}

export async function revokeSystemAdminInvitation(ownerUserId: number, tenantPublicId: string, invitationPublicId: string, now = new Date()) {
  const database = databaseRequired(); const [tenant] = await database.select().from(systemTenants).where(and(eq(systemTenants.ownerUserId, ownerUserId), eq(systemTenants.systemTenantId, tenantPublicId))).limit(1); if (!tenant) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped system tenant was not found.' }); const [invitation] = await database.select().from(systemAdminInvitations).where(and(eq(systemAdminInvitations.ownerUserId, ownerUserId), eq(systemAdminInvitations.systemTenantId, tenant.id), eq(systemAdminInvitations.invitationId, invitationPublicId))).limit(1); if (!invitation) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped invitation was not found.' }); if (invitation.status === 'revoked') return { invitationId: invitation.invitationId, status: invitation.status, replayed: true }; if (invitation.status !== 'pending') throw createError({ statusCode: 409, statusMessage: 'Accepted or expired invitation is terminal.' }); const update = await database.update(systemAdminInvitations).set({ status: 'revoked', revokedAt: now } as any).where(and(eq(systemAdminInvitations.id, invitation.id), eq(systemAdminInvitations.ownerUserId, ownerUserId), eq(systemAdminInvitations.status, 'pending'))); if (affected(update) !== 1) { const [current] = await database.select({ status: systemAdminInvitations.status }).from(systemAdminInvitations).where(eq(systemAdminInvitations.id, invitation.id)).limit(1); if (current?.status === 'revoked') return { invitationId: invitation.invitationId, status: 'revoked' as const, replayed: true }; throw createError({ statusCode: 409, statusMessage: 'Invitation revoke collided with another terminal transition.' }) }; return { invitationId: invitation.invitationId, status: 'revoked' as const, replayed: false }
}

export async function retrySystemProvisioning(ownerUserId: number, runPublicId: string, now = new Date()) {
  const database = databaseRequired(); const [run] = await database.select().from(systemProvisioningRuns).where(and(eq(systemProvisioningRuns.ownerUserId, ownerUserId), eq(systemProvisioningRuns.runId, runPublicId))).limit(1); if (!run) throw createError({ statusCode: 404, statusMessage: 'Owner-scoped provisioning run was not found.' }); if (run.status === 'queued') return { runId: run.runId, status: 'queued' as const, replayed: true, executorInvoked: false, nextSafeAction: 'bounded_scheduler_claim' }; if (run.status !== 'retry_wait' || run.attempt >= run.maxAttempts || !run.retryEligibleAt || run.retryEligibleAt.getTime() > now.getTime()) throw createError({ statusCode: 409, statusMessage: 'Provisioning run is not retry-eligible.' }); const update = await database.update(systemProvisioningRuns).set({ status: 'queued', leaseOwner: null, leaseExpiresAt: null, retryEligibleAt: null } as any).where(and(eq(systemProvisioningRuns.id, run.id), eq(systemProvisioningRuns.ownerUserId, ownerUserId), eq(systemProvisioningRuns.status, 'retry_wait'), eq(systemProvisioningRuns.retryEligibleAt, run.retryEligibleAt))); if (affected(update) !== 1) { const [current] = await database.select({ status: systemProvisioningRuns.status }).from(systemProvisioningRuns).where(eq(systemProvisioningRuns.id, run.id)).limit(1); if (current?.status === 'queued') return { runId: run.runId, status: 'queued' as const, replayed: true, executorInvoked: false, nextSafeAction: 'bounded_scheduler_claim' }; throw createError({ statusCode: 409, statusMessage: 'Provisioning retry collided with another transition.' }) }; return { runId: run.runId, status: 'queued' as const, replayed: false, executorInvoked: false, nextSafeAction: 'bounded_scheduler_claim' }
}
