import { fingerprint, SystemFactoryError } from './canonical'
import type { CompiledSystemPlan } from './compiler'
import type { OperationReceipt } from './control-plane'
import type { ProvisionContext, SystemFactoryProvisionerPort } from './provisioner'
import { testRuntimeAuthority, type SystemFactoryRuntimeAuthority } from './runtime-authority'

export const SYSTEM_TENANT_STATES = ['draft', 'preview_ready', 'quote_ready', 'awaiting_payment', 'payment_verified', 'provisioning_planned', 'provisioning', 'health_checking', 'invitation_pending', 'active', 'failed', 'retry_wait', 'suspended', 'deprovision_pending', 'deprovisioned'] as const
export type SystemTenantState = typeof SYSTEM_TENANT_STATES[number]
export type VerifiedWorkflowEvent = { eventId: string; type: string; ownerId: string; clientId: string; systemTenantId: string; verified: true; authorityFingerprint: string; occurredAt: string; payloadFingerprint: string }
export type TenantProjection = { ownerId: string; clientId: string; websiteId: string | null; managedSiteId: string | null; systemTenantId: string; state: SystemTenantState; stateVersion: number; specFingerprint: string; compiledPlanFingerprint: string; managedSiteOrderId: number | null; verifiedPaymentReceiptFingerprint: string | null; leaseOwner: string | null; leaseExpiresAt: string | null; attempt: number; maxAttempts: number; retryEligibleAt: string | null; healthyReceiptFingerprint: string | null; invitationReceiptFingerprint: string | null; projectionFingerprint: string }
export type WorkflowReceipt = { receiptId: string; tenantId: string; step: string; status: 'succeeded' | 'failed' | 'blocked' | 'rolled_back'; requestFingerprint: string; responseFingerprint: string | null; exactResponseIdentity: string | null; createdAt: string; metadata: Record<string, unknown> }
export type WorkflowRepository = { transaction<T>(work: (repo: WorkflowRepository) => Promise<T>): Promise<T>; getTenant(ownerId: string, tenantId: string): Promise<TenantProjection | null>; saveTenant(expectedVersion: number, tenant: TenantProjection): Promise<TenantProjection>; claim(ownerId: string, tenantId: string, leaseOwner: string, now: Date, leaseMs: number): Promise<'claimed' | 'stale_recovered' | 'busy' | 'terminal'>; release(ownerId: string, tenantId: string, leaseOwner: string, patch: Partial<TenantProjection>): Promise<TenantProjection>; appendEvent(event: VerifiedWorkflowEvent): Promise<void>; appendReceipt(receipt: WorkflowReceipt): Promise<void>; listReceipts(ownerId: string, tenantId: string): Promise<WorkflowReceipt[]> }

const TRANSITIONS: Record<string, SystemTenantState[]> = {
  spec_saved: ['draft'], preview_built: ['preview_ready'], quote_created: ['quote_ready'], order_created: ['awaiting_payment'], payment_receipt_verified: ['payment_verified'], provisioning_plan_created: ['provisioning_planned'], provisioning_started: ['provisioning'], health_check_started: ['health_checking'], health_check_passed: ['invitation_pending'], invitation_created: ['active'], retry_scheduled: ['retry_wait'], retry_started: ['provisioning'], failed: ['failed'], suspended: ['suspended'], reactivated: ['active'], deprovision_requested: ['deprovision_pending'], deprovision_completed: ['deprovisioned'],
}
const REQUIRED_PREVIOUS: Record<string, SystemTenantState[]> = {
  spec_saved: ['draft'], preview_built: ['draft', 'preview_ready'], quote_created: ['preview_ready'], order_created: ['quote_ready'], payment_receipt_verified: ['awaiting_payment'], provisioning_plan_created: ['payment_verified'], provisioning_started: ['provisioning_planned', 'retry_wait'], health_check_started: ['provisioning'], health_check_passed: ['health_checking'], invitation_created: ['invitation_pending'], retry_scheduled: ['provisioning', 'health_checking'], retry_started: ['retry_wait'], failed: ['provisioning', 'health_checking', 'retry_wait'], suspended: ['active'], reactivated: ['suspended'], deprovision_requested: ['active', 'suspended'], deprovision_completed: ['deprovision_pending'],
}

function projectionFingerprint(value: Omit<TenantProjection, 'projectionFingerprint'>): string { return fingerprint(value) }
function assertTenantLineage(tenant: TenantProjection, event: VerifiedWorkflowEvent): void { if (!event.verified || event.ownerId !== tenant.ownerId || event.clientId !== tenant.clientId || event.systemTenantId !== tenant.systemTenantId || !/^[a-f0-9]{64}$/u.test(event.authorityFingerprint) || !/^[a-f0-9]{64}$/u.test(event.payloadFingerprint)) throw new SystemFactoryError('EVENT_AUTHORITY', 'Workflow event authority or tenant lineage is invalid.', 409) }

export async function applyVerifiedTransition(repository: WorkflowRepository, ownerId: string, tenantId: string, event: VerifiedWorkflowEvent): Promise<TenantProjection> {
  return repository.transaction(async tx => { const tenant = await tx.getTenant(ownerId, tenantId); if (!tenant) throw new SystemFactoryError('TENANT_NOT_FOUND', 'System tenant was not found.', 404); assertTenantLineage(tenant, event); const next = TRANSITIONS[event.type]?.[0]; if (!next || !REQUIRED_PREVIOUS[event.type]?.includes(tenant.state)) throw new SystemFactoryError('INVALID_TRANSITION', 'Stored system tenant state cannot accept this verified event.', 409); if (tenant.state === 'deprovisioned') throw new SystemFactoryError('TERMINAL_STATE', 'Deprovisioned tenant is terminal.', 409); const draft = { ...tenant, state: next, stateVersion: tenant.stateVersion + 1, ...(event.type === 'payment_receipt_verified' ? { verifiedPaymentReceiptFingerprint: event.authorityFingerprint } : {}), projectionFingerprint: '' }; draft.projectionFingerprint = projectionFingerprint(draft); await tx.appendEvent(event); return tx.saveTenant(tenant.stateVersion, draft) })
}

const PROVISION_STEPS: Array<keyof Pick<SystemFactoryProvisionerPort, 'createSite' | 'installApp' | 'applyCompiledSpec' | 'createRolesAndPermissions' | 'configureModules' | 'healthCheck' | 'createAdminInvitation'>> = ['createSite', 'installApp', 'applyCompiledSpec', 'createRolesAndPermissions', 'configureModules', 'healthCheck', 'createAdminInvitation']

export async function executeProvisioning(input: { ownerId: string; tenantId: string; compiledPlan: CompiledSystemPlan; siteName: string; credentialReference: string; controlPlaneCredentialReference?: string; tenantAppCredentialReference?: string; executor: SystemFactoryProvisionerPort; repository: WorkflowRepository; executionMode: 'mocked' | 'live'; runtimeAuthority?: SystemFactoryRuntimeAuthority; now?: Date }): Promise<{ tenant: TenantProjection; receipts: WorkflowReceipt[] }> {
  const now = input.now || new Date(); const leaseOwner = `system-provisioner:${fingerprint({ tenant: input.tenantId, at: now.toISOString() }).slice(0, 24)}`; const claim = await input.repository.claim(input.ownerId, input.tenantId, leaseOwner, now, 300_000)
  if (claim === 'busy') throw new SystemFactoryError('LEASE_BUSY', 'System tenant provisioning is already leased.', 409); if (claim === 'terminal') throw new SystemFactoryError('TERMINAL_STATE', 'System tenant provisioning is terminal.', 409)
  let tenant = await input.repository.getTenant(input.ownerId, input.tenantId); if (!tenant) throw new SystemFactoryError('TENANT_NOT_FOUND', 'System tenant was not found.', 404)
  if (tenant.state !== 'provisioning_planned' && tenant.state !== 'retry_wait' && tenant.state !== 'provisioning') throw new SystemFactoryError('PROVISIONING_STATE', 'Provisioning requires stored planned or retry state.', 409)
  if (!tenant.verifiedPaymentReceiptFingerprint || input.compiledPlan.specFingerprint !== tenant.specFingerprint || input.compiledPlan.planFingerprint !== tenant.compiledPlanFingerprint) throw new SystemFactoryError('PAYMENT_OR_SPEC_LINEAGE', 'Verified payment and exact compile lineage are required.', 409)
  const context: ProvisionContext = { ownerId: tenant.ownerId, clientId: tenant.clientId, websiteId: tenant.websiteId, managedSiteId: tenant.managedSiteId, systemTenantId: tenant.systemTenantId, siteName: input.siteName, controlPlaneCredentialReference: input.controlPlaneCredentialReference || input.credentialReference, tenantAppCredentialReference: input.tenantAppCredentialReference || input.credentialReference, idempotencyKey: `provision:${tenant.systemTenantId}:${tenant.attempt + 1}`, compiledPlan: input.compiledPlan, executionMode: input.executionMode, runtimeAuthority: input.runtimeAuthority || testRuntimeAuthority() }
  const receipts: WorkflowReceipt[] = []; let healthPassed = false
  try {
    for (const step of PROVISION_STEPS) {
      if (step === 'createAdminInvitation' && !healthPassed) throw new SystemFactoryError('HEALTH_REQUIRED', 'A healthy receipt is required before invitation creation.', 409)
      const result = await input.executor[step](context) as OperationReceipt & { healthy?: boolean }
      if (step === 'healthCheck' && result.healthy !== true) throw new SystemFactoryError('HEALTH_FAILED', 'Frappe health check failed closed.', 409)
      if (step === 'healthCheck') healthPassed = true
      const receipt: WorkflowReceipt = { receiptId: `receipt-${result.receiptFingerprint.slice(0, 24)}`, tenantId: tenant.systemTenantId, step, status: 'succeeded', requestFingerprint: result.requestFingerprint, responseFingerprint: result.responseFingerprint, exactResponseIdentity: result.exactResponseIdentity, createdAt: now.toISOString(), metadata: { externalCalls: result.externalCalls, runtimeAuthorityFingerprint: result.runtimeAuthorityFingerprint, replayed: result.replayed } }; await input.repository.appendReceipt(receipt); receipts.push(receipt)
    }
    tenant = await input.repository.release(input.ownerId, input.tenantId, leaseOwner, { state: 'invitation_pending', stateVersion: tenant.stateVersion + 1, attempt: tenant.attempt + 1, healthyReceiptFingerprint: receipts.find(item => item.step === 'healthCheck')!.responseFingerprint, invitationReceiptFingerprint: null, retryEligibleAt: null })
    return { tenant, receipts }
  } catch (error) {
    const attempt = tenant.attempt + 1; const retry = attempt < tenant.maxAttempts; const code = error instanceof SystemFactoryError ? error.code : 'PROVISIONING_FAILED'; const receipt: WorkflowReceipt = { receiptId: `receipt-${fingerprint({ tenant: tenant.systemTenantId, attempt, code }).slice(0, 24)}`, tenantId: tenant.systemTenantId, step: 'provisioning', status: code === 'MISSING_CREDENTIAL' ? 'blocked' : 'failed', requestFingerprint: fingerprint({ tenant: tenant.systemTenantId, attempt }), responseFingerprint: null, exactResponseIdentity: null, createdAt: now.toISOString(), metadata: { code } }; await input.repository.appendReceipt(receipt); receipts.push(receipt); tenant = await input.repository.release(input.ownerId, input.tenantId, leaseOwner, { state: retry ? 'retry_wait' : 'failed', stateVersion: tenant.stateVersion + 1, attempt, retryEligibleAt: retry ? new Date(now.getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, attempt - 1))).toISOString() : null }); return { tenant, receipts }
  }
}

export async function executeUpgrade(input: { context: ProvisionContext; executor: SystemFactoryProvisionerPort }): Promise<{ status: 'active' | 'rolled_back'; receipts: OperationReceipt[] }> {
  const receipts: OperationReceipt[] = []; receipts.push(await input.executor.planUpgrade(input.context)); receipts.push(await input.executor.backupBeforeUpgrade(input.context))
  try { receipts.push(await input.executor.applyUpgrade(input.context)); const verification = await input.executor.verifyUpgrade(input.context); receipts.push(verification); if (!verification.healthy) throw new SystemFactoryError('UPGRADE_HEALTH', 'Upgrade verification failed.', 409); return { status: 'active', receipts } } catch { receipts.push(await input.executor.rollbackUpgrade(input.context)); return { status: 'rolled_back', receipts } }
}

export class MemoryWorkflowRepository implements WorkflowRepository {
  tenants = new Map<string, TenantProjection>(); events: VerifiedWorkflowEvent[] = []; receipts: WorkflowReceipt[] = []
  async transaction<T>(work: (repo: WorkflowRepository) => Promise<T>): Promise<T> { return work(this) }
  seed(input: Omit<TenantProjection, 'projectionFingerprint'>): TenantProjection { const value = { ...input, projectionFingerprint: projectionFingerprint(input) }; this.tenants.set(`${input.ownerId}:${input.systemTenantId}`, value); return value }
  async getTenant(ownerId: string, tenantId: string) { return this.tenants.get(`${ownerId}:${tenantId}`) || null }
  async saveTenant(expectedVersion: number, tenant: TenantProjection) { const current = await this.getTenant(tenant.ownerId, tenant.systemTenantId); if (!current || current.stateVersion !== expectedVersion) throw new SystemFactoryError('CONCURRENT_UPDATE', 'System tenant state changed concurrently.', 409); this.tenants.set(`${tenant.ownerId}:${tenant.systemTenantId}`, tenant); return tenant }
  async claim(ownerId: string, tenantId: string, leaseOwner: string, now: Date, leaseMs: number) { const tenant = this.tenants.get(`${ownerId}:${tenantId}`) || null; if (!tenant) throw new SystemFactoryError('TENANT_NOT_FOUND', 'System tenant was not found.', 404); if (['active', 'deprovisioned'].includes(tenant.state)) return 'terminal' as const; const stale = Boolean(tenant.leaseExpiresAt && Date.parse(tenant.leaseExpiresAt) <= now.getTime()); if (tenant.leaseOwner && !stale) return 'busy' as const; const claimed = { ...tenant, leaseOwner, leaseExpiresAt: new Date(now.getTime() + leaseMs).toISOString(), projectionFingerprint: '' }; claimed.projectionFingerprint = projectionFingerprint(claimed); this.tenants.set(`${ownerId}:${tenantId}`, claimed); return stale ? 'stale_recovered' as const : 'claimed' as const }
  async release(ownerId: string, tenantId: string, leaseOwner: string, patch: Partial<TenantProjection>) { const tenant = await this.getTenant(ownerId, tenantId); if (!tenant || tenant.leaseOwner !== leaseOwner) throw new SystemFactoryError('LEASE_MISMATCH', 'System tenant lease is invalid.', 409); const updated = { ...tenant, ...patch, leaseOwner: null, leaseExpiresAt: null, projectionFingerprint: '' }; updated.projectionFingerprint = projectionFingerprint(updated); this.tenants.set(`${ownerId}:${tenantId}`, updated); return updated }
  async appendEvent(event: VerifiedWorkflowEvent) { if (this.events.some(item => item.eventId === event.eventId && item.payloadFingerprint !== event.payloadFingerprint)) throw new SystemFactoryError('EVENT_COLLISION', 'Event identity collision.', 409); if (!this.events.some(item => item.eventId === event.eventId)) this.events.push(event) }
  async appendReceipt(receipt: WorkflowReceipt) { if (this.receipts.some(item => item.receiptId === receipt.receiptId && item.requestFingerprint !== receipt.requestFingerprint)) throw new SystemFactoryError('RECEIPT_COLLISION', 'Receipt identity collision.', 409); if (!this.receipts.some(item => item.receiptId === receipt.receiptId)) this.receipts.push(receipt) }
  async listReceipts(ownerId: string, tenantId: string) { return (await this.getTenant(ownerId, tenantId)) ? this.receipts.filter(item => item.tenantId === tenantId) : [] }
}
