import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

const root = process.cwd()
const source = (path: string) => readFileSync(join(root, path), 'utf8')
const redesign = source('src/styles/redesign.css')
const immersive = source('src/styles/immersive.css')
const hybrid = source('src/styles/hybrid-refresh.css')
const home = source('src/components/HomePage.astro')
const departments = source('src/components/DepartmentTabs.vue')
const journey = source('src/components/JourneySequence.vue')
const aiQa = source('src/components/AiQaDock.vue')
const analysis = source('src/components/AutomaticSiteAnalysis.vue')
const cookie = source('src/components/CookieConsent.vue')
const api = source('src/lib/publicApi.ts')
const robots = source('src/pages/robots.txt.ts')
const envExample = source('.env.example')
const legacyUiEnv = ['PUBLIC', 'OPS', 'UI', 'ORIGIN'].join('_')
const legacyUiExport = ['public', 'Ops', 'Ui', 'Origin'].join('')
const privateSeoGeoApi = ['/api', 'seo-geo'].join('/')
const privateOwnerEntry = ['/audit-lab', 'seo-geo'].join('/')

describe('public-site visual and boundary contract', () => {
  it('retains the public route/content source in Astro only', () => {
    expect(readdirSync(join(root, 'src/content/pages/en'), { recursive: true }).filter(file => String(file).endsWith('.md'))).toHaveLength(8)
    expect(readdirSync(join(root, 'src/content/pages/zh-hant'), { recursive: true }).filter(file => String(file).endsWith('.md'))).toHaveLength(8)
    expect(existsSync(join(root, '../nuxt-app/pages/glossary'))).toBe(false)
    expect(existsSync(join(root, '../nuxt-app/content/pages'))).toBe(false)
    expect(existsSync(join(root, '../nuxt-app/components/landing'))).toBe(false)
    expect(existsSync(join(root, '../nuxt-app/layouts/default.vue'))).toBe(false)
  })

  it('keeps the editorial visual system and motion opt-out', () => {
    expect(redesign).toContain('--sand:')
    expect(redesign).toContain('--paper:')
    expect(redesign).toContain('--ink:')
    expect(redesign).toContain('--cobalt:')
    expect(redesign).toContain('.site-header')
    expect(redesign).toContain('.route-rail')
    expect(hybrid).toContain('.hybrid-home')
    expect(immersive).toContain('prefers-reduced-motion:reduce')
    expect(immersive).toContain('.qa-prompts button:focus-visible')
    expect(departments).toContain('department-system')
    expect(home).not.toContain('hero-constellation')
  })

  it('keeps SSR-visible story scenes and progressive client behavior', () => {
    expect(journey).toContain('const panels = [')
    expect((journey.match(/number: '0[1-4]'/g) || [])).toHaveLength(4)
    expect(journey).toContain('<h3>{{ copyFor(panel)[1] }}</h3>')
    expect(journey).toContain('@pointermove="updatePointer"')
    expect(journey).toContain("window.matchMedia('(pointer: fine)')")
    expect(journey).toContain("prefers-reduced-motion: reduce")
    expect(journey).toContain("window.addEventListener('scroll'")
    expect(journey).toContain("window.removeEventListener('scroll'")
  })

  it('keeps accessible bounded AI QA and analysis forms on the public API allowlist', () => {
    expect(aiQa).toContain('class="qa-launcher"')
    expect(aiQa).toContain(':aria-controls="panelId"')
    expect(aiQa).toContain('@keydown.esc="closeDock"')
    expect(aiQa).toContain('launcher.value?.focus()')
    expect(analysis).toContain('modelImprovementConsent')
    expect(analysis).toContain('不包含姓名、Email、電話、預算或自由填寫內容')
    expect(api).toContain("'/api/leads'")
    expect(api).toContain("'/api/site-analysis'")
    expect(api).toContain("credentials: 'omit'")
    expect(api).not.toContain(privateSeoGeoApi)
    expect(api).not.toContain('document.cookie')
    expect(api).not.toContain(legacyUiEnv)
    expect(api).not.toContain(legacyUiExport)
    expect(home).not.toContain(legacyUiEnv)
    expect(home).not.toContain(privateOwnerEntry)
    expect(envExample).not.toContain(legacyUiEnv)
    expect(robots).not.toContain('/audit-lab')
    expect(robots).not.toContain('/api/')
  })

  it('keeps cookie choice and footer reopen behavior explicit', () => {
    expect(cookie).toContain("save('necessary')")
    expect(cookie).toContain("save('all')")
    expect(cookie).toContain('目前本站尚未啟用第三方分析追蹤')
    expect(cookie).toContain('no third-party analytics are currently enabled')
    expect(cookie).toContain("discoverystack:open-cookie-settings")
    expect(source('src/layouts/BaseLayout.astro')).toContain('id="cookie-settings"')
  })
})
