import type { DatasetManifest, ModelArtifact, ModelArtifactSummary, TrainingRun } from '../../../geo-outcome-model/types'
import type { ModelOpsAdvisoryAssignment, ModelOpsCycle, ModelOpsCycleResult, ModelOpsEvent, ModelOpsPolicy, ModelOpsRollbackDecision, ModelOpsShadowEvaluation, ModelOpsWorkspace } from '../../../geo-outcome-model/modelops-types'

const preview = (value: string | null | undefined, length = 12): string | null => value ? value.slice(0, length) : null
const safeKeys = (payload: Record<string, unknown>): Record<string, unknown> => Object.fromEntries(Object.entries(payload).filter(([key, value]) => !/(fingerprint|hash|url|token|secret|credential|response|body|prompt|stack|weight|coefficient|intercept)/iu.test(key) && (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean' || value === null || (Array.isArray(value) && value.length <= 12 && value.every(item => typeof item === 'string')))))

export function projectPolicy(policy: ModelOpsPolicy | null) {
  if (!policy) return null
  return { policyId: policy.policyId, status: policy.status, cadence: policy.cadence, minimumNewVerifiedCandidates: policy.minimumNewVerifiedCandidates, minimumNewQueryGroups: policy.minimumNewQueryGroups, minimumNewWebsites: policy.minimumNewWebsites, minimumObservationSpanDays: policy.minimumObservationSpanDays, allowedModelFamilies: policy.allowedModelFamilies.slice(0, 8), maximumTrainingRunsPerCycle: policy.maximumTrainingRunsPerCycle, cooldownHours: policy.cooldownHours, shadowEvaluationEnabled: policy.shadowEvaluationEnabled, autonomousExecutionEnabled: policy.autonomousExecutionEnabled, expiresAt: policy.expiresAt }
}

export function projectCycle(cycle: ModelOpsCycle) {
  return { cycleId: cycle.cycleId, ownerUserId: cycle.ownerUserId, policyId: cycle.policyId, trigger: cycle.trigger, status: cycle.status, eligibleCandidateCount: cycle.eligibleObservationFingerprints.length, trainingRunId: cycle.trainingRunId, modelArtifactId: cycle.modelArtifactId, reasonCodes: cycle.reasonCodes.slice(0, 20), limitations: cycle.limitations.slice(0, 12), errorClass: cycle.errorClass, startedAt: cycle.startedAt, completedAt: cycle.completedAt, attempt: cycle.attempt, createdAt: cycle.createdAt, updatedAt: cycle.updatedAt }
}

export function projectEvent(event: ModelOpsEvent) { return { eventId: event.eventId, cycleId: event.cycleId, eventType: event.eventType, eventPayload: safeKeys(event.eventPayload), createdAt: event.createdAt } }

export function projectShadowEvaluation(evaluation: ModelOpsShadowEvaluation) { return { evaluationId: evaluation.evaluationId, artifactId: evaluation.artifactId, evaluationWindowStart: evaluation.evaluationWindowStart, evaluationWindowEnd: evaluation.evaluationWindowEnd, candidateCount: evaluation.candidateCount, positiveCount: evaluation.positiveCount, negativeCount: evaluation.negativeCount, queryGroupCount: evaluation.queryGroupCount, websiteCount: evaluation.websiteCount, engineCounts: evaluation.engineCounts, binaryMetrics: evaluation.binaryMetrics, rankingMetrics: evaluation.rankingMetrics, calibrationDiagnostics: evaluation.calibrationDiagnostics, driftDiagnostics: evaluation.driftDiagnostics, status: evaluation.status, reasonCodes: evaluation.reasonCodes.slice(0, 20), createdAt: evaluation.createdAt }
}

function projectDataset(dataset: DatasetManifest) { return { manifestId: dataset.manifestId, manifestFingerprint: preview(dataset.manifestFingerprint), taskType: dataset.taskType, readiness: dataset.readiness, status: dataset.status, websiteCount: dataset.websiteCount, queryGroupCount: dataset.queryGroupCount, positiveCount: dataset.positiveCount, hardNegativeCount: dataset.hardNegativeCount, engineCounts: dataset.engineCounts, trainRowCount: dataset.trainRowCount, validationRowCount: dataset.validationRowCount, testRowCount: dataset.testRowCount, siteHoldoutRowCount: dataset.siteHoldoutRowCount, queryHoldoutRowCount: dataset.queryHoldoutRowCount, temporalHoldoutRowCount: dataset.temporalHoldoutRowCount, observationStart: dataset.observationStart, observationEnd: dataset.observationEnd, limitations: dataset.limitations.slice(0, 12) } }
function projectTrainingRun(run: TrainingRun) { return { trainingRunId: run.trainingRunId, datasetManifestId: run.datasetManifestId, modelFamily: run.modelFamily, status: run.status, artifactId: run.artifactId, artifactHash: preview(run.artifactHash), reason: run.reason, createdAt: run.createdAt, startedAt: run.startedAt, completedAt: run.completedAt } }
export function projectArtifact(artifact: ModelArtifact | ModelArtifactSummary) { const datasetFingerprint = 'datasetManifestHash' in artifact ? artifact.datasetManifestHash : artifact.datasetManifestFingerprint; return { artifactId: artifact.artifactId, artifactHash: preview(artifact.artifactHash), taskType: artifact.taskType, modelFamily: artifact.modelFamily, datasetManifestFingerprint: preview(datasetFingerprint), status: artifact.status, featureCatalogVersion: 'featureCatalogVersion' in artifact ? artifact.featureCatalogVersion : undefined, labelContractVersion: 'labelContractVersion' in artifact ? artifact.labelContractVersion : undefined, trainingRowCount: artifact.trainingRowCount, evaluationMetrics: 'evaluationMetrics' in artifact ? artifact.evaluationMetrics : artifact.metrics } }
function projectDatasetDecision(decision: ModelOpsWorkspace['outcome']['datasetDecisions'][number]) { return { decisionId: decision.decisionId, manifestId: decision.manifestId, previousStatus: decision.previousStatus, newStatus: decision.newStatus, reviewerUserId: decision.reviewerUserId, reason: decision.reason, createdAt: decision.createdAt } }
function projectModelDecision(decision: ModelOpsWorkspace['outcome']['modelDecisions'][number]) { return { decisionId: decision.decisionId, artifactId: decision.modelArtifactId, previousStatus: decision.previousStatus, newStatus: decision.newStatus, reviewerUserId: decision.reviewerUserId, reason: decision.reason, createdAt: decision.createdAt } }
export function projectRollbackDecision(decision: ModelOpsRollbackDecision) { return { decisionId: decision.decisionId, artifactId: decision.artifactId, rollbackArtifactHash: preview(decision.rollbackArtifactHash), reason: decision.reason, decisionStatus: decision.decisionStatus, createdAt: decision.createdAt } }
export function projectAdvisoryAssignment(assignment: ModelOpsAdvisoryAssignment) { return { assignmentId: assignment.assignmentId, policyId: assignment.policyId, cycleId: assignment.cycleId, candidateArtifactId: assignment.candidateArtifactId, currentArtifactHash: preview(assignment.currentArtifactHash), candidateArtifactHash: preview(assignment.candidateArtifactHash), datasetFingerprint: preview(assignment.datasetFingerprint), splitFingerprint: preview(assignment.splitFingerprint), metricsFingerprint: preview(assignment.metricsFingerprint), shadowEvaluationFingerprint: preview(assignment.shadowEvaluationFingerprint), status: assignment.status, version: assignment.version, reasonCodes: assignment.reasonCodes.slice(0, 20), rollbackFromAssignmentId: assignment.rollbackFromAssignmentId, productionActivation: false, createdAt: assignment.createdAt, rolledBackAt: assignment.rolledBackAt } }

export function projectCycleResult(result: ModelOpsCycleResult) { return { cycle: projectCycle(result.cycle), dataset: result.dataset ? projectDataset(result.dataset) : null, trainingRun: result.trainingRun ? projectTrainingRun(result.trainingRun) : null, artifact: result.artifact ? projectArtifact(result.artifact) : null, shadowEvaluation: result.shadowEvaluation ? projectShadowEvaluation(result.shadowEvaluation) : null, productionActive: false, approvalsChanged: false } }

export function projectWorkspace(workspace: ModelOpsWorkspace) {
  return { ownerUserId: workspace.ownerUserId, policy: projectPolicy(workspace.policy), cycles: workspace.cycles.slice(-50).map(projectCycle), events: workspace.events.slice(-100).map(projectEvent), shadowEvaluations: workspace.shadowEvaluations.slice(-50).map(projectShadowEvaluation), rollbackDecisions: workspace.rollbackDecisions.slice(-50).map(projectRollbackDecision), advisoryAssignments: workspace.advisoryAssignments.slice(-50).map(projectAdvisoryAssignment), outcome: { readiness: workspace.outcome.readiness, datasets: workspace.outcome.datasets.slice(-50).map(projectDataset), trainingRuns: workspace.outcome.trainingRuns.slice(-50).map(projectTrainingRun), models: workspace.outcome.models.slice(-50).map(projectArtifact), datasetDecisions: workspace.outcome.datasetDecisions.slice(-50).map(projectDatasetDecision), modelDecisions: workspace.outcome.modelDecisions.slice(-50).map(projectModelDecision) }, productionActive: false, automaticApprovals: Boolean(workspace.policy?.autonomousExecutionEnabled), approvalActor: workspace.policy?.autonomousExecutionEnabled ? 'machine-policy' : 'owner-review' }
}
