import { canonicalJson, fingerprint, sha256Hex } from './canonical'
import { GEO_OUTCOME_ARTIFACT_SCHEMA_VERSION, GEO_OUTCOME_LABEL_CONTRACT_VERSION, GEO_OUTCOME_MODEL_VERSION, type TaskType } from './constants'
import type { EvaluationBundle, ModelArtifact, ModelArtifactSummary } from './types'
import type { TrainedParameters } from './trainer'

export function createModelArtifact(input: { ownerUserId: number, taskType: TaskType, modelFamily: ModelArtifact['modelFamily'], datasetManifestFingerprint: string, splitManifestFingerprint: string, parameters: TrainedParameters, evaluationMetrics: EvaluationBundle, limitations?: string[], rollbackArtifactHash?: string | null }): ModelArtifact {
  if (!Number.isSafeInteger(input.ownerUserId) || input.ownerUserId <= 0) throw new Error('ownerUserId must be server-derived.')
  if (input.parameters.trainingRowCount <= 0) throw new Error('Artifact requires positive training row count.')
  const payload = { artifactSchemaVersion: GEO_OUTCOME_ARTIFACT_SCHEMA_VERSION, taskType: input.taskType, modelFamily: input.modelFamily, modelVersion: GEO_OUTCOME_MODEL_VERSION, featureCatalogVersion: input.parameters.trainingConfiguration.featureCatalogVersion, labelContractVersion: GEO_OUTCOME_LABEL_CONTRACT_VERSION, datasetManifestFingerprint: input.datasetManifestFingerprint, splitManifestFingerprint: input.splitManifestFingerprint, coefficients: input.parameters.coefficients, intercept: input.parameters.intercept, normalizationStatistics: input.parameters.normalizationStatistics, trainingConfiguration: input.parameters.trainingConfiguration, trainingRowCount: input.parameters.trainingRowCount, evaluationMetrics: input.evaluationMetrics, limitations: input.limitations || ['Experimental baseline only; this artifact is not a verified citation probability.', 'No production promotion is available in V1.', 'Evaluation scopes with insufficient data remain insufficient_data.'], rollbackArtifactHash: input.rollbackArtifactHash || null }
  const artifactFingerprint = fingerprint(payload); const artifactHash = sha256Hex(canonicalJson({ ...payload, artifactFingerprint }))
  return { ...payload, artifactFingerprint, artifactHash, artifactId: `geo-model-${artifactFingerprint.slice(0, 20)}`, ownerUserId: input.ownerUserId, status: 'ready_for_owner_review', revokedAt: null }
}
export function summarizeArtifact(artifact: ModelArtifact): ModelArtifactSummary { return { artifactId: artifact.artifactId, modelFamily: artifact.modelFamily, taskType: artifact.taskType, modelVersion: artifact.modelVersion, status: artifact.status, artifactHash: artifact.artifactHash, datasetManifestHash: artifact.datasetManifestFingerprint, trainingRowCount: artifact.trainingRowCount, metrics: artifact.evaluationMetrics, limitations: artifact.limitations, rollbackArtifactHash: artifact.rollbackArtifactHash, revokedAt: artifact.revokedAt } }
export function artifactFingerprintIsStable(first: ModelArtifact, second: ModelArtifact): boolean { return first.artifactFingerprint === second.artifactFingerprint && first.artifactHash === second.artifactHash }
