import { GEO_OUTCOME_FEATURE_CATALOG_VERSION, MAX_FEATURES, MAX_TRAINING_ROWS, type ModelFamily } from './constants'
import type { DatasetMember, TrainingConfig } from './types'

const CONFIG_KEYS = ['epochs', 'learningRate', 'l2', 'seed', 'featureCatalogVersion'] as const
const MAX_TRAINING_PAIRS = 50_000
export interface TrainedParameters { coefficients: number[]; intercept: number; normalizationStatistics: { mean: number[], standardDeviation: number[] }; trainingRowCount: number; featureKeys: string[]; trainingConfiguration: TrainingConfig; pairCount?: number }
function at<T>(values: readonly T[], index: number, label: string): T { const value = values[index]; if (value === undefined) throw new Error(`${label}[${index}] is missing.`); return value }
function assertFinite(value: number, label: string) { if (!Number.isFinite(value)) throw new Error(`${label} must be finite.`) }
function sigmoid(value: number): number { if (value >= 35) return 1 - 1e-15; if (value <= -35) return 1e-15; return 1 / (1 + Math.exp(-value)) }

export function parseModelFamily(value: unknown): ModelFamily { if (value !== 'regularized_logistic_baseline_v1' && value !== 'pairwise_logistic_ranker_v1') throw new Error('Unsupported model family.') ; return value }
export function parseTrainingConfig(input: unknown): TrainingConfig {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('Training config must be an object.')
  const value = input as Record<string, unknown>; for (const key of Object.keys(value)) if (!(CONFIG_KEYS as readonly string[]).includes(key)) throw new Error(`Unknown training config field: ${key}.`)
  for (const key of CONFIG_KEYS) if (!(key in value)) throw new Error(`Missing training config field: ${key}.`)
  const epochs = value.epochs; const learningRate = value.learningRate; const l2 = value.l2; const seed = value.seed; const featureCatalogVersion = value.featureCatalogVersion
  if (typeof epochs !== 'number' || !Number.isSafeInteger(epochs) || epochs < 1 || epochs > 500) throw new Error('epochs is outside the bounded range.')
  for (const [key, numberValue] of [['learningRate', learningRate], ['l2', l2], ['seed', seed]] as const) if (typeof numberValue !== 'number' || !Number.isFinite(numberValue) || !Number.isSafeInteger(numberValue) && key === 'seed') throw new Error(`${key} must be finite and valid.`)
  if (typeof learningRate !== 'number' || typeof l2 !== 'number' || typeof seed !== 'number' || learningRate <= 0 || learningRate > 1 || l2 < 0 || l2 > 100 || seed !== 0) throw new Error('Training configuration is invalid or non-deterministic.')
  if (featureCatalogVersion !== GEO_OUTCOME_FEATURE_CATALOG_VERSION) throw new Error('Feature catalog version is unsupported.')
  return { epochs, learningRate, l2, seed, featureCatalogVersion }
}
function validateConfig(config: TrainingConfig): TrainingConfig { return parseTrainingConfig(config) }
function prepareRows(members: readonly DatasetMember[]) {
  if (!members.length) throw new Error('No training rows.')
  if (members.length > MAX_TRAINING_ROWS) throw new Error('Too many training rows.')
  const sorted = [...members].sort((a, b) => a.observationFingerprint < b.observationFingerprint ? -1 : a.observationFingerprint > b.observationFingerprint ? 1 : 0); const seen = new Set<string>(); const first = at(sorted, 0, 'training rows'); const featureKeys = first.featureVector.values.map(value => value.key)
  if (!featureKeys.length || featureKeys.length > MAX_FEATURES || new Set(featureKeys).size !== featureKeys.length) throw new Error('Feature count or feature identity is invalid.')
  for (const member of sorted) { if (seen.has(member.observationFingerprint)) throw new Error('Duplicate training example.'); seen.add(member.observationFingerprint); const rowKeys = member.featureVector.values.map(value => value.key); if (rowKeys.join('\u0000') !== featureKeys.join('\u0000')) throw new Error('Training rows have inconsistent feature contract.'); for (const feature of member.featureVector.values) assertFinite(feature.value, `feature ${feature.key}`) }
  return { sorted, featureKeys, matrix: sorted.map(member => member.featureVector.values.map(value => value.value)) }
}
function normalize(matrix: number[][]) {
  const first = at(matrix, 0, 'matrix'); const columns = first.length; const mean = Array.from({ length: columns }, (_, index) => matrix.reduce((sum, row) => sum + at(row, index, 'matrix row'), 0) / matrix.length); const standardDeviation = mean.map((average, index) => { const variance = matrix.reduce((sum, row) => sum + ((at(row, index, 'matrix row') - average) ** 2), 0) / matrix.length; return variance > 1e-12 ? Math.sqrt(variance) : 1 }); const normalizedMatrix = matrix.map(row => row.map((value, index) => (value - at(mean, index, 'mean')) / at(standardDeviation, index, 'standardDeviation'))); return { mean, standardDeviation, matrix: normalizedMatrix }
}

export function trainRegularizedLogisticBaseline(members: readonly DatasetMember[], rawConfig: TrainingConfig): TrainedParameters {
  const config = validateConfig(rawConfig); const { sorted, featureKeys, matrix } = prepareRows(members); const positives = sorted.filter(member => member.label === 1).length; const negatives = sorted.length - positives; if (!positives || !negatives) throw new Error('Both positive and negative classes are required.'); const normalized = normalize(matrix); const weightCount = at(normalized.matrix, 0, 'normalized matrix').length; const weights = Array<number>(weightCount).fill(0); let intercept = 0
  for (let epoch = 0; epoch < config.epochs; epoch += 1) { const gradient = Array<number>(weights.length).fill(0); let interceptGradient = 0; for (let rowIndex = 0; rowIndex < sorted.length; rowIndex += 1) { const row = at(normalized.matrix, rowIndex, 'normalized matrix'); const prediction = sigmoid(intercept + row.reduce((sum, value, index) => sum + value * at(weights, index, 'weights'), 0)); const error = prediction - at(sorted, rowIndex, 'sorted members').label; for (let index = 0; index < weights.length; index += 1) gradient[index] = at(gradient, index, 'gradient') + error * at(row, index, 'row'); interceptGradient += error } for (let index = 0; index < weights.length; index += 1) weights[index] = at(weights, index, 'weights') - config.learningRate * ((at(gradient, index, 'gradient') / sorted.length) + config.l2 * at(weights, index, 'weights')); intercept -= config.learningRate * (interceptGradient / sorted.length) }
  weights.forEach((value, index) => assertFinite(value, `weight[${index}]`)); assertFinite(intercept, 'intercept'); return { coefficients: weights, intercept, normalizationStatistics: { mean: normalized.mean, standardDeviation: normalized.standardDeviation }, trainingRowCount: sorted.length, featureKeys, trainingConfiguration: config }
}

export function trainPairwiseLogisticRanker(members: readonly DatasetMember[], rawConfig: TrainingConfig): TrainedParameters {
  const config = validateConfig(rawConfig); const { sorted, featureKeys, matrix } = prepareRows(members); const normalized = normalize(matrix); const groups = new Map<string, Array<{ member: DatasetMember, row: number[] }>>(); sorted.forEach((member, index) => { const list = groups.get(member.queryGroupKey) || []; list.push({ member, row: at(normalized.matrix, index, 'normalized training matrix') }); groups.set(member.queryGroupKey, list) }); const pairs: Array<{ difference: number[] }> = []
  for (const group of [...groups.values()].sort((a, b) => { const left = at(a, 0, 'group').member.queryGroupKey; const right = at(b, 0, 'group').member.queryGroupKey; return left < right ? -1 : left > right ? 1 : 0 })) { const positives = group.filter(item => item.member.label === 1); const negatives = group.filter(item => item.member.label === 0); for (const positive of positives) for (const negative of negatives) { if (pairs.length >= MAX_TRAINING_PAIRS) throw new Error('Too many training pairs.'); pairs.push({ difference: positive.row.map((value, index) => value - at(negative.row, index, 'negative row')) }) } }
  if (!pairs.length) throw new Error('At least one positive/negative pair is required.'); const weights = Array<number>(featureKeys.length).fill(0)
  for (let epoch = 0; epoch < config.epochs; epoch += 1) { const gradient = Array<number>(weights.length).fill(0); for (const pair of pairs) { const probability = sigmoid(pair.difference.reduce((sum, value, index) => sum + value * at(weights, index, 'ranker weights'), 0)); const error = probability - 1; for (let index = 0; index < weights.length; index += 1) gradient[index] = at(gradient, index, 'ranker gradient') + error * at(pair.difference, index, 'ranker difference') } for (let index = 0; index < weights.length; index += 1) weights[index] = at(weights, index, 'ranker weights') - config.learningRate * ((at(gradient, index, 'ranker gradient') / pairs.length) + config.l2 * at(weights, index, 'ranker weights')) }
  weights.forEach((value, index) => assertFinite(value, `ranker weight[${index}]`)); return { coefficients: weights, intercept: 0, normalizationStatistics: { mean: normalized.mean, standardDeviation: normalized.standardDeviation }, trainingRowCount: sorted.length, featureKeys, trainingConfiguration: config, pairCount: pairs.length }
}

export function trainDeterministicBaseline(modelFamily: ModelFamily, members: readonly DatasetMember[], config: TrainingConfig): TrainedParameters { return parseModelFamily(modelFamily) === 'regularized_logistic_baseline_v1' ? trainRegularizedLogisticBaseline(members, config) : trainPairwiseLogisticRanker(members, config) }
export function scoreWithParameters(parameters: Pick<TrainedParameters, 'coefficients' | 'intercept' | 'normalizationStatistics'>, values: number[]): number { if (values.length !== parameters.coefficients.length) throw new Error('Prediction feature count does not match artifact.'); const score = parameters.intercept + values.reduce((sum, value, index) => sum + ((value - at(parameters.normalizationStatistics.mean, index, 'mean')) / at(parameters.normalizationStatistics.standardDeviation, index, 'standardDeviation')) * at(parameters.coefficients, index, 'coefficients'), 0); return sigmoid(score) }
export function standardizedFeatureContributions(parameters: Pick<TrainedParameters, 'coefficients' | 'normalizationStatistics'>, values: number[], keys: string[]): Array<{ key: string, contribution: number, missing: boolean }> { if (values.length !== parameters.coefficients.length || keys.length !== values.length) throw new Error('Contribution feature count does not match artifact.'); return values.map((value, index) => ({ key: at(keys, index, 'feature keys'), contribution: ((value - at(parameters.normalizationStatistics.mean, index, 'mean')) / at(parameters.normalizationStatistics.standardDeviation, index, 'standardDeviation')) * at(parameters.coefficients, index, 'coefficients'), missing: false })) }
