import { and, eq } from 'drizzle-orm'
import { createError } from 'h3'
import { getDatabase } from '../../database'
import { managedSiteProjects, managedSiteStorageConnections, users } from '../../database/schema'
import { stableFingerprint } from '../../seo-geo-core/repository'

export async function configureMediaStorageConnection(input: { ownerOpenId: string; projectId: number; providerKey: 's3_compatible' | 'local_dev'; credentialReference: string | null; configuration: unknown }) {
  const database = getDatabase(); if (!database) throw createError({ statusCode: 503, statusMessage: 'Media storage configuration database is unavailable.' }); const [owner] = await database.select({ id: users.id }).from(users).where(and(eq(users.openId, input.ownerOpenId), eq(users.role, 'admin'))).limit(1); if (!owner) throw createError({ statusCode: 403, statusMessage: 'Platform owner authority could not be resolved.' }); const [project] = await database.select({ id: managedSiteProjects.id }).from(managedSiteProjects).where(and(eq(managedSiteProjects.ownerUserId, owner.id), eq(managedSiteProjects.id, input.projectId))).limit(1); if (!project) throw createError({ statusCode: 404, statusMessage: 'Managed site project was not found.' })
  if (!['s3_compatible', 'local_dev'].includes(input.providerKey) || input.providerKey === 'local_dev' && process.env.NODE_ENV === 'production') throw createError({ statusCode: 422, statusMessage: 'Media storage provider mode is invalid.' }); if (!input.configuration || typeof input.configuration !== 'object' || Array.isArray(input.configuration)) throw createError({ statusCode: 422, statusMessage: 'Media storage configuration is invalid.' }); const configuration = input.configuration as Record<string, unknown>
  if (input.providerKey === 's3_compatible') { if (typeof input.credentialReference !== 'string' || !/^[A-Z][A-Z0-9_]{7,159}$/u.test(input.credentialReference) || typeof configuration.bucket !== 'string' || typeof configuration.region !== 'string' || typeof configuration.prefix !== 'string') throw createError({ statusCode: 422, statusMessage: 'S3-compatible storage requires an opaque credential reference and fixed bucket/region/prefix.' }); if (Object.keys(configuration).some(key => !['bucket', 'region', 'prefix', 'endpoint', 'publicCdnOrigin'].includes(key))) throw createError({ statusCode: 422, statusMessage: 'S3-compatible storage configuration contains unknown fields.' }) } else { if (input.credentialReference !== null || typeof configuration.root !== 'string' || Object.keys(configuration).some(key => key !== 'root')) throw createError({ statusCode: 422, statusMessage: 'Local development storage configuration is invalid.' }) }
  const configurationFingerprint = stableFingerprint({ version: 'managed-site-storage-connection-v1', ownerUserId: owner.id, projectId: project.id, providerKey: input.providerKey, credentialReference: input.credentialReference, configuration }); await database.insert(managedSiteStorageConnections).values({ ownerUserId: owner.id, projectId: project.id, providerKey: input.providerKey, credentialReference: input.credentialReference, configuration, configurationFingerprint, status: input.providerKey === 'local_dev' ? 'configured' : 'configured', verifiedAt: null }).onDuplicateKeyUpdate({ set: { providerKey: input.providerKey, credentialReference: input.credentialReference, configuration, configurationFingerprint, status: 'configured', verifiedAt: null, updatedAt: new Date() } }); return { projectId: project.id, providerKey: input.providerKey, credentialReference: input.credentialReference, configurationFingerprint, status: 'configured', credentialValueStored: false, healthChecked: false }
}
