import { isIP } from 'node:net'
import { createError } from 'h3'
import type { MediaScannerVerdict, MediaSecurityScanner } from './types'

const VERDICTS = new Set<MediaScannerVerdict>(['passed', 'blocked', 'owner_review'])
function scannerEndpoint(raw: string): URL { let url: URL; try { url = new URL(raw) } catch { throw createError({ statusCode: 503, statusMessage: 'Media scanner endpoint is invalid.' }) } if (url.protocol !== 'https:' || url.username || url.password || url.port && url.port !== '443' || url.search || url.hash || isIP(url.hostname) || url.hostname === 'localhost' || url.hostname.endsWith('.local')) throw createError({ statusCode: 503, statusMessage: 'Media scanner endpoint is not an approved HTTPS authority.' }); return url }
function credential(reference: string): string { if (!/^[A-Z][A-Z0-9_]{7,159}$/u.test(reference)) throw createError({ statusCode: 503, statusMessage: 'Media scanner credential reference is invalid.' }); const value = process.env[reference]; if (!value || value.length < 16 || value.length > 4096) throw createError({ statusCode: 503, statusMessage: 'Media scanner credential reference is unresolved.' }); return value }

export function createHttpMediaSecurityScanner(input: { endpoint: string; credentialReference: string; timeoutMs?: number; fetchImpl?: typeof fetch }): MediaSecurityScanner {
  const endpoint = scannerEndpoint(input.endpoint); const token = credential(input.credentialReference); const timeoutMs = Math.max(1000, Math.min(15_000, input.timeoutMs || 8000)); const fetchImpl = input.fetchImpl || fetch
  return { async scan(request) { let lastStatus = 0; for (let attempt = 1; attempt <= 3; attempt++) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), timeoutMs); try { const response = await fetchImpl(endpoint, { method: 'POST', redirect: 'manual', signal: controller.signal, headers: { authorization: `Bearer ${token}`, 'content-type': 'application/octet-stream', 'x-media-sha256': request.sha256, 'x-media-tenant': `${request.tenant.ownerUserId}:${request.tenant.projectId}` }, body: Buffer.from(request.bytes) }); lastStatus = response.status; if (response.status === 429 || response.status >= 500) { if (attempt < 3) continue; throw createError({ statusCode: 503, statusMessage: 'Media scanner is temporarily unavailable.' }) } if (!response.ok || response.status >= 300 && response.status < 400) throw createError({ statusCode: 503, statusMessage: 'Media scanner rejected the bounded server request.' }); const declaredLength = Number(response.headers.get('content-length') || 0); if (declaredLength > 32_768) throw createError({ statusCode: 503, statusMessage: 'Media scanner response exceeds the bounded limit.' }); const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.byteLength > 32_768) throw createError({ statusCode: 503, statusMessage: 'Media scanner response exceeds the bounded limit.' }); let parsed: any; try { parsed = JSON.parse(Buffer.from(bytes).toString('utf8')) } catch { throw createError({ statusCode: 503, statusMessage: 'Media scanner response is malformed.' }) } if (!parsed || typeof parsed !== 'object' || !VERDICTS.has(parsed.verdict) || parsed.reasonCode !== null && typeof parsed.reasonCode !== 'string' || parsed.scannerReference !== null && typeof parsed.scannerReference !== 'string') throw createError({ statusCode: 503, statusMessage: 'Media scanner response contract is invalid.' }); return { verdict: parsed.verdict as MediaScannerVerdict, reasonCode: parsed.reasonCode?.slice(0, 120) || null, scannerReference: parsed.scannerReference?.slice(0, 255) || null } } catch (error: any) { if (attempt >= 3 || !['AbortError', 'TimeoutError'].includes(error?.name) && ![429, 500, 502, 503, 504].includes(lastStatus)) throw error } finally { clearTimeout(timeout) } } throw createError({ statusCode: 503, statusMessage: 'Media scanner is unavailable.' }) } }
}
