export type PublicResearchCase = { id: string, market: 'Dubai' | 'UK' | 'Singapore', category: string, sourceUrl: string, sourceName: string, signals: { primaryCta: boolean, serviceRouting: boolean, expertContact: boolean, insights: boolean, trustSignals: boolean, priceOrEstimator: boolean, faqOrGuidedTopics: boolean }, researchNote: string, status: 'pending_source_card_review', restrictions: readonly ['private_registry', 'policy_gate_required', 'no_client_outcome_claim', 'not_auto_admitted'] }

/** Human-researched public examples. They are high-value Source Card candidates, not an auto-admitted crawl queue, client assessment or source of performance claims. */
export const publicResearchCases: readonly PublicResearchCase[] = [
  { id: 'public-research-dxb-001', market: 'Dubai', category: 'Business setup consultancy', sourceName: 'Business Setup Consultants', sourceUrl: 'https://businessetup.com/', signals: { primaryCta: true, serviceRouting: true, expertContact: true, insights: true, trustSignals: true, priceOrEstimator: true, faqOrGuidedTopics: false }, researchNote: '初始人工觀察：成本估算、服務分流與內容導流。建立 Source Card 後可依政策擴充為 topic、entity、service、technical SEO 與語意特徵。', status: 'pending_source_card_review', restrictions: ['private_registry', 'policy_gate_required', 'no_client_outcome_claim', 'not_auto_admitted'] },
  { id: 'public-research-dxb-002', market: 'Dubai', category: 'Business & tax consultancy', sourceName: 'Creation Business Consultants', sourceUrl: 'https://www.creationbc.com/', signals: { primaryCta: true, serviceRouting: true, expertContact: true, insights: true, trustSignals: true, priceOrEstimator: false, faqOrGuidedTopics: false }, researchNote: '初始人工觀察：多服務線、諮詢入口、內容資源與信任區塊。經來源審核後可擴充為可複核的多維 artifact。', status: 'pending_source_card_review', restrictions: ['private_registry', 'policy_gate_required', 'no_client_outcome_claim', 'not_auto_admitted'] },
  { id: 'public-research-uk-003', market: 'UK', category: 'Business consulting', sourceName: 'Grant Thornton UK', sourceUrl: 'https://www.grantthornton.co.uk/services/consulting/business-consulting/', signals: { primaryCta: true, serviceRouting: true, expertContact: true, insights: true, trustSignals: true, priceOrEstimator: false, faqOrGuidedTopics: true }, researchNote: '初始人工觀察：具名專家、主題展開與 contact path。通過 Source Card policy gate 後，可建立主題、頁面關係與語意 representation。', status: 'pending_source_card_review', restrictions: ['private_registry', 'policy_gate_required', 'no_client_outcome_claim', 'not_auto_admitted'] },
  { id: 'public-research-sg-004', market: 'Singapore', category: 'Strategy consulting', sourceName: 'Simon-Kucher Singapore', sourceUrl: 'https://www.simon-kucher.com/en/country/singapore', signals: { primaryCta: true, serviceRouting: true, expertContact: true, insights: true, trustSignals: true, priceOrEstimator: false, faqOrGuidedTopics: false }, researchNote: '初始人工觀察：地區化顧問頁、觀點內容、可見專家、產業導覽與聯絡入口。完成來源核准後可建立版本化多維特徵。', status: 'pending_source_card_review', restrictions: ['private_registry', 'policy_gate_required', 'no_client_outcome_claim', 'not_auto_admitted'] },
]
